### ISSUE TITLE
Eclipse launch can fail if other jars exist in build output

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1068]
## Background

The eclipse plugin has a defect where if there are multiple jars in the build output location for a test, then it can pick incorrectly pick up that one (aka sources/javadoc for example). This will then just fail with an NPE, so we need not only a better fail message, but a solution for selecting the correct jar.

Need to add logic which selects the correct jar with code in, from those available.

To re-create:
- configure maven or gradle to build a javadoc jar, and/or a sources jar, and the built code jar. So 2-3 jars are built.
- create a galasa eclipse run launcher for that test project
- try to run the test

Most of the time, the wrong jar gets picked.

Workaround for now: Don't build more than the normal code jar, so there is only one jar to select from.

## Tasks
- [ ] Change the jar selection from using the 1st one in the list of jars to doing a recursive-search of the jar and find at least one .class file, then we know it should be a jar containing tests... so that's the one we use.
- [ ] Logic to check a jar for the .class files can be unit tested separately.
- [ ] Test that this solves the issue.

**Comment by techcobweb** [comment]
Although this is a valid defect, we are not going to fix it.
The Eclipse plugins are going to be archived, and not developed further at this point.
