### ISSUE TITLE
Remediate vulnerability found in com.squareup.okhttp3:okhttp:3.11.0 - CVE-2021-0341 (High)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1091]
dev.galasa.selenium.manager contains CVE-2021-0341 (High) through com.squareup.okhttp3:okhttp:3.11.0. This is a direct dependency. Need to upgrade version of com.squareup.okhttp3:okhttp:3.11.0 to version that does not contain the vulnerability.

- only one package
- not a big jump
- no code changes

## Tasks
- [x] update the version
- [x] re-run tests
- [x] some extra docs update

**Comment by hobbit1983** [comment]
would probably need to upgrade to 4.10

**Comment by hobbit1983** [comment]
Everything compiles with okhttp 4.10 but I did have to remove the include on okio which I believe is now included as a transitive dependency.  Running the Selenium manager at the new level will assure that

**Comment by hobbit1983** [comment]
code pushed to branch iss1091

**Comment by hobbit1983** [comment]
I can now run the test so need to ensure my code is being executed and then this can close

**Comment by hobbit1983** [comment]
OKHTTP now requires not only okio but also the kotlin runtime (which by default is not an osgi bundle) so that took some digging

**Comment by hobbit1983** [comment]
Now ready for review
