### ISSUE TITLE
Document build and release pipelines for Galasa, and educate the development team on them

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1107]
## Story
As a Galasa development team member, I need to be able to understand the build pipelines and the technologies used within them, and be able to kick off main builds, regression pipelines and release pipelines, just by following clear documentation.

## Tasks
- [ ] Document how we use different technologies within the builds
- [ ] Document the build pipelines
   - This is an ongoing task until all build pipelines have been created. Documentation will keep being added as each pipeline is added: github.com/galasa-dev/automation/README.md
- [ ] Document how the regression pipeline works
   - [ ] Figure out where is the best place for this, most likely the galasa developer docs
- [ ] Document the release pipeline
   - [ ] First, we need to complete a release to understand this
- [ ] Hold education/knowledge sharing session with the development team after all of the above items are complete, so that everyone has the same baseline of knowledge
