### ISSUE TITLE
Understand and document the release pipelines for Galasa

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1115]
## Tasks
- [ ] Release process for Javadoc. eg:
  - [ ] Moving the dev best-so-far to the latest stable release area.
  - [ ] Moving latest stable release to archived other releases area.

**Comment by hobbit1983** [comment]
@eamansour @jadecarino can we call this complete?  It's stuck in the Backlog since the move to GH projects?

**Comment by eamansour** [comment]
Yep, I'm happy to mark this as complete.

**Comment by hobbit1983** [comment]
Closing as completed
