### ISSUE TITLE
Create Vault entries for all credentials for the release process

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1118]
We have vault entries needed for the development pipelines.

We need a service ID/account created instead of personal credentials being used.

## Tasks
- [ ] Understand the permissions and accounts needed to release galasa (duplicate of 1116)
- [ ] Check the release scripts/steps to find any secrets which need to be added to vault.
- [ ] Add the secrets to vault as required.
- [ ] Plumb-in the use of these secrets/credentials.
- [ ] Revoke access of previous accounts for maven central...etc.

**Comment by techcobweb** [comment]
@Jimbo4794 We will need your assistance on this I think.

**Comment by techcobweb** [comment]
Maybe @Jimbo4794 and @hobbit1983 will be able to work together on this one ?

**Comment by hobbit1983** [comment]
Failed at the first hurdle and neither @Jimbo4794 or I have access to update the users associated with maven central

**Comment by techcobweb** [comment]
@Jimbo4794 @hobbit1983 Did this one get completed ?
