### ISSUE TITLE
Build and release Javadoc

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1122]
## Story
As a galasa consumer I want to be able to read the javadoc from the galasa dev web site so that I can see the available api calls in the managers.

## Background

Ideal picture

- Development best-so-far version
- Latest stable
- Archived others

> Note: The javadoc used to be working so we should be able to salvage value from that.

## Scope excluded
- Release process for Javadoc. eg:
  - Moving the dev best-so-far to the latest stable release area.
  - Moving latest stable release to archived other releases area.

## Tasks
- [x] Understand how javadoc is built in general. Try building a site with any source code.
- [x] Build process to build the HTML site
  - [x] in OBR to pull in all the sources dependencies in the galasa family of maven assets, so Framework and Managers is available in one source tree.
  - [x] build the javadoc html into a site.
  - [x] Package the site as a zip
  - [x] Share the zip of the html in a maven repo. This is at https://development.galasa.dev/main/maven-repo/javadocs/
- [x] The build-locally.sh build process to build the zip, so we can see javadoc errors locally and shift-left the resolution of those later.
- [x] Build process to create a container image of the unpacked javadoc site.
- [x] Push a version of the javadoc manually to https://javadoc.galasa.dev/ (as we don't have anything useful live there right now).

- [x] Build process to push the javadoc container image to a live site on the galasa.dev site (development best-so-far)

**Comment by hobbit1983** [comment]
This might be a helpful link https://stackoverflow.com/questions/58836862/jdk-11-and-javadoc

**Comment by techcobweb** [comment]
code/external/galasa-dev/build/docker/javadoc
![image.png](https://images.zenhubusercontent.com/63402c6f7f805e171c1684f1/a7b39a41-05c7-4b5f-b74c-36f65df1b621)
- The docker file builds an apache docker image to host the html 
- The pom.xml pulls-in the javadoc jar artifact:
```
<artifactItem>
	<groupId>dev.galasa</groupId>
	<artifactId>galasa-uber-javadoc</artifactId>
	<version>0.15.0</version>
	<classifier>javadoc</classifier>
	<type>jar</type>
</artifactItem>
```

**Comment by techcobweb** [comment]
`./managers/galasa-managers-parent/galasa-uber-javadoc/pom.xml`
This pom appears to get all the classifier='sources' .jars on which the 'uber' jar depends.
```
		<dependency>
			<groupId>dev.galasa</groupId>
			<artifactId>dev.galasa.uber.obr</artifactId>
			<version>0.25.0</version>
			<type>obr</type>
		</dependency>
```
- The sources are all unpacked into the 'sources' folder.
- The maven javadoc plugin then javadocs all the source in one go.
- `code/external/galasa-dev/managers/galasa-managers-parent/galasa-uber-javadoc/src/main/resources/Dockerfile` is copied into place so it can be used to put the javadoc into a container image.

**Comment by techcobweb** [comment]
@Jimbo4794 tells me that that looks like an older mechanism which probably isn't used now. 
As it's a maven file, and doesn't appear to be called from gradle... I would say it's not used.
Perhaps there is something which replaced it ? Perhaps that's the last time it worked, and javadoc
stopped working when the build switched to using gradle.

**Comment by techcobweb** [comment]
https://stackoverflow.com/questions/45997976/how-generate-javadoc-with-gradle This article seems to show how to run javadoc from a gradle build.

**Comment by techcobweb** [comment]
@jadecarino took this one over. I still don't understand how the galasa-dev site build  uses it. Need to ask @CaroMac 

The build process stands up a deployment of a small maven repository with a version of the javadoc inside. I assume the galasa-dev site build picks this up and packages it in the web site ? If so, it will need to use the new URL at which the javadoc built html zip/jar is now located, as that's different to where it used to be.

**Comment by techcobweb** [comment]
The build process creates 2 things:
- A maven site, hosting a zip file which contains the javadoc site. This maven site is hosted at https://development.galasa.dev/main/maven-repo/javadocs/
- A docker image of the javadoc site, in harbor. This is the image which needs to be hosted on javadoc.galasa.dev But should also be hosted elsewhere on a best-so-far basis.

**Comment by techcobweb** [comment]
@jadecarino Are you able to add a deployment which hosts the harbor image at https://harbor-cicsk8s.hursley.ibm.com/harbor/projects/10/repositories/galasa-javadocs/artifacts-tab and have the OBR build refresh it, so we can see the best-so-far javadoc whenever the OBR build runs ? Then I think we're done on this story.

**Comment by jadecarino** [comment]
@techcobweb Hi Mike, sure I will take a look at this today

**Comment by techcobweb** [comment]
Terriffic work @jadecarino Great to see the javadoc site working again and visible for latest build pipeline.
Closing this as all items are now complete. Pls re-open if you disagree...
