### ISSUE TITLE
Dump the current DfG release into MEND to be scanned

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1123]
## Tasks
- [x] create a git repo
- [x] tell MEND to do the scanning
- [x] Gary may have to link it up to PCERT

**Comment by hobbit1983** [comment]
Two issues found by MEND that need to be closed within (30days?)
https://app.zenhub.com/workspaces/galasa-5dc3f56cf3f3b50001ac0432/issues/gh/galasa-dev/projectmanagement/1301
https://app.zenhub.com/workspaces/galasa-5dc3f56cf3f3b50001ac0432/issues/gh/galasa-dev/projectmanagement/1300
