### ISSUE TITLE
Setup Galasa Simplatform Build

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1148]
### Story
As a Galasa developer, I want to be able to build the Simplatform repo and application.

### Tasks
- [x] Create build-pr pipeline
   - This will consist of git-verify, clone-automation, clone-simplatform, get-commit, maven-build-simplatform-application, maven-build-simbank-tests, docker-build-simplatform-repo, docker-build-simplatform-jar and git-status
   - [x] Research what the Dockerfile buildArg 'branch' is for
- [x] Create main-build pipeline
   - This will consist of clone-automation, clone-simplatform, get-commit, main-maven-build-simplatform-application, main-maven-build-simbank-tests, main-docker-build-simplatform-repo, main-docker-build-simplatform-jar, recycle-deployment and wait-deployment
- [x] Create the resources needed for the Simplatform maven repo instance
   - [x] Deployment
   - [x] Ingress
   - [x] Service

To test the pipelines:
- [x] Create an empty commit on the Simplatform repo and open a PR
- [x] Merge in PR

**Comment by Jimbo4794** [comment]
Same as core build

**Comment by jadecarino** [comment]
I have started on this as a) it's needed and b) I think the simplatform maven repo might need to be deployed for the Eclipse, Isolated and MVP builds to pull artifacts from.

**Comment by jadecarino** [comment]
Code pushed to simplatform branch and PR open so changes can be found easily: https://github.com/galasa-dev/automation/pull/89

**Comment by jadecarino** [comment]
For the purposes of the Eclipse and Isolated pipelines needing development.galasa.dev/main/maven-repo/simplatform, I have put together the Simplatform pipelines. The simplatform repo is now deployed. Still need to figure out what the simplatform application resources are for.

**Comment by jadecarino** [comment]
Unfortunately I did not have time to investigate the Simplatform application and recreate the resources needed for it in this sprint. The maven repo is up and running though. 

Due to our team discussions about how to proceed with the distribution of Simplatform, maybe it would be a good idea to double check that the remaining tasks on this work item are still correct? @techcobweb
