### ISSUE TITLE
Galasa CLI Build should be a gradle build

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1149]
## Story
As a galasa developer, I want to be able to build the CLI project in isolation locally, without having to download sibling projects it depends upon, using only one command within the project, so that it is simple to build and test locally.

## Background
The build of the CLI projects needs some attention to make it build in isolation so we can get the benefits of shift-left, and build it on our local laptops.

## Tasks
- [ ] Convert the CLI project into a standard gradle project such that all the things done by the Tekton task are performed by gradle. Then it can build locally.
- [ ] The frameworks repo needs to expose the openapi.yaml as an external artifact which can be downloaded
- [ ] Figure out how the openapi generator tool can be obtained as part of the gradle process (may require re-packaging it as a maven artifact which can be depended upon)
- [ ] Built artifacts should be made available on gradle so they can be obtained from there after the CLI project is built
- [ ] Document how to do a build within the CLI projects
- [x] Basic build-locally.sh script added to call anything needed to build it locally.
  - See galasa-dev/cli#34

**Comment by techcobweb** [comment]
Taking the liberty of re-sizing the story points because 
- I've not done anything with Go before, so need to learn how to build/package/handle dependencies.
- I've not done gradle before, so need to learn that.
- I've not done anything with the galasa build pipeline stuff before, so need to learn that.
We can re-visit the sizing if we wish in a team grooming session or the sprint planning next week.

**Comment by techcobweb** [comment]
Maybe we should use Gradle to pull in the dependencies, and push out the built artifacts, and use what we do today to build the actual code ?

**Comment by techcobweb** [comment]
This is a duplicate of story #1254. Closing as a result.
