### ISSUE TITLE
Migrate images from the docker repo to somewhere more appropriate

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1198]
## Story
As a galasa developer I want to be able to build all of the released images in a consistent manner so that process is both obvious and easy to repeat.

## Background
- This will be needed for a release.
- Leave the docker repo alone, as we can only remove it when the new release is released.
- Not clear whether the docker files will need changing or not.

## Tasks
- [x] Decide where each docker image build should live
   - Dockerfiles moved to automation/dockerfiles/runtime and builds for the images in new pipeline, branch-obr-generic.
- [x] Move images over to automation repository
   - [x] bootEmbedded
      - bootEmbedded-dockerfile and needed files in automation/dockerfiles/runtime. bootEmbedded image built in branch-obr-generic pipeline.
   - [x] dockerOperator
      - We will no longer be distributing the docker operator.
   - [x] ibmBootEmbedded
      - ibmBootEmbedded-dockerfile and needed files in automation/dockerfiles/runtime. ibmBootEmbedded image built in branch-obr-generic pipeline.
   - [x] obrGeneric
   - [ ] resources
      - resources pipeline made and in automation/pipelines/pipelines/release. Image does not need to be deployed to harbor unless for release (looks like it is built at the start of a release then deleted)
   - [x] retag
      - retag-dockerfile created in automation/dockerfiles. Not currently used but there if needed.
- [x] Re-build the images from the new homes of the Docker files
   - branch-obr-generic successfully ran.
- [x] Re-deploy to Harbor

- [x] Document what these images are for and how they are built

**Comment by jadecarino** [comment]
Unfortunately we did not have time to start this, hopefully will be able to tackle next sprint.

**Comment by techcobweb** [comment]
resources pipeline is written but not tested, as scared it may accidentally release something or be visible when it shouldn't. Lets test when we do an actual release.
