### ISSUE TITLE
Create eclipse build-pr pipeline

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1199]
### Story

As a Galasa dev, we need to be able to build the Eclipse repository at the PR level when someone PRs a source code change, to verify their changes are okay.

### Tasks
- [x] Refer to the existing Eclipse build pipeline and task:
   - [x] Check if any new custom images are required
   - [x] Check what tasks are needed
   - [x] Check what buildArgs are passed into the maven and docker build tasks (you will need to refer to the yaml to check whether the default value from the values.yaml is used, or if a value is passed in. As the simbankSourceRepo has not yet been set up, use maven central for this temporarily.
- [x] Find how the value $(resources.inputs.git/eclipse.commit) is populated
- [x] Write the pr-eclipse build pipeline
- [x] Run the pipeline
   - [x] Clone the eclipse repo
   - [x] Make an empty commit: git commit -s -S -m "Empty commit" --allow-empty
   - [x] Open a PR which will set off the build

If this fails due to needing the simbankSourceRepo to **not** be maven central, then we will have to create the Simbank build pipelines first.

**Comment by jadecarino** [comment]
resources are deprecated so decided not to include this line in the new pipelines. I will investigate in future what this did but not a priority right now
