### ISSUE TITLE
Create Eclipse main build pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1219]
### Story

As a Galasa dev, we need to be able to run a main build of the Eclipse repository when changes are merged into main, to update the docker image and recycle the maven repo.

### Tasks
- [x] Refer to the existing Eclipse Main build pipeline and task:
   - [x] Check if any new custom images are required
   - [x] Check what tasks are needed
   - [x] Check what buildArgs are passed into the maven and docker build tasks (you will need to refer to the yaml to check whether the default value from the values.yaml is used, or if a value is passed in. As the simbankSourceRepo has not yet been set up, use maven central for this temporarily.
- [ ] Find how the value $(resources.inputs.git/eclipse.commit) is populated
- [x] Write the main-eclipse build pipeline
- [x] Create the Eclipse Deployment, Ingress and Service
- [x] Run the pipeline
   - [x] Clone the eclipse repo
   - [x] Make a PR with an empty commit and merge it in

**Comment by jadecarino** [comment]
resources are deprecated so decided not to include this line in the new pipelines. I will investigate in future what this did but not a priority right now.
