### ISSUE TITLE
Enhance build pipelines: Support building of branches beyond the 'main' branch.

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1228]
## Story
As a galasa developer I want to be able to run a build and deployment on a branch of a repository so that I can use the built artifacts.

## Background
This may be due to a need to re-build an older patched branch, eg: The log4j issue which came up recently. We would probably have to re-build and re-version all our previous releases with the fix-patch as soon as we could, else force everyone to upgrade to the latest release.

If we want to re-build older releases, we would need to build a branch taken from a release tag.

---

Optimise build pipelines: change 'main' build pipelines to take parameters instead of hard code

Currently the main build pipelines take a hard coded set of parameters (revision = main and refspec = refs/heads/main:refs/heads/main), which disables branch level builds. If we want to be able to do branch level main builds, we need to replace these hard coded values with parameters instead. Once built, the helm chart will need to be updated to be able to retrieve and deploy these artifacts.

## Tasks
- [x] Image created needs to be tagged with the branch name rather than hard-coded 'main'
- [x] Remove other hard-coded 'main' references in favour of the branch name.
- [x] Create `branch` and `imageTag` helm values for each repo rather than using global branch and image tag values.
    - Update the templates to make use of these new values
- [x] Create a `deploy` helm value to make deployments conditional
- [x] Test that this hasn't disturbed the building of the actual 'main' branch.
- [x] Test that a non-'main' branch can be built.
- [x] Test that non-'main' build artifacts can be deployed.

**Comment by hobbit1983** [comment]
@Jimbo4794 is this what @eamansour is currently working on?
