### ISSUE TITLE
Quality: Build Verification Test : Verify that Galasa builds actually work

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1232]
## Story
As a galasa dev engineer, I want to know that a build of galasa works, so I know my current story is delivered and can be marked as complete.

## Background
There is currently no way of testing that a new build is working, or that a delivered change has degraded the Galasa code at all.

Ironically perhaps, we need to create a BVT for Galasa.

This should be done for every build of main (ideally). Or kicked off once a 'main' build completes, and the results monitored.

Wondering if we could use Galasa to test that a new build of Galasa is working ok. 

Then upgrade the version we use to do the testing with...
Kind of enabling a boot-strapping of Galasa. Using Galasa in the development of Galasa. 
There's something poetic about that idea.

## Tasks
- [ ] Decide which aspects of Galasa we can test with some tests.
- [ ] Develop a few tests which should work.
- [ ] Decide where a test system could be deployed.
- [ ] Deploy a galasa system which is able to test the build

- [ ] Write a build pipeline to:
   - [ ] Deploy the Galasa images to somewhere they can run
   - [ ] Build and deploy some tests
   - [ ] Run some tests (which should work)
   - [ ] Verify that we can get results out
   - [ ] Report back that it works OK.

- [ ] Some way of monitoring the results, so we notice if it fails. 
  - eg: A slack message, or auto-raised Defect..., email, http dashboard...etc.

- [ ] Drive the BVT when a main build is complete, using some automated trigger.
