### ISSUE TITLE
Exception panic from galasactl - bootstrap loading failure.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1235]
Command was :
```script
galasactl runs prepare \
--bootstrap "http://galasa-test.cics-ts.hur.hdclab.intranet.ibm.com:8080/bootstrap" \
--portfolio test.yaml \
--stream mike 
```

Which caused an exception rather than a nicely formatted error message explaining what's wrong:

```
2022/10/25 08:32:07 Galasa CLI - Assemble tests
panic: Get http://galasa-test.cics-ts.hur.hdclab.intranet.ibm.com:8080/bootstrap: dial tcp: i/o timeout

goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/api.loadBootstrap()
        /workspace/git/cli/pkg/api/api.go:58 +0x3a7
github.com/galasa.dev/cli/pkg/api.InitialiseAPI(0x205d84153, 0x45, 0x1)
        /workspace/git/cli/pkg/api/api.go:38 +0x98
github.com/galasa.dev/cli/pkg/cmd.executeAssemble(0x186f600, 0xc000070840, 0x0, 0x6)
        /workspace/git/cli/pkg/cmd/runsPrepare.go:69 +0x1e7
github.com/spf13/cobra.(*Command).execute(0x186f600, 0xc0000707e0, 0x6, 0x6, 0x186f600, 0xc0000707e0)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x186f100, 0x103acea, 0x18368a0, 0xc000058750)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/galasa.dev/cli/pkg/cmd.Execute()
        /workspace/git/cli/pkg/cmd/root.go:28 +0x31
main.main()
        /workspace/git/cli/cmd/galasactl/main.go:14 +0x20
```

From the exception it seems that the loadBootStrap() failed, but it should be a nice (internationalised) message which appears in front of the user.

```
>galasactl --version
galasactl version 0.20.0-alpha-2305ba574524af5cd0fba59de18411582f470de5
```

`http://galasa-test.cics-ts.hur.hdclab.intranet.ibm.com:8080/bootstrap` resolves OK in my browser to:
```
#Galasa Bootstrap Properties
#Tue Oct 25 07:54:01 UTC 2022
framework.config.store=etcd\:http\://galasa-test.cics-ts.hur.hdclab.intranet.ibm.com\:2379
framework.extra.bundles=dev.galasa.cps.etcd,dev.galasa.ras.couchdb
```

When I added `9.0.0.1` to my DNS list at the top, Galasactl seems to resolve the bootstrap URL, and no panic occurs.

Why is is that a browser could resolve the URL but GalasaCtl can't  ?

This error needs catching and handling properly.

## Tasks
- [x] Figure out why browser URL resolution is different to that used by galasactl.
- [x] Better error message
```text
The bootstrap file could not be loaded from `http://galasa-test.cics-ts.hur.hdclab.intranet.ibm.com:8080/bootstrap`
The url could not be resolved.
- Check you can resolve this url with a browser
- Check you have adequate permissions to access that file
- Check your DNS servers are configured on your current network configuration
```
- No need to internationalise the error message, just make sure you use a template to build the message rather than string concatenations, to make internationalisation easier later on.
- ~~Unit test coverage~~ New unit tests not added, fixed up ones which are already there.
- [x] Documentation of new error message in the externals.
- ~~Other testing ??? What could we test ? How ?~~ Scope removed. Just fixed up the errors which are in the code already.

**Comment by jadecarino** [comment]
I too get an error loading the bootstrap, however only when running a built binary of galasactl. 
FYI - I use a different bootstrap: http://galasa-cicsk8s.hursley.ibm.com/bootstrap

When running galasactl using 'go run', everything is okay:
`jadecarino in ~/Desktop/Galasa/other/cli on branch main > go run cmd/galasactl/main.go runs prepare --portfolio test.yaml --bootstrap http://galasa-cicsk8s.hursley.ibm.com/bootstrap --stream inttests --package local
2022/11/01 10:40:13 Galasa CLI - Assemble tests
2022/11/01 10:40:13 Test catalog retrieved
2022/11/01 10:40:13     Selected test class 'dev.galasa.inttests/dev.galasa.inttests.zosFileDataset.local.mvp.ZosFileDatasetLocalJava11UbuntuMvpRse'`

However when running a built binary, I get the bootstrap loading erorr:
`jadecarino in ~/Desktop/Galasa/other/cli on branch main > bin/galasactl-darwin-amd64 runs prepare --portfolio test.yaml --bootstrap http://galasa-cicsk8s.hursley.ibm.com/bootstrap --stream inttests --package local
2022/11/01 10:24:22 Galasa CLI - Assemble tests
panic: Get "http://galasa-cicsk8s.hursley.ibm.com/bootstrap": dial tcp: lookup galasa-cicsk8s.hursley.ibm.com on 192.168.101.66:53: no such host

goroutine 1 [running]:
github.com/galasa.dev/cli/pkg/api.loadBootstrap()
        /Users/jadecarino/Desktop/Galasa/other/cli/pkg/api/api.go:58 +0x28b`


It seems Go can handle loading the bootstrap but the binaries cannot.

**Comment by hobbit1983** [comment]
I think this has something to do with the way that go handles DNS lookups over a VPN. I’ve raised a issue with golang for this

**Comment by techcobweb** [comment]
- add doc of workaround to galasa-dev
- enhance error message to say what you can try...
