### ISSUE TITLE
CLI improvement : List valid streams when specified stream not found

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1236]
## Story
As a command line user, when I do a `runs prepare` action and specify a stream which doesn't exist, then I want to receive an error message which lists the streams I could have validly specified, so I can correct my mistake and carry on without having to try to remember or look-up what stream names are valid.

## Background
This story is to improve the usablility of the command line tool, so it provides more guidance to users who may otherwise draw a blank, or need to ask for help.

Use the command-line `galasactl` tool and specify a stream which doesn't exist, for example: `example`
You get this message :
```text
2022/10/25 09:09:52 Galasa CLI - Assemble tests
2022/10/25 09:09:52 Stream "example" is missing from ecosystem
```

The tool could be far more helpful and list the possible streams I could have chosen. The list isn't expected to be very large, so there should be no problem displaying it.

For example:
```text
Stream "example" is not defined in the ecosystem. 
Try using one that does exist : 'EXAMPLE', 'BSF', 'PROD' ...etc
or ask your Galasa systems administrator to add a new stream with the desired name.
```

I ran into this issue when learning Galasa, as the `example` package is listed in the test catalog, and I was confused in thinking that this was the stream name. It turns out that (by convention), the stream names are 
always in upper-case, so when they are added to `etcd` they are upper-case, and the `galasactl` tool is doing an `etcd` lookup to resolve it, which is case-sensitive.

## Tasks
- [x] Detect that the stream doesn't exist, then query the list of valid stream options, and display them.
- [x] What if the list is empty, as galasa is not set up with any streams :

```text
Stream "example" is not defined in the ecosystem. 
There are no streams defined in the ecosystem. 
Galasa needs setting up with streams before tests can be run.
Contact your Galasa systems administrator so that a stream can be configured in the ecosystem.
```
- [x] Unit tests with coverage
