### ISSUE TITLE
OBR Build should be possible on a dev laptop.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1238]
## Story
As a galasa developer I want to clone the OBR repo and build it, without having to download and build any other repositories, so I can practice shift-left, and find bugs/issues earlier.

## Background
The OBR repo cannot be build currently unless other repositories are also cloned as sibling projects on the local disk.
Gradle should be used to get the artifacts which the OBR build depends upon, so this cloning of sibling projects should not be needed.

We had discussions on how to do this. There is lots of history in this area to understand before we have a solution.
Some observations so far:
- The OBR project depends upon having the Framework, Managers and Extensions repositories checked-out as sibling folders for the OBR build to work. This needs to change so the OBR pulls in resources published by the building of those projects.
- Each of the Framework, Managers and Extensions repositories have a `release.yaml` file detailing the levels of things. This gets converted into a `pom.xml` dynamically at some point.
- The pom.xml of the parent project isn't used to work out transitive dependencies of all the various managers in the repo.

## Tasks
- [ ] Investigate and understand what we have today, and why it is the way it is.
- [ ] Propose a better solution which satisfies the various requirements
- [ ] Implement the solution.

All of the above tasks are very 'fluffy' so we probably need a spike story to be done before scheduling any implementation.
