### ISSUE TITLE
Mechanism for relaying events from GitHub into a Tekton event listener inside the IBM firewall.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1240]
## Story
As a developer of the galasa build process, I want events which occur on external github galasa repositories (like PR create, close, branch push...etc) to be relayed into a Tekton event listener running within the IBM firewall, such that the event listener can't tell that it isn't github posting the webhook events directly, so the build process can react to events on github.

## Background
Github has an events history API which a polling mechanism can visit to find out what events occurred recently.
Such a 'polling event monitor' can be run within the IBM firewall.

The polling monitor needs a token to get authenticated access to the external repository.

We can probably make use of the tool written previously to do the job for the cics sample code build process here: https://github.ibm.com/cics-samples/samples-build-infrastructure-github-monitor

## Notes from @Jimbo4794 
We should use this URL:
`/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}`
E.g `https://api.github.com/repos/galasa-dev/automation/hooks/383086863/deliveries/29160660713`

Route: `https://api.github.com/repos/galasa-dev/automation/hooks`
```json
[
  {
    "type": "Repository",
    "id": 378840532,
    "name": "web",
    "active": true,
    "events": [
      "pull_request"
    ],
    "config": {
      "content_type": "json",
      "insecure_ssl": "0",
      "secret": "********",
      "url": "https://triggers.galasa.dev/pr"
    },
    "updated_at": "2022-10-10T11:05:59Z",
    "created_at": "2022-09-11T19:26:24Z",
    "url": "https://api.github.com/repos/galasa-dev/automation/hooks/378840532",
    "test_url": "https://api.github.com/repos/galasa-dev/automation/hooks/378840532/test",
    "ping_url": "https://api.github.com/repos/galasa-dev/automation/hooks/378840532/pings",
    "deliveries_url": "https://api.github.com/repos/galasa-dev/automation/hooks/378840532/deliveries",
    "last_response": {
      "code": 202,
      "status": "active",
      "message": "OK"
    }
  },
...
```
Then: `https://api.github.com/repos/galasa-dev/automation/hooks/378840532/deliveries`
```json
[
  {
    "id": 29530614887,
    "guid": "4a4f4a30-5548-11ed-98e5-7c3e93523f1f",
    "delivered_at": "2022-10-27T09:27:13Z",
    "redelivery": true,
    "duration": 0.51,
    "status": "OK",
    "status_code": 202,
    "event": "pull_request",
    "action": "synchronize",
    "installation_id": null,
    "repository_id": 533705943,
    "url": ""
  },
...
```

Then: `https://api.github.com/repos/galasa-dev/automation/hooks/378840532/deliveries/29530614887`

```json
{
  "id": 29530614887,
  "guid": "4a4f4a30-5548-11ed-98e5-7c3e93523f1f",
  "delivered_at": "2022-10-27T09:27:13Z",
  "redelivery": true,
  "duration": 0.51,
  "status": "OK",
  "status_code": 202,
  "event": "pull_request",
  "action": "synchronize",
  "installation_id": null,
  "repository_id": 533705943,
  "url": "https://triggers.galasa.dev/pr",
  "request": {
    "headers": {
      "Accept": "*/*",
      "User-Agent": "GitHub-Hookshot/ede37db",
      "X-GitHub-Delivery": "4a4f4a30-5548-11ed-98e5-7c3e93523f1f",
      "X-GitHub-Event": "pull_request",
      "X-GitHub-Hook-ID": "378840532",
      "X-GitHub-Hook-Installation-Target-ID": "533705943",
      "X-GitHub-Hook-Installation-Target-Type": "repository",
      "X-Hub-Signature": "sha1=534700188308aeb87743e822e7a59f652291c70c",
      "X-Hub-Signature-256": "sha256=1a45c6b23545826e6c0eeec821fff972fc59afd76172e57d81529811d2a9e236",
      "content-type": "application/json"
    },
    "payload": {
      "action": "synchronize",
      "number": 79,
      "pull_request": {
        "url": "https://api.github.com/repos/galasa-dev/automation/pulls/79",
        "id": 1100212797,
        "node_id": "PR_kwDOH8-0185Bk-o9",
...
```

## Tasks
- [x] Create the monitor program
- ~~Create a 'null' web hook 'swallower' which accepts webhook events, and returns 200 OK responses back to Github.~~ - Scope moved to story #1263
- ~~Add a web hook onto the org we want to monitor which points to this 'web hook swallower'~~
  - Scope moved to story #1263
- [x] Build a docker image we can deploy to the cluster
- [x] Configure the monitor program deployment with 
  - [x] the org we want to poll
  - [x] the token so it can authenticate
  - [x] the PVC so it can bookmark where it got to with replaying events, and can recover after a failure without missing events.
  - [x] the time-span between polling attempts
- [x] Test that it all works

**Comment by techcobweb** [comment]
Think we should separate out these items:
> Create a 'null' web hook 'swallower' which accepts webhook events, and returns 200 OK responses back to Github.
> Add a web hook onto the org we want to monitor which points to this 'web hook swallower'

Then we can close this one out this iteration, and work on the 'swallower' next.
Thoughts @Jimbo4794  ?

**Comment by Jimbo4794** [comment]
Yeah i agree. The external webhook is a nice to have once we have the barebones in place

**Comment by techcobweb** [comment]
Scope moved to story #1263 - Presumably we can close this now.

**Comment by techcobweb** [comment]
Agreement in sprint kickoff mtg that this can be closed.
