### ISSUE TITLE
Internal developer docs - instructions on how to build Galasa code locally - totally missing everywhere

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1243]
## Story
As a galasa developer, I want to be able to build each repo locally, so I can run unit tests which may (or may not) exist in each repo, find bugs earlier, and generally understand what the official build process is doing.

## Background
For the CLI repo, and all the others, it's not obvious how to build things.

## Tasks
- [x] Add a build-locally.sh into the root of each repo, and mention it in the readme.
- [x] Add a set of instructions into the developer-docs
  - [x] How to over-ride the sourceMaven setting on the gradle command-line.
  - [x] How to set up a certificate store so https can be used to pull-in plugins and artifacts.
- [x] CLI
- [x] maven
- [x] gradle
- [x] obr
- [x] framework
- [x] extensions
- [x] managers
- [x] wrapping

**Comment by techcobweb** [comment]
Now have several repositories with build-locally.sh scripts to demonstrate the building of each repo.
Allows us to run unit tests without submitting code to a pull request for official building.

**Comment by techcobweb** [comment]
OBR should be in-scope for this. Then it can all be run locally without first deploying it to docker or kube.

**Comment by techcobweb** [comment]
This should close out today.
