### ISSUE TITLE
Migrate build pipelines from the external to internal cluster

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1244]
## Story
As a galasa developer I want to have builds run off the internal Kube cluster, so that they are fast and reliable and cheap for the department.

## Background
We need to migrate the build pipelines back to the internal cluster from the external cluster, due to the external cluster's speed (or lack thereof).

Aaron and I have put together the build pipelines and the necessary tasks for the Automation, Wrapping, Gradle, Maven, Framework, Extensions, Managers, OBR, and BuildUtils repos. The pipelines for Automation, Wrapping, Gradle, Maven and BuildUtils we have successfully ran.

## Tasks
To be able to run these pipelines in the internal cluster, the following changes need to be made:

- [x] Change Webhooks in Github org to call new proxy program (find out more from James)
- [x] Deploy EventListeners in a different namespace.
- [x] Make sure all Secrets that are needed are set up in internal cluster (I believe the GPG secrets for maven and gradle are, but unsure about the others)
  - [x] re-configure secrets into the vault
  - [x] re-config secrets manager into the new namespace.
- [x] Create apps in the internal ArgoCD to sync the K8s cluster with the Automation repo
- [x] Change namespace in yaml files from 'galasa-pipelines' to the new namespace name (galasa-build)
- [x] Update documentation to reflect any changes

Once ready to run the pipelines:
- [x] The task recycle-deployment will need to be completely changes as it will no longer be interacting with a Deployment on the same cluster, so cannot simply do 'kubectl rollout restart deployment X'

- [x] Convert pipelines to use Helm chart so they can be used for releases

**Comment by jadecarino** [comment]
Yesterday I manually moved all Secrets to Vault from the IBM Secrets Manager. We need a Secrets Manager Operator set up to configure the internal cluster to use Vault. James has raised an issue for Mike Baylis to do this.

Build tasks for the Github Monitor have been added to the main-automation pipeline, and I am trying to run it manually using a PipelineRun to get that image built and pushed to harbor. I have created a harbor-creds secret for this in the meantime while waiting for the secrets manager operator etc. Unfortunately, still getting an Unauthorised, investigating this today.

**Comment by jadecarino** [comment]
Github monitor image pushed to harbor

**Comment by hobbit1983** [comment]
@jadecarino can we update the tasks on this issue.  I know we have made progress in this area.

**Comment by jadecarino** [comment]
@hobbit1983 I'd argue this can be closed now, as all builds that we had running externally have now been migrated to the internal cluster. The only thing in that task list that hasn't been done is the secrets manager operator, but this work is not with us, its with Mike B.

**Comment by jadecarino** [comment]
@hobbit1983 Ignore previous comment - have discussed with James to convert these to use Helm chart so they can be used in releases.
