### ISSUE TITLE
Verify that 3270 streams support colours.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1248]
## Story
As a galasa user, I want 3270 streams from applications my test code uses to contain colour, so that my tests can validate that the application is using the correct colours.

## Background
This issue was done in haste: https://github.com/galasa-dev/projectmanagement/issues/990

We need to prove that the new API works as described in the issue above.
So that it provides colour to the 3270 manager.

The test code should be able to inquire the colour of the current cursor position and the highlighting of that field.   These issues were also discovered by the CiP team testing the CBSA application.  A starting point would be to write 3270 manager test code that interacts with that application to ensure that from an E2E perspective the code runs as expected.  From this we should be able to extract the 3270 byte stream that represents the colour fields in the terminal to allow us to write unit tests for this capability

## Tasks
- [x] Understand what the above story was aiming at ;-)
- [x] Write an 'exploratory' piece of code to capture what colour-enabled 3270 streams look like
  - we have code which will trace out the byte stream of the 3270 stream mid-test on the wire.
  - we have the updates to the `ITerminal` class on what the new enhancements are.
- [x] Embody the colour-enabled 3270 streams into a unit test which runs as part of the manager build.
- [x] Double-check that when we write the terminal output to the RAS recording, you can play it back and still get the colours.
- [x] Understand what manager docs are there already, and update the manager docs as required.

**Comment by hobbit1983** [comment]
Is this code ready for review?

**Comment by eamansour** [comment]
Yep, will be opening another PR for a small 3270 manager documentation update now.
