### ISSUE TITLE
Technical Debt: Clean up garbage javadoc warnings in framework/managers build.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1249]
## Story
As a galasa developer I want to be able to build the framework and manager component without seeing a ton of warnings which may hide a more important error amongst the garbage, so I can be sure the code is good before submitting it.

## Background
Run a local build on the framework component:

```
/Users/mcobbett/builds/galasa/code/external/galasa-dev/framework/galasa-parent/dev.galasa/src/main/java/dev/galasa/SharedEnvironment.java:26: warning: no @return
    int expireAfterHours() default 8;
        ^
Note: /Users/mcobbett/builds/galasa/code/external/galasa-dev/framework/galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/TestClassWrapper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/mcobbett/builds/galasa/code/external/galasa-dev/framework/galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/internal/cps/FrameworkConfigurationPropertyService.java:24: error: bad use of '>'
 * p>This class is used to drive the registered CPS service, and retireve values
    ^
/Users/mcobbett/builds/galasa/code/external/galasa-dev/framework/galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/internal/cps/FrameworkConfigurationPropertyService.java:26: error: unexpected end tag: </p>
 * </p>
   ^
...etc... There are a ton of these.
```

The same happens in these repositories:
- Managers
- Framework

There is an issue with gradle wherebye javadoc errors are sent to the terminal rather than the stdout stream, so can't be captured and logged normally, resulting in this pollution of the build console output.

It can be turned off, by turning off the javadoc linting in the builds, but then we wouldn't see any failures at all ever.

The errors can be classified simply as:
- Missing text against the javadoc element. (so what).
- Some other issue (parameter not described, mis-match in parameters vs. javadoc parameter name)...

The first of these can be left, the 2nd part needs fixing. Then we can hide all the errors by turning off Xlint. Rationale for this is that we wouldn't see any new failures anyway, amongst the mass of missing text warnings.

OR

We fix up all the errors and leave XLint working.

## Tasks
- [ ] Managers repo:
  - [ ] Fix the issues relating to bad javadoc names/missing parameters/return statements...
  - [ ] Turn off javadoc Xlint setting so we don't see the other errors.
  
- [ ] Framework repo:
  - [ ] Fix the issues relating to bad javadoc names/missing parameters/return statements...
  - [ ] Turn off javadoc Xlint setting so we don't see the other errors.
