### ISSUE TITLE
CLI tool should be internationalised

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1252]
## Story
As a galasa command-line tool user, I want to be able to received error messages in my own language, so I can understand what to do to correct the situation.

## Background
The CLI tool `galasactl` does not internationalise any of its error output strings.

I imagine that this won't be one of our highest priorities for now.

## Tasks
- [ ] Gather the strings into string templates in a message catalog
- [ ] Load the catalog based on locale settings the user is currently using
- [ ] Organise the strings so they could be translated if required.
- [ ] Build process to render the strings into something which can be added to the documentation.
