### ISSUE TITLE
CLI tool should not output logging unless asked to.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1253]
## Story
As a user of the galasactl CLI tool I want to invoke the tool and not see the logging by default, and see it when I opt-in to see it, so that I have more control over what the tool outputs.

## Background
The `galasactl` tool outputs logging (to stderr or stdout) which it should only do if some command-line option is used.
eg: --log -

This makes any script have verbose output, when you might want it to be quiet and just get on with what it has been told to do.

Error messages should not have timestamps on them. Timestamps belong in the log.

An option to direct the log at a file would be good also.

Example of current output:
```
2022/11/07 12:55:03 Galasa CLI - Assemble tests
2022/11/07 12:55:03 Stream "XXXXX" is missing from ecosystem
```

## Tasks
- [x] Log only when `--log -` is specified. To stdout.
- [x] Logs stored in file when --log ${filepath} | -l ${filepath}
- [x] Updated -h | --help instructions
- [x] Error messages should be on stderr (and in the log).

**Comment by techcobweb** [comment]
Implemented in teh same pull request as story #1261
