### ISSUE TITLE
CLI project should be built using Gradle

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1254]
## Story
As a galasa developer, I want to build the CLI project using gradle so that it's easy to build, and the build process can use the same steps that I am using locally in order to build the tool, so that building is easier, and I can trust my local build throws up the same results as the remote build.

## Background
There are several reasons why I think we should be building the CLI using Gradle:
- The reliance on the `framework/openapi.yaml`, currently being found by using `../framework/openapi.yaml` to jump to the sibling folder project. Each project should be self-reliant. This is breaking modularity. You should be able to build the cli code without first having to clone the framework code.
- The `openapi.yaml` in the framework folder should be a versioned artifact in its' own right, for such purposes above.
- There is a generate step in the build, which should be part of the gradle build, using a gradle plugin.
- The build of the go code should re-run the unit tests, which is what you get with a gradle build of go code I believe.
- The command-line tools built should be published to the local maven repo, so the artifacts can be extracted and published elsewhere.

## Tasks
- [ ] The frameworks repo gradle build should publish the openapi.yaml as a versioned artifact which the cli tool can rely upon.
- [ ] The CLI repo should use gradle to get the openapi.yaml file, preserving modularity.
- [ ] The CLI build should publish a jar/zip containing the built executables.
- [ ] The CLI build should be running unit tests.
- [ ] Can the generate steps be enclosed within a gradle builder ? If so then it will make the tekton task loads easier.
