### ISSUE TITLE
Code coverage metrics report needs creating and publishing for each build component

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1255]
## Story
As a client looking to see if Galasa is ready for adoption, I want to see that the galasa code coverage is substantial, so that I have confidence in the galasa code, and it's not a blocker for my adoption.

## Background
- We had some unit tests at some point, and spent some time in the past looking at gathering Jacoco reports.
- Junit tests were discontinued for some reason. Taking too long to write them ?
- last ran in June: https://galasadev-cicsk8s.hursley.ibm.com/codecov/

## Tasks
- [ ] For each component, alter the build process (of the 'main' branch) to produce a code coverage report.
  - [ ] cli (no unit tests until recently)
  - [ ] framework
  - [ ] managers
  - [ ] gradle
  - [ ] maven
  - [ ] others ? 
There are 6+ repositories with code we want to do this for.

- [ ] Gather all of the coverage reports into a single report site, merging reports as required.
- [ ] Publish the reports on public site.
