### ISSUE TITLE
Javadoc : @author tags should be stripped/not used.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1257]
## Story
As a galasa developer I don't want to see `@author` tags in the source code, so that the javadoc output isn't cluttered with such information, and so the javadoc can be re-shipped in IBM documentation.

## Background
- Git blame can tell you who wrote something very easily, with more granularity than the @author tagging can.
- @author tags clutter up javadoc
- IBM guidelines say we shouldn't use @author tags
  - Galasa javadoc is pulled-in for the IBM VTP which gets shipped, so we should follow IBM guidelines

- This isn't a very high-priority issue, as it's not functional, but more like a quality improvement to the readability of the source code.

## Tasks
- [ ] Add this restriction to the contribution guidelines.
- [ ] Write a script which strips out all lines with @author tags in the source code.
- [ ] Check-in any source files which have the been changed.
