### ISSUE TITLE
Technical Debt: Wrapping project should use Gradle instead of Maven

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1259]
## Story
As a galasa developer, I want to be able to build all the source projects using the same build tool (gradle), so that I don't need to install others (maven), update versions, and have fewer moving parts in our overall build system.

## Background
The wrapping project uses maven.

What's stopping it being converted to being a gradle project ?

We should be consistent so we only need one build orchestration tool, and that's gradle.

## Tasks
- [ ] Spike story to investigate what's holding us back from doing this now.
- [ ] Convert the local build over to use gradle.
- [ ] Change the tekton build to use the new gradle mechanism.

**Comment by techcobweb** [comment]
@Jimbo4794 Is there any meat you'd. like to add to this story ?

**Comment by Jimbo4794** [comment]
I dont have much detail interms of current blockers on preventing us from doing this work, but can give some detail on the current impl.

The purpose of the wrapping project is to take non-osgi bundled dependancies from maven central, and create an osgi bundle and corresponding manifest for the dependancy. This is required for the apache felix container we use to operator the galasa runtime. The current process uses the apache felix bundle plugin to produce the bundle. It is down to the developer "wrapping" the dependacy to understand the exported packages from the original dependancy to ensure they are currently added to the produced manifest.

Looking at a current example I see that maven-bundle-plugin is being used over the biz.aQute.bnd.builder used for producing the osgi bundles. Spike story is needed to look into why this is the case
