### ISSUE TITLE
OBR project build should use Gradle instead of Maven

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1260]
## Story
As a galasa developer I want to build the OBR project using gradle instead of maven, so we have consistency across all of the projects in the choice of build orchestration tooling, I have fewer tools to use/install/understand, and there is less to go wrong in our builds.

## Background
- The OBR project uses a custom maven plugin (what does it do?) which was never ported to gradle.

## Tasks
- [ ] Spike to understand why we can't do this nowl.
- [ ] Port the custom maven build plugin to be a gradle plugin.
- [ ] Implementation of the gradle build
- [ ] Change the tekton build process to use gradle instead of maven.

**Comment by techcobweb** [comment]
@Jimbo4794 Is there any meat you'd like to add to this story ?

**Comment by Jimbo4794** [comment]
I think you have captured this quite well. As this was an a piece of work to enable the same features from the maven plugin inside the gradle plugin.
