### ISSUE TITLE
CLI should be able to create a blank project structure with an OBR laid out on the file system

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1261]
## Story
As a galasa user trying to build a test suite, I want to use a command-line tool to create a blank project structure with an OBR laid out on the file system

## Background
- Similar to creating an archetype.
- Parameters could form tokens to inject into the project.
- Could work with maven or gradle. Could create both, one or the other ?
- Could use custom template ?
- Could create the OBR, leave the OBR out, update the OBR ?
- What would the syntax be ? Something like this ?
```
galasactl \
project create \
--package myBasicPackageName \   << used for java package, OSGi package, maven group ID.
--obr  \.  << optional
--log -                                                   << log progress output to stdout
--force    << over-write things if they exist already, else leave intact.

```
~~--maven --gradle   << preferred build mechanism. Both allowed if you want. Default to maven.~~ - Removed from scope until we have a gradle OBR builder. See Story #1000 

## Tasks
- [x] Extend galasactl to include the new syntax, unit tests
- [x] Generated output includes 
  - [x] parent project + pom.xml
  - [x] test project + pom.xml
  - [x] obr project + pom.xml
  - [ ] manager project + pom.xml
  - [x] maven build process 
- ~~Test that generated output builds with gradle~~ Removed from scope until we have a gradle builder. See story #1000 and story #1333
- [x] Test that generated test runs without errors
- [x] Warnings and errors appear on stderr
- [x] Document new capability in the readme
- [x] Draft documentation to improve the official docs. See here: https://ibm.box.com/s/mz154y5e5q9a0k86zw619cfyfxmtj9of

**Comment by techcobweb** [comment]
The code for this has been delivered. Seems to work for me.
