### ISSUE TITLE
Allow PRs to show pending rather than errors when invoking the build.

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1263]
## Story
As a Galasa developer I wish to get the feedback during PR processing that the build is pending, rather than an error response - So I know that things are progressing and I need to wait for the build

## Background
- Currently the web hook gets a 404 response as there is nothing to direct the web hook at
- @jadecarino knows similar code we have already, which should be easier than starting from scratch.

## Tasks
- [x] Create a 'null' web hook 'swallower' which accepts webhook events, and returns 200 OK responses back to Github.
- [x] Update the PR to show 'pending'.
- [x] source lives in github monitor and other tools are in automation repo. build-images ...
- [x] Package the 'swallower' into a docker image as part of the build process
- [x] Build process should deploy the new docker image through argo CD on the external cluster
- [x] Add a web hook onto the org we want to monitor which points to this 'web hook swallower'
