### ISSUE TITLE
Trigger following main build pipelines after a main build

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1264]
### Story 

As a Galasa developer, when I merge changes into a repository and the main build for that repository gets triggered, I want all builds that follow that repo in the chain to get triggered also, so that my changes are reflected in the artefacts used by the following repos.

I also want to have artefacts built against my branch, so I can run regression tests against my branch's OBR.

### Background

Galasa repos are built sequentially, due to some repos using built artefacts of another repos. The other this happens in is:
- Wrapping
- Gradle
- Maven
- Framework
- Extensions
- Managers
- OBR

### Tasks 

- [x] Research how to trigger pipelines from the end of pipelines
   - [x] Using a tkn command is the simplest option here
- [x] Find docker official image for tkn or create our own
   - [x] No official image so will create own
- [x] Create tkn-cli task which allows us to use the tkn CLI to trigger a pipeline (this could also be used for other tkn commands as is generic)
- [x] Figure out what command you need to send to tkn to trigger a pipeline 
   - [x] workspace template yaml file needs to be passed in
   - [x] pod template yaml file needs to be passed in
   - [x] set serviceaccount so that it can push to harbor

- [x]  Add a trigger at the end of the Wrapping main build to trigger the Gradle main build
- [x]  Add a trigger at the end of the Gradle main build to trigger the Maven main build
- [x]  Add a trigger at the end of the Maven main build to trigger the Framework main build
- [x]  Add a trigger at the end of the Framework main build to trigger the Extensions main build
- [x]  Add a trigger at the end of the Extensions main build to trigger the Managers main build
- [x]  Add a trigger at the end of the Managers main build to trigger the OBR main build
- [x] Test a main build (up until OBR) (takes around 40 mins...)

These are the pipelines which I consider done/stable, triggers for the following pipelines can be added in future.

After the above is done:
- [x] Edit so that parameters can be passed in for branch builds, instead of just --use-param-defaults 
- [x] As task check-branch is conditional and only runs if the build isn't against main, figure out how to use it as the runAfter. If check-branch is executed, it should be the runAfter for anything else, but if not, it can be ignored
   - This will need to be improved in future, I have removed the conditional when statement for check-branch, and used a conditional in the script itself to essentially not do anything if the branch is 'main'
- [x] Test this by running a branch build from Wrapping to OBR, check the images are in harbor and the maven repos are up

**Comment by techcobweb** [comment]
Why do we have to do this ?
In other projects I've worked on which are multi-repo, the change would be built, but won't be 'adopted' by the overall packaging until you bump the dependencies on the later components. Then you have explicit control of what versions are picked up for everything, and you can re-create a build if necessary. Wondering what the differences are here. Maybe I just need it explained to me how the inter-component versioning works.

**Comment by jadecarino** [comment]
Hi Mike, thanks for your comment, interesting to hear a different viewpoint. I have updated the story with more detail now, as I only opened the issue quickly on a call earlier, so I have a bit more of an explanation for which repos this applies to.

I believe we do this in development so that all components have the most up-to-date version of the previous components code. I suppose we do this because, if Extensions was already using v25 of Framework and then I fixed a bug in Framework, I'd want it reflected in Extensions right away instead of waiting for the next version change. That's how we have always worked, but happy to speak next week about it :)

**Comment by techcobweb** [comment]
The CLI also depends on the framework currently.

**Comment by jadecarino** [comment]
Useful link: https://github.com/chmouel/tektoncd-cli/blob/main/docs/cmd/tkn_pipeline_start.md

**Comment by jadecarino** [comment]
Nearly there, but seems tkn does not recognise the kube cluster we are on (Error: Pipeline name branch-gradle does not exist in namespace galasa-build). Can configure by doing --kubeconfig and pass it a config file during the tkn command but unsure if thats the right thing to do.

**Comment by jadecarino** [comment]
Hoping to have this done today but getting an odd error: when I run tkn pipeline start branch-gradle it says 'branch-gradle does not exist on galasa-build', and when running tkn pipeline start --filename ...../gradle/build-branch.yaml, it says 'no such file or directory'.

**Comment by jadecarino** [comment]
Unfortunately, I didn't manage to get this done this sprint. If anyone plans to continue tomorrow:
- [ ] A config file needs to be made for the galasa-build-bot service account (Useful link on how to do this: https://www.ibm.com/docs/en/cloud-paks/cp-management/2.0.0?topic=kubectl-using-service-account-tokens-connect-api-server)
- [ ] The config file **cannot** be checked into Github as it contains a certificate to connect to our k8s cluster. The config file needs to be added to the cluster as some sort of Secret. Maybe add the certificate and token to a secret in vault, and pass them into the ExternalSecret I have started working on (infrastructure/cicsk8s/galasa-build/external-secrets/secret-kube-config.yaml).
- [ ] As always everything is managed by argocd so remember to sync.
- [ ] I have added the first use of the task to the branch-wrapping pipeline, where it calls branch-gradle. The tkn command is correct (I have tested locally) other than the value for --kubeconfig, as the location of the config file will depend on how/where you add the config file as a secret/volume etc. I have commented this task out of the pipeline for now though, so branch-wrapping isn't caused to fail.

**Comment by techcobweb** [comment]
You can create a sealed secret in Kube, essentially getting Kube to sign the secret, and that sealed secret can be checked-in to public git and deployed with ArgoCD as a regular kube resource. Is that the sort of thing you need here ?

Article on creating them here: https://medium.com/codex/sealed-secrets-for-kubernetes-722d643eb658
