### ISSUE TITLE
Validate the technology stack for Galasa.dev

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1270]
## Story
As a galasa content developer I want to understand how the website is running, and understand the networking and SSL configuration, so that we are ensuring we are running the most appropiate stack.

## Background
The galasa.dev site is currently running using a code engine and a Cloud Internet services instance on IBM cloud. There appears to be lots of unusual activity and setup in place. We need to ensure that the site is being run to best practises with a better understanding of the SSL configuration

## Tasks
- [ ] Understand best preactise for webite hosting on IBM cloud
- [ ] Determine if we want to move the site onto the k8s cluster
- [ ] Understand the SSL configuration and certificate ordering and renewl process
- [ ] Correctly use the loadbalancing
- [ ] Ensure Edge functions are being appropiatly used

**Comment by KirbyKatcher** [comment]
tasks in this issue have been completed as part of the #1280 spike task in order to understand the correct way to expand our use of the IBM cloud technologies
