### ISSUE TITLE
Automate the cloud engine deployment of Galasa

### ISSUE THREAD

**Issue by Jimbo4794** [galasa-dev/projectmanagement#1271]
## Story
As a content developer, I want to push my changes to github, so that the changes can be built and validated automatically.

## Background
The old cloud foundry instances are still the automated process. We need to move that to code engines

## Tasks
- [x] Speak to James and understand the process for creating a new galasa.dev image and image recycling
- [x] Add process to write up of cloud processes
- [x] Plan new build process
- [x] Create a pipeline to deploy a new docs image on 
- - [x] a image in ICR
- - [x] an application code engine
- - [x] ~a new code engine instance~( not needed as going to use the existing path)
- - [x] ~a new code engine pool~( not needed as going to use the existing path)
- - [x] ~a new load balancer~( not needed as going to use the existing path)
- - [x] add the wildcard certificate in the new application domain mapping
- [x] ~Create dockerfile for use on ibm cloud (i.e. doesn't include external mimages)~( Completed by Ben Cox as part of issue #1334)
- [x] Continue non-deploy checks 
- - [x] Dead link check
- - [x] Certificate expiration check and update
- [x] Automate image recycle in the galasa.dev code-engine (for main only)

**Comment by techcobweb** [comment]
waiting to see if we will be using cloud engine or cirrus

**Comment by techcobweb** [comment]
What's stopping this issue being closed please ? @KirbyKatcher
