### ISSUE TITLE
Build pipelines need additional parameters to build from a branch other than main

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1273]
## Story
As a galasa developer, I want to specify a branch to build artefacts from in the build process, so that I can run regression tests on a branch other than main.

## Background
Currently, the build process only builds artefacts from main - there is no option to build from a different development branch. By parameterising the branch and `docker-build` task in the pipelines, builds will become more flexible and will help in allowing us to test changes to one galasa component (e.g. managers) without needing to rebuild every other component.

## Tasks
- [x] Replace hardcoded references to the `main` branch in all the pipelines with a `branch` parameter, defaulting the parameter to `main`
- [x] Parameterise `refspec` as above
- [x] Parameterise the `imageName` (specifically the image tag) and the `buildArg`'s `tag` argument in the pipelines' `docker-build` task
