### ISSUE TITLE
CemtManagerSpi package is wrong

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1276]
## Story
As a galasa test developer I want ICemtManagerSpi to appear in the correct place in the package hierarchy such that it is more consistent with the other manager spi interfaces.

## Background
ICemtManagerSpi is in a package dev.galasa.cicsts.cemt.spi.spi all on it's own.

Seems it should be in dev.galasa.cicsts.cemt.spi (without the trailing .spi)

## Tasks
- [x] Move it to the correct place in the java package hierarchy.
- [x] Bump CECI Manager
- [x] Bump CEMT Manager
- [x] update Release.yaml
- [x] Find where the build fails and fix it
- [x] Run what tests we can to verify nothing is broken

**Comment by hobbit1983** [comment]
might also affect the ceci package

**Comment by hobbit1983** [comment]
This is done.  Just need to sort out my signing keys again so I can sign the commit and I will create a PR

**Comment by hobbit1983** [comment]
@techcobweb happy for me to estimate this as a point or so - or would we prefer we do it at a meeting to get the shared understanding?

**Comment by hobbit1983** [comment]
Configured my gpg keys and pushed - some copyright failures I need to fix and then this can go to review

**Comment by hobbit1983** [comment]
@techcobweb can you review https://github.com/galasa-dev/managers/pull/827 please
