### ISSUE TITLE
Release a container image which has the galasactl tool installed, so it can easily be used in CI/CD pipelines

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1279]
## Story
As a CI/CD engineer, I want to use the galasactl tool packaged inside a container image to launch automated tests on my infrastructure, so I can do so without the hassle of installing the tool and having to build my own container image with it inside.

## Background
- The galasactl tool is expected to be used in CI/CD containers, so we should ship a docker/container image with it installed inside. 
- Ideally it would be a multi-arch image, but not sure how to build those yet.
- Should be published every (main) build of the CLI tools
- Should be made available as a 'released' artifact externally
- We should be using it ourselves for testing galasa
- Not sure of the priority for this

## Tasks
- [ ] CLI build process to construct a docker image
- [ ] CLI build process to push docker image to an external repo
- [ ] Investigate multi-archi images, in case it's easy to turn the image into mult-arch
- [ ] Change test process to use our own CLI docker image
- [ ] Document that this image is available and where in the external docs.

**Comment by techcobweb** [comment]
Duplicate story. Closing as a result of talking to @AaronJhaj

**Comment by techcobweb** [comment]
Duplicate story. Closing as a result of talking to @AaronJhaj
