### ISSUE TITLE
spike: Understand how best to host web applications like galasa-dev in IBM cloud.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1280]
## Story
As a galasa dev engineer I want to understand how to use the available IBM cloud technology in the best way possible to host a web site such as galasa-dev.

## Background
- This is a spike story kulled from story #1270
- Perhaps would be good to talk to @ind1go and @Jimbo4794 or someone who may have already explored the technology stack available.
- The 'edge' functions are 'weird' ! << @Jimbo4794 

## Tasks
- [x] Get access to the IBM cloud account (Will can grant magic powers!)
- [x] Learn about the most recent code engine technology (self-education) (reading and playing (if safe))
- [x] Decide how we would use code engines technology to host the galasa-dev site properly
- [x] How would we replace the existing github actions automation we have - update story #1271 as required
- [x] Review with @CaroMac so she is aware of how it works and can update things with their release process in future
- [x] Write up conclusions on what work needs doing, adapting story #1270 with the results.

**Comment by techcobweb** [comment]
@KirbyKatcher perhaps this is something you can look at with help from @Jimbo4794 and @hobbit1983 ?
