### ISSUE TITLE
Set up Simplatform application

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1283]
## Story
As a Galasa user, I want to be able to run galasa example tests against a simbank application running on a deployed kubernetes cluster, so I can test that I am able to reach my ecosystem with Galasa and everything is working OK.

## Tasks
- [x] Create the resources needed for the Simplatform application (old versions here https://github.com/galasa-dev/simplatform/tree/main/argocd/applicationHelm )
   - [x] 1 Simbank Deployment
   - [x] 4 Services
- [x] Set up Helm chart and values
- [ ] Document how to start the Simplatform application in the readme only.
  - ~~Create a draft of the docs in markdown in the internal developers guide~~.

**Comment by techcobweb** [comment]
Ready for review. James/Mike.

Not sure the importance of this. Is it really necessary to host an instance ? Benefits ?

**Comment by CaroMac** [comment]
Agreed with Mike that we need discussion in the team regarding this issue to confirm the best way forward.

**Comment by techcobweb** [comment]
Aaron Jhaj
  11:10
also that work item regarding docs, i spoke to Caroline and she said that Will and James were going to have a discussion about it and she agreed to do it in the new year


Michael Cobbett
:spiral_calendar_pad:  11:11
Yes, but that's really about whether she harvests the information it the galasa-dev docs. We can still create draft docs in an md file in the developer guide ?
11:12
If she has to put anything into the galasa-dev docs she has nothing to go on in terms of content to tidy-up and deliver. She will have to come asking questions and distracting people to get answers... easier for her if we had draft docs with the important bits/syntax snippets/examples...etc ready for her no ?


Aaron Jhaj
  11:16
ah ok yep makes sense

**Comment by techcobweb** [comment]
Lets make sure the readme is up to date with the helm install instructions, but not add to the official dev.galasa site.

**Comment by jadecarino** [comment]
I have been staring at this item for several days now, and I still don't understand what it is about, hence why I think I've been pushing it to the bottom of my list for so long. I suppose I'm happy enough with the fact that if you exec into the simplatform-amd64 image and run the simplatform.jar, it starts Simplatform, inside that image. I can see that there is an ArgoCD app on the internal ArgoCD for the cicsk8s cluster called 'simplatform-prod-app' that has applied all of the resources for the app to the cicsk8s cluster. I don't understand how you would connect a locally running Galasa Simbank test to this instance of the application running on the cluster. Would it be through CPS properties?  What would be the benefit of doing this also? I'm struggling to close this item off as I don't feel I understand really what it's for. I suppose I just opened this item thinking it was important to recreate any and all of the old infrastructure, but this bit seems almost like its not that useful. @hobbit1983 @Jimbo4794 if we could have a quick chat about this anytime you're free that would be great?

**Comment by techcobweb** [comment]
As it is, I think someone could get hold of the simplatform stuff, and use the helm chart to install it right ?
In that case, it's done I think. 
We don't want to publicise this further, as it's not a 'normal' thing people will be doing.
Simbank app is typically run locally when people are learning Galasa, so I personally don't care if it gets installed on a kube system to invoke tests against.
Suggest we close this one as "done enough"
