### ISSUE TITLE
Re-instate the CECI Manager Unit Tests

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1284]
## Story
As a Galasa developer, I want to have the CECI Manager unit tests working, so that quickly test changes to that code base.

## Background
This uses power mock and mockito which in later release don't always play together nicely.  Some of the function used from power mock is now available in mockito and we should be able to remove all the power mock code from the test

## Tasks
- [x] remove imports on power mock to find all the places it is used
- [x] replace those statements with mockito replacements
- [x] keep running the test to prove it all works
