### ISSUE TITLE
Automate the branch-level regression testing process

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1286]
## Story
As a galasa developer, I want to automate the branch-level regression testing process, so that I can simplify and speed up the process for other developers.

## Background
Currently, several manual steps need to be completed in order to run regression tests against branch builds. These include running branch-level build pipelines, creating an argocd app that deploys the built artifacts, running the regression test suite against the deployed artifacts, and deleting the argocd app once the regression tests are complete. This process can be automated with a shell script.

## Tasks
- [x] Create a shell script that:
  - [x] Runs the appropriate branch-level build pipeline (triggers will start subsequent pipelines)
  - [x] Creates an argocd app to deploy the relevant artifacts
  - [x] Runs `galasactl runs prepare` to create a regression test portfolio if it does not exist
  - [x] Runs `galasactl runs submit` to run regression tests
  - [x] Deletes the argocd app once the regression tests are complete
- [x] Update argocd roles to allow code-committers to create/edit/delete new apps, while leaving existing apps (main-maven-repos, javadoc-site, etc.) for the code-admins to manage
- [x] Test the shell script on an existing branch
