### ISSUE TITLE
3270 screen images available in an image format (eg: png) for local tests.

### ISSUE THREAD

**Issue by ApurvaS28** [galasa-dev/projectmanagement#1290]
## Story
As a Galasa user I want to view the terminal screens as image files so I can archive them and view them without having to use the eclipse UI.

## Background
This story was raised by a Galasa user but lines up with our CLI ideas so creating as a new story

I wanted to view the images of the past runs but they are in a different format ? 
![image](https://user-images.githubusercontent.com/94789018/205502325-a718e75a-6a72-44ce-b545-3507c68c04c4.png)
![image](https://user-images.githubusercontent.com/94789018/205502346-6140070b-30d0-413f-9cd8-04d645679c29.png)

The terminal images are listed as below .How can i view these ?
![image](https://user-images.githubusercontent.com/94789018/205502365-70f5acb3-0e8a-466a-aaf6-326d82006b9f.png)

There is a known limitation in how we store files in couchDB... see epic https://github.com/galasa-dev/projectmanagement/issues/1414

As a temporary workaround, we will limit the writing-out of 3270 images to the local file system, so running local tests can get these images easily, and ecosystems will be able to get the images once epic #1414 is implemented.

## Tasks
- [x] Separate the code which generates images and unit test it.
- [ ] 3270 manager to figure out if the ArtifactRoot file folder it's passed from the RAS service is a local filesystem or a remote one.
- [ ] 3270 images are always created if the file system is local.

**Comment by hobbit1983** [comment]
@jadecarino  can you help Apurva out please

**Comment by techcobweb** [comment]
Wondering. Is it possible to attach one of these terminal files to this issue please ?
That might help with diagnosing the problem...

**Comment by ApurvaS28** [comment]
[term1-00001.gz](https://github.com/galasa-dev/projectmanagement/files/10152149/term1-00001.gz)
Please refer to the file . It might also help if you could check and let me know if i am looking at the correct place.

**Comment by hobbit1983** [comment]
@ApurvaS28 when Galasa records a terminal screen, it is stored as a compressed JSON file.  The Eclipse Galasa plugin contains a 'Galasa Results' view that can be used to view the content of the RAS and parses the content and displays the terminal screen.  

have you tried to view the terminals through the Galasa Eclipse plugin and found problems?

**Comment by ApurvaS28** [comment]
Hey will ,

It's working when I tried through galasa .But i wanted to view the images through any other app so that I can make a doc and store it for the future .
________________________________
From: Will Yates ***@***.***>
Sent: Monday, December 5, 2022 7:19:47 PM
To: galasa-dev/projectmanagement ***@***.***>
Cc: Apurva Saxena ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [galasa-dev/projectmanagement] View galasa termianl images of past runs in Galasa ? (Issue #1290)

@ApurvaS28 when Galasa records a terminal screen, it is stored as a compressed JSON file. The Eclipse Galasa plugin contains a 'Galasa Results' view that can be used to view the content of the RAS and parses the content and displays the terminal
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

@ApurvaS28<https://github.com/ApurvaS28> when Galasa records a terminal screen, it is stored as a compressed JSON file. The Eclipse Galasa plugin contains a 'Galasa Results' view that can be used to view the content of the RAS and parses the content and displays the terminal screen.

have you tried to view the terminals through the Galasa Eclipse plugin and found problems?

**Comment by hobbit1983** [comment]
Thanks for that clarification Arpurva.  Currently we don't store the terminal screen shots as images (although we are thinking about adding some capability in the future.  Would you mind if we converted this to a feature request to help us track the enhancement?

**Comment by ApurvaS28** [comment]
Sure .That would be great .


From: Will Yates ***@***.***>
Sent: 05 December 2022 19:28
To: galasa-dev/projectmanagement ***@***.***>
Cc: Apurva Saxena ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [galasa-dev/projectmanagement] View galasa termianl images of past runs in Galasa ? (Issue #1290)

Thanks for that clarification Arpurva. Currently we don't store the terminal screen shots as images (although we are thinking about adding some capability in the future. Would you mind if we converted this to a feature request to help us track
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Thanks for that clarification Arpurva. Currently we don't store the terminal screen shots as images (although we are thinking about adding some capability in the future. Would you mind if we converted this to a feature request to help us track the enhancement?

**Comment by techcobweb** [comment]
I guess in the meantime you might screen-grab/capture the images you need from the eclipse views then.

**Comment by techcobweb** [comment]
Current thinking about this is that the images should be rendered server-side when they are created and deposited with the other test artifacts in the dss store.

Then the images are available whether a command-line tool downloads them later, or whether the eclipse client is used to open the stored artifacts.

format of svg or some vector-based format might be easier for compression to shrink, rather than png or other rasterised format.

**Comment by techcobweb** [comment]
Scheduled this item for getting work attention, but hoping that it will be split up into pieces which are deliverable independently.

eg: 
- Generate a file which doesn't have much inside. But store it and retrieve it as if it did.
- Pump detail into the generated image file to make it match the json visually.

Or perhaps there is a better split ?

**Comment by hobbit1983** [comment]
@eamansour @jadecarino should this be marked as in progress?

**Comment by hobbit1983** [comment]
@eamansour @jadecarino should this be marked as in progress?

**Comment by ApurvaS28** [comment]
Hi Will ,

I was trying to install the eclipse in my pc and could see the that any older version of JDK before v17 is not supported for Eclipse IDE for Java Developers .

Can you suggest me a way I can fix this .

Thanks & Regards
Apurva Saxena
CICS System Programmer-Mainframe
Phone:91-7523862924
E-mail: ***@***.******@***.***>
Webex: https://kyndryl.webex.com/meet/apurva.saxena
***@***.***

From: Will Yates ***@***.***>
Sent: Friday, March 3, 2023 3:12 PM
To: galasa-dev/projectmanagement ***@***.***>
Cc: Apurva Saxena ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [galasa-dev/projectmanagement] 3270 screen images available in json and an image format (eg: png/svg/jpg?) (Issue #1290)

@eamansour @jadecarino should this be marked as in progress? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned. Message ID: <galasa-dev/projectmanagement/issues/1290/1453245868@ github. com>
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

@eamansour<https://github.com/eamansour> @jadecarino<https://github.com/jadecarino> should this be marked as in progress?

**Comment by hobbit1983** [comment]
@ApurvaS28 you should be able to run eclipse with a Java17 JDK but specify Java 11 in the JRE tab of the galasa  launch configuration - does that help?  If not can you open a new issue please rather than re-use this
