### ISSUE TITLE
Build pipeline for CLI repo

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1293]
## Story
As a galasa developer, I want to be able to build the CLI repo that contains code for galasactl, so that I can test changes in my PRs and build and redeploy the binary when I merge changes into main.

## Background
The old pipeline to build the CLI can be found in https://github.com/galasa-dev/argocd/tektonHelm/templates/cli/task-galasactl-build.yaml.

## Tasks
Convert the existing CLI pipeline into one we can use in the new infrastructure.

- [x] Create pr-cli and branch-cli pipelines
- [x] Create any necessary tasks that don't already exist
- [x] Deploy the 3 images to harbor:
   - [x] galasa-cli-amd64
   - [x] galasa-cli-ibm-amd64
   - [x] galasa-cli-binary
- [x] Test the galasa cli binary by pulling and running a galasactl command inside the image

**Comment by AaronJhaj** [comment]
pulling the cli-binary image and trying to run it I get a platform error:` WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by AaronJhaj** [comment]
pulling the cli-binary image and trying to run it I get a platform error:` WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

**Comment by AaronJhaj** [comment]
cli binaries downloadable here https://development.galasa.dev/main/binary/cli/
