### ISSUE TITLE
Build pipeline for integratedtests

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1294]
## Story
As a galasa developer, I want to be able to build the integratedtests repo, so that I can test changes at the PR level and build changes at main, so that the latest version of Galasa code is reflected in our integration tests.

## Background
The old pipeline to build the integrated tests can be found in https://github.com/galasa-dev/argocd/tree/main/tektonHelm/templates/integratedtests

## Tasks
Convert the existing pipeline into one we can use in the new infrastructure.

- [x] Create pr-integratedtests and branch-integratedtests pipelines
- [x] Create any necessary tasks that don't already exist
- [x] Create any necessary deployments, services and ingresses
- [x] Deploy the integratedtests images to harbor

**Comment by techcobweb** [comment]
@jadecarino Are you able to flesh the wording out please to conform to the template ?

**Comment by jadecarino** [comment]
@techcobweb Yes sure was meant to do this on Friday, thank you for reminding me

**Comment by AaronJhaj** [comment]
changed maven-build task to take an array for the 'command' param instead of a string. reflected these changes in the other pipelines that call a maven-build
