### ISSUE TITLE
Build pipeline for codecoverage

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1295]
## Story
As a galasa developer, I want to be able to run the codecoverage pipeline, so that I can see an up-to-date report of our test code coverage of Galasa.

## Background
The old pipeline to run codecoverage can be found in https://github.com/galasa-dev/argocd/tree/main/tektonHelm/templates/codecoverage

This pipeline doesn't build a 'codecoverage' repo, so pr- and branch- are not necessary - it runs the jacoco tool against our code to generate a code coverage report (which was deployed to here: https://galasadev-cicsk8s.hursley.ibm.com/codecov/)

## Tasks
Convert the existing pipeline into one we can use in the new infrastructure.

- [x] Create codecoverage pipeline
- [x] Create any necessary tasks that don't already exist
- [x] Create any necessary deployments, services, ingresses etc for deploying the report
- [x] Deploy the report to development.galasa.dev/codecov

**Comment by AaronJhaj** [comment]
Currently blocked as integration tests need to be stable before changes to the maven artifact locations can be merge. These changes are needed to be merged before this pipeline can continue.

**Comment by AaronJhaj** [comment]
Pipeline is working and image is built and gets pushed to harbor. however the deployment currently isn't working and currently returns 404

**Comment by techcobweb** [comment]
Hi @AaronJhaj Welcome back. We had to delete your argocd application (sorry) to free up space, but feel free to re-create it as we freed up more space from elsewhere in the end anyway.

**Comment by jadecarino** [comment]
Fixed the path issue which was why the report was not being deployed, so this issue is now finished. Closing on Aaron's behalf.
