### ISSUE TITLE
Helm install into Minikube times out

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1296]
## Story
As a developer of testcases using Galasa, I want to deploy an ecosystem to a minikube instance of Kubernetes to try out galasa locally on my laptop.

As a developer of galasa code, I want to be able to deploy galasa to a minikube cluster, so that I can fix-test my changes to galasa code in a running environment.

## Background
- @Jimbo4794 and @techcobweb tried to deploy to miniukube on 9th Dec. It failed with a timeout somewhere.
- Should have worked.
- @hobbit1983 had it working on his older laptop I believe.

## Tasks
- [ ] Try it again, to show that it times out still.
- [ ] Investigate why it failed by looking at the logs in the pods, to find some long-running activity which doesn't complete.
- [ ] Figure out how we can increase the timeout values using settings in the helm chart.
- [ ] Make the changes to the code/helm chart to increase the timeouts, or make it so that the timeout doesn't occur.
- [ ] Re-test to show that it can be deployed to minikube.

**Comment by techcobweb** [comment]
Does it work in windows ? Do we have to cover this in this story too ?

**Comment by eamansour** [comment]
Still need to test it on Windows, it would be worth covering as part of this story.

**Comment by eamansour** [comment]
Successfully deployed an ecosystem to minikube on both Windows and Linux machines and have been able to run Galasa tests on the ecosystem.

**Comment by techcobweb** [comment]
Is this one complete now ? What's left to review ?
