### ISSUE TITLE
Improved admin experience adding streams to ecosystem : GalasaCtl to be able to manipulate Galasa streams in a deployed ecosystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1299]
## Story
As an administrator of a galasa ecosystem I want to be able to use the Galasactl to administer streams in an ecosystem, so I don't have to interact with etcd directly, and it's easier to use, and runs through the security mechanisms added already/later to the REST API.

## Background
Here's an excerpt from here: https://github.com/Jimbo4794/galasa-samples/tree/Sample-1-4-test-streams :

From this point we need to add several properties using the command of etcdctl put <key> <value>. This is to fuly define the test stream and the location of all the test artifacts to galasa. This can be made easier with a shell script if being commonly done, but you can also just run these commands (edited to your own needs):

```
etcdctl put framework.test.streams SIMBANK,EXAMPLE << separate story to remove this property

etcdctl put framework.test.stream.EXAMPLE.repo http://<XXX>:8081/repository/maven
etcdctl put framework.test.stream.EXAMPLE.obr mvn:dev.galasa/dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr
etcdctl put framework.test.stream.EXAMPLE.location http://<XXX>:8080/testcatalog/example
etcdctl put framework.test.stream.EXAMPLE.description "Example Test Stream"
```

Any new functionality MUST pass through the REST API, so adding new function to the command-line tool also requires the REST API to be enhanced.

### Stories covering this functionality:

Galasactl should be able to add a stream
The input should be a yaml file

```
galasactl create -f streamdefinition.yaml
```
where the file contains this:
```
api: v1alpha1
kind: galasa-stream
repo: http://mymavenrepo:8081/myrepo/maven
obr:
  - mvn:dev.galasa/dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr
initialTestCatalog: http://mymavenrepo:8080/testcatalog/example
description: "Example test stream"
```

- Properties need to be resources on the ecosystem
```
api: v1alpha1
kind: galasa-property
namespace: mynamespace
name: my.property 
value: xxxxxxx
```

- Separate story to add a checksum to guard against race conditions

- zosImage needs the same treatment
- cluster
- zosmf
- selenium

- ??? should we embrace the kubectl-similar syntax for resources on the ecosystem ?
- Should we retro-fit that to the properties APIs we've worked on already ?

multiple obrs can be specified. Either as a comma-separated list, or using multiple occurrances of the --obr flag.

All going well, there is no output, only a 0 exit code.
Errors end with a 1 exit code.

POST /resources

JSON payload to the REST Api: POST /streams
```
{
  "api" : "v1alpha1"
  "kind": "galasa-stream"
  "name": "bestsofar"
  "repo": "http://mymavenrepo:8081/myrepo/maven"
  "obr": "mvn:dev.galasa/dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr"
  "testcatalog": "http://mymavenrepo:8080/testcatalog/example"
  "description": "Example Test Stream"
  "testcatalog": [
    {
       name : xxx
       tags: [ ] 
       bundle: xxx
       class: (fully qualified)
    }
    ...
  ]
}
```

JSON respose: 201 (Created)
```
{
  ... the same as you'd receive from a GET command.
}
```

### Galasactl should be able to get the details about a stream
`galasactl streams get --name SIMBANK --format yaml`

should yield something like this on stdout
```
api: v1alpha1
kind: galasa-stream
name: SIMBANK
repo: http://<XXX>:8081/repository/maven
obr:   
  mvn:dev.galasa/dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr
  ... the other OBRs.
location: http://<XXX>:8080/testcatalog/example
description: "Example Test Stream"
state: enabled
...etc
}
```

### Galasactl should be able to update a stream
The input should be a JSON object: eg:
galasactl streams update --name "bestsofar" \
--description "new description" \
--obr "mvn:dev.galasa/new.group.id.dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr"

`location` and `repo` can also be updated.

`state` of enabled/disabled can also be updated.

multiple `obr` flags can be specified. The entire list gets updated.

Rest API to do this: PUT /url-to-ecosystem/streams/bestsofar
```
{
   ... the same as you'd receive from a GET command.
}
```
> Is the catalog a list ? or just a separate object ?
> What does the catalog url refer to ?

### Galasactl should be able to delete a stream
`galasactl streams delete --name SIMBANK`

### Galasactl should be able to list available streams in human readable form
`galasactl streams get`
Output is :
```
name     state
SIMBANK  enabled
EXAMPLE  enabled
BSF      enabled
PROD     enabled
```
ie: The most important thing about a stream is state. enabled/disabled.

This would have resulted in the REST call:
`GET /url-to-ecosystem/streams`
which returns a summary;
```
[
  {
    "name":"SIMBANK"
    "url":"http://ecosystem/streams/SIMBANK"
  }
  {
     ...etc
  }
]
```

To get the enabled/disabled state, the CLI will have to query the details from each one.
  

## Tasks
- [ ] add
- [ ] Trying to add to a stream which already exists should fail. You should be doing an update.
- [ ] galasactl streams get --format summary 
  - scoped out here: [CLI can list available streams with summary format (https://github.com/galasa-dev/projectmanagement/issues/1615)
- [ ] galasactl streams get --format raw
- [ ] galasactl streams get  --format yaml
  - scoped out here: [CLI: streams get supports --format yaml](https://github.com/galasa-dev/projectmanagement/issues/1604)
- [ ] galasactl resources apply -f xxx.yaml
  - scoped out here: [CLI: streams created using galasactl apply -f xxx.yaml](https://github.com/galasa-dev/projectmanagement/issues/1603)
- [ ] galasactl resources create -f xxx.yaml
- [ ] galasactl resources update -f xxx.yaml
- [ ] change/add this detail to the documentation, about how to administer an ecosystem.

**Comment by Jimbo4794** [comment]
We did discuss at one point to deactivate a stream, aka remove from the `framework.test.streams` property without removing the stream defintion. If we do want to have that feature you may want to add a state to your json object.

I am wondering wether this should be yaml to simplify for user creation and make it familiar to kubernetes style

**Comment by Jimbo4794** [comment]
If you want to go down the kubernetes route too i would suggest:
api: v1alpha1
kind: galasa-stream

rather than kind with version
