### ISSUE TITLE
Improved Helm user experience : Helm chart should do all the work in one pass.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1303]
## Story
As a galasa admin installing galasa with helm, I want to install it completely using a single helm chart, rather than having to invoke helm twice, so it's simpler to install, and doesn't appear to be 'unusual', and unlike anything else I have installed on Kubernetes with helm before.

## Background
Galasa install using Helm uses a 2-pass approach, where a single pass should be possible.

This exchange may be relevant...

https://stackoverflow.com/questions/71284091/helm-run-pods-and-dependencies-with-a-predefined-flow-order
That's talking about using init containers to initialise a database in a helm chart.
This is the most interesting answer I think:
(It's talking about how to migrate a database, when the migration code needs the database to be started up before the migration happened).

---

~~Helm hooks can cause more problems than they solve, in my experience. This is because most often they actually rely on resources which are only available after the hooks are done. For example, configmaps, secrets and service accounts / rolebindings. Leading you to move more and more things into the hook lifecycle, which isn't idiomatic IMO. It also leaves them dangling when uninstalling a release.~~

I tend to use jobs and init containers that blocks until the jobs are done.

```
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: bitnami/kubectl
          args:
            - wait
            - pod/mysql
            - --for=condition=ready
            - --timeout=120s
      containers:
        - name: migration
          image: myapp
          args: [--migrate]
      restartPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      initContainers:
        - name: wait-for-migration
          image: bitnami/kubectl
          args:
            - wait
            - job/migration
            - --for=condition=complete
            - --timeout=120s
      containers:
        - name: myapp
          image: myapp
          args: [--server]
```

Moving the migration into its own job, is beneficial if you want to scale your application horizontally. Your migration need to run only 1 time. So it doesn't make sense to run it for each deployed replica.
Also, in case a pod crashes and restarts, the migration doest need to run again. So having it in a separate one time job, makes sense.
The main chart structure would look like this.

```
.
├── Chart.lock
├── charts
│   └── mysql-8.8.26.tgz
├── Chart.yaml
├── templates
│   ├── deployment.yaml    # waits for db migration job
│   └── migration-job.yaml # waits for mysql statefulset master pod
└── values.yaml
```
---
...So we might be able to use a technique like this to wait for the ETCD services to come up before starting the other services which use it ?

The helm installation also includes a post-install step that runs after all the pods have initialised successfully, which causes the API server to restart as it reconfigures the URIs to the different services. It would be worth refactoring this to configure the services as they are deployed instead of configuring them as a separate step in the installation process.

## Tasks
- [x] Investigate whether simplifying the helm charts are feasable using the above method
- [x] If it is possible, implement it
- [x] Testing
- [x] Document how it works in the repo README
- [x] Investigate feasibility of refactoring the post-install job
- [x] Refactor the post-install job
- [ ] Update readme based on review comments

**Comment by techcobweb** [comment]
In terms of priority, this is about improving the Helm experience installing into Kubernetes.

Probably not as important as documenting that Helm should be used instead of the docker operator for example.
