### ISSUE TITLE
CLI tool to create default galasa dev env

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1304]
## Story
As a galasa testcase developer, I want to use the command-line to create an initial Galasa environment, ~/.galasa folder, properties and overrides files in the same way that the eclipse tooling can do, so that I have
an easy way of setting myself up for writing and using galasa in future.

## Background

To use Galasa tools, or to run galasa tests, you need to set up some basic file structures and files in your home folder, so you have a default bootstrap file, and local properties files which can be extended in future by user activities. 

This is a one-time command. Use it once per user just to get set up quickly.

Tool should create:
```
${HOME}/.galasa
├── bootstrap.properties
├── cps.properties
├── credentials.properties
├── dss.properties
├── overrides.properties
```

> Q: Should the location of this be configurable ?

With default contents in each of the files.

Should this be a shell-script ? or a golang-tool. What are the differences ? +ve and -ve aspects of either approach ?

### Option 1 : A golang tool
Something like this:
```
galasadevenv init --log $mylogFilePath
```

- +ve: Works in windows easily. Just use the windows variant of the tool.
- +ve: Consistently documented with other CLI tools
- +ve: Errors handling and structure can be same as the galasactl command... easier to maintain.
- +ve: Faster execution. Easier to debug.
- +ve: Can do complex checking in a more maintainable manner.
- +ve: Same tool can do multiple tasks with more flags/options. Fewer shippable things.
- +ve: Easier to unit-test, using mock file system.

### Option 2: A bash/sh script
If it's a bash script, we can suggest the user run the script using 
`curl $url | bash` or similar if required.

- +ve: Easy to change/develop
- -ve: Hard to unit test. Mocking in script is garbage.
- -ve: Breaks in windows easily. Parallel need for a powershell script doing the same thing.
- +ve: Easy for customer to take, customise, and re-use.
- -ve: Another thing we'd have to package into a shippable asset.

### Conclusion
Conclusion is that we should house this logic in a golang tool, and ignore the script option.

## Tasks
- [ ] Re-run the eclipse logic, and see what it creates, so we can create the same thing. Update this story with all the contents of each file to specify what we are creating in more detail above.
- [ ] Write a golang tool which builds executables, makefile, build-locally.sh script...etc. In the `cli` repo
- [ ] Tool uses mock file system to unit-test all the functionality
- [ ] Creates folder
- [ ] Creates files
- [ ] Puts contents into files
- [ ] Does any required substitution as it creates content in the files.
- [ ] Logs debug information to a file if specified with the `--log $filename` option
- [ ] Logs to the stdout when using the `--log -` option.
- [ ] Supports help syntax
- [ ] Uses the cobra framework to be as consistent as possible.
- [ ] Syntax is documented in html in the same way that galasactl is documented (currently: rendered by a local build, checked-in, and linked with the README.md)
- [ ] Code coverage report available
- [ ] Error messages are standardised, and appear on stderr.
- [ ] Usage documentation added to .md files in the repo so it's easy to pick up and use in the 
- [ ] Allow the user to configure which folder the files are all created in, instead of defaulting to `${HOME}/galasa` ? Is this needed ? Don't think that eclipse supports this ?
- [ ] Write a piece of docs entitled "Understanding what was created" to go through each artifact, why each one is needed, when it is user or important, and what each setting inside each file means. We don't currently do this for the eclipse variant of this functionality, but it's something which should have been done, and can be shared between approaches when it exists.

**Comment by AaronJhaj** [comment]
'Galasa local init' is now delivered and running the command 'galasactl local init --log -' will show this.
Need to separate this item into two:
1. writing docs for the delivered functionality
2. removing this same functionality from eclipse

**Comment by techcobweb** [comment]
Given that the remaining scope has been moved to separate stories, I think we can close this one.
