### ISSUE TITLE
Supply CICS TS team with an example project

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1309]
## Story
As a CICS TS tester I want to have an example repository in cics.ibm.com which I can clone, containing an example Galasa test+manager+obr showing how a galasa test can do something to a CICS region, so I can learn from it, clone/copy/change to embellish to suit my needs easily.

## Background
The Galasa team need to supply this to provide some inspiration for the CICS TS test folks to get them started.

The repo should contain two test packages/bundles, each with two tests inside.

> Q: Does it have to be built using maven or gradle or both ?

## Tasks
- [ ] Create the new repository in the CICS TS internal github organisation.
- [ ] Populate the repo with a half-decent example
- [ ] Readme of the example shows how it can be run ? Or at least points off to the information someone might need ?
- [ ] Test that the example is buildable from the command-line
- [ ] Test that the example is buildable within eclipse ?
- [ ] Test that the example is runnable within eclipse ?
- [ ] Test that the example is runnable locally in a JVM outside of eclipse ?

**Comment by techcobweb** [comment]
Blocked, awaiting the CICS TS work item to get an automated build pipeline going for the CICS-internal managers.
