### ISSUE TITLE
Pair with someone in CICS TS org to deploy a 0.25 ecosystem for CICS TS team to use

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1310]
## Story
As a CICS TS tester responsible for the Galasa CICS TS infrastructure, I want to pair with a member of the Galasa team to get a Galasa ecosystem deployed into a namespace on the internal CICS TS kubernetes cluster.

## Background

This is dependent on release 0.25 being available.

Assumed that the Helm chart will be used to do the deployment.

> Q: Who in the CICS TS organisation will do this pairing with one of the Galasa team ?

> Q: Where is the test repository ? Can an example test be deployed there to demonstrate that the deployment is working ?

## Tasks
- [ ] Pair with the nominated CICS TS person to deploy 0.25 to kubernetes using Helm
- [ ] Set it up so that it can run tests made available from a test repository
- [ ] Take an example CICS-specific test, deploy the build test bundle, run the test on the infrastructure.

**Comment by techcobweb** [comment]
Tom Slattery will bring up the first instance, and others to manage it part-time after.
Ticket to create a namespace is open, waiting for it before Tom can start.

**Comment by techcobweb** [comment]
Tom Slattery is going to be doing this so we don't need to track it here in Galasa-land.
