### ISSUE TITLE
Copyright tooling is broken for Golang code.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1311]
## Story
As a galasa developer, when I submit Golang code containing the correct copyright statements, I want my pull request to show no errors. When it is missing the copyright statement, I want my PR build to fail with a decent error message telling me how to fix the error. So that I can be efficient and copyright-safe when making go-related changes in future, and I don't have to over-ride such checks to be able to merge my changes.

## Background
The copyright tooling for Golang is broken. It errors when perfectly decent Golang code is submitted which has the correct copyright at the top.

## Tasks
- [ ] Fix the copyright program.
- [ ] Re-deploy the copyright program.
- [ ] Document how to re-deploy the copyright program
- [ ] Automate the re-deployment of the copyright checker tool ?
