### ISSUE TITLE
galasactl tools (all archivecture variants) needs including in DFG

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1313]
## Story
As a consumer of the DFG distribution, I want to be able to use the galasactl tool from the DFG packaging so I don't have to download it from an un-trusted source.

## Background
We've never had the galasactl tools in the DFG package. They need to be added.

## Tasks
- [x] Build CLI before we build the isolated build
- [ ] Understand what the open source the CLI pulls in and update the DFG notices file
- [x] Add the galasactl tool (all architecture variants) into the DFG packaging, by changing the packaging of the isolated pom.xml

**Comment by techcobweb** [comment]
Leave until an iteration where we are going to ship a DFG

**Comment by techcobweb** [comment]
decided to make a single chain which includes CLI and eclipse, and runs all the time.

**Comment by AaronJhaj** [comment]
cli binaries seem to be in isolated builds
