### ISSUE TITLE
Replace all references to old maven repository/images with the new external ones

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1315]
## Background
Since putting together Galasa's new build pipelines which build and push artefacts to the new external maven repositories and the new external harbor, we are yet to update Galasa to actually start using these endpoints. Galasa is still pulling from the old locations, which is fine as we haven't stopped building and pushing to the old repositories. However, before we release 0.25.0, we need to update Galasa to start pulling from the new endpoints, so that we are releasing using our new infrastructure and releasing artefacts that have been built from our new pipelines.

Any references to https://galasadev-cicsk8s.hursley.ibm.com/main/maven/* should be changed to their equivalent https://development.galasa.dev/main/maven-repo/*

Any direct references to images / references to the https://harbor-cicsk8s.hursley.ibm.com/ image registry should be updated to https://harbor.galasa.dev

If these references are in a location which we plan to discontinue, for example, the argocd repo, these can be ignored.

**Note:** Please open PRs to get ready to make these changes but do not merge in yet. We need the integration tests in a stable state so that we can use them to test this story has gone successfully.

## Tasks
There will be references to the old maven repositories in the following places. This list may grow as we remember other locations.
- [x] Galasa CPS properties (These are located in a repo in Github Enterprise, which you may need to request access for)
   - [x] framework.test.stream.inttests.location
   - [x] framework.test.stream.inttests.repo
   - [x] galasaecosystem.runtime.repository
   - [x] galasaecosystem.simplatform.repository
   - [x] galasaecosystem.isolated.mvp.zip
   - [x] galasaecosystem.isolated.full.zip
- [ ] build-locally.sh scripts, the following two directly reference the old endpoint
   - [x] Extensions
   - [x] OBR
- [x] build-image-webapp Pipeline in automation
- [x] buildutils repository
   - [x] tests.yaml (unsure if this is being used but update to be safe)
   - [x] pkg/cmd/secvulnMaven.go - line 290 can be removed altogether
- [x] Potentially references in the Developer Docs (also Github Enterprise)
- [ ] Change k8s test engines to use harbor.galasa.dev:galasa-ibm-boot-embedded:prod (not sure where this location is set)

**Comment by AaronJhaj** [comment]
pr for secvulnMaven.go https://github.com/galasa-dev/buildutils/pull/23
pr for extensions build-locally https://github.com/galasa-dev/extensions/pull/196
pr for obr build-locally https://github.com/galasa-dev/obr/pull/108
pr for developer-docs https://github.ibm.com/galasa/developer-docs/pull/3

Will come back to the tests.yaml in buildutils as that location is currently https://galasadev-cicsk8s.hursley.ibm.com/codecov/maven/obr

I have requested access to the  HurJazz104users BlueGroup to get access to the CPS properties in Github enterprise

**Comment by AaronJhaj** [comment]
pr for CPS.properties https://github.ibm.com/CICS/cicsts-galasa-config/pull/19

**Comment by AaronJhaj** [comment]
obr pr https://github.com/galasa-dev/obr/pull/112 - seems to be merge commits not signed so is refusing to merge. I made a new branch and pr but still is retreiivng unsigned merge commits.
