### ISSUE TITLE
Update credentials to make zosmf requests in Creds

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1316]
### Background/Problem

All of the Zos and CICS integration tests are failing, due to getting a 401 Unauthorised back when making Zosmf requests.

It is likely that the CICS delt password has been rotated - this needs reflecting in the Creds server.

### Tasks
- [x] Exec on to Creds pod on the K8s cluster
- [x] Update W3 password using etcdctl commands
- [x] Verify fix by running Zosmf tests again

**Comment by jadecarino** [comment]
Tests ran locally from CLI passing again so closing as fixed
