### ISSUE TITLE
Fix failures in CECI integrated tests 

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1319]
### Background

Now that the inttests bundle has been fixed according to the artifact manager changes, and the nested 'resources' folder removed, the path to the COBOL code in AbstractCECILocal needs to be updated. It currently refers to '/resources/zosPrograms', it should just be '/zosPrograms'

There is also a second bug in the CECIManagerIVT in getExpectedEIBDate. If dayOfYear <= 9, an extra 0 should be added into that part of the string.

### Tasks
- [x] Make change in AbstractCECILocal
- [x] Make change in CICSManagerIVT
- [x] Run CECI inttests from the CLI to confirm fix
