### ISSUE TITLE
Create snapshot-integration and snapshot-prod 

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1320]
### Background

In the old infrastructure/pipelines, after main-runtime (equivalent of our new 'Core/Main build'), Jenkins triggers main-isolated, then snapshot-integration, then snapshot-prod. snapshot-prod being complete is what is needed for code changes to be reflected in Galasa tests, as the test engines use the ibm-boot-embedded:prod image. We need the equivalent of this process in our new pipelines.

### Old pipelines

- PRun snapshot-integration: https://github.com/galasa-dev/argocd/blob/main/prun/pipeline/prun-snapshot-galasa-main-integrated.yaml

This pipeline takes the images tagged 'main' in harbor and essentially makes an identical snapshot image, but tagged 'integration'

- PRun snapshot-prod: https://github.com/galasa-dev/argocd/blob/main/prun/pipeline/prun-snapshot-galasa-main-prod.yaml

This does similar to above, gets the 'integration' images and makes 'prod'.

Note the branch params used in the above are what differentiates them ^

They both call:

- Pipeline snapshot-galasa: https://github.com/galasa-dev/argocd/blob/main/tektonHelm/templates/pipeline/pipe-snapshot-galasa.yaml 

Tasks used:
- snapshot-repo: https://github.com/galasa-dev/argocd/blob/main/tektonHelm/templates/pipeline/task-snapshot-repo-build.yaml

- snapshot-generic: https://github.com/galasa-dev/argocd/blob/main/tektonHelm/templates/pipeline/task-snapshot-generic-build.yaml

### Tasks
- [x] Call branch-isolated from the end of obr-generic when in 'main'
- [x] Create new version of snapshot-integration pipeline that works with the structure of our pipelines/tasks
- [x] Create new version of snapshot-prod pipeline
- [ ] Test the changes to the run-test pipeline.

**Comment by techcobweb** [comment]
snapshot-prod is mis-named. Should it not be integration-prod ? As it takes from integration, and promotes it to prod ?

**Comment by AaronJhaj** [comment]
need to create run-tests pipeline that runs in between the integration and prod pipelines. However having issues with galasactl image
