### ISSUE TITLE
galasactl to launch a single test locally without an ecosystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1322]
## Story 
As a galasa test author I want to use the command-line to launch a collection of tests at once, without having the burden of setting-up an ecosystem.

## Background
Tests can be run immediately using a local java runtime environment, rather than dynamically deploying the tests to a remotely deployed Galasa ecosystem.

Calling it with `--local` indicates explicitly that it’s a local run, even if you have a GALASA_BOOTSTRAP env var defined.

Can be used with the `--bootstrap` option, if you want to run the code locally, but use the configuration inside the bootstrap definition to access cps properties remotely.

### Where is Java installed ?
To use the `--local` option, $JAVA_HOME must be set. The local java run-time environment is used to launch the test locally. So `$JAVA_HOME/bin/java` can be invoked. 

> On other machines, will it always be called `$JAVA_HOME/bin/java` ? Used to be called 'jre' ?

### What level of Java can be used ?
The level of Java must match the required/supported level of the galasa version being launched.

### To stop a running test
Use Ctrl-C to interrupt the `galasactl` tool. It will exit immediately, ending all test activity.

> Note: This may leave the system under test with resources which are not cleaned-up

You should be able to run a portfolio of tests, or a single test.

If running locally, all the tests have to be in the obr (or obrs) passed. 

Q: How do you run a list of tests locally using a portfolio ?
A: decide later.

### Running a single test using the Java command line
James wrote an article on doing this already, which wasn't published at the time...

To run a test, do this:
```script
export BOOT_JAR_VERSION="0.24.0"
export M2_PATH=$(cd ~/.m2 ; pwd)
export BOOT_JAR_PATH=${M2_PATH}/repository/dev/galasa/galasa-boot/${BOOT_JAR_VERSION}/galasa-boot-${BOOT_JAR_VERSION}.jar

export OBR_VERSION="0.25.0"
REMOTE_MAVEN=https://repo.maven.apache.org/maven2

java -jar ${BOOT_JAR_PATH} \
--localmaven file:${M2_PATH}/repository/ \
--remotemaven $REMOTE_MAVEN \
--bootstrap file://${HOME}/.galasa/bootstrap.properties \
--overrides file://${HOME}/.galasa/overrides.properties \
--obr mvn:dev.galasa/dev.galasa.uber.obr/${OBR_VERSION}/obr \
--obr mvn:com.myco.example/com.myco.example.obr/0.0.1-SNAPSHOT/obr \
--test com.myco.example.test/com.myco.example.test.SampleTest
```

The Java code which implements the above is galasa-dev/framework/galasa-parent/galasa-boot/src/main/java/dev/galasa/boot/Launcher.java

### Knowing where Galasa data is installed locally
Normally this would be `~/.galasa` 

### Knowing which version of galasa runtime the tool will use
The galasactl tool could launch a galasa framework which is a different galasa version than the galasactl tool was released in. So a `0.25.0` version of `galasactl` can launch a `0.24.0` version of the galasa framework.

The tool has a 'default' version burnt-in at build-time.

If someone wants to launch using version "0.24.0", then they can modify this file, or specify it explicitly on the command-line using the `--galasaversion 0.25.0` option.

### Obtaining the boot jar
To execute any java code, the `galasactl` tool requires a boot jar to invoke, which in turn starts up the OSGi framework, galasa framework and the user tests.

To obtain the boot jar, the galasactl tool can search for it:
- Look for it at `~/.galasa/0.25.0/lib/galasa-boot0.25.0.jar`
- Unpack an embedded version of it from the `galasactl` executable, and place it in `~/.galasa/0.25.0/lib/galasa-boot0.25.0.jar`

### Local or Remote jars ?
To use this `--local` feature of galasactl, you need to have run a maven or gradle build, to download dependencies and place them on your local machine.

The tool will look for the uber-obr of the desired version in 
~/.m2/repository/dev/galasa/dev.galasa.uber.obr/0.25.0/dev.galasa.uber.obr-0.25.0.obr
- If that file is found, the galasactl will assume that everything it needs in terms of galasa has been gathered already on the local machine.
- If that's not found, then the tool can assume that the version 0.25.0 of the jars have not been downloaded, and they need to be prior to continuing.

### Downloading pre-requisite Galasa jars
If required, when the `--local` option is used, the galasactl tool will download files it needs to launch a test.

To download the files required to perform a local run, the `galasactl` tool will unpack an embedded file (if it's not already present) in ~/.galasa/0.25.0/install/pom.xml 

Either gradle or maven need to have been installed as a pre-req.
The default is to assume `mvn` will be on the path. If the user has specified `--maven` or `--gradle` explicitly, then 'mvn' or 'gradle' are assumed to be on the path.

The tool can invoke maven/gradle to perform the downloading of the 'uber-jar', and all the transitive dependencies it has.

This does mean that the first time you invoke the tool it may take some time to download everything it needs, and may fail if connectivity is not available.

### Syntax
Example:
```
galasactl runs submit --local \
--portfolio test.yaml \
--throttle 4 \ << limit to running only 4 tests in parallel.
--obr <url-to-obr-containing-all-the-tests> << The user-built OBR
--galasaversion 0.25.0 << The version of galasa we want to launch. Defaults to the version baked-into the galasactl tool.
--maven. << Use maven to gather pre-requisite jar files. Could be --maven or --gradle. Defaults to --maven if not present.
```

More than one user-OBR could be specified if required.

The tests mentioned in the portfolio file must exist in the OBR(s) specified.

The `--obr` parameter specifies the maven co-ordinates of the 
obr jar, in the format `mvn:`_groupId_`/`_artifactId_`/`_version_`/`_classifier_

For example:
```
mvn:dev.galasa/dev.galasa.uber.obr/${OBR_VERSION}/obr
```

### Implementation
Each test will run as a result of a separate JVM being spawned in a separate process.

The Go program will have a separate go routine/thread for each JVM.

Eclipse creates a temporary file in `/var` like this:
```
#Galasa overrides file
#Wed Feb 01 12:46:36 GMT 2023
framework.run.requestor=hobbit
zos3270.live.terminal.images=http\://localhost\:49769/d0b31d15-2ab0-470e-9c11-a5ed15717a3d/zos3270/liveterminals
framework.credentials.store=file\:///Users/hobbit/.galasa/credentials.properties
framework.resultarchive.store=file\:///Users/hobbit/.galasa/ras/
framework.bootstrap.url=file\:///Users/hobbit/.galasa/bootstrap.properties
```
and then passes the file as an argument to the JVM. We should be doing a similar thing. 

## Tasks
**Basic use**
- [x] Add the `--local` option
- [x] Error if `--local` is used with any other options it can't support.
- [x] Mention which options don't work with the `--local` option in the (generated) docs.

**Boot jar acquisition**
- [x] Embed the boot jar into the galasactl executable
- [x] Look for the boot jar
- [x] Unpack the boot jar if required

**Dependency galasa jar acquisition**
- [x] Gradle to pull down and embed the bootstrap jar.

**Launching single test**
- [x] Launch a single test in a JVM
- [x] Wait for the JVM to exit
- [x] If the test fails, exit code of 2, if the infrastructure fails, exit code of 1
- [x] Support multiple user OBRs being specified
- [x] Go code understands that JVM X is running test with runID Y
  - [x] extract the runid from the trace of the JVM
- [x] Go code understands that JVM X ras data is stored in ras folder Y
  - [x] extract the ras folder path from the trace of the JVM (so we pick up the resolved value).

- [x] Allow some flags from the parent runs submit come through without

- ~~Pass the override parameters and values that eclipse currently does.~~ Scope moved to story #1377 https://github.com/galasa-dev/projectmanagement/issues/1377
- ~~Override properties from ~/.galasa/overrides.properties are also passed to the test.~~ Scope moved to story #1377 https://github.com/galasa-dev/projectmanagement/issues/1377

- [x] Monitor the JVM output to gather the run-id. Then report test status using json file in RAS.
- ~~Test with a portfolio.~~ scope moved to story #1376
- ~~Allow a portfolio to be created with an `ad-hoc` stream~~ scope moved to story #1376  https://github.com/galasa-dev/projectmanagement/issues/1376
- [x] Validate parameters
- [ ] Decent error messages
- [x] Respect the throttle parameter
- [ ] Respect the requestor parameter
- [x] Poll time should be smaller than 60 seconds by default for local runs. Last run should wake up the poll sleeper. If the poll timeout was done in many smaller time intervals, then we could check for completion locally quickly without network traffic...
- [x] Progress reports should run if the test is long-running. This requires separating the start and waiting for completion of the JVM process.

**Shutting down**
- [x] Ctrl-C kills everything

**Documentation**
- [ ] Includes "why do this"
- [ ] Includes "how to do this"
- [ ] Includes readme updates showing examples

**Testing**
- [ ] Build pipeline runs the command and checks the results.
- [ ] Test on a windows system.
> How to test on a windows system ?

**Comment by techcobweb** [comment]
Trying to pin-down the syntax of things on the command-line.
We currently have
galasactl runs submit
galasactl runs prepare
We are soon going to have galasactl local init to initialise the ~/.galasa folder.
So now we want to add launching tests in the local JVM... Thinking we can have

- a) galasactl local runs submit or
- b) galasa runs submit local or
- c) galasactl runs submit --local

Benefits of (a) and (c) is that any options get documented separately from those which launch a remote test on an ecosystem. (b) ends up adding all the options for local and remote together, which is more confusing.

The command needs to know additional properties:
- The obr(s) the tests are in. Possibly multiple.
- The remote maven repo where the galasa and/or in-house managers may be found.
- JAVA_HOME (which we can get from the environment variables), but maybe we should allow it to be stated explicitly.

The local maven repo... Which we can default for ~/.m2/repository, or from a value in ~/.m2/settings.xml , but probably need to set explicitly.

The command options we can't use from the regular galasactl runs submit in a local runs context I'm not sure of yet. Most of them may be relevant eventually. Initially throttle, throttlefile, trace, requestor, requestortype. (Not seen how to punch trace,requestor,requestortype into the JVM yet).

Option (b) which gives the best of both worlds, being able to 'inherit' flags from the 'parent command' if we want to, but not having to. But (a) allows that too, and is consistent with the 'local init' more.

What do folks prefer ?

Failing a consensus otherwise I will go with option (b)

**Comment by techcobweb** [comment]
I've got it the `jvm-launches-test5` branch to a point where it can launch a JVM (or many, in series).
But I think we can do better.

It's still not very clean code yet. Needs more polishing, but basic syntax like this:

```
    ${GALASACTL} runs submit local \
    --obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/obr \
    --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount \
    --class dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccountExtended \
    --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayee \
    --class dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayeeExtended \
    --log - 2>&1 | tee ${BASEDIR}/temp/log.txt
```
will run 4 tests... and show this:
```
*** Final report
*** ---------------
***
*** Passed test runs:-
***     None
***
*** Failed test runs:-
***     None
***
*** Passed With Defects test runs:-
***     None
***
*** Failed With Defects test runs:-
***     None
***
*** Other test runs:-
***     None
***
*** results
*** results , Lost=4, Passed=0, Failed=0, Passed With Defects=0, Failed With Defects=0
***
*** Final report
*** ---------------
***
*** Passed test runs:-
***     None
***
*** Failed test runs:-
***     None
***
*** Passed With Defects test runs:-
***     None
***
*** Failed With Defects test runs:-
***     None
***
*** Other test runs:-
***     None
***
*** results
*** results , Lost=4, Passed=0, Failed=0, Passed With Defects=0, Failed With Defects=0
2023/02/04 19:09:36 GAL1017E: Not all runs passed. 4 failed.
GAL1017E: Not all runs passed. 4 failed.
2023/02/04 19:09:36 Exit code is 2
```

... so it says the tests are lost currently. I think there must be some way of finding the summary of each run, so need to get the reporting working correctly next.

These options are also added so far:
```
--remoteMaven https://development.galasa.dev/main/maven-repo/obr/    # as it defaults to maven central
--galasaVersion 0.25.0 # So it 
```

Currently doesn't do the overrides which eclipse does.

**Comment by techcobweb** [comment]
Command which actually runs is this:
```
/Users/mcobbett/.sdkman/candidates/java/current/bin/java \
-jar /Users/mcobbett/.galasa/lib/0.26.0/galasa-boot-0.24.0.jar \
--localmaven file:/Users/mcobbett/.m2/repository \
--remotemaven https://repo.maven.apache.org/maven2 \
--bootstrap file:/Users/mcobbett/.galasa/bootstrap.properties \
--overrides file:/Users/mcobbett/.galasa/overrides.properties \
--obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/obr \
--obr mvn:dev.galasa/dev.galasa.uber.obr/0.26.0/obr \
--test dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount
```

**Comment by hobbit1983** [comment]
@techcobweb Looking good. Really good. I take it each of the submitted runs are sequential and not run in parallel?  Another question is what we do with the parameter: framework.results.store. Do we force it on a local run to get a local RAS? Or allow the user to choose and set it themselves?

Great stuff Mike

**Comment by techcobweb** [comment]
Looks like the structure.json (if present in the RAS folder) shows the completion state. Not sure if it shows any state mid-way through the test ?
Is that where the tool should read current state of a run from ? @Jimbo4794 ?

Also, not sure how I can get the run-id used in the RAS folder to find out the state yet either...

The log says things like :
```
Allocated Run Name U498 to this run
```
So I could parse it from the log, and make the connection...

**Comment by techcobweb** [comment]
Currently thinking that I should spawn a separate go thread to look after each JVM, then the throttling stuff will start to mean something... Also if the test is long-running, the regular status check updates won't work currently, until a separate thread is waiting for the JVM to finish, and the polling thread is reporting status.

**Comment by techcobweb** [comment]
Extra detail to ignore:

`framework.request.type.LOCAL.prefix=L` property in dss specifies what the prefix of the runID should be.
Read that, then look up the `dss.framework.request.prefix.L.lastused=1` 

Monitor the standard out and extract the runid from there.

**Comment by techcobweb** [comment]
@jadecarino Pull request is ready for review.  https://github.com/galasa-dev/cli/pull/53
