### ISSUE TITLE
Investigate whether we should be using one-pipeline

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1326]
## Background
The one-pipeline initiative may save us lots of work w.r.t. DFG

https://pages.github.ibm.com/one-pipeline/docs/#/

Should we adopt it ? What are the +ve and -ves ?

Seems that it may not be helpful for the open source stuff, but may be good for DFG ?

## Tasks
- [ ] Read and investigate the one-pipeline material
- [ ] Share information and discuss with others
- [ ] Come to a conclusion, be able to justify it
- [ ] Get agreement that the conclusion is correct
- [ ] Document the decision and move on.

**Comment by techcobweb** [comment]
It's not suitable for open source projects.
