### ISSUE TITLE
Helm install also installs a default stream to start with

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1329]
## Story
As an admin tying to get the ecosystem installed using Helm, I want it to have a default stream pre-installed, so I can quickly add a test to the stream and run the test on the ecosystem to prove that it is installed and working correctly, giving me confidence I have a working system.

## Background
The CPS properties need initialising to add a stream "default" which can be deleted as required later.

## Tasks
- [ ] Add the required stream property values into the CPS as part of the helm install
- [ ] Verify that the stream exists after a fresh install
- [ ] Verify that a testcase can be added to the stream and executed on the helm-installed ecosystem

**Comment by techcobweb** [comment]
@eamansour Tagging you as we discussed this item earlier today.
