### ISSUE TITLE
galasactl able to launch multiple tests from a portfolio file.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1330]
## Story
As a developer trying to launch tests locally, without an ecosystem, I want to be able to launch more than one at a time, using a portfolio file, so that I don't have to write a script to string together lots of individual launches.

## Background
This story needs the galasactl tool to be launching singular tests before we start on it.

## Tasks
- [ ] Parse the portfolio file for the list of tests to run
- [ ] Make use of the --throttle flag
- [ ] Launch several JVMs all at once and manager their execution
- [ ] Return when all the JVMs are completed.

**Comment by hobbit1983** [comment]
Should this be more a force of the throttle flag as we wouldn't be able to support multiple tests in parallel

**Comment by techcobweb** [comment]
@hobbit1983 I think that's fair enough. If the users want parallel tests they will have to use an ecosystem. Reflected this limitation in the story text above.

**Comment by techcobweb** [comment]
Will and Mike exchanged ideas on a call today.

ref: https://github.com/Jimbo4794/galasa-samples/tree/Sample-1-2-obr-project

The underlying problem is that the `runs prepare` command needs to be told the OBR where the tests live.

Something like --obr mvn://galasa-dev/galasa.dev.examples.banking.obr

Then the tool would try to download from that location, a test catalog which is published to those maven coordinates. The Go tool would then have access to the list of tests associated with that OBR. Then the command can filter that list using the regex and --class, --test, --package ...etc. filters.

To @techcobweb it made sense that the test bundles themselves present mini-catalogs, and the dependencies listed within the OBR are used to navigate to all the smaller test-bundles, and the catalogs all extracted and combined by the tool on the fly, rather than have some extra construct which works when the obr is re-built to gather the test names.

Will said this idea had merit, but part of the infrastrcuture is already there (see the referenced URL above).

Thoughts will continue on this one for a bit yet before we can solidify.

Will is OK warning if tests can't be run locally/remotely due to lack of obr/stream knowledge.
