### ISSUE TITLE
Gradle builds for example projects generated by `galasactl project create`

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1333]
## Story
As a developer of galasa tests, I want to create an example galasa test using `galasactl project create` which builds using gradle, so I don't have to install/learn/need maven at all.

## Background
Maven or Gradle. The organisation has often made their choice. This function which only supports maven will gall for I.T. shops which have chosen Gradle.

Add gradle.build files to the generated examples.

Story #1000 is a pre-req to getting this done. As we can't build the OBR project at the time of writing this.

## Tasks
- [x] Generate the .gradle files necessary to build the example projects when --gradle is used
  - [x] settings.gradle in parent directory
  - [x] build.gradle in test project directory
  - [x] bnd.bnd in test project directory
  - [x] build.gradle in obr directory (if obr is needed)
- [x] Generate the maven pom.xml files when --maven is used.
- [x] Set the maven option to be the default.
- [x] Allow both flags to be specified.
- [x] Test the created project, resolve any issues
  - [x] Resolved - Issue encountered: Unable to locate OBR when running tests, `publishToMavenLocal` does not publish the built OBR. Needs to be explicitly published.
- ~~Document updates to explain how to use these new flags in galasa.dev in a PR for Caroline to approve or take over as required.~~ Scope split out into story #1409

**Comment by techcobweb** [comment]
@KirbyKatcher  Has any of this progressed ? You've not ticked off any progress so far ? Stuck on anything ? Need help ?

**Comment by techcobweb** [comment]
I made a few very minor changes and pushed, and delivered this change. Hoping that was ok. Couldn't see anything wrong.
