### ISSUE TITLE
galasactl project create generated example should demonstrate logging

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1335]
## Story
As a developer of galasa tests I want to see an example of how a testcase can add to the logging content of the test run, so that I can debug my tests using logging.

## Background
When the `galasactl project create` command runs it generates examples. 
The 'extended' example test should use a logger to log some information to demonstrate this function.

## Tasks
- [x] Enhance the template which generates the 'extended' java sample to include a logger
- [x] Make any pom changes as required to make the testcase build.
- [x] Test that logging appears when the testcase is executed.

**Comment by hobbit1983** [comment]
PR is here https://github.com/galasa-dev/cli/pull/56
