### ISSUE TITLE
`galasactl project create` to generate an example testcase which stores an artifact in RAS

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1336]
## Story
As a developer of galasa tests, I want to call the `galasactl project create` tool to generate an example testcase which demonstrates how I can store an artifact into RAS so it can be retrieved and viewed later.

## Background
The 'extended' testcase which gets generated needs to create a file on disk (perhaps using the text bundle resource file it can load already), then maybe add the run-id to it, and save it to disk. Then use the required manager to store this file into RAS for viewing later.

So now when I do `galasactl project create --package dev.galasa.examples.banking --features payee,account `...etc. I get a folder tree as normal with source code in.

In the 'extended' testcase, you will see this code added:
```
import dev.galasa.core.manager.*;
import java.nio.file.*;

...

// Where we can save files relating to this test if they help with diagnosing a problem.
@StoredArtifactRoot
public Path archivedArtifactRoot ;

...

@Test
public void testStoreFileInResultsArchiveStore() throws Exception {

	String testMessageEmbedIntoArtifact = "Hello Galasa !";

	// Now store the artifact in the test repository.
	Path artifactFilePath = archivedArtifactRoot.resolve(runName+"-TestPayeeExtended-Artifact.txt");

    Files.write(artifactFilePath, testMessageEmbedIntoArtifact.getBytes());
}
```

When executed, you see something like this (assuming the run-name is 'L2')...
```
L2
├── artifacts
│   ├── L2-TestPayeeExtended-Artifact.txt
│   └── framework
│       └── cps_record.properties
├── artifacts.properties
├── run.log
└── structure.json
```

The `L2-TestPayeeExtended-Artifact.txt` file above contains the text `Hello Galasa !`.

So you can see that the code above 

## Tasks
- [x] Change the example template to save the artifact into RAS.
- ~~Pom changes~~
- [x] Run the test, and make sure the artifact is stored, and can be retrieved.
- [x] review the sample code generated with others.
- [x] Update the docs and send a PR to Caroline

**Comment by techcobweb** [comment]
Moved this story back to the issue backlog as will didn't have time to do it, and I don't see anything changing there.
