### ISSUE TITLE
`galasactl project create` should allow maven `groupId` to be specified.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1337]
## Story
As a developer of galasa tests, I want to be able to specify the maven 'GroupID' when using the `galasactl project create` command, so I have more control over how the generated artifacts are named.

## Background
Currently the package name is gathered from the user, and that is used in all the pom files.

Syntax:

`--group` <groupId>

This is an optional parameter. If it isn't specified, the tool should use the packageName which it does today.

The tool is opinionated. The groupId specified must form all or a (leading) subset of the packageid which is also specified. This is not how everyone structures their maven built assets, but it is how the galasa team currently recommend they are structured. It is only an example, so if you use a different naming scheme, that's fine.

For example:
`--package dev.galasa.example.banking --group dev.galasa` << that's fine. The dev.galasa is a prefix/ subset in the package name.

`--package dev.galasa.example.banking --group dev.galasa.example.banking.app` << invalid. The group id is a super-set of the package name.

`--package dev.galasa.example.banking` (no group ID) << valid. The default groupID will be `dev.galasa.example.banking`

`--package dev.galasa.example.banking --group org.galasa` << invalid. The groupID is not a prefix/subset of the package.

## Tasks
- [ ] Add the --group parameter to the galasactl project create command.
- [ ] Defaults to the correct thing. + unit tests.
- [ ] Validates that it is a subset of the package name which was specified + unit tests
- [ ] Pom.xml files all use the specified group id + unit tests
- [ ] Informal testing to try it out.
- [ ] Generated artifacts build, appearing in the correct place in the .m2 folder tree.
- [ ] Generated artifacts can run as a test
- [ ] Documentation drafted and conveyed for inclusion in product docs.
