### ISSUE TITLE
Release Version 0.26.0

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1338]
## Story
As a galasa user I want to get the 0.26.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

We want someone else to do it this time with help from Jade, who released 0.25.0

## Tasks
- [x] Run through the release process
  - [x] Create branches
  - [x] Build Galasa
  - [x] Get regression tests to pass
  - [x] Manually test Simbank in eclipse
  - [x] GHE issue tasks and release approval
  - [x] Deployment
  - [x] Update reference sites
  - [x] Tag release and deploy CLI
  - [x] Clean up (do not delete images before DfG image is pulled)
  - [x] Bump to new version (0.27.0)
- [x] Identify problems/improvements and raise them for next time
