### ISSUE TITLE
Create pipeline to test Galasa Ecosystem helm chart installation

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1341]
## Story
As a galasa developer, I want to test the installation of the Galasa Ecosystem helm chart whenever any changes are made to Galasa, so that changes do not introduce defects in the ecosystem.

## Background
Currently, the Galasa Ecosystem chart in the [helm repo](https://github.com/galasa-dev/helm) is not covered by any CI/CD pipelines. We need to create pipelines that install and test the chart when making any changes to it or any other part of Galasa that may impact the ecosystem.

## Tasks
- [x] Prep the cloud namespace so it's ready to use
  - [x] Create the namespace
  - [x] Create a role with permissions equivalent to the internal cluster's galasa-admin role
  - [x] Create a user/ServiceAccount with that role
  - [x] Create a certificate so we can feed it into the helm chart's ingresses, stored within a secret.
  - [x] Set up a DNS record to refer to galasa.dev.ecosystem1 (or galasa-ecosystem1.galasa.dev)

- [x] Set up GIthub to add the galasa dex Oauth application to the github org for the test ecosytem1
  - [x] Save the secret in the secrets manager
  - [x] Add an external secret to refer to it from the build namespace where the pipeline runs from

- [x] Add pipeline for main/branches
  - [x] set up secrets so the pipeline can run
    - [x] token or credentials of user/ServiceAccount to access the kube namespace
    - [x] may or may not need logic to get the github OAuth secret to feed into dex config. Or we may be able to draw this from a kube secret (ideally)
  
  - [x] give the pipeline permissions to install on the cloud cluster (i.e. assign a ServiceAccount with the right Role/RoleBinding and then authenticate as that ServiceAccount using a kubeconfig file as an ExternalSecret and a KUBECONFIG env variable set to that ExternalSecret when running helm commands)
  - [x] Run a `helm install` command to install the ecosystem helm chart
  
  - [x] Wait for the ecosystem to enter the "Ready" state (i.e. add `--wait` to the `helm install` command, possibly with `--timeout <duration>` to override the default 5min timeout)
  
  - [x] Run the `helm test` command to submit a test to the new ecosystem
  
  - [x] Run helm uninstall after to make sure it can be deleted & check that it was deleted.
  
  - [x] Once the maven material on main builds is complete, they should chain-call the helm chart build which will re-deploy everything to galasa-ecosystem1.galasa.dev

Story #1568 will also make overlapping changes to the helm repo's README (e.g. changing the redirect URIs in the Dex config), so it might be worth moving the below scope to that item:

- [x] Docs in an md file in the repo

**Comment by eamansour** [comment]
Blocked - Changes to the framework's use of etcd are required to be able to add Ingress support and remove the need to expose the etcd service externally.
