### ISSUE TITLE
Correct complete build

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1343]
**Needed for 0.25.0**

## Background 

After closer examination due to the release, I have realised the Complete build should not contain Simplatform.

Simplatform main should trigger Simplatform snapshot-prod (main > prod)

Simplatform also should not be part of the branch-maven-repository.

## Tasks 
- [x] Create simplatform-snapshot-prod Pipeline
- [x] Remove simplatform from complete build (and join the missing pieces)
- [x] Remove simplatform from branch-maven-repository
- [x] Set up simplatform-main and simplatform-prod apps on ArgoCD to test changes 

Simplatform snapshot-prod hasn't been ran since September 2022, kicked off by James. There is a typo in the trigger in Jenkins. Unsure if this was done intentionally to stop the chain or if is a mistake. 
- [x] Check with James when snapshot prod for simplatform should be run
   - Seems likely its a mistake this wasn't hooked up properly
