### ISSUE TITLE
Create new galasa-prod Ecosystem with Infrastructure as Code / Helm chart

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1344]
## Background

Since recreating our infrastructure, the galasa-prod Ecosystem has not been updated to use the new images that are stored in our external Harbor. We should recreate a new Ecosystem to ensure that nothing old is 'hanging around' for want of a better term. We also do not have checked in YAML files that define the Deployments (api, engine-controller, resmon, etc), these were local on Mike B's laptop. We should define these YAMLs somewhere and have Infrastructure as code.

## Questions
- [x] Is this going to be on the internal or external cluster?
- [ ] What is 'galasa-buildutilities'? (line 167 of server-cps-etcd.yaml)
- [x] Is the RAS host going to stay the same? (line 15 of ingress-ras.yaml)
- [x] Is the WebUI host going to stay the same? (line 14 of ingress-webui.yaml)

## Tasks
- [x] Update to use new boot-embedded image
   - [x] test engines
   - [x] api
   - [x] testcatalog
   - [x] engine-controller
   - [x] resource-monitor
   - [x] metrics
- [x] Create equivalent of recycle-ecosystem Pipeline for the new infrastructure, that is triggered after 'integration-to-prod', so the ecosystem gets all the newest code
- [x] Define YAMLs for galasa ecosystem (In GHE, CICS organisation, are backups for the current ecosystem. Use to recreate)
- [ ] Recreate Update CPS and Backup CPS pipelines (look in Jenkins Galasa-Prod project)

Images needed:
- [x] etcd:v3.2.25
- [x] couchdb:2.3.1
- [x] busybox:1.32.0
- [ ] galasa-webui-amd64:prod (not sure if continuing this way with the webui...)
- [ ] galasa-semmodels:prod

**Comment by techcobweb** [comment]
What benefit does this give ?

**Comment by techcobweb** [comment]
Jade wanted to get this done while the info was still fresh.
Needs fleshing out and sizing.

**Comment by jadecarino** [comment]
Closing as all relevant tasks completed as part of other work items/endeavours.
