### ISSUE TITLE
Final step of 0.25.0 release: bump Galasa to 0.26.0

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1346]
## Story

This is the last step in the release process for 0.25.0. All parts of Galasa below need to have 0.26.0 listed in them.

## Tasks

These are manual steps:

1. Create new branch on these repos (not called 'release')
2. clone framework
     - [x] galasa-parent/dev.galasa.framework/build.gradle - bump framework to next version
     - [x] release.yaml - bump framework to next version
     - [x] Open PR for branch bump-0.26.0 into main and merge     
3. clone obr
     - [x] release.yaml - bump overall release version
     - [x] Open PR for branch bump-0.26.0 into main and merge     
4. clone eclipse
     - [x] galasa-eclipse-parent/dev.galasa.eclipse.feature/feature.xml
     - [x] galasa-eclipse-parent/dev.galasa.eclipse.feature/pom.xml
     - [x] galasa-eclipse-parent/dev.galasa.eclipse.site/category.xml
     - [x] galasa-eclipse-parent/dev.galasa.eclipse.site/pom.xml
     - [x] galasa-eclipse-parent/dev.galasa.eclipse/META-INF/MANIFEST.MF
     - [x] galasa-eclipse-parent/dev.galasa.eclipse/pom.xml
     - [x] galasa-eclipse-parent/dev.galasa.simbank.feature/feature.xml
     - [x] galasa-eclipse-parent/dev.galasa.simbank.feature/pom.xml
     - [x] galasa-eclipse-parent/dev.galasa.simbank.ui/META-INF/MANIFEST.MF
     - [x] galasa-eclipse-parent/dev.galasa.simbank.ui/pom.xml
     - [x] galasa-eclipse-parent/dev.galasa.zos.feature/feature.xml
     - [x] galasa-eclipse-parent/dev.galasa.zos.feature/pom.xml
     - [x] galasa-eclipse-parent/dev.galasa.zos3270.ui/META-INF/MANIFEST.MF
     - [x] galasa-eclipse-parent/dev.galasa.zos3270.ui/pom.xml
     - [x] galasa-eclipse-parent/pom.xml
     - [x] Open PR for branch bump-0.26.0 into main and merge     
5. Clone isolated
     - [x] full/pomDocs.xml
     - [x] full/pomJavaDoc.xml
     - [x] full/pomZip.xml
     - [x] mvp/pomDocs.xml
     - [x] mvp/pomJavaDoc.xml
     - [x] mvp/pomZip.xml
     - [x] Open PR for branch bump-0.26.0 into main and merge     
6.  CLI
    - [x] Version
    - [x] Open PR for branch bump-0.26.0 into main and merge
