### ISSUE TITLE
Make improvements to release pipeline in automation to make v0.26.0 release smoother

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1347]
## Background:
While releasing v0.25.0 of Galasa, I noticed a few things throughout the automation repository which I thought needed cleaning up, optimising or fixing.

## Tasks:
 
Optimising tasks:
- [x] Investigate how to delete images from ICR in an automated fashion (in a pipeline)
- [x] Create IBMCloud CLI task
- [x] Add into branch-delete-all in releasePipeline
- [x] Ask Will to help create API Key for general Galasa user
- ~~Create Service ID on IBM Cloud with API key~~
- ~~Create ExternalSecret with that API Key and use it in the branch-delete-all pipeline~~
Two tasks above moved to a new work item.

Clean up tasks:
- [x] ~~Delete 'branch-' from the name of all Pipelines that aren't needed for branch level development - it doesn't make sense as you wouldn't really have a 'branch' build including these repos~~ This can't be done unfortunately as the PipelineRuns triggered from the Github monitor call the Pipelines using branch-x.
- [x] Delete all old images from harbor.galasa.dev - as we have been developing the new infrastructure, sometimes we have changed the name of an image. The old image hasn't been deleted so it's confusing what it's for:
   - [x] galasa-eclipse-p2
   - [x] galasa-javadocs-image
   - [x] galasa-javadocs
   - [x] galasa-isolated
   - [x] galasa-mvp

- [x] Manually delete release tagged images from ICR
   - [x] icr.io/galasadev/galasa-resources
   - [x] icr.io/galasadev/galasa-isolated
   - [x] icr.io/galasadev/galasa-isolated-zip
   - [x] icr.io/galasadev/galasa-mvp
   - [x] icr.io/galasadev/galasa-mvp-zip

Fix tasks:
- [x] Add deployment/service/ingress to host buildutils binaries

**Comment by techcobweb** [comment]
The first batch of tasks need moving to the checklists for performing a release. Pre-release steps ?
The other tasks need sizing.

Jade thought she should be doing these while they are fresh in her mind ?
