### ISSUE TITLE
CLI can show time left before bearer token expires.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1348]
## Story
As a galasactl user (tester, admin or automation script) I want to find out how long I have before my bearer token expires, and I have to log back in again, so I can make sure I am still logged-in before launching a lengthy set of test runs, as I don't want them failing half-way through with authentication issues.

## Background

Find out expiry time of current bearer token, or logged-out status

```galasactl auth timeleft ```
...Tells us how many seconds are left in in the current bearer token, held in GALASA_BEARER_TOKEN

```
galasactl auth timeleft --bearertokenfile  ~/.galasa/bearer-token.json 
```
Tells us how many seconds are left in in the current bearer token, held in a file.

Output (stdout)
```
Auth timeout in seconds
245
```

```
galasactl auth timeleft --noheader «suppress the header information
```

If the bearer token has already timed out, or there is no bearer token available. 

Output (stdout):
```
Auth timeout in seconds
0
```

Q: What is the longest test we expect to run ? Do we have to ask at login-time how long we want the bearer token to work for ?

This could either be implemented in the galasactl itself (if it can make any sense of the bearer token itself) or it may require a new REST call added to the API server so the client can check. Obviously if the token has timed out it will fail to authenticate for that REST call anyway.

## Tasks
- [ ] Add the command husk to the galasactl tool.
- [ ] Figure out how to find the time left on the token. Perhaps the login needs to tell us separately, and we store that info with the token ? or is it in the token itself to be de-coded at will ?
- [ ] Add the logic (in the API server or in the galasactl tool) how to figure out the time left.
