### ISSUE TITLE
Pre-release for Galasa v0.26.0

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1350]
## Story
As a member of the Galasa team, I want to be able to run pre-release steps before starting the actual release of v0.26.0, so that we can iron out any problems and ensure the actual release is done at speed.

## Background
When releasing v0.25.0, we got to a step at around the halfway point, deploying the release artifacts to Maven Central, and realised that the artifacts had not been signed with the GPG key. This meant I had to go back to one of the very first steps of the release and start again, which extended the release by around 1 day. As there is a freeze on delivering code while doing a release, we should aim to do them as quickly as possible.

## Tasks

Release process is documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline
**Do not check in any changes you make to files during this work item - back out everything at the end**

- [x] Complete Steps 1, 2 and 3 of the 'Set up' section in the release process
- [x] Complete Steps 1, 3 and 4 of the 'Create branch and ArgoCD applications' section in the release process.
   - [x] Before doing Step 1, in 02-create-argocd-apps.sh, do a find and replace on the word 'release' and change to 'prerelease'. 
   - [x] In Step 4, **ensure that the following parameters are set**: distBranch=prerelease, fromBranch=main
- [x] Complete Step 1 of 'Build the components' **ensuring that the following parameters are set**: toBranch=prerelease, revision=prerelease, refspec=refs/heads/prerelease:refs/heads/prerelease, imageTag=prerelease, appname=prerelease-maven-repos, jacocoEnabled=false, isRelease=true
- [x] Go to a maven artifact from each repository and check that the .asc files are present, which means the artifact has been signed. For example, https://development.galasa.dev/prerelease/maven-repo/wrapping/dev/galasa/com.auth0.jwt/<VERSION> should contain a file called com.auth0.jwt-<VERSION>.jar.asc.
  - If the .asc files aren't present, debug and diagnose why the artifacts have not been signed.
