### ISSUE TITLE
Automate the release of Maven artefacts to the Sonatype staging repo.

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1355]
## Story 

As a Galasa releaser, I want to be able to use the deploy-maven-galasa Pipeline to deploy the maven artefacts to Maven Central in automated fashion,  avoiding several manual steps we have to do instead (including Jade sharing a secret from Vault if the releaser doesn't have access).

## Background

During the 0.25.0 release, I ran the deploy-maven-galasa Pipeline which uses the `galasabld maven deploy` command as part of an automated step, to deploy the artefacts to Maven Central. It ran into an error where it was trying to read some maven-metadata files as a directory, however there is no proper error handling or logging in galasabld, so it took me a while to understand the problem. 

The program needs to be fixed so that if it is iterating over directories and instead it reads a file, it does not attempt to go into it as a directory. It also needs improved error handling and logging so that if errors occur, we can diagnose the problem easily.

There is also a strange nested if statement which was hard to read so probably needs refactoring.

## Tasks
In buildutils for galasabld:
- [x] Add proper logging messages to galasabld maven deploy
- [x] Add proper error handling to galasabld maven deploy for when trying to read a file as a directory
- [x] Refactor and remove the if statements from lines 73-80, they are hard to read

In automation/releasePipeline for the pipeline that calls this:
- [x] galasabld will need access to the credentials for sonatype in order to run this. So add a volumeMount to the galasabld Task like lines 42-48 of the deploy-maven-galasa Task
- [x] Now switch the deploy-maven-galasa Pipeline to use the generic galasabld Task instead of the very specific deploy-maven-galasa Task, passing in the parts of the `galasabld maven deploy ...` command as parameters (see Pipeline branch-create-galasa as example of how to use galasabld Task)

Testing and docs:
- [x] Stop here and work with Jade to test the pipeline as we don't want to accidentally release any artefacts here
- [x] Create a script for deploying maven artifacts
- [x] Once confirmed everything works, edit the release.md in automation/releasePipeline for the release instructions to automate this step again and remove the manual steps that have replaced it (the automated step is commented out)
- [x] Locate all release scripts that define a PipelineRun and add the mavencreds volume to it like the githubcreds and harborcreds
- [x] Other PipelineRuns that use the galasabld Task will need this too or they wont be able to run (for branch-delete-all, branch-tag-galasa and deploy-maven-galasa, update the PipelineRun defined in the release scripts)

**Comment by jadecarino** [comment]
I think this is a good issue for Fiona to complete.

**Comment by techcobweb** [comment]
I'm wondering if it's a bit 'dangerous' to get Fiona to work on because the testing could actually go wrong and we accidentally release something... which we can't delete afterwards.

**Comment by Akyiaa** [comment]
The first 3 tasks seems to have been completed by @eamansour already: [here](https://github.com/galasa-dev/buildutils/commit/439e42ba0ee05f2709bddb05db27e371c5d78f8a#diff-2e07535206dbe9377c853fb63353e458c5442e6748f1557aa2432a49d28756ac) so added minor changes, like logging. But moving focus to 2nd and 3rd parts

**Comment by Akyiaa** [comment]
Changed the error handling to not use panics, but print the error and exit with an exit code of 1
