### ISSUE TITLE
Investigate why 'galasabld harbor delete' now fails and fix

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1356]
**This needs to be done before the 0.26.0 release**

## Story 

As a member of the Galasa team, I want to be able to use 'galasabld harbor delete' to clean up all 'release' images from Harbor after a release, so that we do not waste storage in Harbor and have unnecessary images held.

## Background

After the 0.25.0 release, I ran the galasabld harbor delete command to clean up the images in Harbor that were tagged 'release' as these aren't needed after the release is complete. The pipeline failed so I had to delete the images manually which was time consuming. I didn't manage to copy the error message but running the pipeline again shouldn't be hard to do, however, you will need to first build and push a test image to Harbor to test the delete on.

## Tasks
- [ ] Run the command again as part of a pipeline
- [ ] Run the command using the galasabld binary
- [ ] Make required fix after diagnosing the error
- [ ] Add proper logging messages
- [ ] Add proper error handling

**Comment by jadecarino** [comment]
Fixed in https://github.com/galasa-dev/projectmanagement/issues/1392 - this was a bit of a duplicate issue to be honest so closing.
