### ISSUE TITLE
Webhook-receiver should exclude repositories using a configmap

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1358]
## Story 
As a galasa developer I don't want the webhook receiver to send any pull request update message to github when certain repositories are mentioned in the webhook payload, so that PRs against these repositories are not stopped from merging.

## Background
The tool picks up parameters from the command-line. It should pick them up from environment variables, or a file contents.

## Tasks
- [ ] To configure parameters for the web hook receiver, it should be configured using a configmap, which should be mapped either into environment variables or a file contents.
- [ ] The command-line tool should pick these values up.
- [ ] Add the dev.galasa repo to the exclusions list

**Comment by techcobweb** [comment]
We are not using the webhook receiver right now. So closing.
