### ISSUE TITLE
Update Docker integration tests to use new Harbor

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1360]
## Background

The Docker inttests are still using the old internal Harbor. We need to update them to use the new external Harbor, and make any other necessary changes to fit our new infrastructure.

https://github.com/galasa-dev/integratedtests/blob/main/galasa-inttests-parent/dev.galasa.inttests/src/main/java/dev/galasa/inttests/docker/AbstractDocker.java

## Tasks:
- [ ] Update Docker integration tests
- [ ] Rebuild integration tests
- [ ] Run Docker inttests to confirm okay

**Comment by jadecarino** [comment]
Having investigated this item further, the Docker integration tests pull the busybox and httpd images from harbor-cicsk8s (the library repository which is a Docker proxy) to use in the tests. As harbor-cicsk8s isn't going anywhere as is used by the whole CICS team, I think we can leave this for now. I don't believe there is any reason to migrate the Docker proxy to harbor.galasa.dev as it's going to remain in harbor-cicsk8s.
