### ISSUE TITLE
Remove references to the old infrastructure

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1361]
## Background 
As a Galasa developer, I want references to the old infrastructure to be removed, so the repositories are cleaner and it is not confusing if things are old or active.

## Tasks
- [ ] Remove /argocd directories in the individual repositories in Github. These are no longer needed as are recreated in the automation repository.
- [ ] Once new galasa-prod ecosystem is built with the new images (see story https://github.com/galasa-dev/projectmanagement/issues/1344), delete old ecosystem.
- [ ] Delete old images in the internal harbor repository.
- [ ] Delete old argocd apps that are no longer used.
- [ ] Disable old Jenkins pipelines

**Comment by jadecarino** [comment]
Closing as this is a duplicate item (https://github.com/galasa-dev/projectmanagement/issues/1432 is more detailed so I'll keep this one)
