### ISSUE TITLE
Document 'galasactl local init'

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1367]
## Story
As a Galasa user, I want to use the CLI tool to initialise my Galasa home folder and environment and understand what is being created and what each file is for.

## Tasks:
- [ ] Document what the command will do as a first time Galasa user
- [ ] What the command will do when the user already has a Galasa home folder
- [ ] Explanation of what is created and what the content and why they are important  
- [ ] Put this doc into an .md file and link to it from the cli project README.md

- [ ] Put this doc into a pull request for Caroline to include in a vnext release of the docs ?
- [ ] Make sure that this documentation follows the 'how to install the command line' material, ahead of the 'how to do things in eclipse' sections.
