### ISSUE TITLE
Document the Gradle OBR Plugin

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1374]
## Story
As a galasa user, I want to read documentation focused on the gradle OBR plugin, so that I learn how to use it when building a Gradle test project.

## Background
The Gradle OBR plugin is lacking documentation, so we need to document its purpose and instructions on its usage in the Gradle repo and galasa.dev.

## Tasks
- [x] Update the [Gradle repo's](https://github.com/galasa-dev/gradle) README
- [x] ~Update/Add documentation on the Gradle plugin on galasa.dev~ Covered by https://github.com/galasa-dev/galasa.dev/issues/548 and https://github.com/galasa-dev/projectmanagement/issues/1333
- [x] Follow the documentation to ensure the instructions are correct
