### ISSUE TITLE
CLI can create an ad-hoc portfolio outside of a stream and use it in local runs

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1376]
## Story 
As a CLI user, I want to create a portfolio without the use of an ecosystem so that I can feed it into a local execution of tests.

## Background
Currently to create a portfolio you have to contact an ecosystem to fish out the list of streams, one of which must be specified on the command-line.

Proposal is to have a special 'local' stream value which doesn't require the stream name. OR 'local' mode in which the portfolio creation tool runs so it doesn't try to contact the server.

Currently believe that if a portfolio could be created locally, it could be run locally. But it needs testing.

## Tasks
- [ ] Collaborate with others to decide how we want to express this functionality.
- [ ] Allow a local portfolio file to be created so tests can be run in batch.
- [ ] Test that the portfolio can be run locally.

**Comment by techcobweb** [comment]
Duplicate of #1330
