### ISSUE TITLE
CLI running test in Local JVM can pass overrides

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1377]
## Story
As a CLI user running tests in a local JVM I want to pass overrides in addition to those in the `~/.galasa/overrides.properties` file, so I can control my tests better, and so some standard overrides for local tests can be injected also.

## Background
Eclipse invokes tests using a few special override properties.

```
framework.resultarchive.store=file://\Users\097775866.galasa\ras
```
> Should there be any others ?

It creates a temporary overrides file which is passed to the local tests. And the contents of the `~/.galasa/overrides.properties` is optionally added to that temporary file too.
This means you can get a mix of what the tool wants and what the user wants to use.

This feature is not yet offered by local test runs in a CLI setting.

## Tasks
- [ ] Find out what the normal override behaviour is in eclipse.
- [ ] Create a temporary file containing standard tool-centric special override properties.
- [ ] Optionally? add the contents of the `~/.galasa/overrides.properties` file
- [ ] Document.

**Comment by techcobweb** [comment]
Pulling this issue into the iteration as Chris A needs it already.
