### ISSUE TITLE
Convert json representations of terminals into images

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1381]
## Story
As a galasa user, I want 3270 terminal images in the RAS to show the 3270 terminal screens from my tests, so that I can easily review the terminal screens in the future without needing to use Eclipse.

## Background
Part of #1290 - This story focuses on adding content to the generated 3270 image files by converting the existing screen outputs into viewable images.

Story #1383 focuses on adding colours and highlights to the generated images.

## Tasks
- [x] Investigate how terminals currently rendered in Eclipse etc
- [x] Decide on image format (png, jpg?)
- [x] Implement the algorithm and code with unit tests into 3270 Manager (code to set up file structure and save to RAS in separate work item)
- [x] Get rid of confidential text
- [x] Add Inbound/Outbound last row
- [x] Run CICS IVT
- [x] Test locally
- [x] Test in Ecosystem

**Comment by techcobweb** [comment]
Is this now complete ? What's left to do ?

**Comment by jadecarino** [comment]
Merged in
