### ISSUE TITLE
Set up directory structure for terminal images and save to RAS

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1382]
## Story
As a galasa user, I want to access 3270 terminal images from a directory in the RAS, so that I can view test results without using Eclipse and can easily share the images.

## Background
Part of #1290 - This story focuses on adding functionality to create the directory structure for 3270 images to be stored under as they should be separated from the existing gzipped JSON files that are used by the Eclipse plugin.

This story only needs to create a set of empty image files in the appropriate locations. Stories #1381 and #1383 will handle adding content to the images.

## Tasks
- [x] Decide on the folder structure for storing the images. Multiple terminals in each test, generating a sequence of images. Numbered. In folders.
- [x] Running a test locally deposits the images onto disk. Empty files appear, images to be produced in a separate work item.
- [x] Running a test on the ecosystem deposits the images into RAS (this should be a no-op). Check it works.
- [x] Eclipse doesn't barf when it finds these images files in the RAS artefacts 
- [x] Documentation changes to 3270 Managers in galasa.dev to describe that the manager creates these images and puts into RAS

**Comment by jadecarino** [comment]
'sort out alt sizes' - removed TODO comment. We are unsure what this means.

**Comment by jadecarino** [comment]
Ran this structure passed Will and he thinks we should have 'images' inside 'zos3270' as the zos 3270 manager is what is creating the images.

**Comment by jadecarino** [comment]
PR opened on galasa.dev to add docs for this: https://github.com/galasa-dev/galasa.dev/pull/594

**Comment by jadecarino** [comment]
PR for docs approved - will merge in when code is at main

**Comment by techcobweb** [comment]
Is this now complete ?

**Comment by jadecarino** [comment]
Merged in
