### ISSUE TITLE
Docker inttests failing due to "no linux images available for provisioning the @LinuxImage tagged DOCKER"

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1386]
## Describe the bug

There are two parts to this problem:

1. The Docker inttests (DockerLocalJava11Ubuntu and DockerLocalJava16Ubuntu) are both getting Environmental Failures due to the error below, no linux images available.

```
----------------------- Test Class dev.galasa.inttests.docker.local.DockerLocalJava16Ubuntu status=started
-----------------------     Test Method dev.galasa.inttests.docker.local.DockerLocalJava16Ubuntu.setProps, type=BeforeClass, status=Unknown
-----------------------     Test Method dev.galasa.inttests.docker.local.DockerLocalJava16Ubuntu.setupEnvironment, type=BeforeClass, status=Unknown
-----------------------     Test Method dev.galasa.inttests.docker.local.DockerLocalJava16Ubuntu.testDockerIvtTest, type=Test, status=Unknown
25/02/2023 06:12:43.763 INFO  main dev.galasa.framework.TestRunner.generateEnvironment - Starting Provision Generate phase
25/02/2023 06:12:44.121 INFO  main dev.galasa.linux.internal.shared.LinuxSharedProvisioner.provisionLinux - Selected shared Linux image for PRIMARY host id is GALLNX01, with username galasa59
25/02/2023 06:12:44.165 DEBUG main dev.galasa.linux.internal.shared.LinuxSharedImage.<init> - Linux shared image GALLNX01 has hostname of 9.20.206.13
25/02/2023 06:12:44.256 TRACE main dev.galasa.linux.internal.shared.LinuxSharedImage.<init> - Creating username galasa59 on host GALLNX01
25/02/2023 06:12:44.680 TRACE main dev.galasa.ipnetwork.spi.SSHClient.connect - SSH Client connected to '9.20.206.13:22
25/02/2023 06:12:44.682 TRACE main dev.galasa.ipnetwork.spi.SSHClient.issueCommand - Issuing 'sudo useradd -s /bin/bash -m galasa59 && echo galasaresponse=$?'
25/02/2023 06:12:46.392 INFO  main dev.galasa.framework.internal.cts.FrameworkConfidentialTextService.registerText - Confidential text registered as '*************1**************', with comment Temporary password for username galasa59
25/02/2023 06:12:46.396 TRACE main dev.galasa.ipnetwork.spi.SSHClient.issueCommand - Issuing 'echo -e "ThisIsTheFutureOfTesting7382
ThisIsTheFutureOfTesting7382" | sudo passwd galasa59 && echo galasaresponse=$?'
25/02/2023 06:12:46.878 TRACE main dev.galasa.ipnetwork.spi.SSHClient.connect - SSH Client connected to '9.20.206.13:22
25/02/2023 06:12:46.878 TRACE main dev.galasa.ipnetwork.spi.SSHClient.issueCommand - Issuing 'pwd'
25/02/2023 06:12:47.735 INFO  main dev.galasa.linux.internal.shared.LinuxSharedImage.<init> - Home directory for linux image tagged PRIMARY is /home/galasa59
25/02/2023 06:12:47.774 TRACE main dev.galasa.linux.internal.shared.LinuxSharedProvisioner.provisionLinux - There are no suitable shared Linux images available
25/02/2023 06:12:48.514 DEBUG main dev.galasa.openstack.manager.internal.OpenstackHttpClient.connectToOpenstack - Connected to the OpenStack server
25/02/2023 06:12:50.935 INFO  main dev.galasa.framework.TestRunner.generateEnvironment - Provision Generate failed
dev.galasa.framework.spi.FrameworkResourceUnavailableException: Resources unavailable during provision generate
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:475) ~[-1677305558102:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435) [-1677305558102:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1677305558102:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.framework.spi.ResourceUnavailableException: There are no linux images available for provisioning the @LinuxImage tagged DOCKER
	at dev.galasa.linux.internal.LinuxManagerImpl.generateLinuxImage(LinuxManagerImpl.java:256) ~[?:?]
	at dev.galasa.linux.internal.LinuxManagerImpl.provisionGenerate(LinuxManagerImpl.java:203) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:473) ~[-1677305558102:?]
	... 9 more
dev.galasa.framework.spi.FrameworkResourceUnavailableException: Resources unavailable during provision generate
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:475) ~[-1677305558102:?]
	at dev.galasa.framework.TestRunner.generateEnvironment(TestRunner.java:435) [-1677305558102:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:368) [-1677305558102:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:235) [boot.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:168) [boot.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:122) [boot.jar:?]
Caused by: dev.galasa.framework.spi.ResourceUnavailableException: There are no linux images available for provisioning the @LinuxImage tagged DOCKER
	at dev.galasa.linux.internal.LinuxManagerImpl.generateLinuxImage(LinuxManagerImpl.java:256) ~[?:?]
	at dev.galasa.linux.internal.LinuxManagerImpl.provisionGenerate(LinuxManagerImpl.java:203) ~[?:?]
	at dev.galasa.framework.TestRunManagers.provisionGenerate(TestRunManagers.java:473) ~[-1677305558102:?]
	... 9 more
25/02/2023 06:12:51.051 INFO  main dev.galasa.framework.TestRunner.markWaiting - Placing this run on waiting for 227 seconds
25/02/2023 06:12:51.058 INFO  main dev.galasa.framework.TestRunner.runTest - Placing queue on the waiting list
25/02/2023 06:12:51.463 INFO  main dev.galasa.ras.couchdb.internal.CouchdbRasWriteByteChannel.close - Stored artifact /framework/cps_record.properties, length=0, contentType=plain/text
25/02/2023 06:12:51.485 INFO  main dev.galasa.ras.couchdb.internal.CouchdbRasWriteByteChannel.close - Stored artifact /framework/cps_record.properties, length=2796, contentType=plain/text
25/02/2023 06:12:51.486 INFO  main dev.galasa.framework.Framework.shutdown - Shutting down the framework
25/02/2023 06:12:51.486 TRACE main dev.galasa.framework.Framework.shutdown - Shutting down the Confidential Text Service
25/02/2023 06:12:51.486 TRACE main dev.galasa.framework.Framework.shutdown - Shutting down the Credentials Service
25/02/2023 06:12:51.489 TRACE main dev.galasa.framework.Framework.shutdown - Shutting down the Result Archive Store
```

2. They are not stopping at this point, the tests are retrying multiple times, the most times I've seen before managing to shut them down was ~290. This is absolutely filling up galasa-prod with Pods and most importantly, blocking the regression-test job from finishing, so we are not getting an accurate timely report of the rest of our test results every morning as we should be. **I have removed these two tests from the regression testing schedule for now to avoid the blockage.**

## Tasks
- [x] Determine why there are no linux images available to provision the DOCKER instance
- [x] Once fixed, run these two tests using galasactl
- [x] Add tests back into the schedule

**Comment by jadecarino** [comment]
This is also blocking item https://github.com/galasa-dev/projectmanagement/issues/1366

**Comment by jadecarino** [comment]
The DSS is not being cleared properly, which was leaving multiple properties for compute resources in there, so it seemed to tests that there were no available resources. I have since cleared the DSS so this problem has stopped (for now).
