### ISSUE TITLE
Upgrade snake-yaml to remediate PSIRT ???

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1390]
## Story
As a galasa consumer I want to use a galasa which doesn't contain the snakeyaml ecurity vulnerability so my test solution scans cleanly.

## Background
snakeyml now has a fix for the sockets vulnerability (which never effected galasa anyway), and a new version is available which passes mend scans.

PSIRT link is here: https://ibm.service-now.com/sn_vul_ibm_advisory.do?sys_id=ee66edfe1bbced18d4122f42b24bcb4a&sysparm_view=&sysparm_view_forced=true

Previous stories which were in this area:
- https://github.com/galasa-dev/projectmanagement/issues/1300
- https://github.com/galasa-dev/projectmanagement/issues/683

## Tasks
- [x] Indentify the level we need to migrate to
- [x] Replace snakeyaml with the latest version available
- [x] Verify that it builds and doesn't regress the system
- [ ] Populate a branch of the mend database to make sure mend scans give a clean bill of health
- [x] Make it ready for the 0.26.0 release.

**Comment by techcobweb** [comment]
@hobbit1983 Raised this to make sure we make the basic change a.s.a.p.
