### ISSUE TITLE
Automate deletion of images from IBM Cloud Container Registry post-release of OS Galasa

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1391]
## Story
As a Galasa developer, I want to automate the deletion of docker images that were built as part of a Galasa release from the IBM Cloud Container Registry, so that I don't have to do it manually.

## Tasks 
I already started the work for this and pushed it to the branch 'delete-images-from-icr' of the automation repository.

The only step left is to create a Service ID on IBM Cloud, to then generate an API Key for this Service ID. The API Key is needed so that we can authenticate to the IBM Cloud CLI in a pipeline. We need an API Key that is for a Service ID, so that it is not linked to an individual user, as this is bad practice.

- [x] Create Dockerfile for image that has capability to run the IBM Cloud CLI
- [x] Create Task that has two steps, 1. authenticate to the IBM Cloud CLI using ExternalSecret mentioned below 2. execute command using the IBM CLI.
- [ ] Create Service ID on IBM Cloud with API key
- [x] Create an ExternalSecret that pulls from Vault the IBM Cloud API Key created in the above step
- [x] Use Task mentioned above on the 'branch-delete-all' pipeline to delete the galasa-isolated, galasa-isolated-zip, galasa-mvp, galasa-mvp-zip and galasa-resources images from ICR.

**Comment by jadecarino** [comment]
No longer needed as we don't publish the intermediate images to ICR in the release process anymore.
