### ISSUE TITLE
Automate deletion of images from Harbor post-release of OS Galasa

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1392]
## Story
As a Galasa developer, I want to automate the deletion of docker images that were built as part of a Galasa release from Harbor, so that I don't have to do it manually.

## Background
During the release, the automated deletion of images from Harbor using 'galasabld harbor' did not work. I have just ran the command locally against an image that can be deleted to get the error again:
```
[galasabld harbor deleteimage --harbor harbor.galasa.dev --project galasadev --repository galasa-wrapping --tag jadecarino --username XXX --password XXX]
panic: Delete "harbor.galasa.dev/api/v2.0/projects/galasadev/repositories/galasa-wrapping/artifacts/jadecarino/tags/jadecarino": unsupported protocol scheme ""

goroutine 1 [running]:
galasa.dev/buildUtilities/pkg/cmd.executeHarbor(0x170c660?, {0x141e11b?, 0xc?, 0xc?})
	/workspace/git/trigger-buildutils-main-8lm4z/buildutils/pkg/cmd/harborDeleteImage.go:62 +0x477
github.com/spf13/cobra.(*Command).execute(0x170c660, {0xc0001280c0, 0xc, 0xc})
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x170cde0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
galasa.dev/buildUtilities/pkg/cmd.Execute()
	/workspace/git/trigger-buildutils-main-8lm4z/buildutils/pkg/cmd/root.go:22 +0x25
main.main()
	/workspace/git/trigger-buildutils-main-8lm4z/buildutils/cmd/galasabld/main.go:20 +0x6a
```

I think the Harbor API galasabld is using could be outdated but this needs investigating properly. Not super urgent to be completed before the next release as we can delete images manually, it's just more time consuming.

## Tasks 
- [x] Check the galasabld harbor code to determine the problem
- [x] Fix the code in galasabld
- [x] Deliver the fix ensuring the galasabld:main image is rebuilt
- [x] Test fix by running galasabld locally
- [x] Test fix by running the branch-delete-all pipeline (no need to try with all images, can comment most of the pipeline out and just do one dummy image)
