### ISSUE TITLE
Upgrade IBM Cloud Kubernetes cluster to version 1.24 by 26th April

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1394]
##  Background
v1.23 of Kubernetes is no longer being supported in IBM Cloud after 26th April. We need to upgrade to v1.24.

## Tasks
Pre-work:
- [x] [Research any API changes between 1.23 and 1.24](https://kubernetes.io/blog/2022/04/07/upcoming-changes-in-kubernetes-1-24/)
- Main change in v1.24 is the removal of Dockershim as a container runtime. Taken from the Kubernetes docs: "You need to install a [container runtime](https://kubernetes.io/docs/setup/production-environment/container-runtimes) into each node in the cluster so that Pods can run there. This page outlines what is involved and describes related tasks for setting up nodes." Some common container runtimes are [containerd](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd), [CRI-O](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o), [Docker Engine](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker) and [Mirantis Container Runtime](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#mcr). 
- [x] [Find out what container runtime we use](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/)
- We use containerd so the Dockershim removal doesn't affect us
- [x] Make necessary updates based on those changes
- No updates required

Upgrade the cluster:
- [x] Let galasa-devs know about the upgrade as cluster services may be down
- [x] Upgrade cluster by pressing the button on IBM Cloud - this will update the master node
- [x] Update both worker nodes one after the other
- [x] Check state of cluster on dashboard to make sure everything happy
- [x] Run regression tests to check things seem okay

**Comment by jadecarino** [comment]
Now that the pre-work is done, I am planning to upgrade the cluster on Monday 17th April PM before I go on annual leave. If that doesn't work for everyone (as cluster will be down temporarily during the uprgrade), then my next day available to do it is Monday 24th April, so I'd rather go for the 17th so we're not too close to the deadline.

**Comment by jadecarino** [comment]
Cluster updated to v1.24.12
