### ISSUE TITLE
CLI galasactl jvm launch to work in Windows

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1395]
## Story
As a galasa test case developer I want to use Windows to run tests in the local JVM using the galasa CLI, so I can avoid using any IDE.

## Tasks
- [ ]  URLs in the command we build for the JVM should use `file:///`
`file:///` instead of `file:` or `file://`. 
This effects the variables `--localmaven` `--removemaven` `--bootstrap` and `--overrides`

- [ ] URLs should have slashes which all slant up to the right. `/` and not `\`.

- [ ] The jar path slants to the left `\` rather than `/`

For example:
```
 java -jar C:\Users\mcobbett\.galasa\lib\0.26.0\galasa-boot-0.26.0.jar `
-Dfile.encoding=UTF-8 `
--localmaven file:///C:/Users/mcobbett/.m2/repository `
--remotemaven https://development.galasa.dev/main/maven-repo/obr/ `
--bootstrap file:///C:/Users/mcobbett/.galasa/bootstrap.properties `
--overrides file:///C:/Users/mcobbett/AppData/Local/Temp/galasa-3114329541overrides.properties `
--obr mvn:dev.galasa.example.banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/obr `
--obr mvn:dev.galasa/dev.galasa.uber.obr/0.26.0/obr `
--test dev.galasa.example.banking.account/dev.galasa.example.banking.account.TestAccount 
```

- [ ] The overrides file to which we refer must have parameters which describe the RAS folder by slanting in the correct way.
