### ISSUE TITLE
CLI to generate an OBR project source folder from other projects it can find.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1404]
## Story

As a galasa test case developer, I want to create an OBR project which includes all the sub-projects available from the current folder, so I don't need to remember how to create an OBR project.

## Background
If you use eclipse, and there is a task to create an OBR project to index the test-case projects.

- Auto-detect what other modules are available, from the current folder, or a specific folder.
- Create the OBR with pom/gradle artifacts to package those modules.
- Allow --force to over-write any OBR project files which already exist.

## Tasks
- [ ] Parameter for folder to draw information from gathered and documented.
- [ ] Detect modules based on the source folder.
- [ ] Create OBR project from templates
- [ ] Test on linux
- [ ] Test on Windows
- [ ] Maven and Gradle variants.
