### ISSUE TITLE
CLI to show passed/fail status downloading test result of a test run from an ecosystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1405]
## Story
As a CLI user, I want to get all the pass/fail state of a particular test run, so I can see what the end-state was when the test was run.

## Background
- Using the cmd line tool `galasactl`, given a runname, get the summary describing the end-state of the test
- Download the summary file from the (new) REST interface API.
- DO NOT Store the information. Output goes to stdout
- See https://ibm.box.com/s/lytyx26hw0v9mqik5yyl51di0xo3ip8z for possible syntax of the command.

## Tasks
- [x] Design the REST interface objects, updating the OpenAPI yaml document so we can see the API documented clearly. Or re-use/modify the existing interface.
- [x] Review and agreement on the contents of the REST API
- [x] Summary output from CLI, given a single runid, and unit tests.
- [x] ~Validate (something) about the runname given by the user to the CLI~ - runname prefixes can be overridden by CPS properties, so validating is unnecessary
- [x] Page number starts with 1. add that detail to openapi.yaml
- [x] CLI unit tests produce each of the possible error codes.
- [x] Galasactl CLI command added to exercise the rest interface.
- Unit tests as we go.
- [x] Integration test to call the REST API for a runID and check the results.
- [x] Stand up a real servlet ? and test against that.
- [x] The URLs can be called while a test is in-flight/not yet complete, and still gives sensible results.
- [x] Fails if the RUNname is unknown

**Comment by hobbit1983** [comment]
@KirbyKatcher Nice work on the design.  Really helps to see examples of what can be specified.  I've added a comment that I think we need to address
