### ISSUE TITLE
REST interface in our documentation reference section.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1406]
## Story
As an application developer, I want to read the REST interface to Galasa so I can understand what integrations I could be coding to get more value out of a Galasa ecosystem.

## Background
Can we render the openapi documentation into a reference section of the docs during the build process ?
There are a number of tools which can do this... which one should we be using ?

## Tasks
- [x] Identify the tooling we plan to use to render the documentation
- [x] Get it working in the build-locally.sh script of a repo.
- [x] Get it working in the tekton PR and mainline builds.
- [x] Fix the issue with the generated docs that is causing schemas to be rendered empty
- [x] Publish the built documentation
  - [x] Development version to a path on development.galasa.dev - https://development.galasa.dev/main/restapidoc-site
  - [x] Release version to rest.galasa.dev
- [x] Add to the galasa-dev website in the reference section, with a textual introduction.
