### ISSUE TITLE
CLI command to get the test run artifacts from an ecosystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1407]
## Story
As a tester running test cases, I want to use the CLI to retrieve all the artifacts associated with that runid from a remote galasa ecosystem, so I can see what happened to a test run.

### Original requirement written by @alfonso-rios-ibm
It would be nice to get the run log using a CLI command or maybe adding a flag in the existing **prepare** and/or **submit** command to print it as the test is being executed. This way we do not have to look at the log in the Eclipse plugin. Other people who does not have Galasa installed and properly configured in their system can check the log.

### Syntax
`galasactl runs get --runid xyz ` >> creates a folder 'xyz' in the current folder, and copies the artifacts from the ecosystem test run into it.

`galasactl runs get --runid xyz --targetdir abc` >> gets artifacts associated with a test run, putting the folders into a target folder rather than the current folder, failing if the folders already exist.

`galasactl runs get --runid xyz --runid abc` >> gets everything about both runids into the current folder, in sub-folders `xyz` and `abc`

`galasactl runs get --runid xyz --force` >> gets artifacts associated with the test run deleting any folders which already exist, and re-creating the runid folder in the targetdir

> Note: Deletes the existing folder prior to creating new content. This is important because we don't want to mix old run artifacts in the same folder as new run artifacts.

`galasactl runs get --runid r1 --runid r2 --targetdir abc` >> gets results and unpacks them into the target dir in folders r1 and r2

> Note: The `--runid r1` flags are a trivial example of testrun selection criteria. This concept can be expanded in later stories to include queries by regex, test case, test package, tag, date started, today, yesterday, this week, last week, the past 2 weeks, the past month, 2 hours ago...etc

A bootstrap location is needed explicitly using the `--bootstrap` parameter or via the `GALASA_BOOTSTRAP` environment variable.

### Parameters
- `--runid` The id of the run detail to get. Multiple runids can be used in one command.
- `--targetdir` The folder things are unpacked into. The files are always placed in a folder with the runid.
If not specified, then the current folder is used.
- `--force` force-overwrite files if they already exist.

## Tasks

- [ ] Support the `runs get` command in a basic form, which does nothing.
- [ ] Support the `--runid` field.
- [ ] Support multiple runid fields.
- [ ] Collect the targetdir folder parameter, defaulting it to the current folder
- [ ] Get the summary of the run from the REST API.
- [ ] Get the un-zipped data, leaving it in a folder name
- [ ] Fail if the file already exists, and `--force` isn't used
- [ ] Overwrite existing files if `--force` is used.
- [ ] Documentation PR to Caroline.

**Comment by hobbit1983** [comment]
Just some comments around the testing of this:
 * We should test the API when the test is in flight (and might not have written anything yet)
 * A test that doesn't exist in the ecosystem
 *
