### ISSUE TITLE
CLI to zip downloaded test artifacts

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1408]
## Story
As an an application developer debugging a failing test, I want to download the artifacts associated with a test run, into a zipped archive, so I can easily send the artifacts to someone else.

## Background
Artifacts from the CLI are not stored in folders as files, they are stored in .zip files. 

For example: `galasactl runs get --runid xyz --zip` - Creates a zip file called xyz.zip for that runid.

If multiple runids are requested, you get multiple zip files.

For example: `galasactl runs get --runid xyz --runid abc --zip` - Creates a zip file called `xyz.zip` for that runid, and another called `abc.zip` for the second runid.

## Tasks
- [ ] Add the --zip parameter to the CLI
- [ ] Downloads to be targeted in a temporary folder elsewhere on the disk. MkTempDir ...etc.
- [ ] Zip up the contents of the downloaded folder.
- [ ] Folder structure has a folder within which contains the run-id, so if several are un-packed, you get separate top-level folders with the runIDs as names.
- [ ] Support the `--targetfolder` parameter so you can direct the zip files to appear where you want, defaulting to the current directory.
- [ ] Documentation PR to Caroline.
