### ISSUE TITLE
CLI create project --manager creates a manager module

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1410]
## Story
As a galasa testcase developer I want to use the galasa CLI to create a new project of an example manager, and an extra test class which uses that manager, and an entry in the OBR which refers to that manager

## Background
This would be a good feature to then go on and talk about the manager in the docs.

The manager name should be gathered from the CLI syntax. For example with a `--managerName xxx` parameter. Then we can use that to name the project folder, and manager annotation...etc.

## Tasks
- [ ] Finalise syntax of the CLI
- [ ] Add the new parameters
- [ ] Generate the new manager project
- [ ] OBR generated adds the manager project
- [ ] Extra testcase generated which demonstrates the use of the manager
- [ ] Docs explaining what got generated, and why you might like to.

**Comment by aadityasinha-dotcom** [comment]
Hi @techcobweb is this issue available?

**Comment by techcobweb** [comment]
Yes, @aadityasinha-dotcom we have nobody looking at this right now, with no outlook of when we might resource it.

Is the story clear enough to attempt the suggested tasks ?

**Comment by aadityasinha-dotcom** [comment]
Hi @techcobweb, thanks for the reply. I did tried the galasa-cli. Like when we create a Galasa project we add flags like `--package`, here for this issue we need a `--manager` flag which will create a manager class and will take the manager name from the cli syntax.
The thing I want to know is where can I see manager examples in `galasactl`.

**Comment by techcobweb** [comment]
Aaditya Sinha
> Hi, Update: I  managed to resolved the error, had to do some changes in the build file
Now I will start working on the project create --manager issue, thanks for the help

Mike Cobbett
> That's super news. Very interested to see how you get on.

Aaditya Sinha
> thanks

Aaditya Sinha
> Hi, sorry I didn't post the update to you. I was sick for a week
Here's the update on the manager module, I have added the the flag `--manager` which will create the manager folder having .bnd, gradle and pom.xml with a src directory.
Currently I am working on adding the template files for the manager class which were in the managers repo that you gave me.

Mike Cobbett
> Sry for not getting back also, I've been on vacation. Back now. That sounds amazing. Really keen to see it in action ! Any time you want me/the team to review a pull request please raise it (even if it's draft).

**Comment by techcobweb** [comment]
See PR https://github.com/galasa-dev/cli/pull/256

**Comment by techcobweb** [comment]
Messaged with @aadityasinha-dotcom today about some more background information.

**Comment by Mark-J-Lawrence** [comment]
FYI - @techcobweb @Jimbo4794 I've now finished putting together an example manager that's self-documenting containing an example of resource management.
This is going into the internal CICS Galasa manager creation wizard, but could be contributed here also.

**Comment by techcobweb** [comment]
[com.ibm.cics.galasa.blahhh.manager.zip](https://github.com/user-attachments/files/17376050/com.ibm.cics.galasa.blahhh.manager.zip)
Authored by Mark-J-Lawrence

This zip file contains an example we might like to encode in templates.

blahhh being the manager name, which would be tokenized.

java package names are also tokenized of course.

**Comment by Mark-J-Lawrence** [comment]
Should it help.....here is our tokenised version of the manger
[example-manager-tokenised.zip](https://github.com/user-attachments/files/17376151/example-manager-tokenised.zip)
