### ISSUE TITLE
CLI ability to launch a specific method, or methods rather than the whole test class.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1411]
## Story
As a galasa testcase developer, I want to be able to run a specific method within a test, rather than all the methods marked with @test within a class.

## Background

This constitutes a selection criteria on the test methods which get run.

It could be a specific match for the test method, a regex.

The criteria needs to be a list of method selection criteria

It could be added to a portfolio ? Needs thought and perhaps a separate story to cover this.

This was asked about in the recent customer call.

Eclipse UI has fields to supply this information, but does nothing with them so far. Need to raise a separate story to also add this functionality into eclipse.

## Tasks
- [ ] Add the ability to take a list of method selection criteria into the core test runner in the framework.
- [ ] Add the ability to specify the list of methods from the command-line using exact matching.
- [ ] Decide on the command-line syntax for test method selection. Default is '.*' 
- [ ] Add the ability to specify a regex to match against the method names.
- [ ] Update test reporting in the CLI to allow a count of test methods passed/failed to show in the overall and interrim text reports when the tests are running.
- [ ] Allow the passing of the test methods over the REST API so that this can control which tests run on a remote ecosystem

**Comment by haripra86** [comment]
Looking forward for this enhancement.
