### ISSUE TITLE
CLI command-line tool needs testing on z/Linux

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1412]
## Story
As a galasa testcase developer working on zLinux, I want to be able to use the Galasa command-line tooling to create a project which is compileable on zLinux, and execute a test in a local JVM, then view the results and artifacts generated by it.

## Background
Launching a local JVM on zLinux works, but the testcase results were 'lost'... probably because the path specified in the RAS location isn't correctly set in the tool. There is a default URL path which is hard-coded right now.

Can we develop a script which is runnable on zLinux ? How would that differ from running on normal Linux or a mac ? eg: test-locally.sh could determine whether it was linux/mac and do some things different if required...

## Tasks
- [ ] Get a zLinux instance we can test with
- [ ] Install the galasactl tool
- [ ] Test as much as we can... up to running a local test

**Comment by techcobweb** [comment]
@hobbit1983 may be able to provide extra details about the failure discovered so far.
