### ISSUE TITLE
RAS runs out of space when large changes to data in couchdb take place

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1415]
## Story
As a galasa developer, I want to keep the size of the RAS database as small as possible by using the minimum number of revisions, so that tests can continue to run without the risk of storage space running out and clogging up the database.

## Background
An overnight test pack failed due to the RAS running out of memory thus further tests where not able to complete as they where unable to save their results on the couchdb instance.
Initial investigation by @hobbit1983 , @jadecarino and @eamansour has suggested that this is due to the number of revisions being stored for each entry by the database. 

This value is set by default at 1000 revisions in order to enable sharding for replication across clustered instances.
As we use a single instance for the RAS it would be best to reduce the number of revisions for each data entry to a more suitable size.

https://docs.couchdb.org/en/stable/api/database/misc.html#db-revs-limit

This has already been tested and has shown a significant reduction in the amount of space needed and alongside manual compaction of the database allows for the RAS to behave as intended.
 
https://docs.couchdb.org/en/stable/maintenance/compaction.html#manual-database-compaction

## Tasks
- [ ] Identify and agree on an appropriate number of revisions for each of the databases to use.
- [ ] Identify and agree on an appropriate compaction method and it's triggers.
- [ ] Identify and locate the best code implementation for the above points and update the tasks for this issue
