### ISSUE TITLE
CLI to get status from multiple runs at once

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1420]
## Story
As a command-line user of galasa, I want to view the status from several runs at the same time, so I don't have to repeatedly call the galasactl command

## Background
`galasactl runs get --name U456,U457` will display summaries of two runs U456 and U457 on stdout.

eg:
U456 Finished Passed ...

See https://ibm.box.com/s/lytyx26hw0v9mqik5yyl51di0xo3ip8z for a full detailed list of syntax

## Tasks
- [ ] CLI to cope with accepting multiple run names
- [ ] OpenApi.yaml indicates that you can repeat the runname field.
- [ ] Servlet to accept mutiple runname query parameters
- [x] CLI loops through processing each one in turn.
- [ ] Tabular view of results looks good
