### ISSUE TITLE
CLI runs download supports --all and --artifact flags

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1424]
## Story
As a command-line galasa user I want to use galasactl to specify which artifacts I want to download, rather than downloading them all.

## Background
See the CLI syntax draft document here: https://ibm.box.com/s/lytyx26hw0v9mqik5yyl51di0xo3ip8z

## Tasks
- [ ] `galasactl runs download` supports --all flag
- [ ] `galasactl runs download` supports one `--artifacts <regex>` parameter
- [ ] `galasactl runs download` supports a list of `--artifacts <regex>` parameters
- [ ] Unit tests are assumed
- [ ] IVT
