### ISSUE TITLE
CLI runs download supports the --destination option

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1425]
## Story
As a galasa tester trying to download test run artifacts, I want to specify which folder the downloaded artifacts get placed, not just my current directly.

## Background
See the CLI syntax design doc here: https://ibm.box.com/s/lytyx26hw0v9mqik5yyl51di0xo3ip8z

The target file replaces the '.' file which is the default location.

Folders below that will still have the run name folder, containing sub-folders and artifacts.

## Tasks
- [ ] Folder is created if it doesn't already exist
- [ ] Fail if it does exist already
- [ ] --force flag to over-write it if it exists already, after first deleting the folder which exists.
- [ ] `galasactl runs download` allows the --destination to indicate where the data should end up.
