### ISSUE TITLE
CLI artifact download adds timestamp to downloads folder if test is still running

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1426]
## Story
As a test developer investigating a problem, I want to download artifacts associated with a test run which hasn't yet finished.

## Background
Tests may not have finished, so the artifact collection may not be complete yet.

Suggestions so far:
- If the test isn't finished, append the current time to the folder name into which the test is stored.
- Should we output the folder names/locations into which we have put information ?
eg:
```
GAL1xxxxI: Downloaded 11 files to folder U344_2023-06-08_16:40:28. << Test is still running.
GAL1xxxxI: Downloaded 5 files to folder U476 << This test has completed.
```
That seems to have been the best solution so far. Any better ideas ?

## Tasks
- [x] Implement
- [x] Test added to IVT ?
- [x] Documentation of this behaviour ?

**Comment by techcobweb** [comment]
## Story
As a test developer investigating a problem, I want to download artifacts associated with a test run which hasn't yet finished.

## Background
Tests may not have finished, so the artifact collection may not be complete yet.

Suggestions so far:
- If the test isn't finished, append the current time to the folder name into which the test is stored.
- Should we output the folder names/locations into which we have put information ?
eg:
```
U476 downloaded to xxx
U476 downloaded to yyy
```
That seems to have been the best solution so far. Any better ideas ?



## Tasks
- [ ] Implement
- [ ] Test added to IVT ?
- [ ] Documentation of this behaviour ?

**Comment by techcobweb** [comment]
This story superceeded by the --active and --result filter stories.
