### ISSUE TITLE
API server to generate and use openapi transport beans.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1428]
## Story
As a galasa developer I want the servlets within the API server layer to use generated transport beans, so that I know the code responses are consistent with the openapi.yaml

## Background
This will save no end of headaches where the yaml doesn't match what the server sends back, or chat it expects from client code. Also means that the externals in the openapi.yaml are the truth in what the code actually does.

## Tasks
- [ ] Build locally changes to generate transport beans
- [ ] Tekton build process to generate transport beans
- [ ] Check that the bean code is NOT checked in
- [ ] Servlets to adopt the transport beans rather than handle their own serialisation
  - [ ] CPS
  - [ ] RAS
  - [ ] ...etc for the other servlets that we have

**Comment by techcobweb** [comment]
Duplicate of [Investigate generating api pojos from the openapi.yamls#529](https://github.com/galasa-dev/projectmanagement/issues/529)
