### ISSUE TITLE
Automated testing of the Galasa CLI - extended scope

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1429]
## Story
As a Galasa developer, I want to be able to test that the test projects generated by 'galasactl project create' are able to run in a Galasa ecosystem, in automation.

## Background
This story encompasses extended scope for the Issue 1413 https://github.com/galasa-dev/projectmanagement/issues/1413

## Tasks:
- [x] Generate a test project with 'galasactl project create' (Already done in 1413)
- ~~Push the generated test project to GitHub~~ scope removed
- ~~Figure out which GitHub repository (existing or new) we push this to~~
- ~~In the pipeline that executes the automated CLI tests, trigger build of the GitHub repository, to rebuild with the new generated project inside, to ensure that rebuild has recycled the testcatalog~~
- ~~Run those tests using 'galasactl runs submit' in the ecosystem~~

- [x] Add test for galasactl runs get --runname for an ecosystem test
- [x] Add test for overriding --galasaHome
- [x] Add test for project create adding .gitignore file

- ~~Add tests for different os architecture for in the CLI pipeline, currently only does linux-amd64~~ Can't do this. scope removed.

**Comment by techcobweb** [comment]
@jadecarino How is this work doing ? Stuck ?

**Comment by jadecarino** [comment]
@techcobweb Nope, just wanted to check if there was anything higher priority. Happy to work on this :)

**Comment by jadecarino** [comment]
@techcobweb Having had a think about this, I don't think there is any benefit from pushing the test project generated with galasactl, to GitHub to add it to a testcatalog, to then run that test in the ecosystem. We're not really testing galasactl here, more our ability to add something to a testcatalog. Can I remove this from the spec of this item?

**Comment by techcobweb** [comment]
There would be some benefit in that we capture the entire lifecycle, and could then really push a failing test for variety. But it's less important than just getting something to work. Would require a stream to draw from artifactory and a maven push to that.

**Comment by jadecarino** [comment]
Closing this as tasks on this item complete. Additional tests will be added to the script when new features added to the cli.
