### ISSUE TITLE
Clean up old infrastructure from pre-August 2022

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1432]
## Story
As a Galasa developer, I want all references to the old infrastructure cleaned up or archived, so that it is not confusing what we actively use and what we don't.

## Background
Unsure if this is a duplicate item, I thought we already had an item for this but I can't seem to find it. If it's a duplicate please feel free to merge and delete.

## Tasks

While working through this, keep a detailed list of what has been done, in case anything goes wrong so hopefully we can fix it easily. 

- [x] Pull harbor-cicsk8s version of galasa-cli-ibm-amd64 as that is an older but stable version of the CLI, that we are using for regression testing
- [x] Retag it as harbor.galasa.dev/galasadev/galasa-cli-ibm-amd64:stable
- [x] Push it to harbor.galasa.dev
- [x] Same tasks for galasa-bld-ibm-amd64
- [x] Change regression-test CronJob to use these images in their respective containers (use kubectl patch, but Jade doesn't have permissions)
- [x] Add steps to release documentation about retagging release as stable so that after each release we are using the newest released version of the CLI

~Update ecosystem CPS properties (in GHE) to point to https://harbor.galasa.dev~ See comment below.
- [x] galasaecosystem.docker.registry
- [x] docker.registry.HARBOR.url
- [x] docker.registry.PROXY.url

Disable Jenkins pipelines (can be deleted later once confirmed stable without)
- [x] Bld_Pipeline
- [x] Cli_Pipeline
- [x] CodeCoverage_Pipeline
- [x] Eclipse_Pipeline
- [x] External_Pipeline - This means docker.galasa.dev will no longer be rebuilt
- [x] Integration_Pipeline
- [x] Inttests_Pipeline
- [x] Main_Builds
- [x] Pull_Requests
- [x] Regression_Testing
- [x] SimPlatform_Pipeline
- [x] Template_Pipeline
- [x] VsCode_Plugin
- [x] WebUI_pipeline

Delete images in the internal Harbor that we have new versions of in the external Harbor (potentially pull in the image locally in case it needs to be temporarily repushed):
- [x] galasadev/busybox
- [x] galasadev/galasa-maven-base
- [x] galasadev/galasa-maven-wrapping
- [x] galasadev/galasa-maven-gradle
- [x] galasadev/galasa-maven-maven
- [x] galasadev/galasa-maven-framework
- [x] galasadev/galasa-maven-extensions
- [x] galasadev/galasa-maven-managers
- [x] galasadev/galasa-maven-obr
- [x] galasadev/galasa-maven-inttests
- [x] galasadev/galasa-maven-eclipse
- [x] galasadev/galasa-maven-javadoc
- [x] galasadev/galasa-maven-simplatform
- [x] galasadev/galasa-maven-isolated
- [x] galasadev/galasa-maven-mvp
- [x] galasadev/galasa-mvp
- [x] galasadev/galasa-isolated
- [x] galasadev/galasa-p2
- [x] galasadev/galasa-javadocs
- [x] galasadev/galasa-obr-generic
- [x] galasadev/galasa-boot-embedded-amd64
- [x] galasadev/galasa-ibm-boot-embedded-amd64
- [x] galasadev/galasa-cli-amd64
- [x] galasadev/galasa-cli-ibm-amd64
- [x] galasadev/galasa-cli-binary
- [x] galasadev/galasa-bld-amd64
- [x] galasadev/galasa-bld-ibm-amd64
- [x] galasadev/galasa-bld-binary
- [x] galasadev/galasa-codecoverage
- [x] galasadev/galasa-build

Deleting the above will break the old internal maven repositories. So, delete the apps on the internal ArgoCD to bring those down:
- [x] bld-main-repo
- [x] bld-prod-repo
- [x] cli-main-repo
- [x] cli-prod-repo
- [x] galasa-main-repo
- [x] galasa-prod-repo
- [x] inttests-main-repo
- [x] inttests-prod-repo
- [x] scheduler-main-repo
- [x] simplatform-main-repo
- [x] simplatform-prod-repo

Hesitant to delete these in case it deletes all resources therein, check with James:
- [x] galasa-codecov-tekton
- [x] galasa-main-tekton
- [x] galasa-1008-tekton
- [x] galasa-1029-tekton
- [x] galasa-1063-tekton
- [x] galasa-976-tekton
- [x] galasa-955-tekton
- [x] galasa-828-tekton
- [x] galasa-984-tekton
- [x] galasa-990-tekton

Delete the argoCd directories and docker directories in various GitHub repos:
- [x] wrapping
- [x] gradle
- [x] maven
- [x] framework
- [x] extensions
- [x] managers
- [x] obr
- [x] eclipse
- [x] isolated
- [x] cli
- [x] buildutils

Archive old GitHub repositories and add note to README.md:
- [x] tekton-build
- [x] kubernetes-operator
- [x] docker-operator
- [x] vscode
- [x] examples
- [x] argocd (Do this one last, as ArgoCD apps depend on this GitHub repository)

All repositories Jade is unable to archive due to access have been moved to #1457 .

**Comment by jadecarino** [comment]
I think this item is important to do while we are doing this work: https://github.com/galasa-dev/projectmanagement/issues/1360

**Comment by jadecarino** [comment]
Having had a closer look, I don't think we need to update the CPS properties to point to https://harbor.galasa.dev as mentioned above, as all this is used for currently is to pull the busybox and httpd images from harbor-cicsk8s (the library repository which is a Docker proxy) to use in the DockerManagerIVT / Docker integration tests. As harbor-cicsk8s isn't going anywhere as is used by the whole CICS team, I think we can leave this for now.
