### ISSUE TITLE
Eclipse to respect GALASA_HOME environment variable

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1433]
## Story
As a galasa testcase developer using eclipse I want to set the GALASA_HOME environment variable and have the eclipse code pick it up and use it, so it's consistent with the `galasactl` command-line tooling.

I also want a UI panel where I can see the value, and set it based on my eclipse shell configuration for the workspace, so I don't have to set system-wide environment variables if I don't want to do that prior to launching eclipse.

## Background
Story https://github.com/galasa-dev/projectmanagement/issues/1397 added the support for GALASA_HOME into the command-line galasactl tool, and the framework. 

Eclipse users don't really need this functionality as much. 

CLI users need it for automated testing, so each test run can execute inside a temporary folder with custom settings.

## Tasks
- [ ] Pick up the GALASA_HOME environnment variable and use it in constructing all paths which currently use the users' home folder.. If it's missing, then revert to whatever we did before. ie: It's optional.
- [ ] Add a galasa home Galasa setting which over-rides the GALASA_HOME environment variable if set.
- [ ] Document these changes.

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
