### ISSUE TITLE
Galasa.dev certificates need renewing in June 2023

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1443]
## Story
As a galasa user I want the galasa.dev site to stay live, and not stop working because of expired certificates.

## Background
In April, the certificates for galasa.dev expired, and needed to be renewed.

They have a shelf-life of 3 months, so need replacing in June 2023 to avoid an outage.

## Tasks
- [x] Follow the instructions here: ??? in the devguide repo, 
- [x] Change the certificates over.
- [x] Raise another story for another 3 months' time.

**Comment by techcobweb** [comment]
@hobbit1983 Any idea when exactly they are going to expire ?

**Comment by KirbyKatcher** [comment]
https://pages.github.ibm.com/galasa/developer-docs/100-technologies/IBMCloud/
