### ISSUE TITLE
Removal of VTP Manager from OS Project

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1444]
## Story
As an IBM Commercial Offering I want to move the VTP Manager out of the OS project to make it only available through Distribution for Galasa

## Tasks
- [ ] remove the project (and IVT from the open source project)
- [ ] update the build files (if needed)
- [ ] update the OBR and uber OBR
