### ISSUE TITLE
CLI 'runs get' to support '--name U*' wildcard search on run names.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1447]
## Story
As a tester launching tests against the ecosystem, I want to use the command-line to query results of test runs grouped by the test run prefix, so I can see the results of these and act accordingly.

## Background
When a test is submitted to the ecosystem, you can specify a prefix on the runid. This can be used to group the batch of runs if you wish. Getting the results for the group of runs in one go is useful.

`galasactl runs get --name "U*" --age 5d` gets all the runs with a U prefix in the past 5 days.

## Tasks
- [ ] CLI accepts a wildcarded name.
- [ ] Validate the prefix. A letter.
- [ ] CLI passes the wildcarded name on the query parameter to the servlet
- [ ] Servlet accepts the wildcarded name on the query parameter
- [ ] Servlet calls the DB with a different search criteria (run-name like U% instead of the more normal run-name==U456)
- [ ] List of results returned and sorted
- [ ] CLI Docs update in the readme 
- [ ] Servlet openapi.yaml docs updates
- [ ] Pull request for galasa.dev docs
