### ISSUE TITLE
0.28.0 release

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1453]
## Story
As a galasa user I want to get the 0.28.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [x] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [x] Identify problems/improvements and raise them for next time
- [x] Add more detail for asking for release approval
- [x] Add more detail for how to manually install Simbank
- [x] Add documentation to developer-docs for where to upload GPG public key
- [x] Add note about --secret-type to the Eclipse marketplace task.

**Comment by AaronJhaj** [comment]
I think everything has been completed and can be closed @techcobweb
