### ISSUE TITLE
Remove Simplatform (old infrastructure)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1456]
## Story
As a Galasa developer, I want to remove all references to our old infrastructure, so that it is not confusing what is being developed/maintained/used.

## Background
Unsure the repercussions for using Simplatform for deleting these so have removed from https://github.com/galasa-dev/projectmanagement/issues/1432 . 

## Tasks (in this order)
- [x] Delete the app simplatform-prod-app from argocd-cicsk8s
- [x] Remove the argoCd directory in the Simplatform repository
- [x] Delete the galasadev/galasa-simplatform-amd64 from harbor-cicsk8s

**Comment by techcobweb** [comment]
Confirm with @hobbit1983

**Comment by techcobweb** [comment]
- I believe the simbank application is run locally on laptops...etc. 
- You can run it from the command-line.
- This argocd just hosts an image with that simbank application on in cicsk8s.
- We don't really need it hosted for simbank to work I believe.
- So it's safe to delete the argocd application and docker image which causes it to be hosted.

**Comment by jadecarino** [comment]
Tasks have been completed however the Simplatform main build after the PR was merged to remove argocd directory failed. Unfortunately it can't be rerun until Tuesday morning as the cicsk8s cluster is unavailable for maintenance. I'll put on my to-do list for Tuesday AM.

**Comment by AaronJhaj** [comment]
simplatform main build is now working
