### ISSUE TITLE
Archive inactive GitHub repositories

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1457]
## Background
All of the GitHub repositories which are not being actively developed/discontinued etc should be archived so it's not confusing to users/contributors what we are maintaining. This has been stripped out from #1432 as Jade does not have sufficient access to do this.

## Tasks
- [x] Archive https://github.com/galasa-dev/build
- [x] Archive https://github.com/galasa-dev/security-scanning
- [x] Archive https://github.com/galasa-dev/docker
- [x] Archive https://github.com/galasa-dev/githubapp-copyright
- [x] Archive https://github.com/galasa-dev/scheduler
- [x] Archive https://github.com/galasa-dev/extended-catalog
- [x] Archive https://github.com/galasa-dev/gitopscreds
- [x] Archive https://github.com/galasa-dev/ansible
- [x] Archive https://github.com/galasa-dev/testapp
- [x] Archive https://github.com/galasa-dev/bulktests
- [x] Archive https://github.com/galasa-dev/common-build

**Comment by techcobweb** [comment]
All archived. Let me know if there are any bad repercussions pls.
