### ISSUE TITLE
Authentication: Dex is installed into Ecosystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1460]
## Story
As a galasa developer I want to learn about DEX by installing it and playing around.

As an installer of a Galasa ecosystem I want to know how to install and configure the DEX authentication system so I can work towards enabling my galasa clients to do authentication.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Tasks
- [x] Read up on and understand how DEX works
- [x] DEX image added to the Helm install charts
- [x] DEX configured to use a default admin user and password 
- [x] Install into a kube cluster and test the initial config
- [x] Enable the dex gRPC API by default in the helm chart's dex installation

**Comment by techcobweb** [comment]
Is Dex deployed ? 
Does it have the gPRC feature enabled ? We're going to need it...

**Comment by techcobweb** [comment]
@eamansour what is needed to close this one out pls ?

**Comment by eamansour** [comment]
Just need a review on this PR https://github.com/galasa-dev/helm/pull/6
