### ISSUE TITLE
Set GPG signing to true for all Main builds

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1462]
## Story
As a Galasa dev, I want main builds of all of the repositories to be GPG signed, instead of just release builds, so that when we come to a release we don't encounter signing problems which then delay the release.

## Background
In our build pipelines, we have a parameter isRelease which if set to true will GPG sign the built artifacts, but if not will skip the signing steps.

## Tasks
- [x] Rename isRelease to isMainOrRelease
- [x] Change default value to be 'true'
- [x] Trickle that change through all of the pipelines (search 'isRelease' on VSCode and ensure all are updated to isMainOrRelease)
- [x] Find all instances in pom.xmls or build.gradles where isRelease is referenced and update to isMainOrRelease
- [x] Merge pipeline changes into automation before merging changes to the Core repositories
- [x] Run through a main build and ensure that the artifacts are signed (go to the Main maven repo and check for presence of .asc files)
