### ISSUE TITLE
Fix recycle-ecosystem Pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1464]
## Story
As a Galasa developer, I want the galasa-prod ecosystem to be recycled automatically when the production runtime image (galasa-ibm-boot-embedded) has been rebuilt with new code so that tests submitted to the ecosystem by the CLI or otherwise have the latest code.

## Background
Recycling the ecosystem can be done manually by doing a `kubectl rollout restart deployment/xxx` on the galasa-prod deployments but would be better if this was automated so I didn't have to remember to do it every now and again.

Currently the Pipeline fails because the Service Account that runs it does not have permission to look at deployments in the galasa-prod namespace (galasa-build-bot is for the galasa-build namespace):
```
Error from server (Forbidden): deployments.apps "api" is forbidden: User "system:serviceaccount:galasa-build:galasa-build-bot" cannot get resource "deployments" in API group "apps" in the namespace "galasa-prod"
```

It's important this is done because otherwise servlet changes which we are making regularly in Framework now need to trickle down to the prod ecosystem, or the CLI builds may fail because they are trying to run commands against incorrect/non-existing endpoints.

## Tasks
- [x] Create a new Service Account which is for the galasa-prod namespace
- [x] Give that Service Account permission with a Role and Role Binding to do 'get' the resource 'deployments' in the 'apps' API group
- [x] Attach that Service Account to the recycle-deployment Pipeline by amending the Tekton trigger that calls it (at the end of the integration-to-prod Pipeline)
- [x] Add galasa-prod namespace to ArgoCd allowed destinations
- [x] Create app in ArgoCd to create the new ServiceAccount
- [x] Sync existing pipelines app
- [x] Test it works

**Comment by jadecarino** [comment]
I don't have permission to do the ArgoCD related tasks so I have opened a CIT ticket to see if this is possible.

**Comment by jadecarino** [comment]
Unfortunately the trigger in integration-to-prod (which sits inside the galasa-build namespace) is unable to call recycle-ecosystem pipeline (galasa-prod namespace). I'll do some digging on how we can get around this.

**Comment by jadecarino** [comment]
Creating a ClusterRole with the needed actions to recycle the deployments, and binding galasa-build-bot to it with a ClusterRoleBinding worked.
