### ISSUE TITLE
Credentials stored in ETCD should be encrypted

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1467]
## Story
As a security auditor I want to know that all credentials stored in etcd servers are encrypted.

## Background
All credentials should be encrypted at rest and in transmission.

We need all pods to have access to a secret which are used to encrypt all the passwords in the creds store.

### How does this effect the existing Galasa application APIs ?
- [Credentials](https://javadoc.galasa.dev/dev/galasa/framework/spi/creds/Credentials.html)

We must be able to instantiate the following types to leave the API unchanged:
- [ICredentialsToken](https://javadoc.galasa.dev/dev/galasa/ICredentialsToken.html) 
- [ICredentialsUsername](https://javadoc.galasa.dev/dev/galasa/ICredentialsUsername.html)
- [ICredentialsUsernamePassword](https://javadoc.galasa.dev/dev/galasa/ICredentialsUsernamePassword.html)
- [ICredentialsUsernameToken](https://javadoc.galasa.dev/dev/galasa/ICredentialsUsernameToken.html)

### Command-line interface to manipulate secrets

get the secrets:
```
> galasactl secrets get
name
SYSTEM1
SYSTEM2
SYSTEM3
Total: 3

> galasactl secrets get --name SYSTEM1
name
SYSTEM1
Total: 1

> galasactl secrets get --name SYSTEM1 --format yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaSecret
metadata:
    name: SYSTEM1
    encoding: base64 << The username and password are encoded using base64
    type: UsernamePassword
data:
    username: mySharedServiceUser123 << base64-encoded
    password: 56780987678988675678 << base64-encoded
    description:|-
      An example credential which controls how the tests log into SYSTEM1.
```

or
```
> galasactl secrets get --name SYSTEM2 --format yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaSecret
metadata:
    encoding: base64 << The username and token are encoded using base64
    name: SYSTEM2
    type: UsernameToken
data:
    username: mySharedServiceUser123 << not base64-encoded
    token: 56780987678988675678 << base64-encoded
    description:|-
      An example encryption key we use on SYSTEM 2 to encrypt things
```

or
```
> galasactl secrets get --name SYSTEM3 --format yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaSecret
metadata:
    << The username is not encoded using base64. 
    name: SYSTEM3
    type: Username
data:
    username: mySharedServiceUser123
    description:|-
      An example encryption key we use on SYSTEM 2 to encrypt things
```

or
```
> galasactl secrets get --name SYSTEM4 --format yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaSecret
metadata:
    name: SYSTEM4
    encoding: base64 << The token is encoded using base64
    type: Token
data:
    token: 4567890876667890898780989786767
    description:|-
      An example encryption key we use on SYSTEM 2 to encrypt things
```

Set a secret
```
> galasactl resources apply -f mySecretsFile.yaml
```

Or

... When the values are supplied as encoded values:
```
> galasactl secrets set --name SYSTEM1 --username mikecobbett@nospam.com --base64-password 123457
> galasactl secrets set --name SYSTEM2 --username mikecobbett@nospam.com 
> galasactl secrets set --name SYSTEM3 --username mySharedServiceUser123 --base64-token 56780987678988675678
> galasactl secrets set --name SYSTEM4 --base64-token 4567890876667890898780989786767 
```

Or when the values are supplied in non-encoded values...
```
> galasactl secrets set --name SYSTEM1 --username mikecobbett@nospam.com --password 123457
> galasactl secrets set --name SYSTEM2 --username mikecobbett@nospam.com 
> galasactl secrets set --name SYSTEM3 --username mySharedServiceUser123 --token 56780987678988675678
> galasactl secrets set --name SYSTEM4 --token 4567890876667890898780989786767 
```

The `--base64-...` flags means that there will be no codepage translations in the way.

We want to be able to set secrets this way, so that when we set a secret locally, into the local creds.properties file, we can use the same syntax.

Delete a secret
```
> galasactl secrets delete --name SYSTEM1
```

### Which pods need the encryption keys ?
- All the test pods
- Any others ?

### How is the encryption key injected into the Java logic in all pods ?
- Need to decide whether we do the following
- The kube secret should be injected as a file, rather than an environment variable. That's more secure
- An environment variable can hold the location of the secret key file.

### Java logic to read/write a secret from the credentials store
- Encryption key is obtained from the environment, or a mounted file secret.
- There is a list of encryption keys we can try to use. May be empty (unencrypted as today)
- The write logic adds a prefix to the data:
  - A number of random bytes of prefix (eg: 24 bytes of random noise)
  - ~~A fixed "GALASA" eye-catcher prefix (so we can tell if the decryption has worked ok)~~ GCM uses an authentication tag to make sure the encrypted data hasn't been tampered with, so it already acts as an eye-catcher
  - The data we want to encrypt
  - All of the above is encrypted with AES algorithm, key length: 256
  - The first encryption key in the list is used to encrypt secrets

- The read logic gets the list of decryption keys (may be an empty list)
- If tries to decrypt the data using successive keys until it either finds one which worked ~~(we could see the 'GALASA' eye-catcher)~~ or it gives up (in which case it treats the credential as being un-encrypted at source).
- The random part and the eye-catcher are stripped off and the credential can be returned to the calling code.

### How would a kube system admin change the encryption key ?
- They create an (opaque) kubernetes secret which can have multiple values. eg: kubectl create secret generic creds_encryption_key
- They call a script which:
  - adds a new key to the front of the list of encryption keys in the kube secret
    - any setting of credentials into the store after this point will be encrypted using this new key
    - any old key can still be read by the system because of the fall-back mechanism in the read-logic (above).
  - gets the list of all the secrets in the ecosystem
  - works through the list:
    - reads out the secret (so it gets decrypted)
    - updates the secret (so it gets re-encrypted)
  - removes all the keys except the most recent from the list of encryption keys
 
So the result is that the upgrade to the new version should leave the secrets un-encrypted, but the systems admin can call the script and it will encrypt the secrets after that point.

It also gives us a good story on how to maintain the thing.

### How kube stores the secret encryption keys
In an opaque secret: 
```
apiVersion: v1
kind: Secret
metadata:
  name: bootstrap-token-5emitj
  namespace: kube-system
type: opaque
data:
  encryption-keys.yaml: |-
  encryptionKey: c3lzdGVtOmJvb3RzdHJhcHBlcnM6a3ViZWFkbTpkZWZhdWx0LW5vZGUtdG9rZW4=
  fallbackDecryptionKeys:
  - 78asd687a78sd6587yawhjq3k4jhawsiduyh23q8e4328wqdah23qewiaodh=
  - 7823492iqhj34kwenad290q4weouih2kjq4ewadoiu2qkjhweadsoihkj2qnwea=
```
Note the encryption key is implicitly in the decryption key list

Or something like that.

### How do secrets interact with Galasa properties
- They are currently visible (sort of) via the properties manipulation mechanism.
- They shouldn't be.

### Get a list of all secrets from the credentials store
Request: `GET /secrets`
Example:
```json
GET /secrets
[
    {
        "apiVersion": "galasa-dev/v1alpha1",
        "kind": "GalasaSecret",
        "metadata": {
            "name": "SYSTEM1",
            "type": "UsernamePassword",
            "encoding": "base64"
        },
        "data": {
            "username": "my-base64-encoded-username",
            "password": "my-base64-encoded-password"
        }
    },
    {
        "apiVersion": "galasa-dev/v1alpha1",
        "kind": "GalasaSecret",
        "metadata": {
            "name": "SYSTEM2",
            "type": "UsernameToken",
            "encoding": "base64"
        },
        "data": {
            "username": "my-base64-encoded-username",
            "token": "my-base64-encoded-token"
        }
    },
    {
        "apiVersion": "galasa-dev/v1alpha1",
        "kind": "GalasaSecret",
        "metadata": {
            "name": "SYSTEM3",
            "type": "Username",
            "encoding": "base64"
        },
        "data": {
            "username": "my-base64-encoded-username"
        }
    },
    {
        "apiVersion": "galasa-dev/v1alpha1",
        "kind": "GalasaSecret",
        "metadata": {
            "name": "SYSTEM4",
            "type": "Token",
            "encoding": "base64"
        },
        "data": {
            "token": "my-base64-encoded-token"
        }
    },
]
```

Should the response always return the base64-encoded secret?

### Get a specific secret from the credentials store
Request: `GET /secrets/{secret-id}`

```json
GET /secrets/SYSTEM1
{
    "apiVersion": "galasa-dev/v1alpha1",
    "kind": "GalasaSecret",
    "metadata": {
        "name": "SYSTEM1",
        "type": "UsernamePassword"
    },
    "data": {
        "username": "my-user",
        "password": "abc123"
    }
}
```

### Delete a secret
Request: `DELETE /secrets/{secret-id}`
Example:
```
DELETE /secrets/SYSTEM1
204 No Content
```

### Create a secret
Request: `POST /secrets`
Request body example:
```json
{
    "name": "SYSTEM1",
    "username": {
        "value": "my-base64-encoded-username",
        "encoding": "base64"
    },
    "password": {
        "value": "my-base64-encoded-password",
        "encoding": "base64"
    }
}
```

or with no encoding:
```json
{
    "name": "SYSTEM1",
    "username": {
        "value": "my-plaintext-username",
    },
    "password": {
        "value": "my-plaintext-password",
    }
}
```

Response:
```
POST /secrets
201 Created
```

### Update a secret
Request: `PUT /secrets/{secret-id}`
Request body example:
```json
{
    "username": {
        "value": "my-base64-encoded-username",
        "encoding": "base64"
    },
    "password": {
        "value": "my-base64-encoded-password",
        "encoding": "base64"
    }
}
```

Response:
```
PUT /secrets/SYSTEM1
204 No Content
```

## Tasks
- [x] Helm chart creates an opaque kube secret with a single encryption key and a known/fixed name so we know where to look for it. 
- [x] Kube + Helm work to supply a secret to all the pods
- [x] Docs to tell the ecosystem admin how to set it and migrate with a script
- [x] Framework code to encrypts before writing
- [x] Framework code to decrypts after reading
- [x] Observe that the passwords are stored encrypted in etcd
- [x] Script to help with migration
- [x] galasactl secrets get --format summary ...
- [x] galasactl secrets get --format yaml ...
- [x] galasactl secrets delete ...
- [x] galasactl secrets set
- [x] galasactl resources -f ...
- [x] Add description to credentials
- [x] Add lastUpdatedTime to credentials
- [x] Add lastUpdatedBy to credentials

Separate stories
- Secrets not visible or settable via the Properties services
