### ISSUE TITLE
REST: Refactor resultnames , testclasses and requestor API endpoints to match the rest of the ras/.../ URLs

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1468]
## Story
As a Galasa developer, I want to reduce the amount of doGet() handlers across the APIs, so that when I try to retrieve an endpoint a common handler is used to return the result, and I can have more flexibility across the end 

## Background

As part of the revision and improvement of the RAS APIs 5/8 of the APIs have already been moved to use the base servlet and covered by unit tests.
In order to match the rest of the APIs we will need to add the remain 3 API endpoints to the routes as well and add unit tests for them.

## Tasks
API Routes:
- [x] Create Route for /ras/requestors + Unit tests.
- [x] Create Route for /ras/testclasses + Unit tests.
- [x] Create Route for /ras/resultnames + Unit tests.

Note: Unit tests are assumed/implicit/necessary to write the code. Write the unit tests before we do the re-factoring if possible (best practice).
