### ISSUE TITLE
CLI needs to cope with "Ignored" test runs

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1470]
## Story 
As a tester using galasa I want to see those tests which were ignored, because of annotations in the test cases.

## Background

Some annotation on the test class can cause it to be ignored.

This shows up as an "Ignored" status/result.

We want such tests to be listed in the `galasactl runs get` commands such that ignored tests are
totalled at the end, together with passed/failed/envfail/...etc.

## Tasks
- [ ] Work out what can come out of the ecosystem by creating a test with one of these annotations inside and running it on an ecosystem.
- [ ] Observe what the result/status does.
- [x] Change the formatters to count the number of ignored tests in the trailing footer of totals.

**Comment by AaronJhaj** [comment]
'Ignored' result defined here https://github.com/galasa-dev/framework/blob/main/galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/spi/Result.java
