### ISSUE TITLE
Authentication: REST endpoints insist on a JWT token

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1473]
## Story
As a user of the REST interface, I want to be rejected from using a REST call if I don't have a valid JWT (java web token).

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background
All rest calls need to reject traffic if the JWT passed isn't valid.

## Tasks
- [x] CLI build process launches a test or two against the ecosystem. Supply the token into that pipeline.
  - [x] external secret is available on the pipeline pod, using the GALASA_TOKEN env variable. (same one we use for int tests)
- [x] The openapi doc reflects that these calls all need a JWT in the header.
  - except: dex callback endpoint, and auth login/refresh jwt endpoint.
- [x] All REST calls check the JWT is present, failing if not
  - except the REST calls which must remain open.
- [x] Check inttests work
- [x] Check you can launch a remote test
- [x] Release notes in the docs about it being required now
