### ISSUE TITLE
Authentication: Eclipse uses a personal access token to log into galasa ecosystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1475]
## Story
As an eclipse user, for each ecosystem I want to be able to store an access token, such that eclipse can use a different access token for each ecosystem, when it accesses the rest calls.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background
We don't want to use userid-password to access the ecosystem unless we are using a web UI.
So... in the same way that the CLI tools access the rest interface, I want to access the 
ecosystem using a (revokable) personal access token.

The personal access token can be turned into a JWT, which can then be used to access an ecosystem.

Each ecosystem will have it's own personal access token.

## Tasks
- [ ] Panels to associate an ecosystem with an access token.
- [ ] Eclipse code calling Rest endpoints gets the JWT
- [ ] Eclipse code calling Rest endpoints uses the JWT

**Comment by techcobweb** [comment]
We are archiving eclipse and removing it from the Galasactl system.
