### ISSUE TITLE
Authentication: Eclipse talks to the REST interface instead of Cloudant directly.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1476]
## Story
As a Galasa testcase developer using eclipse, I want to know that the interactions with a test run use the REST interface, and are authenticated, so other eclipse users who are not authenticated can't see test run results and artifacts.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background

We need to stop eclipse accessing cloudant directly, rather, all traffic to cloudant needs to go via the rest interface.

So listing runs, querying runs, and looking at artifacts needs to be done via the REST interface.

## Tasks
- [ ] Change the panels which deal with test artifacts, queries, views to use REST calls.
- [ ] Use the JWT token for the ecosystem when we make REST calls.
- [ ] Use a generated java client to access the rest calls.

**Comment by techcobweb** [comment]
We are removing eclipse from Galasa so this story is no longer required.
