### ISSUE TITLE
Authentication: As an administrator of galasa, I can use rest calls and options which non-admin users can't

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1477]
## Story
As an Admin, I can access things in galasa which non-admin users can't.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

## Background

Lets initially assume that admin users can do everything, and non-admin users can't do certain things concerning the administration of the Galasa Ecosytem.

What are the things which only admin users can do over our REST interface ? Lets build a list:
- touch CPS properties which are concerned with streams.
- others ?

## Tasks
- [ ] List the things in Galasa which are admin-controlled, versus user-controlled.
- [ ] When we configure a DEX instance, we need to configure Admin and Non-admin users
- [ ] The REST calls which deal with CPS properties that detail what a stream is can only be used by admin-authorised people
