### ISSUE TITLE
CLI downloads cope with multiple retries of the the same runname

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1478]
## Story

As a user investigating a problem with a Galasa test running on an ecosystem, when a test retries, and I want to download its' artifacts, I can download all the artifacts associated with all the retries of that test.

## Background
The following steps occur:

1. Run C7315 runs on the ecosystem. 
2. It gets scheduled. Scheduled time is set.
3. Galasa tries to run the test
3.1 A new record in the RAS store is created name=C7315, start-time={as-above} 
4. The test can't start because there aren't enough resources available
5. The test gets re-queued.
6. time passes
7. Galasa tries to run the test
7.1 A new record in the RAS store is created name=C7315, start-time={as-above} 
9. The test can't start because there aren't enough resources available
10. time passes
11. Galasa tries to run the test
11.1 A new record in the RAS store is created name=C7315, start-time={as-above} 
12. The test can't start because there aren't enough resources available

In this manner, you can see why we have many test runs named C7315...

When you try to download artifacts for C7315... what do you get ?

## Expected result

Folders called:
C7315-1-2023-05-25_18:30:26
C7315-2-2023-05-25_18:30:26
C7315-3

The 1 and 2 because they are different re-tries of the same test. We can tell that as the submitted times and the run name is the same.

The timestamp because the tests never completed, so we write the current timestamp of the CLI client machine into the folder namme.

The third folder because the test run finished and passed.

This also means we have to output something on the console for each folder we create...
```
Created folder C7315-1-2023-05-25_18:30:26
Created folder C7315-2-2023-05-25_18:30:26
Created folder C7315-3
```

## Tasks
- [ ] Detect whether a test run is a retry of another test run. Mark its' name in the folder.
- [ ] Add timestamps to un-finished runs
- [ ] The final run is the one without a timestamp because it finished and has a result value.

**Comment by AaronJhaj** [comment]
Reruns need to be sorted by start time. they all have equal queued time so the only way to know which rerun occured first or second... is by their start time. The API should handle this? and return the runs sorted by start time if all the queued times are equal?
