### ISSUE TITLE
CLI can reset a looping/hung test run

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1479]
## Story
As a testcase automation person wanting to clean-up an ecosystem, I want to be able to 'reset' a test run which appears to be hanging/looping, so that it will re-try running the test.

## Background
Sometimes tests hang. At those times, using eclipse, Jade resets them. Causes them to be re-started. Not sure how that works yet.

We want to do this from the command-line.

`galasactl runs reset --name U345`

Rest api would look something like this:

PUT ~/runs/run-id~ /ras/runs/{runid}
```
{
  status: QUEUED
}
```
Discussion with Savvas around what this JSON payload should look like. Changing 'status' to 'action' as the action is what you want to do (reset/delete) and that implicitly updates a status (queued/deleted altogether).

The eclipse code does this:
```
IFramework.getFrameworkRuns().reset(runid)
```

Which resets the run. How does that work ? We need to know and be able to explain it...

- Resets happen by deleting the runs heartbeat and setting the status of the run in the DSS to "queued".
- Deletes happen by deleting all entries in the DSS for that run. It essentially gets abandoned. Not sure if we can improve that at all as part of this story or an extension.

## Tasks
- [x] Decide what the REST interface should look like
- [x] Openapi yaml changes 
   - [x] Review
- [x] Create the servlet which supports this
   - [x] Review
- [x] Add the `runs reset` command to Golang CLI code.
- [x] Make sure the CLI calls the servlet
   - [x] Review
- [x] Integration test added
- [x] Docs in readme.md
- [x] Docs in galasa.dev

**Comment by jadecarino** [comment]
Discussion with Mike before Christmas - decided to add this servlet as part of the RAS API not the Runs API as the Runs API does stuff to do with groups of runs. Changing the status of one run didn't seem right in that location. So, changed path to  /ras/runs/{runid}.

**Comment by jadecarino** [comment]
Blocked as unable to run tests in the ecosystem so cannot run the integration test script.

**Comment by jadecarino** [comment]
PR open for this story: https://github.com/galasa-dev/cli/pull/213
