### ISSUE TITLE
CLI galasactl runs get to support minutes as a unit

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1490]
## Story

As a galasa CLI user I want to query what runs happened in the past 10 minutes, so I get fewer results than querying for 1 hour.

## Background

Currently the CLI uses 'w' weeks, 'd' days and 'h' hours.

We want it to also support 'm' minutes.

## Tasks
- [x] Change the CLI to add support for minutes
- [x] Docs of the CLI syntax in the CLI help 
- [ ] Docs update in the README
- [ ] Docs update in the galasa-dev site

**Comment by CaroMac** [comment]
added minutes info in this pr https://github.com/galasa-dev/galasa.dev/pull/683
