### ISSUE TITLE
Galasa.dev certificates need renewing by the 4th November 2023

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1491]
## Story
As a galasa user I want the galasa.dev site to stay live, and not stop working because of expired certificates.

## Background
In December 2022 a python script was put in to automatically rotate the certificates for the galasa.dev webpage across all the sites.
Over the past 6 months this does not seem to be working and may be related to some permission issues.

## Tasks
- [ ] Check the automation in IBM cloud is active
   - [ ] if the automation is active, check the logs for the automation to identify why it isn't running. 
- [ ] Identify what changes need to be made to permissions
- [ ] Change the API key for the automation to use the galasa delivery account (for security reasons) and check that galasa delivery has those permissions
- [ ] Test that the automation auto-rotates and updates the certificates as per the guidance in https://pages.github.ibm.com/galasa/developer-docs/100-technologies/IBMCloud/

**Comment by techcobweb** [comment]
@KirbyKatcher I changed the title of the story to make it more obvious what the urgency of this is. Is September correct ? What's the exact date the cert expires please ?

**Comment by techcobweb** [comment]
This has been completed. Closing.
