### ISSUE TITLE
CLI times listed using local timezone with --localtime instead of UTC

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1494]
## Story
As a galasactl user, I want all the times listed by the tool to be converted from UTC into my local time, so I don't have to account for timezone differences when interpreting the tool output.

## Background
Times listed in the tool are in UTC which can be confusing if you don't realise that's what they are.

Titles of time fields are along the lines of 'submitted-time(UTC)' so far.

This story needs to change the titles to 'submitted-time(local)' if that's what you want to see, such that the times are converted from UTC into your local time before being displayed.

## Tasks
- [ ] Convert all times to be local times, in the --details, --summary and --raw formatters.
- [ ] Headings in --details and --summary view to change to submitted-time(local)
- [ ] Docs to explain

**Comment by techcobweb** [comment]
Duplicate issue
