### ISSUE TITLE
Update release process

### ISSUE THREAD

**Issue by AaronJhaj** [galasa-dev/projectmanagement#1496]
## Story
As a developer releasing Galasa, I want to to have up to date instructions that minimise manual fixes.

## Background
The cli is now built into isolated so should be included in release steps as any other repo like framework, managers etc.

## Tasks
- [x] create cli argoCD app within the same script. contents of 03-create-argocd-cli-app.sh to be merged in 02-create-argocd-apps.sh
- [x] clone of cli repo should be done in same pipeline to clone all the other repos. 11-clone-cli should be merged into 10-clone galasa.
- [x] write script/pipeline to delete all 'prerelease' branches from the repos. - should be run before cloning the repos in the release process
- [x] 21-build-cli is now redundant as cli is built as part of the main Galasa build process
- [x] update release process documentation

**Comment by AaronJhaj** [comment]
no need to write script to delete prerelease branches - can call the current delete pipeline and pass 'prerelease'
