### ISSUE TITLE
3270 images should show cursor position

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1497]
## Story
As a tester using Galasa I want any 3270 images which are captured to show the location of the cursor on the screen, so I can see if it's in the correct place for that point in the test.

## Background
3270 images are generated by the 3270 manager if they are turned on.

We need to show the cursor location in some way.

## Tasks
- [ ] Decide how we are going to represent the cursor.
- [ ] Code the logic
- [ ] Unit tests to check that the cursor is where we expect it to be.
- [ ] Docs to say what the cursor looks like ?
