### ISSUE TITLE
3270 manager to store 'hidden' data into artifacts

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1498]
## Story
As a tester using Galasa I want any data hidden within my 3270 stream to be collected in the same way that visual information is collected.

## Background
- Should we create a new artifact for each piece of hidden data ? 
- The file/artifact names need to be in with the images, using a similar naming scheme so you can relate the data to the screen which used it.

## Tasks
- [ ] Figure out how to gather the data
- [ ] Select somewhere to place the data
- [ ] Implement the code to gather and dump the data.
- [ ] Test that records some hidden data.
- [ ] Simbank updated to generate some hidden data which can demonstrate this capability
- [ ] Documentation of this type of artifact
