### ISSUE TITLE
3270 manager images should support different codepages

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1499]
## Story
As a galasa tester, when my mainframe is displaying Kanji characters, I want to be able to see those same glyphs in the image that galasactl can generate.

## Background
The codepage needs setting prior to rendering the text into the graphics context, so that the correct glyphs are generated.

## Tasks
- [ ] Understand about codepages on Z
- [ ] relate that to the images we generate
- [ ] Update code to use codepages
- [ ] Test that the correct glyphs get displayed in the images.
