### ISSUE TITLE
Release 0.29.0

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1504]
## Story
As a galasa user I want to get the 0.28.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [x] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [x] Identify problems/improvements and raise them for next time

**Comment by techcobweb** [comment]
Original story had these tasks inside:
- [ ] Add more detail for asking for release approval
- [ ] Add more detail for how to manually install Simbank
- [ ] Add documentation to developer-docs for where to upload GPG public key
- [ ] Add note about --secret-type to the Eclipse marketplace task.
@AaronJhaj Do we still need to do those ?  Not sure what they mean...

**Comment by AaronJhaj** [comment]
@techcobweb i'm not sure what they mean either. they seem like outdated tasks

**Comment by techcobweb** [comment]
OK. Closing.
