### ISSUE TITLE
etcd needs upgrading everywhere

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1508]
## Story
As a galasa sys admin I want to know that the latest versions of etcd are being used so they may get some support going forward.

## Background
Currently running 3.2.5

3.5 is the current release (stable).

We need to upgrade to it.

## Tasks
- [ ] Upgrade helm chart to use the later etcd version
- [ ] Update the proc ecosystem to use the new version
- [ ] Docs in the what's new section for this release

**Comment by eamansour** [comment]
Related to this issue - using the latest version of minikube (1.33.1) to install the helm chart now fails to pull the etcd image because:

```
Failed to pull image "quay.io/coreos/etcd:v3.2.25": [DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of quay.io/coreos/etcd:v3.2.25 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

A workaround for now would be to either use a down-level version of minikube (e.g. [v1.32.0](https://github.com/kubernetes/minikube/releases/tag/v1.32.0)) or start the latest version of minikube with this command:

```
minikube start --docker-env DOCKER_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE=1
```

Upgrading the version of the etcd image to a newer version should hopefully resolve this.
