### ISSUE TITLE
etcd space : periodic removal of revision history required

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1509]
## Story
As an ecosystem admin, I want to periodically clean-up revision history of the dss data, so that it doesn't blow the available space, so that the ecosystem doesn't just stop at a random point in the future.

## Background
Looking at this: https://etcd.io/docs/v3.3/op-guide/maintenance/ we need to do some tidy-up admin on etcd periodically.

Change the startup script to include this option:
`--auto-compaction-retention=1`

And periodically do this, as it suggests in the above web page.
```
# get current revision
$ rev=$(ETCDCTL_API=3 etcdctl --endpoints=:2379 endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*')
# compact away all old revisions
$ ETCDCTL_API=3 etcdctl compact $rev
compacted revision 1516
# defragment away excessive space
$ ETCDCTL_API=3 etcdctl defrag
Finished defragmenting etcd member[127.0.0.1:2379]
# disarm alarm
$ ETCDCTL_API=3 etcdctl alarm disarm
```

Do we need to put this in the helm chart ? or document advice to admins on this ?

## Tasks
- [ ] Change start-up options for etcd
- [ ] Cron job to compact-away/prune dss history to run regularly.
- [ ] Decide whether we need to update helm
- [ ] Decide what docs/advice to galasa ecosystem admins is required.

**Comment by techcobweb** [comment]
Raised this issue as a result of our prod cluster going down with no space.

We had over half a million revisions. The compaction/prune operation takes ages if there are that many. Doing it more frequently should mean our etcd cluster is less likely to stop suddenly for this same reason again.

**Comment by eamansour** [comment]
Closing as duplicate of https://github.com/galasa-dev/projectmanagement/issues/1887

Auto-compaction was turned on in https://github.com/galasa-dev/helm/pull/27
