### ISSUE TITLE
CLI: draw the versions of things from the build.gradle file

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1511]
## Story
As a developer of galasa CLI code, I want to house all the dependency information about versions of things inside the build.gradle file, rather than in any Golang code, so it's easy to find and update when one of those dependency versions need bumping-up.

## Background
Currenly, the versions are hard-coded inside a golang file.

They need to be read from a data file constructed at build-time.

Proposal: 
- Build a properties file on the fly.
- Embed the properties file in the CLI binary embedded file system
- Galasactl tool dynamically reads out the contents of that properties file, so we have a conduit of metadata we know at build-time into the CLI code itself.
- `galasactl --version` relays the metatadata to the user when that command is used.
- The boot jar we try to load from the embedded repo is more likely to match the one the gradle process placed there.
- A less 'brittle' way of doing things than before. Easier to maintain. Dependency information where we'd expect to find it.

## Tasks
- [x] Makefile to dynamically copy VERSION information into a generated properties file
- [x] Clean build removes the property file to start with
- [x] Boot jar version pulled into the property file from the build.gradle file
- [x] Default version of the galasa framework is pulled from build.gradle file
- [x] Unit tests added

**Comment by techcobweb** [comment]
PR is here: https://github.com/galasa-dev/cli/pull/117
Review required.
