### ISSUE TITLE
CLI: Authentication: User can list their access tokens with a command-line

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1512]
## Story
As a galasa command-line user, I want to see the list of all my personal access tokens in the command-line.

## Background
`galasactl auth token get`

Gets the list of tokens for this user.

Summary format:
```
user                                        id                                      name                                                       
mike_cobbett@uk.ibm.com 020934234902342781 token used to access from my mac.    
mike_cobbett@uk.ibm.com 982398723498723489 token used to access from my phone 
```

This information isn't collected by the server yet.

We need to add a new 'users' database in couchdb.

When a token is created, we need to add the user if they don't exist already. And add the token to the list of tokens.

New route on the auth servlet to get the tokens for a user.

## Tasks
- [ ] CLI improvements to make the landing-page/personal access tokens contain the list of tokens for this user.
- [ ] The REST layer can list personal access tokens for the user who requests the list. The JWT of the bearer token indicates which user it is.
- [ ] IVT
- [ ] Docs
- [ ] Jest unit tests

Follow-on stories:

- Web UI can see the list of my tokens
- Expiry time is shown when you list a token. It is saved in the user doc with the token when the token is allocated. So it can be displayed.
