### ISSUE TITLE
Web UI: Authentication: User can revoke access tokens

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1513]
# Story
As a galasactl command-line user who had their laptop stolen, I want to log into the Galasa web UI, and revoke the personal access token I had associated with that laptop, so my ecosystem and systems under test remain secure.

# Background

Following on from [Spike Story 1918](https://github.com/galasa-dev/projectmanagement/issues/1918) which saw us create a design for the proposed UI changes. We can break the work down into several parts.

### My Settings panel
- User can use the left nav-panel to edit to a "My Settings" page.
  - "my settings" page shows the user id and a list of the tokens they currently have.
  - "My Settings" page can describe what a user token is.
  - "My Settings" page has an "Add token" button and refresh the list shown when it returns.
- User has a profile button from which they can navigate to the "My Settings" page.
- User can delete his own tokens using the "My Settings" page, with an "Are you sure" dialog.

- User can see their role in the "My Settings" page.
- User can see their own previous login time.

### Token last-used date
- Access tokens display their last-used date in the "My Settings" panel.
- User sees warnings about a token being stale/not being used for a long time on the "my settings" panel

### Admin panels
- Admin user can navigate to a "Users" list panel. Columns are sorted in an order the user can change
- "Users" panel has a Search box to make finding a user easier.
- Admin user can select a user an enter the "Edit User" panel, though they can't add a token for that user. They can delete a token.
- Admin user can delete the user.

### Token Expiry
- Access tokens can expire. Expiry time settable on token create.
- Access token expiry time can be changed via the "my settings" panel.
- Recently expired access tokens are visible on the "my settings" panel.
- User sees warnings about access tokens being about to expire on the "my settings" panel.

### Logout
- Logout appears on the user profile menu. https://github.com/galasa-dev/projectmanagement/issues/1948

# Rest API changes required

UI sends revoke request to the auth REST service.

Auth REST service tells Dex to revoke the token.

## How does the UI know what the user is permitted to do ?

We need a new servlet access point:
URL: `https://host/api/users/5678987656789876/actions`

Where "5678987656789876" is the 'galasa-id' number associated with the user.

Actions which are relevent, which will effect the UI:
- ACCESS_TOKEN_DELETE_OWN (implicit permission granted always), 
- ACCESS_TOKEN_DELETE_OTHERS (initially, everyone will have this, but later it may be turned off when we have RBAC), 
- ACCESS_TOKEN_GET_OTHERS (initially, everyone will have this, but later it may be turned off when we have RBAC),

Payload returned:
```
[
  "ACCESS_TOKEN_GET_OWN",
  "ACCESS_TOKEN_DELETE_OWN",
  "ACCESS_TOKEN_DELETE_OTHERS",
  "ACCESS_TOKEN_GET_OTHERS",
  "USERS_GET_OTHERS",
  "USERS_DELETE"
]
```
- Requires a bearer token
- Fails if the user specified differs to the user id information within the access token
- Anyone can get the actions for any other user
- For now, it will return that data hard-coded. When we have an RBAC model

- We need a call from the UI to the server to find out what actions this user has permissions to perform.

## How do we get a list of users ?

Endpoint to get a list of users.
- `https://myhost/api/users?id=*major*` searches users based on their id
- `https://myhost/api/users?name=*major*` searches users based on their name

If present, the id can be used as a filter based on a 'glob' expression.

Returns something like this:
```
[
  { 
    "galasa-id" : "45678987658667"
    "id" : "mike.cobbett@mydomain" ,
    "name" : "Mike Cobbett",
    "roles" : [ "admin" ]
    "user-url" : "https://myhost/api/users/8986578908"
  }
  ...
]
```

Endpoint to get all the details about one user:

```
{
  "galasa-id" : "45678987658667"
  "id" : "mike.cobbett@mydomain" ,
  "name" : "Mike Cobbett",
  "roles-url" : "https://myhost/api/users/8986578908/roles",
  "roles" : [ "admin" ],
  "actions-url" : "https://myhost/api/users/8986578908/actions",
  "tokens-url" : "https://myhost/api/users/8986578908/tokens"
}
```

Question:
Should we assign a uniq number to each user ? rather than this id thing, which may have odd characters inside.

# Tasks

- [x] UI design is split off as a spike story here: https://github.com/galasa-dev/projectmanagement/issues/1918

- [x] UI has a left-justified title with the service name inside. https://github.com/galasa-dev/projectmanagement/issues/1931
- [ ] Galasa service collects and shares user details: https://github.com/galasa-dev/projectmanagement/issues/1975
- [ ] Servlet layer supports getting the list of actions a user is allowed to do.
- [ ] Welcome panel shows customizable text from the Galasa system admin. https://github.com/galasa-dev/projectmanagement/issues/1947
- [ ] Welcome panel shows details about the service.
- [x] UI has a galasa icon top-left which navigates to the service home page.
- [ ] UI has a profile picture top-right which launches a menu to a pretty blank "My Settings" page. https://github.com/galasa-dev/projectmanagement/issues/1949
- [x] "My Settings" page allows users to see/manipulate access tokens : [Web UI: Show table view of access tokens in a my settings page
#1976](https://github.com/galasa-dev/projectmanagement/issues/1976)

- [x] User can log out of the UI, using profile menu top-right.
- [ ] The text describing an access token on the "My Settings" page is collapsable, and a cookie remembers the state for this Galasa Service on this machine for this user.
- [ ] An admin user can see the admin nav options on the left nav bar
- [ ] Admin user can navigate to the "Users" panel, which displays a list of users.
- [ ] Admin user can select a user from the "Users" panel and get to the "User Settings" panel for that user.
- [ ] Admin user cannot add a new token on the "User Settings" panel.
- [ ] Admin user can delete a user from the "User Settings" panel.
- [ ] Admin user can search for a user in the "Users" panel

- [ ] "My Settings" panel displays the last used date of each token
- [ ] "My Settings" panel shows the creation date for each token
- [ ] Warning about possible stale token can appear in the token tiles.

- [ ] Support last login date of user
  - [ ] "My Settings" panel displays the last login date for this user
  - [ ] "Users" panel displays the last login date for each user.

- [ ] Support token expiry
  - [ ] User can set a token expiry date when the token is created
  - [ ] "My Settings" panel displays the token expiry date
  - [ ] "My Settings" panel allows a token expiry date to be edited
  - [ ] System actually expires tokens
  - [ ] "My Settings" panel shows expired tokens in a separate list
  - [ ] My Settings collects the users' email address
  - [ ] Close to tokens expiring, the user gets a warning email
  - [ ] Each token can show the 'this token will expire soon' warning

- [ ] User can see their role (All users are admins to start with).

**Comment by techcobweb** [comment]
This was mostly already done. Token expiry is not. Raising that separtely. Closing this one now.
