### ISSUE TITLE
Release Automation: Use tkn to launch pipelines

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1519]
## Story
As a galasa developer trying to release galasa code, I want to use scripts which can wait until pipelines complete before returning, so I don't have to monitor pipelines using the tekton dashboard.

## Background
The `tkn` commands can be used to launch pipelines. 

The scripts currently create a yaml document, then do a `kubectl create -f <file>`

They should be using tkn to launch pipelines. This has several advantages:
- Parameters can be passed directly to the pipeline
- The tkn command can wait for the pipeline to complete
- The tkn can log things from the pipeline to the terminal so the caller can see what's going on.
- Should allow us to combine-together more scripts back-to-back to save monitoring the pipeline time perhaps.

## Tasks
- [x] Read up on the tkn command
- [x] Instructions how to install tkn
- [x] Update the scripts to use tkn instead of kubectl

**Comment by jadecarino** [comment]
Any Tekton pipelines that we still use for the release process are now kicked off by scripts so this is essentially done.
