### ISSUE TITLE
CLI to allow CRUD of a CPS property

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1521]
## Story
As a tester trying to set up automation tests, I want to set properties into the ecosystem CPS store using the command-line tooling, so that I don't have to mess around contacting etcd directly, and so that later-on the CPS can be secured with authentication via the REST interface.

## Background
Currently to set up values that a testcase can read and use you have to contact etcd in the ecosystem directly. We need to avoid doing this in future.

We need to support the listing/getting/setting of CPS properties using:
- the REST interface
- the CLI

CLI syntax could be something like this:

### Get a list of property values** :
```
> galasactl property get --prefix my.property.name --suffix my.suffix --infix PRIMARY,A,B,DEFAULT
name                               value
my.property.name.PRIMARY.my.suffix "my property value"
my.property.name.B.my.suffix       "another value"
```

```
> galasactl property get --format raw --prefix my.property.name --suffix my.suffix --infix PRIMARY,A,B,DEFAULT
my.property.name.PRIMARY.my.suffix|my property value
my.property.name.B.my.suffix|another value
```

### A flat exact-match query on the property names
```
> galasactl property get --name my.property.name 
name                               value
my.property.name.PRIMARY.my.suffix "my property value"
my.property.name.B.my.suffix       "another value"
```

### Set a value into a new or existing property
```
galasactl property set --name my.property.name --value "my property value"
```

### Delete a property from the cps
```
galasactl property delete --name my.property.name
```

Can we support wildcard-type names ?

## Tasks
- [ ] Add more functionality to the CPS servlet layer to cope with 
  - [ ] set operation
  - [ ] delete operations
- [ ] CLI 
  - [ ] client code to query based on prefix/suffix/infixes
  - [ ] client code to support property delete
  - [ ] client code to support set property
  - [ ] client code to support get based on exact name
- [ ] IVT using the CLI
- [ ]

**Comment by techcobweb** [comment]
Duplicate. This functionality has already been implemented by other stories.
