### ISSUE TITLE
Kubernetes needs upgrading

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1532]
## Story

As an IBM galasa development team member, I want the external kubernetes cluster upgraded so that we are not using the down-level version when it goes out of service in the IBM cloud.

## Background

Our external kubernetes cluster needs to be upgraded by 12th October:

![Image](https://user-images.githubusercontent.com/77053/255624127-955bf289-30ab-48bc-a2f0-4e49fa475858.png)

## Tasks

- [ ] Read the docs to see if there's anything which is going to effect us in the upgrade
- [ ] Do the upgrade. How ? 
- [ ] Check that there are instructions somewhere... and they are referenced by the developers guide ?
- [ ] Verify that things are working after the upgrade. How ?
- [ ] Check that there are instructions for this somewhere... and they are referenced by the developers guide ?
