### ISSUE TITLE
Spike: Investigate the use of Gradle version catalogs in Galasa build processes

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1536]
## Story

As a galasa developer I want to manage the versions of dependencies centrally, rather than have version numbers sprayed throughout the various repositories, so the dependencies (internal and external) are well understood, and easy to change across all the code, without missing a dependency we otherwise have to change manually, which will cause a problem with failed tests, or failures in released code.

## Background

Using gradle, we can create [Version Catalogs](https://docs.gradle.org/current/userguide/platforms.html) which essentially give you the ability to declare external dependencies and their versions centrally.

External dependencies which are specific to a repository (like framework) would be declared in a top-level file. That file would be exported to the maven repository as an artefact, so it can be referred-to by the managers repo...etc. 

Each repository on which other code depends (Frameworks, Managers, Extensions etc) can generate mini-version-catalogs in a similar way to how a release.yaml could be generated. Other components pulling-in versions of those artefacts could use and depend on the version catalog, rather than specific versions of framework packages (for example). So the only place the version of something in framework (for example) would be in the Gradle file within that project.

Each repository using these dependencies would only then need one version: the version of the version-catalogs being used. 

Could an automation process could build these version catalogs from the code itself (for internal cross-dependencies) ?

Can we use this mechanism to check that all cross-dependencies will be correct between code within the same module ? or code between separate repositories ?

This would result in only one reference to each of our external libraries (eg: the crypto library), and none of the versions of framework packages would be needed in the managers repo (for example). 

Is this a viable approach for external dependencies ?

Is this a viable approach for internal dependencies of our bundles being used by our own code ?

The dependencies listed in `bnd.bnd` files would not be covered by this: for that, we'll have to work out something else. What ?

## Tasks

- [ ] Understand Gradle version catalogs
- [ ] Manually create one from the code in the frameworks repo
- [ ] Manually use it from the managers repo
- [ ] Assess whether it was worthwhile making this automation infrastructure
