### ISSUE TITLE
OS version of external Kubernetes cluster (IBM Cloud) is no longer supported

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1542]
## Story
As a Galasa developer and user, I want to keep the OS of the Kubernetes cluster up-to-date, so that we can get continued support and continue to host our maven repositories.

## Background
A notice has popped up on IBM Cloud for our cluster that the Ubuntu 16 OS is not supported anymore. Our nodes of the cluster are Ubuntu 18.04. The minimum the documentation says is supported is 18.64. I'm not sure if upgrading the nodes is our responsibility/we are allowed to do this, so just opening this issue to document the awareness of this in case it causes problems for us.

## Tasks
- [ ] Investigate who is responsible for maintaining the IBM Cloud cluster
- [ ] Report the problem
- [ ] Ask if we can complete the migration ourselves
- [ ] Complete the migration if yes
- [ ] If no, potentially chase up alternative cluster that we can maintain

**Comment by techcobweb** [comment]
New cluster (planB) doesn't have this issue. Closing.
