### ISSUE TITLE
Infrastructure: Move Galasa to 'planb' infrastructure

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1544]
## Story
As a galasa infrastructure developer, I want to be able to build and publish built Galasa material to a public set of infrastructure (not within the IBM firewall), so that any trusted committer can action builds without having to have the code first reviewed by IBM staff.

As the IBM team, we would like the OMP to pay for infrastructure required to run the Galasa project infrastructure, to remove the financial burden from the IBM team who has developed and hosted the project since its' inception in 2019.

## Background
Currently, the Galasa project uses two kubernetes clusters:
- An internal IBM-only cluster on which Tekton runs our builds
- An external public cloud offering on which public material is hosted for everyone

![Image](https://github.com/galasa-dev/projectmanagement/assets/77053/8798e497-5951-429a-8659-e919d2cdaa7f)

### External IBM-cloud infrastructure
- github.com - Galasa is an open source project, so source code lives in public github repositories
- code from github.com is built using an internal-to-IBM tekton build process, which deposits container images in the externally-hosted Harbor instance.
- An externally-hosted ArgoCD instance is also used to re-synchronise kube resource definitions to Kubernetes. It is also called by Tekton when an image has been re-built and needs re-deploying.

### Internal-to-IBM infrastructure
- Within IBM we host a k8S cluster to run our build processes.
- An internal instance of ArgoCD synchronises github-hosted resource file definitions with Kubertnetes
- An internal harbor instance hosts container images which are executed on the internal K8s.

### Problems with the current infrastructure

- IBM would like to retire The IBM cloud infrastructure offering we are using, or otherwise move the Galasa project onto a different IBM cloud infrastructure offering. Ideally by end Sept 2023.
- Pull requests from forks (non-IBM committers) much be reviewed by IBM staff to make sure that there is no malicious code present which could take over the IBM build infrastructure. This infrastructure is behind the IBM firewall, so is subject to IBM-internal constraints, and we need to protect these systems from build-jacking. Using a non-internal kubernetes cluster for builds would allow for equal rights for trusted community members.

## Tasks
- [x] Decide which parts of the build and serve infrastructure can be moved and to where.
- [ ] Work required to bring up the artifact-serve functionality on the new offering
- [ ] Work required to bring-up the build infrastructure functionality on the new offering.

## Tasks to move to the temporary Plan B cluster.
- [x] Allocate the IBM Cloud account and set up the billing to route to IBM
- [x] Invite Will, Mike, James, Jade. 
- [x] Create a resource group
- [x] manage access to add Will to the resource group
- [x] Allocate the secrets manager
- [x] Allocate the cluster (linked to the secrets manager)

### Replicate namespaces (these are defined in the 'automation' repo in namespace.yaml files):
- [x] galasa-development namespace
- [x] argocd namespace
- [x] harbor namespace
- [x] secrets-manager namespace
- [ ] galasa-pipelines namespace (or equivalent. I think this should be renamed as all this contains is the github-webhook-receiver and I don't think galasa-pipelines makes sense for the namespace name)
(Leave this namespace for now, it's not as critical).

### ArgoCD Applications:

Used for builds:
- [x] codecov-maven-repos
- [x] galasa-development-namespace
- [x] github-copyright - GitHub copyright checker 
- [x] gitHub-webhook-receiver (https://github.com/galasa-dev/automation/tree/main/infrastructure/ibmcloud-galasadev-cluster/github-webhook-receiver)
- [x] integration-maven-repos
- [x] main-bld
- [x] main-cli
- [x] main-inttests
- [x] main-maven-repos
- [x] main-simplatform
- [x] prod-maven-repos
- [x] prod-simplatform

### Kube applications
- [ ] Maven downloads site (https://github.com/galasa-dev/automation/tree/main/infrastructure/ibmcloud-galasadev-cluster/galasa-development)
- [x] Harbor.galasa.dev (https://github.com/galasa-dev/automation/tree/main/infrastructure/ibmcloud-galasadev-cluster/harbor) - hosts the main/pr images, also hosts the 'common' images that we use (argocd-cli, tkn-cli, etc)
   - Should eventually move off this anyway... using ICR instead
- [x] ArgoCD (https://github.com/galasa-dev/automation/tree/main/infrastructure/ibmcloud-galasadev-cluster/argocd)
    
Used/pushed to in release (All of these are in the 'default' namespace and controlled by the galasa-ibmcloud application in the internal ArgoCD):
- [x] Javadoc javadoc.galasa.dev  (https://github.com/galasa-dev/argocd-ibmcloud/tree/main/default)
- [x] REST API doc site rest.galasa.dev (https://github.com/galasa-dev/argocd-ibmcloud/tree/main/default)
- [x] Eclipse P2 site p2.galasa.dev (https://github.com/galasa-dev/argocd-ibmcloud/tree/main/default)
- [x] Isolated zip resources.galasa.dev (https://github.com/galasa-dev/argocd-ibmcloud/tree/main/default) 

- [ ] github-copyright
  - [x] build locally for the copyright checker
  - [x] build pipeline for github copyright checker
  - [ ] move over github to use this checker image
  - [x] redirect DNS A record to route traffic to it

### Pipelines

- [ ] Make one pipeline dual-headed so it publishes to the new harbor, and kicks the argocd app.
- [ ] move the DNS records over to refer to the new clusters nexus/harbor/argocd

### Domain migration
- [ ] How to we migrate the domain to a different IBM account ?

### Secrets:
Can use the same ExternalSecret definitions but the remoteRef.key values will need to be updated. Search the ID (click on the secret in Secret Manager and you should see a long string for 'ID') in VSCode to find the yaml files.
- [ ] Create a new SecretStore to access the new Secrets Manager (one for each of the new namespaces)
- [ ] Migrate all secrets in IBM Cloud Secrets Manager **apart from**:
- gpg-passphrase and gpg are not needed for the external cluster also their values are expired
- galasa-id is a duplicate
- galasa-plexma and galasa-plex2 should only be in Vault

~- [ ] When migrating these secrets, name them more clearly:~ I have moved this to a separate issue #1576 to complete after the migration as it might be a bit confusing to migrate and rename in the process, in case you need to look back at the old secret and match it up.

- [x] Use the CIO-account secrets manager for now, rather than a new secrets manager on the PlanB account. Secrets used by planb cluster are named with a prefix of 'planb-'.

### Potentially should be deferred until OMP account is available / part of a new issue to migrate internal secrets:
- [ ] Ask Mike Baylis if we can set up a SecretStore so the internal cluster can connect to the IBM Cloud Secrets Manager to get secrets needed the build pipelines
- [ ] Internal vault needs to hold only internal resources
- [ ] External secrets manager should be used for everything else
- [ ] The password for the 'admin' account on the Harbor application needs to change. See `harbor.yaml`

## Deferred tasks when the OMP account is available
- [ ] Container image registry can be left until we move to the OMP-funded account.
  - requires some communications with the CIO office to move it.
- [ ] Docs site gets deployed in a code engine, so isn't dependent on IKS, so doesn't need moving just yet.
- [ ] Migrate the external Tekton? Not currently being used but maybe in future... https://github.com/galasa-dev/automation/tree/main/infrastructure/ibmcloud-galasadev-cluster/tekton

**Comment by techcobweb** [comment]
Meeting to discuss: Today at 3pm BST. 
Attendees: louisase@uk.ibm.com, @techcobweb jmertic@linuxfoundation.org @RogerBrooks2

Discussed the above. 

MikeC: We can stage any migration to move the publically-visible 'serve' functionality, then the build infrastructure later.

John presented a few options:
- Switch the IBM cluster payment over to the OMP
- Move to something else, like Digital Ocean or AWS, or a different IBM offering funded by the OMP

John suggested that we involve some Linux foundation experience in CI/CD to look at the requirements we have and suggest a course of action, and perhaps help us to get there.

The timings for moving off the public infrastructure was discussed:
- @RogerBrooks2 said we should think about End Sept 2023
- jmertic suggested this wasn't realistically achievable, and we need to look at extending our time-line.

**Comment by techcobweb** [comment]
## Email from Louisa S:

Hi all,
 
Thanks for the call today, here’s the notes I made.
 
## Actions:
- IBM team to investigate other cloud providers if IBM Cloud can’t accommodate Galasa.
- Roger to go back to IBM Cloud and work out when the date is, and what we need to do in case the services are sunset.
- John Mertic to investigate release engineering resource that can speak to James and Will for a deeper dive into Galasa infrastructure.
 
## Notes:
- OMP are agnostic to the cloud provider that Galasa want to use, and if appropriate, are happy to fund the billing for IBM Cloud until a suitable alternative comes available.
- Digital Ocean, AWS, and Azure were all mentioned as possible options.
- OMP appreciate that the restructuring of code in the environment is challenging and with a target of 6 weeks, it is ambitious to move everything.
 
Many thanks,
Louisa

**Comment by techcobweb** [comment]
I have asked a Cirrus architect for a meeting. He says it will be next Tuesday. Time not arranged yet.

Jake Castro raised a ticket to track the request here: https://jsw.ibm.com/browse/HCPCOE-3266

@hobbit1983 @Jimbo4794 @RogerBrooks2 @jadecarino

**Comment by techcobweb** [comment]
The latest on this: The OMP organisation is allocating an IBM cloud account to sort out the billing of the external cluster.

The plan is that they make Mike/James/Jade/Will delegates, so we can allocate the infrastructure components ourselves, and start migrating to use them.

**Comment by techcobweb** [comment]
The integrated builds are working.
So I think this is done.
