### ISSUE TITLE
Move galasa dev team discussions to open slack channel

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1545]
## Story
As a galasa developer I want to be able to see all the development threads and activities of other developers, regardless of whether they are IBM staff or otherwise.

## Background
IBM Galasa development team currently use an internal-to-IBM for all the regular day-to-day communications about stories, progress, problems..etc. It would be better if this chat were external to IBM on a forum where developers from any company or organisation can see and get involved as required.

Suggestion is currently move to the https://galasa.slack.com/archives/C0139132RUL channel.

Bots which the team find helpful will need to be moved over to work against this new channel.

## Tasks
- [ ] Move over the IVT-reporting bot to use this new channel.
- [x] Move over the Scrum-status bot to use this new channel.
- [ ] Add a close-out message to the old channel, and re-work the channel pins and links and description on purpose.

**Comment by techcobweb** [comment]
@louisa-seers Where should the channel be ?

**Comment by louisa-seers** [comment]
One of the aims of the TSC on Tuesday was to vote on the location of the Galasa workspace. There weren't enough people on the call to have a quorum. The feeling however, was to move to the OMP workspace to align with other projects and a wider community (15k in the OMP workspace). It sounds like the sensible decision is to make a new channel in the OMP workspace, however Will was unsure about moving from Galasa. I believe any bots could be considered or added by Yarille as workspace owner if we asked.

Do you need a decision on this now?

**Comment by techcobweb** [comment]
No decision needed, except if we are to work in the open this issue needs to move on.

**Comment by louisa-seers** [comment]
Sure, I appreciate that. My opinion is that we should create a new channel on the OMP slack workspace called #galasa-devs and use that, however I will wait for @hobbit1983 to comment as he owns the workspace.

**Comment by techcobweb** [comment]
This is a duplicate of [Switch to use slack channels on OMP workspace#1575](https://github.com/galasa-dev/projectmanagement/issues/1575)
