### ISSUE TITLE
CLI: Specify a bootstrap of file:/x/... should give error.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1554]
## Story
As a CLI user if I use the --bootstrap parameter, or have specified the GALASA_BOOTSTRAP env variable instead, but the value I set is of the form `file:/x/...` then an error should be issued of the form "GAL00xxE: Bootstrap value is invalid. It starts with file: but is missing two leading slashes to make it a valid URL."

## Background
Users who expect to use file:/my/folder will never have a working system.
We need to tell them specifically to use `file:///my/folder` (linux/mac) or `file://c:/my/folder` (windows) instead.

## Tasks
- [x] Change the validation code + unit test
- [x] Check that it works for env variable
- [x] Check that it works for explicit parameter usage
- [x] Check the docs to see if we could be clearer anywhere.
- [x] Test on mac
- [x] Test on windows
