### ISSUE TITLE
CLI test results summay is in random order.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1556]
As a CLI user I want to see the test status report numbers in a predictable order

Currently when I run tests I see things like this:
```
*** results , Passed=1, Failed=0, Passed With Defects=0, Failed With Defects=0, Lost=0
```
or this:
```
*** results , Passed With Defects=0, Failed With Defects=0, Lost=0, Passed=1, Failed=0
```

It should at least be consistently predictable in order.

Suggest Passed, Passed with defects, failed, failed with defects, envfail, lost, others.

Suggest others are sorted in alphabetical order, as there could be custom end result status we don't know about.

## Tasks
- [ ] Locate the code which posts these results.
- [ ] Change the code with unit tests
- [ ] Find and update any docs which might show the wrong order.

**Comment by techcobweb** [comment]
I'm thinking that we should actually match the formatting of the `runs get` variant, and output something like this instead of what we do currently:

```
submitted-time      name   status   result test-name
2023-08-29 06:07:37 C13333 finished Passed dev.galasa.inttests.compilation.offline.isolated.CompilationLocalOfflineJava11UbuntuIsolated
2023-08-29 06:07:48 C13334 finished Passed dev.galasa.inttests.zosBatch.local.isolated.ZosBatchLocalJava11UbuntuIsolatedRse
2023-08-29 06:07:58 C13335 finished Passed dev.galasa.inttests.compilation.simbank.local.offline.isolated.CompilationLocalJava11UbuntuIsolated
2023-08-29 06:07:58 C13336 finished Passed dev.galasa.inttests.zosFile.local.mvp.ZosFileLocalJava11UbuntuMvpRse
2023-08-29 06:10:00 C13338 finished Passed dev.galasa.inttests.zosTso.local.mvp.ZosTsoLocalJava11UbuntuMvp
2023-08-29 06:09:20 C13337 finished Passed dev.galasa.inttests.zosFileDataset.local.ZosFileDatasetLocalJava11UbuntuRse

Total:6 Passed:6
```

Any problems if we switch over to doing that ? @hobbit1983 @Jimbo4794 @jadecarino

**Comment by techcobweb** [comment]
For reference, this is what get today:
```
*** Final report
*** ---------------
***
*** Passed test runs:-
***     Run L1 - /dev.galasa.example.banking.payee/dev.galasa.example.banking.payee.TestPayeeExtended
***
*** Failed test runs:-
***     None
***
*** Passed With Defects test runs:-
***     None
***
*** Failed With Defects test runs:-
***     None
***
*** Other test runs:-
***     None
***
*** results
*** results , Passed=1, Failed=0, Passed With Defects=0, Failed With Defects=0, Lost=0
```

**Comment by techcobweb** [comment]
Need to update the docs.

cc: @CaroMac
