### ISSUE TITLE
Rename mac, linux, and windows intel 64-bit binary to be called x86_64 instead of amd64

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1560]
## Story
As a newcomer to galasa trying to install the CLI program on my 64-bit intel mac, I want to see a binary CLI program called `galasactl-[os-system]-x86_64` instead of the current `galasactl-[os-system]-amd64` so that it's clearer which binary I should select for download and install.

## Background
If you do a `uname -m` on such a machine, you get `x86_64` and have to know that this equates to our `amd64` binary, rather than them just being the same.

It would be far nicer to tell people to do `uname -m` and select the matching CLI binary to download. without this special-case and mental conversion you need to look-up.

It's easy enough for us to re-name the binary, so lets do that when it's built.

## Tasks
- [x] Change the name of the CLI binary as it is built in the Makefile
- [x] Make sure that the build is working locally
- [x] Adjust the scripts which check for `uname -m` and them adjust for `x86_64` architecture (like the build-locally.sh and run-on-ecosystem.sh and run-locally.sh scripts)
- [x] Update the docs on how to identify the executable which needs to be downloaded.

- [x] Download the executable from the 0.29.0 release, re-name it and upload the new name.
- [x] Check the release process to make sure anything which needs to use the new name uses the new name. Check with @jadecarino as required.

**Comment by techcobweb** [comment]
cc @Caromac ^^ This one should help with the docs explanation also ?
