### ISSUE TITLE
update website with additional OMP information

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1565]
## Story
As a user, I want to see links to OMP assets , so that I have more information about OMP.

## Background
Received email from Mae : 
We also ask that you add a link to the Open Mainframe Project site from the Galasa site and point to any assets we promote. For example, the press release on Monday that announces Galasa or the blog that Will submitted. (Both links will go live on Monday). 

## Tasks
- [ ] Add link to press release in Blog section of site
- [ ] Add link to Will's blog in Blog section of site
- [ ] Add info about OMP and link in About Galasa
- [ ] Update footer with following "© Open Mainframe Project."

**Comment by CaroMac** [comment]
Draft PR raised but awaiting links and therefore overview info to include

**Comment by CaroMac** [comment]
published
