### ISSUE TITLE
Authentication: Web UI should talk to the auth API instead of Dex

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1568]
## Story
As a Galasa developer, I want the web user interface to talk to the auth REST API instead of directly talking to dex, so that it is more maintainable and decoupled from dex-related implementation details.

## Background
The web user interface currently talks directly to dex via OpenID Connect and dex's own gRPC API. Instead, it should only be communicating with the auth service, and the auth service will be the only component that talks to dex.

To achieve this, any functionality currently residing in the web UI that interacts with dex should be moved to the API server's auth service. When this is done, the web UI should make the appropriate calls to the auth servlet to interact with dex.

## Tasks
- [x] Remove the defined `/auth` routes in the web UI
  - [x] Move accompanying unit tests out of the web UI and into the auth servlet
- [x] Generate a Java gRPC client for dex's gRPC API - see https://dexidp.io/docs/api/ (look into using the protobuf gradle plugin)
- [x] Remove the generation of the TypeScript gRPC client in the web UI and build pipelines
  - [x] build-locally.sh - web UI
  - [x] build-branch.yaml - automation
  - [x] build-pr.yaml - automation
- [x] Create equivalent routes in the auth service 
  - [x] GET `/auth` redirects to authenticate with Dex's `/auth` endpoint
  - [x] POST `/auth/clients` creates a new Dex client to later authenticate with and get a refresh token for
  - [x] GET `/auth/callback` is called by Dex and redirects a user back to their original application, appending a returned authorization code as a query parameter to later exchange for a JWT using POST `/auth`
- [x] Update the OpenAPI docs
- [x] Make sure the Helm chart works and update the Helm repo README for configuring Dex (e.g. callback routes will be on the API server instead of the web UI)
- [x] Send appropriate requests to the new auth servlet routes from the web UI - look into using an auto-generated client using the openapi.yaml
  - [x] Generate a REST client using the OpenAPI generator tool
  - [x] Add a step to generate the OpenAPI client in the webui build pipelines as well
