### ISSUE TITLE
Cleaning the 'automation' repository

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1569]
## Story
As a Galasa infrastructure maintainer/developer, I want the automation repository to be tidy and not contain unused resources, so that I am not confused or waste time...

## Background
Looking through 'automation', I have noticed a few things that could be tidier so I will work through these slowly.

## Tasks
Secrets (This might be part of a deferred set of tasks to complete after the migration to new OMP funded IBM Cloud account):
- [x] Rename ExternalSecrets and the file name that defines them more suitably:
   - [x] secret-docker.yaml should be renamed to secret-harbor-creds.yaml
- [x] Delete ExternalSecrets that are not being used on the old cluster/expired credentials:
   - [x] secret-maven.yaml in galasa-pipelines
   - [x] secret-gradle-properties.yaml in galasa-pipelines
   - [x] secret-gpg.yaml in galasa-pipelines
- [x] Rename Secrets in IBM Cloud Secrets Manager to be clearer (or wait until migration to new cluster and name more suitably initially)
- [x] Go through all ExternalSecrets used and determine whether they should be pulling from Vault or Secrets Manager (Might have to stay as Vault otherwise will need a new SecretStore created)

Delete:
- [x] Remove comments from Dockerfiles.
- [x] Remove duplicate resources being used in the Docker builds.
   - [x] httpd.conf - Either rename to be specific for each file if each configuration file contains specific things for the different images, or put the httpd.conf file in a common location and point the context of the Docker build there:
      - [x] eclipse-p2, galasabld-binary, isolated, javadoc-site and restapidoc-site use common file as same configuration
      - [x] delete https://github.com/galasa-dev/eclipse/blob/main/galasa-eclipse-parent/dev.galasa.eclipse.site/httpd.conf
      - [x] delete galasabld-binary in folder
      - [x] delete https://github.com/galasa-dev/isolated/blob/main/full/httpd.conf and https://github.com/galasa-dev/isolated/blob/main/mvp/httpd.conf
      - [x] delete https://github.com/galasa-dev/obr/blob/main/javadocs/httpd.conf
      - [x] delete https://github.com/galasa-dev/framework/blob/main/httpd.conf
      - [x] base and cli use the same file as same configuration
      - [x] delete https://github.com/galasa-dev/cli/blob/main/httpd.conf
      - [x] resources stays with it's own httpd.conf file as configuration is slightly different
   - [x] Put ibmca.pem, ibminter.pem and ibmroot.pem in common location
      - Repeated in cli, common and galasabld
- [x] Delete pipelineRuns directory, I don't think it's needed
- [x] Remove commented out git-clean task from the end of all pipelines
- [x] Delete galasa-pipelines namespace
- [x] Delete the webapp pipeline in galasa-pipelines / Recreate for galasa-build
- [x] Delete ghverify build in galasa-pipelines
- [x] Delete the cleanUp CronJob in galasa-pipelines
- [x] Delete Tasks that are duplicates / could be done more effectively using parameters
   - [x] 'copy' task should be replaced by 'script'
   - [x] 'unix-command' should be replaced by 'general-command'
   - [x] 'maven-build-java18' can use 'maven-build' with the image name passed in

Update:
- [x] Move secrets-manager-operator into the 'galasa-build' directory
   - [x] Update the ArgoCD app pathway to match 
- [x] Replace 'amd64' with 'x86_64' in Task names in CLI build
- [x] Merge the 'docs' and 'docs-images' directories
- [x] Update README.md as it is outdated
