### ISSUE TITLE
CLI runs submit should not have a --requestor flag

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1570]
## Story
As a galasa CLI user I don't want people to be able to imitate me by setting the --requestor flag on the galasactl runs submit command.

## Background
Using the --requestor flag on the runs submit artificially sets who is running the test.

It should be the user id always for local runs.

It should be derived from the access token for ecosystem runs... set by the REST layer, and not by the CLI at all.

Help for runs submit currently has this:
```
--requestor string  the requestor id to be associated with the test runs. Defaults to the current user id.
```

## Tasks
- [x] Remove the flag from the `galasactl runs submit` command. Always setting the requestor to the current user (for now).
- [x] Change the API servlet layer to extract the user id from the bearer token, ignoring anything which is passed-up by the caller of the REST command.
- [x] Make sure `galasactl runs submit local` uses the current user id, and doesn't have the flag either.
