### ISSUE TITLE
CLI: Local test runs should have a requestor and submission time fields displayed.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1574]
## Story
As a tester running a local galasa test I want to see the requestor and submitted-time(UTC) fields being displayed with content inside, rather than blank space, so that I can see how long there was between sequential tests, and would look better in the formatter.

OR

As a tester running tests and formatting them, if there are columns with no content, then drop that column from the display for the summary view.

## Background 
We currently see this when we run a single local test:

```
submitted-time(UTC) name requestor status  result test-name
                    L1             started Passed /my-bundle/my-test-class
```

We either want to see this:
```
submitted-time(UTC) name requestor status  result test-name
xxxx-a-date-time-xx L1   my-id     started Passed /my-bundle/my-test-class
```

or this:

```
name status  result test-name
L1   started Passed /my-bundle/my-test-class
```

## Tasks
- [x] Decide which option we go for.
- [x] Implenent and unit test
- [ ] Update docs as required.

**Comment by KirbyKatcher** [comment]
I consider this a bug as the data is available in the local run structure.json, so we should be displaying it in the same format as ecosystem runs

**Comment by KirbyKatcher** [comment]
@Wyvinar & @Akyiaa 
I have made the implementation of the code for now to quick fix, please review changes and implement the unit tests, as well as the doc changes on branch
`issue-1574-submit-local-runs-missing-fields`
