### ISSUE TITLE
Switch to use slack channels on OMP workspace

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1575]
## Story

As a galasa developer I want the slack channels we use should be hosted on the OMP workspace, so that our communications with each other and with the wider user community to align with the other projects in the OMP.

## Background
To align with a decision made on the TSC call 19th Sept, we will create new slack channels on the OMP community:

- galasa-dev (already exists)
- galasa-users (doesn't exist yet)
- galasa-tsc (for tsc-related discussions)

## Tasks
- [x] Create the missing channels in the OMP workspace
- [x] Switch the dev team to start using the new OMP galasa-dev channel
- ~~Move over the scrum bot to the new channel ?~~ Scope removed. We are getting by with manually adding the message every day.
- ~~Move the IVT test status reporting to the new galasa-dev channel~~ Scope removed. We are getting by with IBM-internal reports so far.
- [x] Shut down the other galasa workspace channels, re-directing them to the OMP galasa-user one
- [x] Email all current Galasa workspace users of the new workspace and reasoning for moving

**Comment by hobbit1983** [comment]
Yarille (from the OMP) has already created the galasa-{tsc/users/devs} channels within the OMP workspace for us

**Comment by hobbit1983** [comment]
I've already pulled the list of people signed up to the galasa workspace
