### ISSUE TITLE
Name secrets in Vault and Secrets Manager, and ExternalSecrets in the clusters, more suitably

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1576]
## Story
As a Galasa infrastructure maintainer/developer, I want the secrets in IBM Cloud Secrets Manager and Vault, to be consistently named and match the names of the ExternalSecrets in the two K8s clusters, so that I can easily match the two and know what secret to update if a credential has expired etc.

## Background
Firstly, I have noticed that the names of the secrets stored in Secrets Manager and Vault are not named very clearly so it's not always clear which secret to look in to find a specific credential if you need to find it to use for some reason. Secondly, they don't always match exactly with the name of the ExternalSecret defined in the cluster which I believe they should for consistency, if there is a 1-1 relationship. Sometimes there isn't a 1-1 relationship, for example, some ExternalSecrets use data from two different secrets in SM or Vault and merge them to make one ExternalSecret, so the name of the ExternalSecret should reflect what it is actually holding. Finally, the .yaml files that define the ExternalSecret should be named to match the ExternalSecret name, so you can easily find the file to update if a secret needs updating/fixing.

This work should be completed following the migration to the new temporary plan-B cluster to not make the initial migration confusing.

## Tasks
My suggestions for what to rename the secrets are below but happy for suggestions from the team if there are different ideas.

Secrets Manager:
- [x] Rename  galasa-github > galasa-github-username-token.
- [x] Rename Galasa-team-GitHub-access > galasa-github-credentials.
- [x] Rename  harbor-admin > harbor-admin-credentials to differentiate between the admin and standard user credentials below...
- [x] Rename habor-credentials > harbor-credentials to get rid of the spelling error.

Vault:
- [ ] 

ExteralSecrets names:
- [ ] 

Names of the actual yaml files holding the ExternalSecret definitions:
- [ ]

**Comment by jadecarino** [comment]
Some of this has been completed as part of https://github.com/galasa-dev/projectmanagement/issues/1569
It looks like I don't have permission to delete secrets in Vault, and you can't rename secrets in Vault either, you need to delete and recreate them, so we'd end up with loads of duplicates, which is counter productive, unless I asked someone with access to delete the old ones.
ExternalSecrets should be renamed to be more suitable I believe.
