### ISSUE TITLE
Create a separate section for the zipped distribution documentation

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1580]
## Story
As a user, I want to be able to review the zipped distribution documentation, so that I can get started easily.

## Background
Currently the zipped distribution information is contained in the getting started with eclipse section. we need to separate out the zd information into a separate, self contained section as it is a different usage scenario.
## Tasks
- [ ] separate out the zd information
- [ ] add any additional information regard the usage scenarios for the zd
- [ ] review / add  information (eg prerequisites, getting started instructions) for the zd

**Comment by jadecarino** [comment]
Completed as part of https://github.com/galasa-dev/galasa/pull/588
