### ISSUE TITLE
Prepare for GSE UK presentation on November 1st

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1582]
## Tasks
- [x] Discuss with team what to demo (last time was galasactl project create, then running a test from Eclipse, then galasactl runs get)
- [x] Set up workspace for demo and practice demo
- [x] Go through content from previous GSE presentation and update slides
- [x] Run through of presentation
