### ISSUE TITLE
Infrastructure cleanup: Update references to docker.galasa.dev

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1588]
# Background

docker.galasa.dev is no longer the docker repository that we use for images. It still exists as a component of the Nexus but is no longer our primary docker repo. It is still referred to in various places throughout Galasa: either in redundant pieces of code so these should be cleaned up, or in documentation so I believe should be replaced with a more suitable/current example, such as harbor.galasa.dev.

## Tasks (files that refer to docker.galasa.dev) 
- [x] https://github.com/galasa-dev/extensions/blob/main/Jenkinsfile - delete (already deleted)
- [x] https://github.com/galasa-dev/extensions/blob/main/Jenkinsfile.gradle - delete (already deleted)
- [x] https://github.com/galasa-dev/framework/blob/main/galasa-parent/dev.galasa.framework.docker.controller/src/test/resources/galasa.properties - delete ([PR](https://github.com/galasa-dev/framework/pull/510))
- [x] https://github.com/galasa-dev/managers/blob/main/galasa-managers-parent/galasa-managers-other-parent/dev.galasa.galasaecosystem.manager/src/main/java/dev/galasa/galasaecosystem/internal/properties/DockerRegistry.java - change the javadoc example. ([PR](https://github.com/galasa-dev/managers/pull/927))
- [x] https://github.com/galasa-dev/galasa.dev/blob/main/src/markdown-pages/docs/managers/galasa-ecosystem-manager.md - put in a different example
- [x] If you unpack the VSCode extension https://github.com/galasa-dev/integratedtests/blob/main/galasa-inttests-parent/dev.galasa.inttests/src/main/resources/galasa-plugin.vsix - we don't support that, so it should already be deleted. take the test out ? (already deleted)
- [x] Several files in the argocd-ibmcloud repository (but this repository should be archived anyway) - already archived.

**Comment by techcobweb** [comment]
@jadecarino This looks like another one which Fiona could do ?
