### ISSUE TITLE
CLI: create project should insist on --maven or --gradle flags, or both.

### ISSUE THREAD

**Issue by ChrisAtkinson1** [galasa-dev/projectmanagement#1593]
## Story
As a tester trying to create a skeleton project, I want to have the tool demand knowledge of whether I want a gradle or maven build system, or both, appear in the examples, so I don't end up with Maven and have to figure out what the incantation is for getting gradle working.

The idea is that there isn't a default of gradle or maven, and we treat them both as equals, insisting on being told explicitly which one to use.

## Tasks
- [x] Code and unit test the changes in the CLI. Unit testing may not be easy/worthwhile for this one.
- [x] Docs example needs an update (explicitly mention --maven)
- [x] Fix failing unit tests
- [x] Change test scripts which exercise the project create command

**Comment by techcobweb** [comment]
This is complete and released.
