### ISSUE TITLE
Automated deploy of ecosystem on PlanB cluster

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1595]
## Story
As a developer I want to deploy the helm chart to the planB cluster, so that I can use it to demonstrate security authentication, and run tests which don't need to interract with Zos hosts.

## Background
We can't test our helm chart on cicsk8s due to permissions/admin roles issues.

We want to test the help chart in automation.

Deploy the helm chart to the planb cluster.

## Tasks
- [ ] New namespace on the planb cluster. galasa-ecosystem-1
- [ ] Helm pipeline builds and deploys main branch to this new namespace on the planb cluster.
- [ ] Authentication set up to refer to two new teams in the galasa-dev github org.
  - GalasaEcosystem1Admins
  - GalasaEcosystem1Users

- [ ] Ability to run tests when authenticated

**Comment by eamansour** [comment]
This is done - we use a Galasa service on the OMP cluster which gets automatically redeployed during main builds
