### ISSUE TITLE
improve error handling and help text for galasactl properties get

### ISSUE THREAD

**Issue by Akyiaa** [galasa-dev/projectmanagement#1598]
## Story

1. As a user trying to see the names and values of a property in a namespace, when I use the command  `bin/galasactl-darwin-arm64 properties get --help` I expect to see helpful and accurate information on how to use 'properties get'.

2. When I use `bin/galasactl-darwin-arm64 properties get` the cobra menu should appear stating that namespace is required

## Background

1. The help menu shows as:
```
-h, --help            help for get
...
--namespace string    Namespace. A container for a collection of properties. It has no default value.
```

2. An error shows up:
`GAL1096E: Could not query namespace results.%!(EXTRA string=400 Bad Request)` 

## Tasks

- [x] Change ` help for get` to be more descriptive
    - [x] properties get
    - [x] properties set
    - [x] properties delete
- [x] Mention that namespace is a mandatory flag 
- [x] Change error message to display cobra command
- [x] Fix an error we've just spotted -fixing this error will lead with scope creep as it is to do with runs, and not properties get, so held it off and will raise another story for it

**Comment by techcobweb** [comment]
Noticed there is another error in this, which is holding it off from being closed.
