### ISSUE TITLE
CLI: CPS properties in the secure namespace CAN be deleted

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1601]
## Story
As a CLI user I want to use the command-line tool to delete a property within the secure namespace, so that I can clean up when mistakes have been made.

## Background
Currently this isn't possible due to a hard-coded limitation, which should be removed.

Any restrictions as to what people should be able to do must form part of a wider epic around role-based security.

## Tasks
- [x] Change REST logic to allow the deletion of such properties.
- [x] Test
- [x] Document ? Maybe not needed.
- [ ] Add to the test-against-ecosystem test suite

**Comment by techcobweb** [comment]
Savvas will try to merge. As holly is away today.
