### ISSUE TITLE
CLI: streams manipulated using galasactl [apply/create/delete] -f xxx.yaml

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1603]
# Story
As a galasa ecosystem admin I want to create or update anything within a stream on the ecosystem from a file definition of that resource, so that I know the stream is in-sync with the file regardless of whether it existed, or had different values before.

# Background

Support the following syntax
```
galasactl resources apply -f {resource.yaml}
```
and
```
galasactl resources delete -f {resource.yaml}
```
and
```
galasact resources create -f {resource.yaml}
```

Such that the resource.yaml contains:
```
api: galasa-dev/v1alpha1
kind: GalasaStream
metadata:
  name: myStream
data:
  repository-url: http://mymavenrepo:8081/myrepo/maven << The maven repo we can draw on.
  obr:  << A list of OBRs which contain tests, or other code required to run the tests.
  - mvn:dev.galasa/dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr
  initialTestCatalog: http://mymavenrepo:8080/testcatalog/example
  description: "Example test stream"
```

REST interface
`POST http://.../resources`

payload:
```
{
  "command": "apply",
  "resources": [
    {
      "api": "galasa-dev/v1alpha1",
      "kind": "GalasaStream",
      "data" : {
        "repository-url": "http://mymavenrepo:8081/myrepo/maven << The maven repo we can draw on.",
        "obr": [ << A list of OBRs which contain tests, or other code required to run the tests.
          "mvn:dev.galasa/dev.galasa.examples.obr/0.0.1-SNAPSHOT/obr"
        ],
        "initialTestCatalog": "http://mymavenrepo:8080/testcatalog/example",
        "description": "Example test stream"
      }
    }
  ]
}
```

The file could have multiple resource definitions inside, separated by a line with '---' on.

The file could be a folder, in which case all the yaml files are recursively gathered to be sent.

# Tasks
- [ ] Add resources endpoint if it's not already there.
- [ ] Openapi.yaml changes
- [ ] Validator on the servlet end to make sure the record is valid.
- [ ] Servlet layer do as much checking up-front as they can, prior to updating/creating anything
  - [ ] Separate validation functions v.s. apply functions.
- [ ] Servlet layer gather as many errors as it can and returns a list of errors if there are any.
- [ ] Ideally, any failure in checks stops any resources being changed. How close to an atomic commit of all resource changes can we get using locking in etcd to avoid race conditions ?
- [ ] Update supported
- [ ] Delete supported
- [ ] Create supported
- [ ] CLI can send one resource from one file
- [ ] CLI can send multiple resources from one file with the '---' separator
- [ ] CLI can send one resource from one folder
- [ ] CLI can send multiple resources from nested folders
- [ ] CLI can show multiple errors/reasons why the overall operation failed.
- [ ] 0 exit code for everything worked, else 1.
- [ ] Enhancements to test-galasactl-ecosystem.sh
- [ ] README updated
- [ ] Updates to galasa.dev website docs

**Comment by techcobweb** [comment]
This was all implemented using other stories. Available in release 0.41.0
