### ISSUE TITLE
CLI: streams get supports --format yaml

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1604]
# Story
As a galasa admin I want to get the stream definitions into a yaml file so that I can apply those yaml files to a different galasa ecosystem later.

# Background

Need to support this on the CLI:
```
$ galasactl streams get --format yaml
apiVersion: galasa-dev/v1alpha1 << Note: No blank line at the top.
kind: GalasaStream
metadata:
  name: myStream1
data:
  ...other streams fields...
---
apiVersion: galasa-dev/v1alpha1
kind: GalasaStream
metadata:
  name: myStream1
  description: |- 
    A stream where testcases are drawn from two source locations.
    Each will be searched in the order
data:
  repositories:
  - url : http://my/maven/repo1
    credentials : myCredential1
    authType: basic
  - url : http://my/maven/repo2 << No authentication needed to read this
  
  test-catalogs:
  - url: http://my/test/catalog.json
    credentials: myCreds2
    authType: basic
  
  obrs:
  - maven-group-id: myGroup
    maven-artifact-id: myArtifact
    maven-version: 0.38.0 
    
```

REST call is GET /streams

# Tasks
- [x] Streams REST interface
- [x] Streams REST openapi.yaml
- [x] CLI streams command
- [x] CLI streams GET support
- [x] Yaml formatter
