### ISSUE TITLE
Release 0.30.0

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1605]
## Story
As a galasa user I want to get the 0.30.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [ ] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [ ] Identify problems/improvements and raise them for next time
- [ ] Add more detail for asking for release approval
- [ ] Add more detail for how to manually install Simbank
- [ ] Add documentation to developer-docs for where to upload GPG public key
- [ ] Add note about --secret-type to the Eclipse marketplace task.
- [x] Make sure scan results are clean

**Comment by jadecarino** [comment]
@techcobweb Hi Mike, as discussed, all integration tests for the release candidate passed, other than 1 which due to environmental issues is stopping the test from running further than provision generate stage. The initial run had 7 failures (6 lack of resource, 1 Will's VM being down). Upon re running the 7 failures, all apart from the 1 mentioned have passed. Unfortunately the Tekton pipeline that was running the original batch of tests took longer than 1 hour and therefore was cancelled, and the results were not reported to the Phoenix dashboard. I ensured to check the result of each test individually in the Eclipse plug-in to confirm the results. With all that in mind, I am proceeding with the release as there is a 98% pass rate.

**Comment by jadecarino** [comment]
Artifacts released to maven central. I am also working on improvements/corrections to the release doc which I'll deliver at the end of the release.
