### ISSUE TITLE
Fix incorrect license URL in all POMs

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1606]
## Story
As a galasa user obtaining artifacts from maven central I want to follow the link from the downloadable artifacts to the license file so I can read the license file. Currently that link gives a 404 not found.

## Background

The license URL in our POMs is incorrect: https://www.eclipse.org/legal/epl-2.0/t

Needs correcting in all the repositories.

It should be https://www.eclipse.org/legal/epl-2.0

## Tasks

- [x] managers
- [x] galasa.dev - already correct license
- [x] automation - couldn't find
- [x] eclipse  - couldn't find
- [x] cli - couldn't find
- [x] isolated - couldn't find
- [x] obr
- [x] extensions
- [x] gradle
- [x] framework
- [x] wrapping
- [x] maven
- [x] githubapp-copyright - couldn't find
- [x] TSC - couldn't find
- [x] integratedtests - couldn't find
- [x] argocd-ibmcloud - couldn't find
- [x] projectmanagement - couldn't find
- [x] helm - couldn't find
- [x] simplatform
