### ISSUE TITLE
CLI: galasactl properties not validating the value of a namespace or property prior to trying to construct a URL

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1607]
## Story

Use a namespace which has a dash inside, or a capital letter, or a value that starts with a number...

galasactl properties set --name xxx --namespace "yy-y" --value zzz is failing, and getting a 404 (NOT_FOUND) error as the reason.

# Background
Server-side has a validator for these things. Copy the logic into Go code and unit test.

## Tasks
- [x] Validation of namespace and property character-patterns needs doing on the CLI prior to the  rest call. Otherwise you get a 404 and have no idea why you can't get it to work.
- [x] Add to the doc what the valid values are.
- [x] galasactl help text for the --namespace, --name and --value flags needs beefing up.
- [x] unit tests
