### ISSUE TITLE
CLI: galasactl properties get to support --format raw

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1612]
## Story

As a galasa user writing automated bash scripts to run tests in an ecosystem, I want to be able to see if a CPS property list as 'raw' pipe-delimited output.

For example:
```
> galasactl properties get --namespace xxx --format raw
my.namespace|my.property.name|my.property.value
my.namespace|my.property.name1|my.property.value1
>
```

A return code of 0 if the answer was produced. 1 if there was an error.

A query returning 0 results will result in no output. That's expected behaviour.

Then a script could check the number of lines in the output, or parse what they want out of the output as they wish.

The `--format summary` is the default, which is what we have today.

## Tasks
- [x] Format raw command-line option added
- [x] summary format supported still
- [x] output appears in raw format
- [x] Test in the ecosystem test script
- [x] Changes merged into main.
