### ISSUE TITLE
CLI can delete a stream

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1614]
# Story
As a Galasa ecosystem admin I want to delete a stream using the command line tool, so that I can remove unwanted streams and keep the system tidy.

# Background

```
galasactl resources delete -f {filename}
```
The file contains the definition of the stream.

OR

```
galasactl streams delete --name {streamName}
```

Rest interface should be:

```
DELETE /streams/{streamName}
```

OR

```
POST /resources
[
  {
    "action" : "delete",
    "data" : [{
      "apiVerson":...
      "metadata": {
        "name" : "myStream"
      }
      "data" : {
        "..."
      }
    }]
  }
]
```

And the payload is the file contents.

OR
DELETE /streams/{streamName}

mc: This seems wrong to me to have two ways of doing the same thing.
If the parsing of the file is client-side, then OK, we can do /streams/{streamName}
But it seems wrong sending a DELETE to a resource which never gets deleted.
The HTTP guides say that payloads on delete have no semantic meaning also. So it's definitely wrong to do that.

>> Discuss some more and agree a way forward.

# Tasks
- [x] delete -f option
- [x] delete --name option
- [x] error message if you use both
- [x] add test to the test-ecosystem.sh script
- [x] docs in the README
- [x] docs in galasa.dev
