### ISSUE TITLE
CLI can list available streams with summary format

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1615]
# Story
As a galasa admin I want to list the available streams within galasa so I can see which ones are defined.

# Background

Syntax like this:

## Get a list of all the streams
```
> galasactl streams get 
name        state   description
bestSoFar   enabled Tests that are the best so far 
experimen3  enabled Experimental tests
Total 2
```

where `galasactl streams get --format summary` would have the same effect.

## Get a single stream by name 
```
>galasactl streams get --name "myStream"
name        state    description
my Stream   enabled  Tests that are the best so far 
Total 1
```

## Get a single stream by name in yaml format
```
>galasactl streams get --name "myStream" --format yaml
```

## Stream names are limited to:
0-9, a-z, A-Z - _
First character must be a-z or A-Z

# REST interface

GET 
`/api/streams`
`/api/streams/myStream`

returns either a single or list of stream definitions:
```
[
  {
    apiVersion: galasa-dev/v1alpha1
    kind: GalasaStream
    metadata: {
      name: "myStream"
      url: http://.../api/streams/myStream
      description: "A stream which I use to..."
    }
    data: {
      isEnabled: true
      repository : {
        url: http://mymavenrepo.host/testmaterial
      }
      obrs: [
        {
          group-id: com.ibm.zosadk.k8s
          artifact-id: com.ibm.zosadk.k8s.obr
          version: 0.1.0-SNAPSHOT
        }
      ]
      testCatalog: {
        url: http://mymavenrepo.host/testmaterial/com.ibm.zosadk.k8s/com.ibm.zosadk.k8s.obr/0.1.0-SNAPSHOT/testcatalog.yaml
      }
    }
  },
 ...
]
```

# Tasks
- [x] Implement endpoint + unit tests
- [x] Update openapi.yaml and docment things there.
- [x] Implement the command in CLI + unit tests
- [x] docs in readme
- [ ] Enhance test-ecosystem.sh script
- [ ] docs in galasa.dev
