### ISSUE TITLE
CLI: properties get supports --format yaml

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1617]
# Story
As a galasa admin/developer, I want to use the CLI to extract a yaml file which describes the properties resources, so I can later apply them from a yaml file with different values.

# Background

We need to support the `--format yaml` file for the `galasactl properties` get command.

Such as this:
```
$ galasactl properties get --namespace test --format yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
  namespace: test
  name: my.property1
data:
  value: my.value
--- << 3 dashes.
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
  namespace: test
  name: my.property2
data:
  value: my.value2
```

Ideally, we'd like the REST interface re-worked to return the data in this format initially.
Otherwise the CLI will have to construct the yaml from different json.

# Tasks
- [x] Change the servlet implementation and REST layer to return this new format (in json).
- [x] CLI to convert the JSON into yaml for display
- [x] Implement the formatter
- [x] Test added to ecosystem script
- [x] Make sure the other properties get formats work OK
- [x] Docs in the readme
- [x] Be careful to bump up versions of bundles which change
- [x] Docs in the galasa.dev website
