### ISSUE TITLE
CLI: build pipelines need to call the ecosystem test script.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1618]
# Story
As a galasa developer I want the builds for CLI to call out into the ecosystem so that I have a warm fuzzy feeling that I've not disrupted anything.

# Background
The `test-ecosystem.sh` script needs to be re-instated as part of the CLI builds.
We disabled it during the migration activity, which is now complete, so now need to get it back working.

# Tasks
- [x] Fix the pr build for CLI
- [x] Fix the branch build for CLI
- [x] Make sure both run.

**Comment by techcobweb** [comment]
Done
