### ISSUE TITLE
Release version 0.31.0

### ISSUE THREAD

**Issue by galasa-team** [galasa-dev/projectmanagement#1625]
## Story
As a galasa user I want to get the 0.31.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [ ] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [ ] Identify problems/improvements and raise them for next time
- [ ] Add more detail for asking for release approval
- [ ] Add more detail for how to manually install Simbank
- [ ] Add documentation to developer-docs for where to upload GPG public key
- [ ] Add note about --secret-type to the Eclipse marketplace task.
- [ ] Make sure scan results are clean
