### ISSUE TITLE
REST: openapi.yaml should include testcatalog and testcatalog/<name> URLs and operations

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1630]
# Story
As a developer of galasa and admin of a galasa ecosystem I want to see the `/testcatalog` and `testcatalog/{name}` URLs represented within the openapi.yaml file so that I understand what REST capabilities are available to me.

# Background
The ecosystem can process the `/testcatalog` and `testcatalog/{name}` URLs.

They are not described in the openapi.yaml

The openapi.yaml file needs to be a reference for all the REST interactions which are possible for the ecosystem.

So we need to update the openapi.yaml file to match the reality of the test catalog REST API.

# Tasks
- [ ] Add the `/testcatalog` URL, operations and payloads to the openapi.yaml specification document.
- [ ] Add the `testcatalog/{name}` URL, operations and payloads to the openapi.yaml specification document.
- [ ] Verify that I can use the swagger UI to interact with the existing REST services.

**Comment by techcobweb** [comment]
We want to deprecate and remove test catalog endpoint now. Direction has changed. Closing.
