### ISSUE TITLE
REST: testcatalog APIs should store the test catalog data in the database, not in a PVC/file-system.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1631]
# Story
As a galasa admin, I want to scale up the number of instances which deal with the test catalogs, and have atomic commits for any changes I make using the REST api, so that I have no partial-updates of the test catalog contents, and can scale the number of API pod instances I have without corrupting/loosing test catalog data.

# Background
- The test catalog REST APIs exist, but don't really handle changes in an atomic manner.
- If the API deployments are scaled, then all the pods each have their own test catalog instances. So the users will see weird results. And if they all mount the same PVC to store the test catalog information, then we start to get affinity problems.
- The answer is to ge tthe test catalog REST API layer to talk to the database, rather than a set of files on a PVC.
- The database can include a 'version number' of the test catalog, which incriments every time it gets changed.
- Any updates to the document/test catalog check that the version number is the same as the current setting, else it implies some other instance has updated it already, and we are about to over-write it. Does this give us atomic changes ? Maybe we need to lock the record prior to updating it, so these checks can happen inside a transaction ?
- Holding the information within a database is a good move. PVCs are harder to back up.
- We want to change the format of the test catalog so there is less duplication, but we need to accept the older format and possibly transform it prior to saving it.
- The rest calls need to return the old format if asked for.
- New REST URL can be introduced to cope with the new format perhaps ? Lets discuss some more.

# Tasks
- [ ] Agree on design with a design meeting to gather opinions and flush out problems which need solving.
- [ ] Agree on format of the test catalog on any new REST API.
- [ ] Deprecate the old REST URLs ?
- [ ] Transform the old test catalog format to the new one for saving, and vice-versa, so the old URLs are still supported, but with a database back-end ?
- [ ] Database tables are created if they don't exist. How is this done ? An init container in the helm chart to patch the database schema ? Is a schema needed if we are using couchdb ?
- [ ] The maven and gradle tools which deploy tests need to use these new APIs
- [ ] Does eclipse use the old APIs ?
- [ ] Other things ?

**Comment by techcobweb** [comment]
cc: @KirbyKatcher

**Comment by techcobweb** [comment]
we want to deprecate and remove test catalogs
