### ISSUE TITLE
Galasa.dev certificates need renewing by the 4th November 2023

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1633]
## Story
Relates to #1491 
As the automate script has not been looked at yet, the certificates on galasa.dev and vnext.galasa.dev need to be rotated to prevent the website from being inaccessible from the 4th November 2023.

## Tasks
- [x] Rotate galasa-cert-no-wildcard certificate
  - [x] Download and prepare certificate chain
  - [x] Upload to the container galasa-eu-gb
  - [x] Upload to the container galasa-au-syd
  - [x] Upload to the container galasa-us-south
- [x] Rotate galasa-cert-vnext certificate
  - [x] Download and prepare certificate chain
  - [x] Upload to the container galasa-eu-gb
