### ISSUE TITLE
Environment variables are not picked up during framework initialisation

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1634]
## Describe the bug
Environment variables (`GALASA_CONFIG_STORE`, `GALASA_RESULTARCHIVE_STORE`, etc.) can be used to set the locations of the CPS, DSS, RAS, and CREDs, but this isn't working in 0.30.0 or main. Instead, the framework sets the locations of these services to locations in Galasa home.

Looking at the framework code, this is happening because the `setStoresFromEnvironmentVariables` method in the `Launcher` class uses `env.getProperty` instead of `env.getenv` (see https://github.com/galasa-dev/framework/blob/main/galasa-parent/galasa-boot/src/main/java/dev/galasa/boot/Launcher.java#L646-L680). The unit tests also use `env.setProperty` instead of `env.setenv`, which is why this wasn't picked up. This also means boot.jar will need bumping to 0.31.0.

The ecosystem Helm chart currently uses environment variables to set these locations, so installing an ecosystem at 0.30.0 or the latest version from main doesn't work.

## Steps to reproduce
This can be reproduced with a local run:
1. Set `GALASA_CONFIG_STORE` to anything
2. Submit a local test with the CLI (I tested this on 0.30.0)
3. Open the test's run.log file and search for "Configuration Property Store is" - this value will be obtained from your Galasa home directory, and will not be the value that you set in `GALASA_CONFIG_STORE`

## Expected behavior
The locations of the CPS, DSS, RAS, and CREDs should be picked up from the `GALASA_<store>_STORE` environment variables if they have been set.

# Tasks
- [x] Script to uplift the boot jar version wherever it is mentioned.
- [x] Run the above script to uplift the boot jar
- [x] The code changes described above
- [x] Check that the code changes have fixed the defect described above

**Comment by eamansour** [comment]
Fixed - closing.
