### ISSUE TITLE
CLI --outputFile captures output into a file.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1637]
## Story
As a galasactl user I want to capture the output of the command into a file, without re-directing it, so that I can see the output in a file rather than on my console.

## Background 
This feature is useful if you want to capture a .yaml file for example:
```
galasactl properties get --name xxx --format yaml --outputFile myOutputFile.yaml
```

That should create an output file in the specified location.

## Tasks
- [x] Add the new command to the root command. All commands can then use the option.
- [ ] The file needs to be a valid file name, which can be checked by the file system.
- [ ] If the file already exists, we should fail the command, as we may over-write data ?
- [ ] When a console is created, that console needs to be captured and saved in the file (if there is any output)
- [ ] Check that commands like `galasactl properties get --name xxx --format yaml --outputFile myOutputFile.yaml` work.
- [ ] Help text for the root-level parameter
- [ ] Docs in the readme.md file.
- [ ] Docs in the website.
- [ ] Unit tests can supply a mock file system to the console, and check the output is as expected from there.
- [ ] Test in the local test script to make sure output appears, and is what we expect.

**Comment by Wyvinar** [comment]
How does this work in conjunction with --log flag? does it capture all output including log? what happens when a command errors?
For now I'm going to take this as yes, no, and doesn't save anything

**Comment by Wyvinar** [comment]
It has been decided that this function can be done using command tools that already exist such as piping into a file.
