### ISSUE TITLE
CLI: Properties should be encoded in base64 characters during transmission over REST and in yaml files

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1638]
## Story

As a galasa user I want to pass CPS properties values in yaml format using special characters in my value, without the characters being mutated by code pages or during transmission, so I know my values won't be corrupted.

## Background
The properties returned from the REST API, and in the yaml/json format should be encoded in base64.
- Over the REST API
- In the json or yaml representation, on the GET
- In the json or yaml representation, on the POST/update/ apply -f

The CLI adds an optional `--encoding base64` flag to the properties set command.
eg:
```
> galasactl properties set --namespace nnn --name a.b.c --value 78FEDEA76ABBA23 --encoding base64
```
Allowing a base64 value to be sent. The actual value doesn't need encoding prior to transmission as a result.

If the encoding is not `base64`, `clear` is also allowed. Which is the same as not specifying any encoding.

The CLI adds the --encoding base64 flag to the properties get command, to show the values in base64
eg:
```
> galasactl properties get --namespace nnn --name a.b.c --encoding base64
namespace name value(base64)
nnn              a.b.c. 78FEDEA76ABBA23
```
Note: The title of the value column should be base64 for clarity.

If the `--encoding clear` flag is used, then the value is shown in the clear, with the 'value' field being as it is today.

The same for the --format raw view of properties (though there are no headers there)

Yaml files always contain base64-encoded values when got from the server
```
kind: .../GalasaProperty
metadata:
  name: xxx
  namespace: yyy
  encoding: base64
data:
  value:
    0FCDDA566756FAAAD ...etc.
```

The server supports yaml files which have not been base64-encoded, such as this:
```
kind: .../GalasaProperty
metadata:
  name: xxx
  namespace: yyy
  encoding: clear
data:
  value: "My string value"
```

or this is also valid:
```
kind: .../GalasaProperty
metadata:
  name: xxx
  namespace: yyy
data:
  value: "My string value"
```

This allows the extraction of a value from an old system which doesn't support base64 encoding, and setting into a newer system.

eg: The encoding metadata is optional.

Clients which are not able to handle the extra field will never see it, as the server will not add that detail into the metadata structure.

## Tasks
- [ ] Change the REST interface to always encode them in base64 before putting the value into the json for transmission on the GET
- [ ] CLI to accept the --encoding base64 flag on `galasactl properties set` to accept a base64-encoded, or clear value. Or the flag can be missing.
- [ ] CLI to accept the --base64 flag on `galasactl properties get` to show values in base64-encoding.
- [ ] When rendered as yaml getting from a server, the yaml contains encoding information
- [ ] When a down-level client asks for a property it appears in clear encoding.
- [ ] 
- [ ] Docs to show examples of both in the Readme
- [ ] Docs in the galasa.dev web-site.
- [ ] Integration tests against the ecosystem to use both variants setting and getting.

**Comment by techcobweb** [comment]
@KirbyKatcher Once the properties yaml stuff is working, we should do this issue prior to releasing anything with the yaml format being used.

I forgot this was how kubernetes handles values, and we should do the same thing to match. Also, saves lots of escape characters being needed when encoding into json and back.
