### ISSUE TITLE
Infrastructure: Transfer the galasa-prod ecosystem definitions and all galasa-* to own repository

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1641]
The resource definitions for the galasa-prod ecosystem need to be transferred to a different repository to take the responsibility away from the CIT team. 

Request: "Please can you transfer your galasa-* argocd to your own repo. I will add the repo to ArgoCD for you to control".

### Tasks:
- [x] Create resource definitions for the galasa-prod ecosystem
- [x] Push to automation repo
- [x] Go through the remaining galasa-* directories in the CIT k8s repository and determine if resources from other namespaces need moving or deleting
- [x] Delete CRDs from the CIT repo

**Comment by jadecarino** [comment]
As discussed with Eamonn, the Helm chart seems to be progressing well and so this might be unnecessary, so leaving this on the backlog for now.

**Comment by jadecarino** [comment]
Proceeding to remove ownership from CIT team.
