### ISSUE TITLE
Infrastructure: Update Ingress points for galasa*-cics URLs to use default certificate

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1642]
### Context

The certificates for 3 Galasa Ingresses are due to expire soon. However, to avoid renewing them and the following certificate management overhead, NGINX allows the definition of a default certificate, which Mike Baylis has taken care of. This means any Ingress can use it by NOT specifying a 'secretName' in the TLS information of the resource definition.

Request from CIT: To prevent hostname collisions: ensure the qualifier is suffixed with the namespace, so 'galasaras' would now be 'galasaras-galasa-prod'

### Tasks
First galasadev, then galasaras, then galasa, to minimise disruption.

1. galasadev-cicsk8s.hursley.ibm.com
- [x] Determine which Ingresses using the host name are still in use as some resource definitions seem outdated
   - Yes: codecov-ingress
   - No:  galasadev-buildutils-ingress, galasadev-inttests-ingress & galasadev-simplatform-ingress
- [x] Create new Ingress with updated host name that uses the default certificate - codecov-ingress-new, host: galasadev-galasa-prod
- [x] Replace references to use the new URLs
- [x] Delete old Ingress and rename new one to original name: codecov-ingress-new > codecov-ingress

2. galasaras-cicsk8s.hursley.ibm.com
- [x] Determine which Ingresses are still in use as some resource definitions seem outdated
   - Yes: ingress-ras
- [x] Create new Ingress with updated host name that uses the default certificate - ingress-ras-new, host: galasaras-galasa-prod
- [x] ~Replace references to use the new URLs~ No references to the URL other than docs
- [x] Delete old Ingress and rename new one to original name: ingress-ras-new > ingress-ras

3. galasa-cicsk8s.hursley.ibm.com
- [x] Determine which Ingresses are still in use as some resource definitions seem outdated
   - Yes: ingress
- [x] Create new Ingress with updated host name that uses the default certificate - ingress-new, host: galasa-galasa-prod
- [x] Replace references to use the new URLs
   - [x] Replace URL in the framework.config.store property in the bootstrap-file configmap
   - [x] Restart the API
   - [x] If successful, manually update the DSS, RAS and CREDS properties in the CPS
   - [x] Restart the API
   - [x] If successful, update all properties in CPS using the Jenkins pipeline
   - [x] If successful, update the webui-base
   - [x] If successful, move on to changes in automation
   - [x] Then CLI
   - [x] Then other repos
- [x] Delete old Ingress

**Comment by jadecarino** [comment]
Waiting a couple of working days to make sure things are stable with the new URL before I delete the old ingress.

**Comment by jadecarino** [comment]
Blocked as not all team using the new URL yet. Certificate for old URL will expire on 24th Nov anyway so I will finish this off Friday PM.

**Comment by jadecarino** [comment]
All team migrated to new URL and old URL certificate expired anyway so ingress deleted.
