### ISSUE TITLE
CLI: Convert integration tests to unit tests where possible.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1643]
## Story
As a galasa CLI developer I want as much testing to be performed in unit tests as possible, rather than integration tests.
They get called more often, are quicker, and easier to see when they break.

## Background
- Now that we have a re-worked CLI which means almost anything can be unit tested, we should convert any integration tests we can into unit tests where it makes sense.
- Any bad-syntax checking we do can easily be tested now.

## Tasks
- [ ] Identify which tests need converting. For each one:
  - [ ] write as a unit test
  - [ ] remove from the integration test scripts.
