### ISSUE TITLE
Authentication: Create Personal access token dialog improvements

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1647]
## Story
As a user of authentication on Galasa, when allocating a personal access token I want to be told within the create dialog what the devil a personal access token is, and what it's for, with in-dialog text, so I'm not confused what I'm allocating.

As a user of authentication on Galasa, 

### Text explanation of what a token is
We need a piece of explanatory text saying what a personal access token is, and why you would want to use one.

eg: 
>  A personal access token is an alternative to using passwords for authentication. It can be used to configure the galasactl command line tool and interact with the Galasa Ecosystem API, so that client tools can access this Galasa Ecosystem on your behalf with your permissions. Such a personal access token should be kept secret and never shared with others.

### Default text for the token name 
We also should have some greyed-out text suggesting an example within the text box.
eg:
> "galasactl access for machine ???"

### Improved token response dialog text
> Copy the following properties into the galasactl.properties file, so your client tool can then access this Galasa Ecosystem.
should be:
> Copy the following properties into the galasactl.properties file in your Galasa home folder, so your client tool can then access this Galasa Ecosystem.

### Improved token response dialog link to GALASA_HOME folder documentation
> (see the [Galasa documentation](https://galasa.dev/docs) for more information)
That link should launch a new tab in the browser, else you loose the details of your token.

### Improved token response copy to clipboard link
If you click on the 'copy to clipboard' link, you get the text (good), but you also get a horizontal scroll-bar at the bottom of the dialog (bad). 

## Tasks
- [x] Check with Caroline about capitalisation of "Personal Access Token" above and the descriptions.
- [x] Add the text to the create dialog
- [x] Add grey-text to the create dialog text box
- [x] Altered wording for response dialog
- [x] link to docs should launched be in different tab
- [x] copy text button should not create horizontal scroll bar

**Comment by CaroMac** [comment]
Have reviewed and will go through suggested updates with Eamonn.
