### ISSUE TITLE
Remove eclipse from all the builds, docs, and archive eclipse repo.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1650]
# Story
As a first-time user of Galasa I don't want to see any mention of Eclipse plugins in the docs, or in any of the code repositories, or built artifacts, so that I have no confusion as to whether eclipse plugins are supported (they are not once this issue is complete)

## Background 
Following the Galasa Technical steering committee decision last on 21st Nov to remove eclipse plugin functionality, we need to do this as soon as we can to limit any support burden coming from them.

## Tasks
- [x] Take down the P2 update site hosted by Galasa
  - [x] remove p2stable.yaml from automation infrastructure/galasa-plan-b-lon02
  - [x] remove p2stable-service.yaml from automation infrastructure/galasa-plan-b-lon02
  - [x] update ingress.yaml in automation infrastructure/galasa-plan-b-lon02
  - [x] remove entry from DNS for p2.galasa.dev
  - [x] remove entry from DNS for p2nightly.galasa.dev
  - [x] remove entry from DNS for p2snapshot.galasa.dev
- [x] Take down the build process which publishes to p2 site.
- [x] Delete the docker images the build process produces
  - [x] Delete harbor.galasa.dev/galasadev/galasa-p2
  - [x] Delete harbor.galasa.dev/galasadev/galasa-eclipse
- [x] Remove Dockerfiles in the directory /dockerfiles/eclipse
- [x] Take down the build process which publishes the docker images
- [x] Remove the development maven registry for Eclipse: https://development.galasa.dev/main/maven-repo/eclipse/
  - [x] Remove Deployment, Ingress and Service from /infrastructure/galasa-plan-b-lon02/galasa-development/branch-maven-repository/templates/eclipse
  - [x] Remove lines 45-49 from all yaml files in /infrastructure/galasa-plan-b-lon02/galasa-development/branch-maven-repository/values-used-by-different-argo-apps
  - [x] Refresh and Sync the apps *-maven-repos in argoCD after the changes above are merged
- [x] Remove eclipse from isolated and mvp packaging build processes
- [x] Bypass the eclipse build-process in the chain of build pipelines. `cli->isolated`
- [x] Remove the eclipse plugin build process

- [x] Remove Eclipse plugin from release pipelines.
- [x] Remove Eclipse plugin mentions from the documentation.
- [x] Remove Eclipse plugin mentions from the developer-docs 
- [x] Remove Eclipse plugin ment from the Isolated README.txt https://github.com/galasa-dev/isolated/blob/main/full/resources/README.txt

- [x] Galasa SimBank Eclipse plug-in should not be built now

- [x] Archive the eclipse github repository
- [x] Look at how we can signpost on the eclipse marketplace that these plugins are being deprecated.

**Comment by techcobweb** [comment]
Blocked until we support Gherkin apparently.
