### ISSUE TITLE
CLI: `galasactl delete -f <filename>` deletes a list of properties

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1651]
# Story
As a galasactl user trying to maintain an ecosystem, when I have a yaml file containing galasa property resource definitions, and I want to delete a matching set up properties in an ecosystem, I want to do it in a single command, so that maintaining  the properties present on the Ecososystem is easy.

## Background
We have a yaml file with multiple property defintions. 

When I call the CLI tool:
```
galasactl resources delete -f {filename}
```
It should delete any corresponding galasa properties on the server.

## Tasks

- [x] Servlet to accept the delete-resources payload.
- [x] Create and document the new entry point in the openapi.yaml file
- [x] Integration tests which create/get/update/get/delete/get properties
- [x] CLI tool has a `delete -f` command
- [x] Document the new command in CLI readme
- [x] Document the new command in docs
- [x] Update Resources test script

**Comment by techcobweb** [comment]
@Akyiaa @KirbyKatcher I don't see any changes to the test-scripts/properties-test.sh or any new script which exercises this functionality. Did that get missed in the "Update Resources test script" task? or is that something you didn't think of doing ? or is it included in a different story ?

**Comment by Akyiaa** [comment]
@techcobweb This functionality is tested in the newly created test-scripts/resources-tests.sh, which is under the "Update Resources test script" task

**Comment by techcobweb** [comment]
@Akyiaa That's not visible in main. Did it get checked-in and merged correctly ?

**Comment by Akyiaa** [comment]
@techcobweb Aah, it is on my branch, which has not yet been merged into main. But visible in the pr: https://github.com/galasa-dev/cli/pull/188/files#top

**Comment by techcobweb** [comment]
Works for me now.
