### ISSUE TITLE
Support more recent version of Gradle 

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1652]
# Story
As a galasa developer I want tto be able to use Gradle v8.x/7.x while building Galasa code, so I can upgrade my environment to be a more recent level

As a galasa user I want to create a project which supports gradle v8.x/v7.x to build using 
galasactl project create ...etc... --gradle

As a galasa user building my existing test cases, I want to be able to upgrade to gradle v8.x/v7.x and have the galasa plugins run as they do today.

# Background
- Galasa works on gradle v6 or v7.
- Gradle 8 changed some API calls

See the [gradle migration guide](https://docs.gradle.org/current/userguide/upgrading_version_7.html) for more details. Look at the v8 notes also.

See the [Gradle and Java compatability matrix](https://docs.gradle.org/current/userguide/compatibility.html) to which java versions are supported on which gradle versions.

# Tasks
- [x] Decide what we need to do with the gradle plugin ? Can it support all versions ? or do we need specific code which supports one or the other ? Existing customers' builds should still work once this level of Galasa ships.
- [x] Upgrade the galasa source projects to build with gradle 8.x locally.
  - [x] gradle
  - [x] framework
  - [x] extensions
  - [x] managers
  - [x] obr (dependency-download subproject)
  - [x] cli
- [x] Change the output from the `galasactl project create` template if necessary to support gradle 8.x
- [x] Change the tekton build process such that it can use gradle 8.x
- [x] Deliver all the changes and get it all working
- [x] Doc updates, especially what a user with existing galasa tests will need to do/change.
