### ISSUE TITLE
Spike: CouchDB : Single binary stored in single couchdb document

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1653]
# Story
As a galasa developer I want to know the performance characteristics of the two approaches to storing attachments in couchdb. Which are are faster ? which take less storage overall ? What are the trade-offs ? So that I can later evolve galasa to use the best approach.

# Background
This is an experiment/spike to guide us with a longer term approach.

For example:

An artifact document
![Image](https://github.com/galasa-dev/projectmanagement/assets/77053/41d02677-b0ec-49be-b9f3-a083a9a571f7)
contains runid and runname, which both refer to the main run document

A document repreenting the run is here:
![Image](https://github.com/galasa-dev/projectmanagement/assets/77053/cfeec226-d526-44a7-9b92-c5aed3d39af3)

# Tasks
- [x] Add a feature flag so that a cps property can turn on the new behaviour.
  - [x] namespace: "couchdb"  property:"one.artifact.per.document". Set it to 'true' and the new feature will be enabled.
  -
- [x] Digest and understand the Ecosystem couchdb implementation to know what it does
- [x] Write unit tests which test the code as-is.

- [ ] Run a test on the ecosystem with couchdb to show that it still blows up.
- [ ] Switch the feature flag on.
- [ ] Check that it doesn't blow up now.

- [ ] Compare the performance between the two approaches

**Comment by techcobweb** [comment]
abandoned
