### ISSUE TITLE
Set up DfG Mend scans using the Unified Agent

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1682]
## Story
As a Galasa developer, I want to be able to scan the DfG source code files for security vulnerabilities, so that I am ensuring to release safe code to our DfG users.

## Background
IBM Distribution for Galasa (DfG) is built from the Galasa MVP.

All files containing references to IBM, such as licenses and README files, were removed from the Isolated repository (github.com/galasa-dev/isolated) as Galasa is an open source project, we need to ensure that no files attributing ownership to IBM exist in github.com. 

The files were moved to a new repository in GitHub Enterprise(GHE) (github.ibm.com/galasa/distribution-for-galasa-resources) along with YAML files defining a build pipeline and associated tasks. The build pipeline currently downloads the MVP zip, unzips it, then copies and pastes the licenses and text files into it. This directory was then pushed into a different repository in GHE where Mend scanning was completed on it. 

This however is not the optimal approach because a) the isolated.tar file from the MVP zip is too large to push into GHE so cannot be Mend scanned and b) scanning built binaries instead of source files is less reliable.

We need to create a pipeline that clones all of the sources files that make up DfG instead of the build binaries. After the scanning is complete and clear, a release candidate for DfG should be pushed and stored somewhere.

## Tasks
In the distribution-for-galasa-resources reposuitory (GHE), amend the build-distribution-for-galasa build pipeline so it does the following. You may be able to keep some of the existing steps but a lot will need to be redone.

Learning/manual steps to try:
- [x] Investigate how the Mend Unified Agent works (https://docs.mend.io/bundle/unified_agent/page/overview_of_the_unified_agent.html)
- [x] Download the Unified Agent 
- [x] Run the Mend UA locally on a single repo to understand the output etc

The pipeline should:
- [x] Clones the wrapping, gradle, maven, framework, extensions, managers, obr, cli, eclipse and isolated repositories from GitHub then the distribution-for-galasa-resources from GHE (all source code that makes up DfG)

- [x] To avoid having to download the Mend UA every time you run the pipeline:
   - [x] Create Docker image with the Unified Agent installed - the Dockerfile should run the curl command to install the UA
   - [x] (Once keys have been obtained) set them in the dockerfile
   - [x] Build the Docker image with `docker build -f Dockerfile .` in the directory of the Dockerfile
   - [x] Tag it with `docker image tag` as harbor.galasa.dev/common/unified-agent:main
   - [x] Push it with `docker image push`.
- [x] In the pipeline, **using the image created above** run the Mend Unified Agent on all source code

- [x] If the Mend scan is successful, copy the licenses and text files (/licenses and README.txt and ..Notices.html) from distribution-for-galasa-resources into the unzipped MVP zip and push this as a release candidate to ~GitHub Enterprise Files~ another location that can stored large artefacts.
   - [x] ~Will need some research on GitHub Enterprise Files (https://docs.github.com/en/enterprise-cloud@latest/repositories/working-with-files/managing-large-files/about-large-files-on-github)~ Not using Git Large File Storage.
- [x] If the Mend scan is unsuccessful, report this back to the galasa-devs channel.

- [x] ~The DfG end product in GitHub Enterprise Files should be in a format possible for someone to take it, complete code signing, and complete the DfG release - this will be a manual process, not part of this pipeline~
- [ ] The DfG end product should be built into a Docker image (see docker-build examples throughout the automation repo) that inside contains a zip file of DfG. It should be named appropriately and pushed to the internal Harbor in the 'galasadev' repository (dockerfile should be similar to isolated-dockerfileZip)

- [x] Add a trigger from the branch-isolated pipeline to the pipeline that builds DfG - as DfG should be built and scanned each time code is introduced into the project (or is this overkill?)
- [x] Create a cronjob to run the unified agent daily

**Comment by jadecarino** [comment]
Confirmed with Paul Taylor that it is okay to use Mend for DfG.

![Image](https://github.com/galasa-dev/projectmanagement/assets/65225359/a44cb5ec-40d7-49d4-b64c-ad234d6730ad)

**Comment by jadecarino** [comment]
As Holly onboarded IBM DfG to Mend UA, the product's user key was for Holly's user but this will cause issues when her internship finishes. You cannot switch the user once the product is onboarded. So, we need to ask the Mend team to archive then re-onboard the IBM DfG product for the Galasa functional ID to obtain a new set of keys.

**Comment by jadecarino** [comment]
https://github.ibm.com/Supply-Chain-Security/Mend/issues/1844

**Comment by techcobweb** [comment]
Blocked currently with questions outstanding on whether it is scanning the correct content.
Why is eclipse code being scanned. Message sent, awaiting reply.

**Comment by RogerBrooks2** [comment]
Are we still blocked from running the correct content scan?

**Comment by Wyvinar** [comment]
I think so? I've messaged Rebecca Quaggin-Mitchel, and she's sent me some information, but have yet to implement it (and see how it's particularly useful? it's to do with the setting file, but there doesn't seem to be anything about the library we are scanning).
Other than that, I need to find out about how to upload something to the internal harbor, for both the unified agent and the dfg, but it requires specific credentials I think, now Jade's back it should be ok. @RogerBrooks2

**Comment by jadecarino** [comment]
Closing this and reopened a new issue for the internal CICS Galasa project board.
