### ISSUE TITLE
CLI: galasactl Stop an active test run

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1685]
# Story 
As a galasa ecosystem user, running tests, I want to kill and remove the existence of a test run I previously launched, so that there are no out of control tests running on the ecosystem.

# Background
Eclipse does this today. Need a CLI-way of doing it.

Syntax:
```
galasactl runs cancel --name xxx
```

UPDATE : /runs/{id}
Payload:
{
  status: COMPLETE (result=?)
}

Note: This won't delete anything in RAS which we've captured already, just clean out the DSS...

# Tasks

- [x] Servlet
- [x] openapi.yaml changes
- [x] CLI command
- [x] CLI unit tests
- [x] Review
- [x] CLI integration test
- [x] Docs in README.md
- [x] Docs in galasa.dev

**Comment by jadecarino** [comment]
Blocked as unable to run tests in the ecosystem so cannot run the integration test script.

**Comment by jadecarino** [comment]
PR open for this story: https://github.com/galasa-dev/cli/pull/213
