### ISSUE TITLE
CLI: `galasactl properties namespaces get` has available raw and yaml format types, but only uses summary format

### ISSUE THREAD

**Issue by Akyiaa** [galasa-dev/projectmanagement#1687]
# Story
As a galasa user trying to set CPS properties, I need to be able to get a list of all the namespaces available, in a raw and yaml format

# Background
`galasactl properties namespaces get` by default returns the cps namespaces in the summary format. `FormatNamespaces()` has been implemented in the raw and yaml formatters, but only the default summary formatter is enabled for use in commands so far.

# Task
- [x] remove `yaml` flag as it is not necessary
- [x] add the ability to call `raw` in the `--format` flag
- [x] Update readme
- [x] Update galasa.dev

**Comment by techcobweb** [comment]
Raw would be good. Can't see much point in yaml format, as a namespace can't be played-back so far.
