### ISSUE TITLE
Security: lock down ports for dex/couchdb/etcd

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1698]
# Story
As a galasa ecosystem administrator I want to restrict network traffic which hits the Galasa Ecosystem to be REST calls to the API server (or auth endpoint), so that I know we can monitor and restrict network traffic to be HTTPS-only.

# Background

From the helm side:
- Change how pods talk to each other using kube services rather than host:port URLs.
- Ingres changes to not publish ports outside of the cluster.
- Removing the node ports in the helm chart.

Assumes that the IVTs are authenticated.

# Tasks

- [x] Ports to these services are open right now which need closing off:
  - [x] etcd - remove this file https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/templates/etcd-service-external.yaml
  - [x] couchdb - remove this file https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/templates/couchdb-service-external.yaml
  - dex - ingress is at https://github.com/galasa-dev/helm/blob/main/charts/ecosystem/templates/dex-ingress.yaml.
 
Update: Not possible to completely remove access to Dex since callbacks from connectors are required to go through Dex's callback endpoint (`<dex-issuer-url>/callback`), otherwise Dex will stop kicking off auth flows.

Restricting the Ingress to only allow traffic to Dex's `/callback` endpoint can be done using the `nginx.ingress.kubernetes.io/server-snippet` annotation, but this would restrict users into using the nginx Ingress controller.
