### ISSUE TITLE
As a Test Author I want to be able to clear the content of a 3270 field

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1707]
## Story
As a test author I want to clear the content of a 3270 field so that I can enter new content into that field

## Background
If I need to re-write the content of a field on a 3270 screen, there is currently no programmatic way to clear the content of a field without manually inserting a sequence of spaces into the field.  I ideally need this in the Gherkin and Java 3270 API

## Tasks
- [ ] Research how to clear a field within the 3270 terminal implementation
- [ ] Construct the TPI in Java to allow a test to drive this new behaviour
- [ ] Add the Gherkin version of the TPI to drive the Java implementation
