### ISSUE TITLE
Change 3270 Terminal Size in a Gherkin test 

### ISSUE THREAD

**Issue by hobbit1983** [galasa-dev/projectmanagement#1708]
## Story
As a Gherkin Test author I want to specify alternative row/cols for a 3270 terminal so I can interact with alternative screen sizes

## Background
Terminal size can be set within a java test by entering the alternative rows/alternative cols parameters on the 3270Terminal Annotation.  However this annotation is not available within a Gherkin Test.  Suggestion that we create new CPS properties to define the alternative size and update Gherkin3270GivenTerminal to use these CPS properties for a given tagged terminal

Add two new CPS parameters:
- `zos3270.gherkin.terminal.rows` defaults to 24 if missing.
- `zos3270.gherkin.terminal.columns` defaults to 80 if missing.

You can also define a terminal like this in the scenario:
```
Given a terminal with 48 rows and 160 columns
Given a terminal B with 24 rows and 160 columns
Given a terminal C tagged ABCD with 24 rows and 80 columns
```

Any values specified in the scenario take precedence over the CPS properties.

Normally we might expect users to use the CPS properties, and over-ride those properties
on an individual test if they wanted to.

## Tasks
- [x] Create new parameters and create the java classes to read them from the CPS
- [x] Update Gherkin3270GivenTerminal to access these fields
- [x] Generated cps properties file in CLI and overrides properties file should have these values commented-out.
- [ ] Docs of the new CPS property
- [x] Docs of the new gherkin syntax for this stepdef.

**Comment by techcobweb** [comment]
Is the proposal good enough ? I got the impression that the user wanted to run one scenario using one terminal size, and a second scenario using a different size again.

We need to go back to the requirement raiser.

**Comment by techcobweb** [comment]
@CaroMac @jt-nti This story has externals which need to be documented somewhere.

**Comment by techcobweb** [comment]
Not waiting for the external docs. Gherkin needs a complete documentation treatment. See
