### ISSUE TITLE
Create an FAQ page

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1709]
## Story
As I user, I want to be able to review FAQs to see if I can find the answer to my question on the website without raising a ticket or Slack request

## Background
When a question is raised in the OMP slack, or elsewhere, it might be useful to include in an FAQ page in the website to help others who could stumble upon the same query

## Tasks
- [x] Review questions raised in Slack etc
- [x] Create a page of FAQs and answers
- [ ] Review and refine the page to make it easy to consume, and add relevant information to the main website if appropriate rather than the FAQ page
