### ISSUE TITLE
Release notes for release 31

### ISSUE THREAD

**Issue by CaroMac** [galasa-dev/projectmanagement#1711]
## Story
As a user I want to know what is in release 31

## Background
Any additional information that would help to explain the story.

## Tasks
- [ ] ability to specify `--localMaven` flag
- [ ] ability to create, update, apply, and delete a one or more properties to an Ecosystem by specifying a checked-in resource file on the  `galasactl resources` command
- [ ] `–format yaml` flag supported on galasactl properties get` command
- [ ] `–format raw` flag supported on `galasactl namespaces get` command
- [ ] error message is generated when the client and server versions are incompatible
- [ ] Various documentation enhancements
- [ ] New blog post
