### ISSUE TITLE
CICS TS: Take a CICS dump as soon as there is a test failure.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1712]
# Story
As a CICS application developer or CICS developer, when my testcase uses the CICSTS manager, and the testcase fails, I want CICS to be told to take a CICS dump so I can diagnose a problem quicker without having to re-run the testcase.

# Background
When a failure occurs, the logs and error message as often not good enough sources of diagnostics information to full diagnose the cause of a problem. For that we need to take a CICS dump.

CICS dumps are not always gathered, but if a test fails, and a dump hasn't already been gathered then it should gather a dump on the first failure.

Dumps gathered should have a limited lifetime, to save bunging-up the system with too many dumps (which are large datasets).

# Q&A

## How would a Galasa CICS TS manager know that a dump has been taken already or not ?
?

## How would a Galasa CICS TS manager cause a dump to be taken ?
?

## Can dumps created in this way be tied-back to the run id of the test which caused them to be created in the first place ?
?
eg: Can the name of the dump be changed to match the run name test test used ?

## How long do dumps last for before they are cleaned up ?
?
Can this be configurable ?
What does the cleaning up ?

## Is this always behavour that CICS application developers will need ? or is it only CICS TS developers which need this functionality ?

# Tasks
- [ ] Answer all the Q&A above
- [ ] Write the extra behaviour into the CICS TS test manager.
- [ ] Testing
- [ ] Docs in galasa-dev for the manager
- [ ] An example which shows how to make use of this feature
- [ ] Blog article and/or recorded video demo
