### ISSUE TITLE
Move CLI integration test that invokes Core test to Ecosystem 1

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1718]

**Comment by techcobweb** [comment]
# Story
As a galasa developer maintaining the build process, I want to run builds which don't have a reliance on the internal cicsk8s cluster prod ecosystem. Builds should run any tests during the build process against the ecosystem1 server on the public cloud, so that it will be easier later to move the build process off the IBM internal cicsk8s cluster.

# Background
The build process currently runs the core ubuntu test, which doesn't need 3270 access at all, so could be run on the ecosystem1 cluster.

# Tasks
- [x] Do whatever we need to do to the ecosystem1 to allow it to run the test
  - [x] Set up a stream on the ecosystem1
- [x] Target the ecosystem1 galasa server to run the test(s)

**Comment by jadecarino** [comment]
This has been done so closing this issue.
