### ISSUE TITLE
Spike: Build 'buildutils' with GitHub Actions pipeline.

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1719]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

As a developer of galasa open source code, I want to try out building a single galasa component to see if github actions are OK to use, and the expected benefits can be observed. We need to add a parallel build process for the build utils component so we have a practical idea of how it compares to tekton, so we can get some experience with github actions, and use of the related artifact stores.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

To test these theories, we have to start small, with a small investment in a spike story.  This story.

Objectives:
- Learn GH Actions skills
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for buildutils](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/buildutils), but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Copy all Dockerfiles used in the buildutils pipelines into the 'buildutils' repository into a `dockerfiles` subdirectory (don't move them as we don't want to disturb the Tekton builds)
- [x] Use GitHub actions to build the 'buildutils' repository similar to the existing Tekton pipelines but adapt where necessary
- [x] Build the `galasabld` and `openapi2beans` binaries into Docker images that contain the executable (see tasks `build-galasabld-executable`, `build-galasabld-ibm-executable`, and `build-openapi2beans-executable`)
- [x] Push the Docker images to the GitHub Container Registry if doing a main workflow, just build if PR
- ~Make downloadable links to each executable available from GitHub packages, like at [this URL](https://development.galasa.dev/main/binary/bld/) (see below)~
- ~Store the executables as downloadable links that can be downloaded from GitHub packages (see below)~
- ~Do a Maven build to wrap the buildutils and openapi2beans executables inside a Maven artefact (similar to how the galasactl executables are wrapped into a Maven artefact in the Isolated build - see [pomGalasactl.xml](https://github.com/galasa-dev/isolated/blob/main/full/pomGalasactl.xml) and the [Task](https://github.com/galasa-dev/automation/blob/main/pipelines/pipelines/isolated/build-branch.yaml#L555))~
- ~Publish the Maven artefact to the GitHub Maven Registry~
- [x] Publish downloadable links to the executables for Main and PR builds available under the actions workflow
- [x] The GitHub actions workflow should be integrated with PRs as well as merges into the main branch, so we see the tekton and github actions build processes side by side
- [x] We gather metrics where we can, so we can discuss it further to see what we need to do next

**Comment by jaydee029** [comment]
@jadecarino can you provide information about the 2nd task `It puts built docker images into the container image store associated with the repository` , to make it more clear.

**Comment by jaydee029** [comment]
Hey @jadecarino some of the docker images fetch the base image from galasa.harbor.dev, i am assuming this needs to be changed right? 
for ex
`FROM harbor.galasa.dev/docker_proxy_cache/library/httpd:2.4.59`

do we use substitutes from docker hub or similar or any specific base image needs to be used ?

**Comment by jadecarino** [comment]
Hi @jaydee029 - for now, this can continue to pull from harbor.galasa.dev. I have opened another [work item here](https://github.com/galasa-dev/projectmanagement/issues/1888) to create a Docker proxy cache in GHCR which we will eventually use instead of Harbor's Docker proxy cache, but this work item isn't scheduled into the iteration yet. 
For now, continue to pull from harbor.galasa.dev, and when the issue I just mentioned is complete, we will update all of the `FROM` tags throughout the Dockerfiles.

**Comment by techcobweb** [comment]
I have made some progress in my forked repository [here](https://github.com/jaydee029/buildutils) , since I didn't raise a draft PR I have written about the changes in detail [here](https://github.com/jaydee029/LFX-progress) .

**Comment by jaydee029** [comment]
##See galasa-dev/buildutils#53 
- [x] Copy all Dockerfiles used in the buildutils pipelines into the 'buildutils' repository into a dockerfiles subdirectory (don't move them as we don't want to disturb the Tekton builds)
- [x] Use GitHub actions to build the 'buildutils' repository similar to the existing Tekton pipelines but adapt where necessary
- [x] Build the galasabld and openapi2beans binaries into Docker images that contain the executable (see tasks build-galasabld-executable, build-galasabld-ibm-executable, and build-openapi2beans-executable)
 - [x] Push the Docker images to the GitHub Container Registry if doing a main workflow, just build if PR
 - [x] Investigate how to make downloadable links to each executable available from GitHub packages, like at [this URL](https://development.galasa.dev/main/binary/bld/) (see below)
 - [ ] Store the executables as downloadable links that can be downloaded from GitHub packages (see below)
 - [ ] Do a Maven build to wrap the buildutils and openapi2beans executables inside a Maven artefact (similar to how the galasactl executables are wrapped into a Maven artefact in the Isolated build - see [pomGalasactl.xml](https://github.com/galasa-dev/isolated/blob/main/full/pomGalasactl.xml) and the [Task](https://github.com/galasa-dev/automation/blob/main/pipelines/pipelines/isolated/build-branch.yaml#L555))
 - [ ] Publish the Maven artefact to the GitHub Maven Registry
 - [x] The GitHub actions workflow should be integrated with PRs as well as merges into the main branch, so we see the tekton and github actions build processes side by side
- [ ] We gather metrics where we can, so we can discuss it further to see what we need to do next
