### ISSUE TITLE
Helm: helm chart sets up a stream to refer to a default test repo

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1721]
# Story
As an installer of a Galasa ecosystem, I want the helm chart to create a stream from which an acceptance test can be loaded and run, so that I can verify that the ecosystem is able to run tests properly as a post-install step in the instructions.

# Background
- We need an acceptance test which can run within the ecosystem, available on maven central.
- When the helm chart runs, it waits for the ecosystem to start, then creates an "acceptance-test' stream which refers to maven central.
- What minimal test would we publish and build ?

# Tasks
- [ ] Helm chart accepts values on an acceptance test stream
- [ ] These values are used to create a stream using the galasactl resources interface ?
- [ ] Instructions need adding to the galasa-dev site so that people can run a test against that ecosystem to prove that it is working ?
  - [ ]  References the instructions on how to get an authentication key and set the galasactl tool up
  - [ ]  Includes syntax of how to run the test against the ecosystem
