### ISSUE TITLE
REST: secure namespace properties should always start with a prefix of credentials

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1722]
# Story
As a galasa admin person trying to set a credential into the ecosystem, if I mis-spell the property being set, omitting the credentials prefix, 
The servlet should always insist that any properties set into the secure namespace have a prefix of credentials, so that all the code which retrieves credentials can find things.

# Tasks
 - [ ] Add checks to limit what a valid credential is when values are set into the secure namespace
   - [ ] The error has a unique code associated with it.
 - [ ] Document in galasa-dev this restriction
 - [ ] Document in openapi.yaml this restriction
 - [ ] Document in the help for galasactl this restriction
