### ISSUE TITLE
3270 images need to be rendered for local and remote runs

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1725]
# Story
As a galasactl user, I want to see image files on disk during and after a local test run of galasactl, and also after downloading test artifacts from an ecosystem, so that I can view the image files locally with regular image viewing tools.

# Background
We have a clutch of related problems which need a mention:

- Prority: Medium
  [Helm: limit couchdb revision history to 10 for all installs by default#1727](https://github.com/galasa-dev/projectmanagement/issues/1727)
- Priority: High
  [3270 images need to be rendered for local and remote runs#1725](https://github.com/galasa-dev/projectmanagement/issues/1725)
- Priority: Low
  [stop storing binary attachments in couchdb](https://github.com/galasa-dev/projectmanagement/issues/1726)
- Priority: High 
  [Helm: limit couchdb revision history to 10 for all installs by default](https://github.com/galasa-dev/projectmanagement/issues/1727)

This story addresses one part of the overall problem.

We will render 3270 images on the client side, rather than generate them on the server-side.

We will create rendering code in Golang, and use it within the galasactl program.

This has the advantage of not creating any more workload on the server at all.

When the client runs a test locally, every n seconds (30 secs?) a separate thread will scan the artifacts directory looking for .gz files containing .json files. Each json file will be rendered into an images folder.

When the client runs a test on the ecosystem, the .gz files containing .json files get created.
When the galasactl client downloads the files, it does the same operation, looking for .gz files in the downloaded artifacts, and converting the .json files to png image files in the images folder.

So the output of the download will look like this:
```
Downloaded xxx artifacts
Rendered yyy 3270 image files.
```
or similar.

Separate to that, we will create a separate command within galasactl to expand a folder containing .gc/.json files into image files..

This approach has several effects:
- It doesn't create any more data on the server, less to download, less to store in couchdb.
- It separates the issues of that couchdb suffers in its' revision history from the issue of rendering 3270 images and having them available.
- 3270 images are needed to claim parity with eclipse, to hasten the removal of eclipse plugins, solving the many-small-attachment-files problem is something that can be deferred until later.
- We can remove eclipse plugin functionality easier if we just tackle this issue rather than solve all the others.

# Tasks
- [x] golang code to take a json file and marshall it into objects
- [x] golang code to render objects into a png image and store the file
- [x] golang code does nothing if the json is already rendered
- [x] golang code to walk through a .gz file processing each .json file in turn
- [x] golang code to recursively descend from a root folder finding .gz files to process
- [x] galasactl code to run the above every 30 seconds when running local tests
- [x] galasactl code to run after files have been downloaded from the ecosystem
- ~~Enhance the ecosystem-test to make sure the files appear~~ Not doing.
- ~~Enhance the local test script to make sure the files appear~~ Not doing
- ~~Docs in readme~~ No changes needed.
- ~~Docs in galasa-dev~~ No changes needed.
