### ISSUE TITLE
CLI: user can revoke an access token using galasactl

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1729]
## Story
As a galasactl command-line user who had their laptop stolen, I want to log into the Galasa ecosystem, and revoke the personal access token I had associated with that laptop, so my ecosystem and systems under test remain secure, using the command-line galasactl tool

## Background
Assumption: User can list the access tokens in the table showing all the access tokens for a particular user.

New command 
```
galasactl auth tokens delete --tokenid xxxx
```

Note: It should be possible to revoke the token which this instance of the galasactl tool is using. If you do this, your JWT will still be valid for use for a few hours.

If you know the token id, you can revoke it, regardless of who you are.
This will be the case until we have admin vs. normal user controls in place.

The user can list tokens already using `galasactl auth tokens get`. See story #1805 

REST api:
```
DELETE /auth/tokens/{tokenid}
```

## Tasks
- [x] new REST endpoint, in openapi.yaml
- [x] REST service relays the revoke command to Dex.
- [x] REST removes the document from couchdb
- [x] galasactl tool coding
- [x] test on ecosystem1 and prod1 (github+oidc)
- [x] demo that a token can be listed and revoked
- [x] galasadev.docs
- [x] cli readme docs
