### ISSUE TITLE
Web UI displays the 'name' of the ecosystem in the header banner

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1733]
# Story 
As a galasa web UI user I want to be able to see the name of the ecosystem on the header banner, so I can tell my UI windows apart when dealing with multiple galasa ecosystems.

# Background
We could supply the name of the ecosystem via a helm chart setting ? and that can feed the value into the web UI deployment ?

# Tasks
- [x] Helm chart has a value which is set
- [x] Helm chart supplies the value to the web UI
- [x] Web UI picks up the value and shows it on the UI panel.
- [x] Testing
- [x] Docs within the helm chart values file itself
- ~~Docs within galasa-dev~~ - not required
