### ISSUE TITLE
Update the certs in dkrengine01

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1736]
## Background

The DockerManager integration test is failing as the dkrengine01 is attempting to contact harbor-cicsk8s but does not have the up to date IBM intermediate certificate.

## Tasks
- [x] Ask James Davies to assign access so I can ssh into the VM
- [x] Create CSR request
- [x] Get manager approval
- [x] Upload the certificate to the VM
- [x] Replace old certs 
- [ ] ~(Maybe?) Upload IBM Inter and root certs~
- [ ] ~Rerun the DockerManager integration test to confirm the engine can contact harbor-cicsk8s and the test passes~

Update: I have instead updated the DockerLocalJava11Ubuntu test to pull the needed image from harbor.galasa.dev to remove the dependency on harbor-cicsk8s completely. Closing this item as no longer needed.

**Comment by jadecarino** [comment]
Blocked as unable to run tests in the ecosystem so cannot run the Docker test to check if this worked.
