### ISSUE TITLE
Create Docker proxy in harbor.galasa.dev to reduce number of pulls from docker.io

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1738]
## Story
As a Galasa developer, I want to be able to pull Docker images from a proxy in our Harbor, so that we do not hit the Docker 6-hourly pull limit and have our builds blocked.

## Background
Release 0.31.0 was slightly held up due to a bug with the new GH Monitor setting off multiple builds coupled with Synk security scanning opening multiple PRs which then built. This meant the Docker pull limit was reached as most Docker builds that occur in the automation pipelines pull straight from docker.io.

The best way to do this is via a docker proxy cache...
https://goharbor.io/docs/2.1.0/administration/configure-proxy-cache/

You shouldn't need to manually pull and push images into harbor, just configure harbor to point to docker hub, and change the docker files/pipeline tasks to draw from there rather than docker hub...

## Tasks
- [x] Create proxy in harbor.galasa.dev
- ~~Place all needed images in there~~ (images are pulled through via the proxy cache).
- [x] Replace references to docker.io with the new proxy
- [x] Change the docker files to draw from the harbor proxy
  - [x] start with the automation pipeline and any Dockerfiles that uses, and make sure it works then - the ones which explicitly refer to docker.io
  - [x] move on to the other pipelines after.

**Comment by KirbyKatcher** [comment]
## Cause
`ERROR: toomanyrequests: Too Many Requests.`
```
The rate limits of 100 container image requests per six hours for anonymous usage, and 200 container image requests per six hours for free Docker accounts are now in effect. Image requests exceeding these limits will be denied until the six hour window elapses.
```
source : <https://www.docker.com/increase-rate-limits/>

**Comment by techcobweb** [comment]
This looks like something fiona can tackle?
