### ISSUE TITLE
Remediate Critical vulnerabilities in the Maven repository

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1741]
## Story 
As a Galasa user, I want to ensure that the Galasa Maven plug-in I am using have as little Critical vulnerabilities as possible, so that I can ensure my data protection, privacy, system integrity and compliance requirements are met.

## Background
Using a Snyk security report, I have found that the Galasa Maven plug-in repository includes 1 Critical vulnerability through the maven-core dependency. This can be fixed by changing the dependency to the maven-shared-utils dependency.

## Tasks
Based on the report, the resolution I propose is:
- [x] Update the org.apache.maven:maven-core v3.6.2 dependency in the pom.xml to the org.apache.maven.shared:maven-shared-utils v3.3.3 - Eamonn: the latest version of maven-shared-utils is 3.4.2, so will try that instead of 3.3.3.
- [x] Ensure the Galasa Maven plug-in builds successfully following this update.
- [x] Run tests to confirm the Galasa Maven plug-in functionality is unaffected.
- [x] Regenerate the Snyk report to confirm the vulnerability has been removed from the code base.
