### ISSUE TITLE
Release: Bump to new version step for galasa properties can be automated with galasactl

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1742]
## Story 

As a Galasa Developer when I am doing a release of Galasa, I would like to be able to trigger a script to update properties on the production ecosystem, so that the release process can be more accurate and easier to complete.

## Background 

Currently to complete the release the changes are done via a repository on the internal GitHub instance. This is very manual and requires access to the repository.

## Tasks
- [x] Create a properties.yml file containing the properties mentioned in the release documentation
- [x] Feed the tokens into the script using secrets
- [x] Create a shell script to 
  - [x] take a parameter for the version value and update the property values in properties.yml
  - [x] run the `galasactl resources update -f properties.yml`
