### ISSUE TITLE
Add testing for the JMeter Manager and include in integration test suite.

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1743]
## Story
As a Galasa user, I want the JMeter Manager to be adequately tested, so that if I try to use it, I know it works!

## Background
When investigating in the Managers repo for issue #1739, I found a Dockerfile that I believe to be unused currently, so I have deleted it as it contained a vulnerability. But I believe the Dockerfile was in the past used by someone to locally build an image that was called galasa-jmeter (this is referred to in the JMeterManageImpl) and then they pushed to a remote registry, but this image is nowhere to be found in the image registries we currently use. 

I then searched where this method from the Manager was used, and it's not used anywhere. This means the JMeterManagerIVT has not got sufficient coverage for the Manager. The IVT has also not been running anyway as it's not part of our integration testing suite. We need to implement testing for the JMeter Manager as it is marked as 'Beta' on the galasa.dev website.

## Tasks
- [ ] Understand the JMeterManager 
- [ ] Improve and refactor where possible
- [ ] Improve upon the JMeterManagerIVT to achieve more coverage
- [ ] Run the JMeterManagerIVT locally and debug any issues that arise (I suspect a few)
- [ ] Add integration test for the JMeterManager to call the JMeterManagerIVT into our test suite
