### ISSUE TITLE
Single Authentication token rather than 3 parts.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1744]
# Story
As a galasactl user I want an access token to be a single value, rather than the three values I have to cope with today, to make it easier to switch between ecosystems and easier to supply secrets to the container.

# Background

Currently we have this:
```
# GALASA_ACCESS_TOKEN="my-access-token"
# GALASA_CLIENT_ID="my-client-id"
# GALASA_SECRET="my-secret"
```

Change to do this, with `:` separators:
```
GALASA_TOKEN="{GALASA_ACCESS_TOKEN}:${GALASA_CLIENT_ID}:${GALASA_SECRET}"
```

So for example:
```
GALASA_ACCESS_TOKEN=Mm9pc2N5cmozeWY1NzNasdjasjkaskjadskjasdsdGwzbGZ2ZWZzNnN5NmVzZ3IyeWN6
GALASA_CLIENT_ID=lyasdjasjkaskjadskja3
GALASA_SECRET=c2FqaG5tdzJhZGYzN3ByanF5cmpya2licHQ2dzJkZHRwNmE3easdjasjkaskjadskja=
```

Would become 
```
GALASA_TOKEN=Mm9pc2N5cmozeWY1NzNasdjasjkaskjadskjasdsdGwzbGZ2ZWZzNnN5NmVzZ3IyeWN6:lyasdjasjkaskjadskja3:c2FqaG5tdzJhZGYzN3ByanF5cmpya2licHQ2dzJkZHRwNmE3easdjasjkaskjadskja=
```
Q: ... which is very long. But I think that's OK. What do others think ?

Q: Do we make the galasactl backwards compatable so it can still work with the old variable names ?

Eamon thinks if we upgrade Dex, then we can get rid of the secret value.

# Tasks
- [x] Check that the changes work on ecosystem1

### Auth servlet
- [x] Remove the client secret from the payload when exchanging a refresh token for a JWT
- [x] Update the Dex gRPC API client to use the latest version of Dex's API
- [x] Make the auth servlet call Dex's GetClient gRPC method to get a given client's secret

### Web UI
- [x] UI panel to show the single token property
- [x] Remove client secrets from being sent in requests for personal access tokens 

### CLI
- [x] CLI to read a single value from the file where properties can live
- [x] CLI to accept a single value from the environment variable for the token
- [x] CLI updates to the template which creates the tokens.

### Documentation
- [x] Docs updates

**Comment by techcobweb** [comment]
Sanity test on ecosystem 1 just to make sure it works.

**Comment by eamansour** [comment]
Changes work on ecosystem1 - closing.
