### ISSUE TITLE
IVT tests to run against an authenticed server

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1747]
# Stories
As a person maintaining regular test runs against galasa to check that galasa isn't broken, I want to have the tests use an authentication token, so when we change the server to make tokens mandatory the tests won't break.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

# Background
Assumes :
- Prod1 supports authentication
- jars for each test are in the container
- pipeline passes the name of the test it wants to run

# Tasks
- [x] When we build inttests, we need to publish test catalogs to prod1 instead of prod
- [x] When the CLI builds are launched, run ecosystem tests on prod1 
- [x] When inttests are launched, do so using prod1 instead of prod 
- [x] Inttests should use a token from prod1's dex/oauth, tied to Eamonn's account.
- [x] Check the logs to make sure it is actually running in authenticated mode
- [x] Move the regression-test cron job to the same namespace that prod1 runs on
  - Awaiting permissions on the galasa-dev namespace, temporarily moved to the galasa-build namespace to keep the regression tests running
