### ISSUE TITLE
Maven and Gradle plugins to talk to Galasa server using authentication tokens.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1748]
# Story
As a galasactl developer maintaining maven and gradle tools, I want to have those tools support authentication over the REST interface whenever they talk to the server.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

# Background
The maven and gradle tools both contact the server to push a test catalog to a stream.

If the server has authentication turned on, how do they do this ?

We will need to understand whether they call rest calls only or contact etc directly...

We also need to design how the galasa auth token will be accepted by the tool/configured/passed/set up.

# Tasks
- [x] For the maven tool:
  - [x] Understand the tool how it contacts the server
  - [x] Understand how plugins normally get auth tokens
  - [x] Describe how the galasa plugins need to change in a future story

- [x] - [ ] For the gradle tool:
  - [x] Understand the tool how it contacts the server
  - [x] Understand how plugins normally get auth tokens
  - [x] Describe how the galasa plugins need to change in a future story

- [x] Add a 'common' layer into the gradle build which adds authentication functionality.
- [x] Use that common layer in gradle
- [x] Use that common layer in maven

- [x] Better documentation in gradle readme
- [x] Better documentation in maven readme
- [ ]
