### ISSUE TITLE
Update the build process for inttests that use SEM to pull from internal artefact

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1749]
Must be completed after #1269 

## Story
As a Galasa developer, I want the integration tests that use CICS Regions to pull from the new internally stored SEM Manager, so that they are able to keeping running using independent provisioned CICS Regions so we don't see clashes of data in test systems.

## Tasks
- [x] Identify all tests that use SemTopology 
- [x] Move these into a separate parent project in the integratedtests repo so they aren't included in the current build process
- [x] Create new build process for the tests on Tom's system that draw on the new internally stored SEM Manager
- [x] Ensure these tests are deployed to the testcatalog
- [x] Run the tests from the galasa-prod system as normal to test everything works
- [x] Add the new test stream into the regression test cronjob
- [x] External SEM Manager can then be removed
