### ISSUE TITLE
CLI: Gherkin support

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1750]
# Story
As a galasa testcase developer I want to be able to run a gherkin test from the CLI, so that the test runs locally, and I can see the results of the test.

# Background
Some customers use the gherkin feature in eclipse.

To replace eclipse, we have to support that feature also from the `galasactl` command.

The boot loader accepts a different/extra command `--gherkin <featureFileUrl>` such that the URL refers to a feature file. 

The bootstrap properties supplied by the eclipse plugin to support this function are :
```
--bootstrap ...
--overrides ...
--localmaven ...
--remotemaven ...
--obr ...
--trace - optional stand-alone flag.
--gherkin URL of the file
```

Do we need a new command completely ? or do we piggy-back off the `runs submit local` command ?

This story is required if we are to have equivalent function to the eclipse plugins.
So needs implementing before we strip eclipse out.

We know for a fact that one, possibly two external customers are using this productively.

# Tasks
- [x] Figure out an example we can use, store in a test resources folder in the CLI project
- [x] Get the simple example working inside eclipse
- [x] Get the simple example working using the java -jar syntax
- [x] Decide on command syntax for the galasactl command
- [x] CLI to collect extra parameter(s) from user when invoking a test
- [x] CLI passes them to the local java runner
- [x] Build-locally to copy the simple exampl, build it and run it, and check output/exit code...
- [x] Tests
- [x] Docs in readme
- [ ] Docs in galasa-dev

**Comment by techcobweb** [comment]
See https://github.com/galasa-dev/cli/pull/209

**Comment by KirbyKatcher** [comment]
Originally tested with simBank:

```cucumber
Feature: simBankGherkin
  Scenario: Is SimBank Available
    
    Given The Simbank is available
    When I navigate to SimBank
    Then I should see the main screen
```

Sample Gherkin to use Core manager to test Gherkin without external dependencies:

```cucumber
Feature: GherkinLog
  Scenario: Log Example Statement
    
    THEN Write to log "This is a log statement"
```

**Comment by KirbyKatcher** [comment]
java command example is:
```shell
java -jar ~/.m2/repository/dev/galasa/galasa-boot/0.31.0/galasa-boot-0.31.0.jar --bootstrap file:///Users/savvas/.galasa/bootstrap.properties --overrides file:///var/folders/_g/q1s0v0yn1z91yj69wqq4yq_r0000gn/T/galasa_eclipse_cache_2655611857600808901/galasaoverrides10587067904716611997.properties --localmaven file:/Users/savvas/.m2/repository/ --remotemaven https://development.galasa.dev/release/maven-repo/obr --obr file:/Users/savvas/eclipse-workspace/.metadata/.plugins/dev.galasa.eclipse/workspace.obr --obr mvn:dev.galasa/dev.galasa.uber.obr/LATEST/obr --gherkin file:/Users/savvas/eclipse-workspace/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/simBankGherkin.feature 
```

**Comment by KirbyKatcher** [comment]
Command should be:

```shell
galasactl runs submit local 
--bootstrap ...
--overrides ...
--localmaven ...
--remotemaven ...
--obr ...
--trace - (optional)
--gherkin URL of the file
```

This should use the same mechanism as the java `--class` equivalent but with a different structure

**Comment by KirbyKatcher** [comment]
--gherkin currently does not support multiple files

```shell
Caused by: java.io.FileNotFoundException: /Users/savvas/eclipse-workspace/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/simBankGherkin.feature,file:/Users/savvas/eclipse-workspace/dev.galasa.simbank.tests/src/main/java/dev/galasa/simbank/tests/GherkinLog.feature (No such file or directory)
```
