### ISSUE TITLE
Testing IDE behaviour with YAML configuration files and schemas

### ISSUE THREAD

**Issue by gohilpr** [galasa-dev/projectmanagement#1752]
## Story
As a software tester using an IDE to create YAML configuration input, I want test automation to simulate the client experience of using an IDE (plus extensions) to create YAML files against known JSON schemas, so that I can be confident that the IDE experience has not degraded and what is produced is still correct.

## Background
In our project we used a well known IDE and extensions for YAML support in order to create YAML configuration files. This would be our clients expected actions. We wanted to check that the files produced were validated against known provided schemas.

In some cases, we found (very late) that the behavour had regressed and we had to pre-req old versions of the IDE and extensions whilst fixes were made available. This was not sustainable, especially after the product released and we want our clients to stay on current supported software levels.

What we found was that the extensions and IDE base function behaviour changed rapidly with updates. We were manually re-checking the behaviour of our expected client's YAML creation interactions. This was not easy to write test automation for.
This covered
- basic text input
- handling of spaces and tabs
- auto complete/prediction of YAML structures from a schema
- schema validation
- syntax checking from a schema, and valid yaml syntax
- error scenarios and IDE error decorators/logs

We would like increased support in the test frameworks to support testing within IDEs for schema and YAML files. And to be able to create robust tests to ensure our schemas are consistently behaving as we expect them to.

We were using Visual Studio Code, with the YAML Langauge Support by Red Hat extension.

## Tasks
- [ ] to have a galasa manager that is able to specify an IDE configuration plus extension for validating YAML files against known JSON schemas
- [ ] to be able to point to schema files to validate input by
- [ ] To test a range of YAML inputs YAML files
- [ ] To validate the YAML files against schema
- [ ] To know when the validation is successful or contains error
- [ ] When an expected error occurs, to be able to match against the expected error output
- [ ] to simulate user inputs such as auto complete / command completion and validate the IDE behavour

**Comment by techcobweb** [comment]
Sounds like you want to do something similar to this: https://developers.redhat.com/blog/2019/11/18/new-tools-for-automating-end-to-end-tests-for-vs-code-extensions#

But have a manager control both the deployment of the vscode + extensions, plus drive the test from Galasa as the central point ?

Sounds a lot of work which we are currently not able to resource from the IBM Galasa team. 

Adding this to the backlog for now.
