### ISSUE TITLE
Automatically generate a client secret value for the webui in the helm chart

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1757]
## Story
As a Galasa user installing an ecosystem with the helm chart, I want the helm chart to automatically generate a client secret value for the webui in the Dex configuration, so that I do not need to worry about managing an additional secret myself.

## Background
Currently, a user installing an ecosystem will need to update the `secret` value for the `galasa-webui` client in the `staticClients` section. Automatically generating a client secret when the helm chart is installed would simplify the helm installation process.

This could be further simplified by removing the need to configure the webui client in the `staticClients` section and have the webui configured automatically on installation.

## Tasks
- [x] Look into using a helm function to automatically generate a client secret (e.g. `randAlphaNum 32` to generate a random 32-length cryptographically secure alphanumeric string)
- [x] Update the helm chart's `values.yaml` file to automatically generate the `galasa-ui` client
- [x] Documentation updates to remove instructions on explicitly setting the `secret` value and client details
