### ISSUE TITLE
Code scanning with 'Detect Secrets'

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1758]
## Story 
As a Galasa developer, I want to ensure that I have not checked in any secrets into source code, to achieve ITSS compliance and avoid secrets being leaked. 

## Background
This is for DfG as detect secrets is an IBM tool.

## Tasks
- [ ] Create new pipeline that clones all github repos that are used in DfG (main build chain from wrapping onwards)
- [ ] Run the detect-secrets tool on each individual repo after it has been cloned. The Detect Secrets container image can be pulled from the IBM Cloud Container Registry (ICR). Create new Task which uses this image.
- [ ] Inside the Task run the tool. Steps can be found: https://w3.ibm.com/w3publisher/detect-secrets which must be translated into what you'd execute in an already running container. `docker run` is not correct.
- [ ] Publish the output in the pipeline's log and also publish to a location (TBC)
- [ ] Continue (don't fail) the pipeline if the tool finds checked in secrets as we want to scan all repos.
- [ ] Create a CronJob to run this pipeline regularly.
