### ISSUE TITLE
Develop Producer code to publish events to Kafka

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1762]
## Background
A Kafka Producer will be created and will publish events to Kafka topics.

## Tasks
- [ ] Create EventProducer class inside the Kafka extension 
- [ ] The EventProducer should have a Constructor, a sendEvent method and a close method
- [ ] Create classes to absorb CPS properties into the Producer (properties will be needed for to contact the Kafka cluster, point to the correct serializer, etc...)
- [ ] Unit tests

**Comment by jadecarino** [comment]
Closing as this has been integrated into a better story.
