### ISSUE TITLE
Display Galasa events from Kafka topics in a client

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1763]
## Story
As a Galasa user, I want to view Galasa events being published to topics in a user-friendly UI, so that I can visualise trends and information easier.

## Background
This story includes finding an OTS client or developing a noddy one to show events coming in from Kafka topics and visualising them in an informative way.

## Tasks
- [ ] Research off the shelf clients that can consume from Kafka topics and visualise/display the events appropriately
- [ ] If one isn't available, develop a POC
- [ ] Connect the client to Kafka topics that Galasa is publishing to
