### ISSUE TITLE
Publish test lifecycle events to Kafka topic directly from the Framework

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1767]
## Story
As a Galasa user, I want to read events about a test's lifecycle from a Kafka topic, so that I can be informed immediately about a test's progression.

## Background
This story includes creating the first proof of concept to prove that it is possible to publish events directly from Galasa to a Kafka topic so that interested parties could consume this information.

## Tasks
- [x] Create feature flag so that event production code is only ran when the flag is set to true
- [x] Create TestRunLifecycleStatusChangeEvent to represent the Event information about a test lifecycle stage changing
- [x] Create EventProducer class to publish the Event to a topic
- [x] Call the EventProducer from the TestRunner when a test's status changes
- [x] Hard code the Kafka cluster configuration for this issue
- [x] Test changes with locally built test with `galasactl runs submit local`
- [x] Verify events reached the EventStreams instance with their consumer UI

**Comment by jadecarino** [comment]
I believe I need to create an OSGi wrapper for kafka-clients before I can proceed. The project builds fine with my changes however when I run a Galasa test, at runtime, the KakfaProducer class can't be found. It needs to be in OSGi bundle form.

**Comment by jadecarino** [comment]
I removed the KafkaProducer initialisation code from the Framework into a Main.java to run in debug mode to diagnose the NullPointerException I was finding in the KafkaProducer class. I diagnosed the NullPointer, fixed it, and reran the code in Main.java. Confirmed with the EventStreams instance in IBM Cloud that the event were being received.

When I moved the exact same code back into the Framework, the NullPointer reappeared. Next steps are to do some refactoring and add more error handling to understand why the KafkaProducer initialisation worked in isolation but not back in the Framework. However, was good to see proof that events coming from a self-coded Kafka Producer could send events to our EventStreams instance.
