### ISSUE TITLE
Publish test lifecycle events to Kafka topic from new Extension

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1768]
## Story
As a Galasa user, I want to read events about a test's lifecycle from a Kafka topic, so that I can be informed immediately about a test's progression.

## Background
We have confirmed that we can publish test lifecycle events to a Kafka topic directly from the Framework.
The Framework implementation of the Events Service has been created which registers with the OSGi whiteboard pattern (#1892 )
This story encompasses stripping out all event-related code from the Framework and placing it into a new Galasa Extension, the Kafka Events Service, so that it can be published from the Extension and turned on and off as required by the user.

## Tasks
- [x] Ensure feature flag only runs these pieces of code when set to true
- [x] Create new Galasa Extension project for the events plugin
- [x] Create gradle file and bundle file with required dependencies
- [x] Add to build-locally.sh script to allow local building during development
- [x] Remove Event POJO and EventProducer code from the Framework and place into a new Galasa Extension
- [x] Consume GALASA_EVENT_STREAMS_TOKEN from environment so it isn't delivered in source code
- [x] Create Service and Registration classes in Extensions that implement the plugin
- [x] Keep hard coded values to connect the Extension to the Kafka cluster and topics
- [x] Add to release.yaml to release the Extension as per the release processes 
- [x] Unit test as required

Testing this story requires story #1893 is completed.

End-to-end testing:
- [x] Fix defect with authentication https://github.com/galasa-dev/projectmanagement/issues/1914
- [x] Fix defect with transactional IDs https://github.com/galasa-dev/projectmanagement/issues/1915
