### ISSUE TITLE
Infrastructure: Replace Secrets with ExternalSecrets

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1772]
## Story
As a Galasa developer, I want all pieces of confidential information used in builds or infrastructure to be held in an ExternalSecret not a Secret, so that only the external secret source needs to be updated with new values if the confidential information is updated.

## Background
We have some Secrets in our Kubernetes cluster which were made directly using a `kubectl create secret` command or similar, rather than being implicitly created by an ExternalSecret, which we should replace with ExternalSecrets, that in turn create Secrets, but are easier to maintain. 

With just a Secret, if the secret information like a password or token expires and needs rotating, it's not as simple as just updating the external secret source (Vault or Secrets Manager) and the Secret automatically being updated. You'd need to find the Secret, update it with a `kubectl command`, etc. Also being a Secret with no YAML definition file stored anywhere means there is no visibility for these Secrets so we could forget they exist and for what.

Format of an ExternalSecret:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:  
  name: {EXTERNAL SECRET NAME}
  namespace: {NAMESPACE}
  annotations:
    {OPTIONAL ANNOTATION IF BEING USED FOR BASIC AUTHENTICATION}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: {EXTERNAL SOURCE VAULT OR SECRETS MANAGER}
    kind: SecretStore
  target:
    name: {TARGET SECRET NAME WHICH WILL BE CREATED BY THE CREATION OF THE EXTERNAL SECRET}
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
          
  data:
  - secretKey: username
    remoteRef:
      property: username
      key: {REFERENCE TO THE SECRET IN THE EXTERNAL SOURCE VAULT (NAME) OR SECRETS MANAGER (ID STRING)}
  - secretKey: password
    remoteRef:
      property: password
      key: {REFERENCE TO THE SECRET IN THE EXTERNAL SOURCE VAULT (NAME) OR SECRETS MANAGER (ID STRING)}
```

## Steps 
- If the Secret is used in the build pipelines (and therefore runs on IBM internal systems), it's data needs to be stored in Vault. Create an entry in Vault with the confidential information replicating the format of the secret (username and password, token, etc)
- If the Secret is used for the external sites (ArgoCD, Harbor, etc), it's data needs to be stored in Secrets Manager. Create an entry in Secrets Manager with the confidential information replicating the format of the secret (username and password, token, etc)
- Create ExternalSecret definitions for each Secret, pulling from Vault or pulling from Secrets Manager. Place in the correct directory for each respective type (automation/infrastructure/cicsk8s/galasa-build/external-secrets or automation/infrastructure/galasa-plan-b-lon02/...)
- The 'target' Secret for the ExternalSecret should match the name of the original Secret so it just updates it
- Once merged, create the new ExternalSecrets by syncing the ArgoCD applications that manage them

## Tasks
- [x] Create ES for slack-webhook
- [x] Create ES for argocd-token
- [x] Create ES for icr-api-key
- [x] Delete gpg-passphrase
- [x] Delete planb-harbor-creds
- [x] Remove planb-harbor-creds from galasa-build-bot's spec
- [x] Delete planb-argocd-token

**Comment by techcobweb** [comment]
@jadecarino Hope this is OK. Does it make sense for you to tackle this given Fiona is out for 3 weeks ?

**Comment by jadecarino** [comment]
@techcobweb Yes makes sense as I know what it requires, happy to complete this.

**Comment by jadecarino** [comment]
All Secrets that need to be updated periodically due to expiration etc, are not created as part of an installation process like Helm, and are not a service account token, have now had an ExternalSecret created for them. I have also completed some clean up of unused secrets.
