### ISSUE TITLE
CLI: runs cancel should set run status and result

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1775]
## Story
As a Galasa user, I want tests that I cancel with `galasactl runs cancel` to be set to finished with a result of cancelled, so that it does not appear as active in `runs get` and it is obvious the test was cancelled if you look at the test structure document.

## Background
Currently, when you invoke `galasactl runs cancel`, it does a PUT request to the /ras/runs/{runId} path with this payload:
```
{ 
  status: finished
  result: cancelled
}  
```
This payload isn't actually used though. As we were just providing parity with the Eclipse plug-in in issue #1685 , we did not take that payload and apply it to the run's test structure. This means that all that happens is the DSS entries for this run are deleted, and the run is abandoned, but the run will still show as 'active' and have no result if you do a `galasactl runs get`.

## Tasks
- [x] Update the Results enum to add Cancelled as a result
- [x] ~In the servlet which cancels the run, take the payload from the request and apply it to the run's test structure, the status should be finished and the result should be cancelled~ Tried and does not work as in the CouchdbRasStore an exception is thrown saying "Not a run".
- [x] ~Update the unit tests for the servlet if necessary / write additional tests that check the run's final state is finished and cancelled~ Done but commented out as the implementation isn't finished, these would fail.
- [x] ~Update the CLI integration test script (run-tests.sh)~ Done but the function in the test script is commented out as above it would fail as the implementation is not finished.
- [ ] Figure out how to apply the status of "finished" and result of "Cancelled" to the run's test structure
- [ ] Figure out how to then tell the K8s controller to shut down the Pod for this run
- [ ] Update the docs to include the Cancelled result

**Comment by techcobweb** [comment]
Great. Getting much better at writing stories.

**Comment by jadecarino** [comment]
Putting this item on the backlog as I need to prioritise Kafka stories as I approach the deadline. I have pushed my half finished changes/experiments to branch "iss1775".

Latest with this story:
- Tried to get the run test structure, update the status and result from the payload, and call `ras.updateTestStructure()`. Tried this before and after the call to `IFrameworkRuns.delete()` and neither works as the `updateTestStructure()` method in `CouchdbRasStore` throws the "Not a run" exception on line 228. Not sure why the run object in `CouchdbRasStore` is showing as null at that point. 
- Did some investigation into if updating the `dss.framework.run.C123.status` property during a run would stop the run and it does not.
- Did some investigation into the Kubernetes controller and how a run gets cancelled using the `IFrameworkRuns.delete() method` - the RunPoll periodically calls `IFrameworkRun.getRun()` and if no DSS properties are returned, it shuts down the Pod.

I think next place to go with this story is:
1. Call the new `cancel()` method instead of `delete()` to cancel a run. This will set in the DSS the runs status to finished and result to Cancelled.
2. The RunPoll will then call the new lines in the `getRun()` method that checks if the DSS status for the run is Cancelled, and if so, it will return null causing the Pod to be shut down. 

I'm unsure with this process though if the TestRunner will have picked up the status and result from the DSS entries, and had time to update the test structure in RAS, before the Pod is shut down. Unfortunately, we are unable to test this other than just trial and error delivering changes, as we can't instantiate a Pod locally, hence why this story is quite time consuming.
