### ISSUE TITLE
Releasing the ecosystem Helm chart isn't included in the release process

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1777]
## Story
As a Galasa user, I want the ecosystem Helm chart to be included as part of Galasa's releases, so that I can make use of the latest ecosystem-related features, like authentication, and avoid having to use a development version of the Helm chart to use these features.

## Background
Looking at the released Helm charts (https://github.com/galasa-dev/helm/releases), the last released version is 0.26.0. This means that recent changes to the Helm chart like Dex and the webui haven't been released, which isn't ideal.

The release process documentation at https://github.com/galasa-dev/automation/blob/main/releasePipeline/release.md doesn't mention anything about releasing the ecosystem Helm chart, so this will need updating.

Currently, the ecosystem Helm chart is released via a GitHub Actions workflow whenever changes are pushed to the `released` branch in the helm repository - see https://github.com/galasa-dev/helm/blob/main/.github/workflows/release.yaml.

## Tasks
- [x] Update the Helm release GitHub Actions workflow to run if pushed to the 'prerelease' or 'release' branches
- [x] If the prerelease branch, mark as skip_upload so it doesn't add the release data to the index.yaml, as Releases/Tags can easily be deleted, but more complex deleting it from the index.yaml
- [x] Update the prerelease and release process documentation to check Helm charts released successfully
- [x] Update the prerelease process documentation to delete the Release and Tags that were created
