### ISSUE TITLE
Add docs page for using Galasa offline (Isolated) without Eclipse

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1778]
## Story
As a Galasa user, I want to understand how to use the Galasa isolated zip with the CLI, so that I can continue to use Galasa offline now that the Eclipse plugin has been removed.

## Background
We will be removing the Eclipse plug-in from Galasa soon, but we will still be shipping the Isolated zip so that users with limited network access can still use Galasa offline. 

This page: https://galasa.dev/docs/getting-started/installing-offline#gatsby-focus-wrapper sits within the 'Getting started using Eclipse section', but actually describes in general what the Isolated zip contains at the top, regardless of Eclipse. We need this info still included in the docs after the Eclipse removal and the bottom section 'Installing the Galasa plug-in' should be replaced with instructions for using the Isolated zip and the Galasa CLI binaries that are shipped as part of it.

## Tasks
- [x] Move the page to a different section, probably the Getting started with the CLI section or even a new 'Using Galasa offline'
- [x] Keep all content above 'Installing the Galasa plug-in' but remove references in the page to Eclipse 
- [x] Write new section about how to use the CLI that is shipped in the Isolated zip

**Comment by jadecarino** [comment]
@CaroMac Hi Caroline, having been looking through the docs to do with the Isolated zip, I've opened this story that we should ideally look at before removing the Eclipse plug-in. I can work with you on the third task about writing the new instructions.

**Comment by CaroMac** [comment]
Published in release 32
