### ISSUE TITLE
Prep for GSE UK Virtual 2024

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1779]
## Conference
GSE UK Virtual 2024 is from 23rd-25th April and the 102 track has invited us back to deliver another 'Testing on the mainframe without knowing the mainframe' session.

Eamonn and Louisa to deliver this session together.
Date of session: April 23rd, 3:00pm - 4:00pm.

## Tasks
- [x] Update Powerpoint presentation (use Jade's feedback from GSE 2023 on flow and order)
- [x] Update slide for new features since last GSE
- [x] Remove any refs to Eclipse if there are any 
- [x] Confirm demos to show
- [x] Practice demos
