### ISSUE TITLE
PSIRT: Upgrade commons-compress dependency from v1.21 to v1.26

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1782]
## Background
A PSIRT for DfG has been reported in commons-compress v1.21 which is a dependency throughout Galasa.
We have until 20th June 2024 to remediate it.

## Tasks
- [x] Upgrade dependency of commons-compress to 1.26 throughout Galasa
  - [x] Upgrade dependencies in framework
  - [x] Upgrade dependencies in managers
- [x] Do a DfG release to remove the PSIRT for DfG users

**Comment by techcobweb** [comment]
Waiting for next dfg release then we can close out.

**Comment by jadecarino** [comment]
The PSIRT has been closed and marked as resolved following DfG release 1.0.6
