### ISSUE TITLE
Release version 0.32.0

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1784]
## Story
As a galasa user I want to get the 0.32.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [x] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [x] Identify problems/improvements and raise them for next time
- [x] Add more detail for asking for release approval
- [x] Make sure scan results are clean
