### ISSUE TITLE
Set the level of trace used in run.log to Info/Debug

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1787]
# Story
As a galasa tester runing test cases using the galasactl CLI tool, I want to have less output in the run log, and on the `galasactl --log -` output so that I have less detail cluttering things up.

# Background
- A team of users wants to cut down on the amount of detail they are seeing in the log of the galasactl tool.
- They are aware that omitting the `--log` option entirely stops all the logged data being seen.
- They are aware that the `--progress 1` would show the overall status of each test currently being run in this command, and how far it has got
- They want a level of detail traced such that a global setting can control it. 
- Currently they see DEBUG statements, but these should be hidden.
- If something fails, they may want to run it again with DEBUG level tracing being visible.
- How to control the logging level.

- Note: The galasactl tool reads the run logs, looking for information it needs. Once it has all it needs, could the trace level be set to what this team wants ? 
- Or do we recommend they use the settings in the JVM java logging properties file, in `$JAVA_HOME/conf/logging.properties` ?

Some investigation and documentation/code changes are needed.

# Tasks
- [ ] See if we can persuade logging to pull settings from the standard mechanism in `$JAVA_HOME/conf/logging.properties`.
Does it work ? if not why not ?
- [ ] Consider adding a cps property to control this, which would work remotely and locally, but could be overridden.
- [ ] Implementation
- [ ] Document in the 'running a test' using the CLI section.

**Comment by techcobweb** [comment]
@Jimbo4794 and @hobbit1983 said there is a -debug flag on the java -jar, which we don't have any control over on the CLI.

Not sure how to do this on the ecosysyem either. How does it get passed to the pod ?

**Comment by techcobweb** [comment]
We do support a flag. The `--trace` flag. When enabled, you get more detailed levels of trace in the java code.

**Comment by haripra86** [comment]
Team , I am also in need of such a control where only INFO logs are needed during regural executions.
