### ISSUE TITLE
Wrap kafka-clients package into an OSGi bundle

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1790]
### Story
As a Galasa developer, I want to be able to import and use the Kafka API into Galasa, so I can code self-coded producers and consumers from within Galasa.

### Background
I had made my changes to the framework to produce test lifecycle status changed events directly from the TestRunner. The builds were working fine but at runtime, I was getting NoClassDefFoundErrors for the KafkaProducer class. After researching, I realised kafka-clients is not an OSGi bundle so needs wrapping into one so we can use it.

### Tasks
- [x] Create new project in wrapping for kafka-clients
- [x] Import into the framework
- [x] Build and test locally
- [x] Deliver changes to the wrapping development maven repo

**Comment by jadecarino** [comment]
Leaving in review until I have finished story #1767 which will use this new wrapper and confirm all is okay with it.
