### ISSUE TITLE
Ecosystem CREDS to be accessed via an extension connector to the IBM Cloud Secrets Manager

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1796]
# Story
As an installer of galasa, I want to configure my ecosystem to draw secrets from a remote centralised secrets manager, so that I know the secrets are being stored and organised in a way consistent with my mandated security policies.

# Background
- Currently credentials are stored in an etcd instance, accessed through the `CredentialsStoreService`
- We need to write a new implementation of the CredentialsStoreService which connects to and reads secrets from an external secrets provider.
- The secrets cannot be cached or stored internally by Galasa.

- There are many secret stores we could decide to use. Each cloud vendor has one for example. This story will code the extension which talks to the IBM Cloud Secrets Manager. (The IBM team have access to instances of this, so it will be possible to code and test). Other extensions may be written in future also. A mechanism needs to be provided to configure the ecosystem to draw from a single credentials extension (etcd, IBMCloud, a.n.other). 

- Once the ecosystem is set up, it is assumed to always draw all its' testcase secrets from that location.

- The ectd menanism needs to be left as-is, for those ecosystems which don't have an any external secret store available, though if the IBMCloud secrets manager connector is used, then the etcd service for creds need not be installed/available).

- The IBM cloud secrets manager supports a 'group' or 'namespace' of secrets, which can have different ACSs assigned for each user ID... so if the secrets manager instance is used for many things, all the secrets which Galasa testcases need could be put into the same 'group', and the access token used by Galasa can be restricted to only be able to read from that group.

# Tasks
- [ ] Learn about how to connect to an IBM Cloud Secrets Manager.
  - It has a simple rest interface to retrieve secrets. https://cloud.ibm.com/docs/secrets-manager?topic=secrets-manager-access-secrets&interface=api
- For our ecosystem1 system:
  - [ ] in the secrets manager, name a 'group' of secrets 'ecosystem1'
  - [ ] create a service id/token such that you can use that token to access ONLY that group of secrets
  - [ ] store that access token in the 'ecosystem1' using name 'secrets_manager_access_token'
- [ ] in kubernetes, in the ecosystem1 cluster,  configure an external secret which refers to the 'secrets_manager_access_token' secret.
- [ ] configure the external secret such that it materialises in resolved form as a file '/mnt/secrets-manager/access-token.txt'. i.e: A known place.
- [ ] Write an extension which reads that secret from the 'known location' of '/mnt/secrets-manager/access-token.txt' if present in the pod.
- [ ] Change the way the testcase pods are launched, such that every place which needs secrets has this known secret loaded and available.
- [ ] The extension gets asked for a secret (with a secret-name supplied by the testcase). It uses the REST api and the access-token.txt content to contact the secrets manager and obtain the secret, to be returned to the testcase.

**Comment by techcobweb** [comment]
I had a discussion with @Tom-Slattery today, and ran this outline plan past him, to which he said that it fitted well with the direction he was going to have to take with secrets management in the future.

**Comment by techcobweb** [comment]
[secrets.drawio.zip](https://github.com/galasa-dev/projectmanagement/files/14872641/secrets.drawio.zip)

This is the source for the diagram in the description.

**Comment by techcobweb** [comment]
https://thenewstack.io/meet-openbao-an-open-source-fork-of-hashicorp-vault/
Is very interesting. 

It's a new project based on a 2023 branch of Hashicorp vault. https://github.com/openbao/openbao/tags

If it matures a bit more, we should be using that for secret storage rather than the etcd back-end we currently use.
