### ISSUE TITLE
Helm to deploy prod1 ecosystem on cicsk8s cluster

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1797]
# Story
As a developer running integration tests, I want to be able to authenticate to the prod server, so my server is more secure.

## Epic
Part of this epic: https://github.com/galasa-dev/projectmanagement/issues/1474

# Tasks
- [x] ~Create the prod1 namespace~ we can re-use the galasa-prod namespace since helm-installed resources are self-contained and will not interfere with existing services
- [x] Create pre-req secrets on galasa-prod namespace to prepare for helm deployments or use an argocd app to install the helm chart
- [x] Set up the dex configuration, to plug into the helm chart. Uses oidc and ibm internal auth.
- [x] Deploy to prod1 whenever we currently deploy to prod
- [x] Manage CPS properties for prod1 from a git file.
- [x] Set up stream(s) required to run int tests. 

# Another story to be raised ?
- Switch to use non-eamon access token.
