### ISSUE TITLE
Retire Prod ecostystem

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1798]
# Story
As a galasa ecosystem admin, I want prod removed so we don't have to look after it any more.

# Background
Assumption before this story can be started: Prod1 exists and has all the prod load running.
In which case we don't need prod any longer, and the namespace and any usage of it can be removed.

# Tasks
- [ ] Stop CLI pipeline using prod. It should be using prod1 instead.
- [ ] Don't deploy any test cases to prod
- [ ] Stop re-deploying to prod from pipelines
- [ ] Remove all prod resources
- [ ] Remove argocd prod application
- [ ] Free up PVCs
- [ ] Tell people to stop using it as their bootstrap

**Comment by eamansour** [comment]
Prod is gone and we now use prod1 - this is done.
