### ISSUE TITLE
Set up retention rules on Harbor

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1800]
## Story
As a Galasa developer, I want unneeded Docker images on Harbor to be cleared automatically with a retention rule, so we don't run out of Harbor capacity and have to manually clear it.

## Background
The new Harbor instance on harbor2 namespace does not have any retention rules set. When I tried to one up, then started a 'Dry Run', the logs from the harbor-jobservice-xxx pod included lines like this:
```
2024-03-19T13:19:47Z [INFO] [/jobservice/worker/cworker/c_worker.go:77]: Job incoming: {"name":"RETENTION","id":"b0042ddd5a464433bb7aa09f","t":1710854386,"args":null}
2024-03-19T13:19:47Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: https://harbor-core:443/api/v2.0/internalconfig
2024-03-19T13:19:47Z [INFO] [/pkg/config/rest/rest.go:47]: get configuration from url: https://harbor-core:443/api/v2.0/internalconfig
2024-03-19T13:19:47Z [INFO] [/jobservice/runner/redis.go:152]: Job 'RETENTION:b0042ddd5a464433bb7aa09f' exit with success
```
which seem okay, then further down, there are lines like this:
```
2024-03-19T13:19:50Z [ERROR] [/jobservice/runtime/bootstrap.go:166]: trigger hook event error: {"errors":[{"code":"UNKNOWN","message":"internal server error"}]}
2024-03-19T13:19:50Z [ERROR] [/jobservice/runner/redis.go:123]: Job 'RETENTION:33dba7c7db22722a18510c18' exit with error: run error: retention job: http error: code 403, message {"errors":[{"code":"FORBIDDEN","message":"forbidden"}]}
```

The Dry Run output shows that these repositories were the ones that failed with the error reported above:
- galasa-javadoc-site
- galasa-javadoc-maven-repo
- galasa-cli-ibm-amd64
- galasabld-amd64

At the time of making this story, the capacity on the harbor-registry is 19%, so we have some time before we need to implement this. It's not super urgent. But we should figure out why the retention rules don't work for those repositories and implement them so we don't have to remember to keep manually running Garbage Collection.

## Tasks
- [ ] Figure out issue with the retention rules on those repositories listed above
- [ ] Set up retention rule on the `galasadev` project to keep always images tagged with `latest,main,prod,stable`
- [ ] Set up retention rule on `common` project to keep always images tagged with `'main`
