### ISSUE TITLE
Move external CPS properties to 'automation'

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1804]
## Story
As a Galasa developer, I want the galasa-prod CPS props to be stored and updated from one central location, so that there is complete visibility over our current CPS props, and we can update them after releases/version bumps in automated fashion.

## Background
The galasa-prod CPS properties were previously stored in Java properties format in this GitHub Enterprise repo: https://github.ibm.com/CICS/cicsts-galasa-config/blob/main/old/CPS.properties After a property was updated in the file (Pull Request and review needed for this), a Jenkins job was triggered to update the properties. 

We now don't use this because a) we have `galasactl properties get` and `set` so people can update properties directly, b) not all of the Galasa team have access to that GitHub repo as it's in the CICS org so they need to be invited, c) we don't have an automated job set up to update the properties based on changes to the file.

Upon discussion with Mike and Fiona, we believe it's best to create a new file to store all CPS properties, in the new GalasaProperty yaml format, in automation. This can only store properties that are okay to be published externally though. We probably don't want to publish details of our z/OS systems we use for testing, or CPS properties belonging to other teams that use galasa-prod, for example.

We can then have two files - one in automation with our regularly updated external properties that can be updated via a Tekton pipeline, and one that stays in the current repo with properties we probably don't want exposed, but these are hardly ever updated, so that's fine.

## Tasks
- [ ] Determine which CPS properties are okay to be published externally and can be moved into automation (work with Jade), these will be anything to do with versions of Galasa, URLs that are external, etc.
- [ ] Create a new file in automation containing these CPS properties in GalasaProperty yaml format 
- [ ] Create a pipeline that uses `galasactl resources apply` to apply that file to the ecosystem so when properties are updated, the CPS is updated with that new property
- [ ] Remove steps from the release documentation anywhere that refers to updating CPS properties directly with `galasactl`
- [ ] Create a new `set-version.sh` script to be ran at the end of each release to update the necessary CPS props instead, add this into the release instructions

**Comment by jadecarino** [comment]
@techcobweb FYI
