### ISSUE TITLE
CLI: User can list the access tokens in the system

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1805]
# Story
As a galasa user I want to be able to list the access tokens in the system.

# Background
This story is needed if tokens are going to be revoked/deleted.

We need a new CLI command:

```
> galasactl auth tokens get 
tokenid                   created(YYYY/MM/DD)  user     description
098234980123-1283182389   2023-12-03           mcobbett So I can access ecosystem1 from my laptop.
8218971d287s1-dhj32er2323 2024-03-03           mcobbett Automated build of example repo can change CPS properties
87a6sd87ahq2-2y8hqwdjj273 2023-08-04           savvas   CLI access from vscode
```

Note: No filtering is needed. That can come later.

Assume: description is only a single line.

Question: Can the id be shorter ? Answer: Yes. Lets do the shorter format then.

The information comes from a new REST endpoint:
```
/auth/tokens
```
gives payload:
```
{
    tokens:[
        { 
          "tokenid":"098234980123-1283182389", // The couchdb document id.
          "created_time":"2023-23-01T18:25:43.511Z",
          "owner": {
               "login-id":"techcobweb"
          }
          "description":"So I can access ecosystem1 from my laptop"
        }...etc
    ],
}
```

The token list is sorted by creation date order, earliest first.

Note: Internally in couchdb we also need to store these fields, which should NOT be available to the user:
- dex-client-id

These are get/create/delete only objects, they won't ever be updated.

Currently the user document should be created at the earliest possible moment when the user first logs in via oauth.

Note: For this story, we don't need /auth/users to be implemented. That can follow later.

No attempt to stop one user seeing tokens from another user is made.

Can we also capture the expiry date of tokens ? If so, then we can occasionally auto-delete expired tokens (not in this story, just capturing the data enables this to be added later).

# Tasks
## Server-side
- ~~Couchdb users database needs to be created and initialised~~
  - We don't actually need this yet. We can store tokens with a user name inside.
- - ~Couchdb token document id is short~ Using CouchDB's uuid generation for now
- [x] Couchdb tokens database needs to be created and initialised
  - [x] CouchDB token document to determine the structure of the data stored in the database
- [x] Auth OSGi extension point needs creating
- [x] framework instantiates the extension based off a CPS property, indicating the implementation class to load
- [x] Add `/auth/tokens` endpoint to OpenAPI spec
- [x] REST endpoint needs creating
- [x] REST endpoint results sorted order (created date-time, earliest-to-latest)
- [x] User couchdb document gets created on initial login. Storing whatever we need.
- [x] dex-client-id stored in couchdb document but not visible to user (separate external transport beans from couchdb beans)

## CLI
- [x] CLI code needs this new command
- [x] Created date to render to nearest day in correct format
- [x] Docs

## Web UI
- [x] Web UI needs to pass the token description to the API server when creating a new access token

## Helm Chart
- [x] Helm chart needs to set the new auth store property
- [x] Helm chart needs to load the new auth bundle

## Other tasks
- [ ] Deploy + test to ecosystem1 and run a test there (github)
- [ ] Deploy + test to prod1 and run a test there (oidc)
- [ ] Docs

Separate stories:
1.
Move the POST endpoint which creates the tokens to the /auth/tokens endpoint
2.
Users are stored separately with sepearate endpoint.
We also need an endpoint for the users:
```
/auth/users/{user-id}
```
gives payload:
```
{
  "id":"456789876545678-4567887",
  "url":"https:/my-server/api/auth/users/456789876545678-4567887"
  "login-id":"techcobweb",
  "real-name":"Mike Cobbett", // Q: Can we get this info from the oauth exchange ?
  "display-name","Mike Cobbett" // Q: Can we get this info from the oauth exchange ?
}
```
