### ISSUE TITLE
Remove test catalog endpoint, PVC, gradle and maven plugins.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1807]
# Story
As a galasa tester trying to set up build infrastructure around a Galasa ecosystem, I want to not have two options on how to manipulate test catalogs, so the docs are prescriptive and clearer.

# Background
There are currently 2 options on how to tell the ecosystem about a test catalog.

1. Use the maven/gradle publishTestCatalog plugins to push a test catalog to the /testcatalog server endpoint, and set the location in the stream to refer to the testcatalog endpoint hosted by the galasa server. It's loosely coupled.
2. Use the galasactl properties set command to set the 'location' property in a stream structure to refer to the test catalog artifact as it exists in a hosted maven repository. For example: https://my.maven.repo/dev/galasa/example/banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/dev.galasa.example.banking.obr-0.0.1-SNAPSHOT-testcatalog.json
The URL refers to a version number which never changes, even if the tests and contents of the test catalog change. eg: 0.0.1-SNAPSHOT so updating the maven site implicitly automatically causes the galasa server to start using the new material.
3. As above, but the URL refers to a specific version number, which gets bumped up with successive changes to built test classes. So the system needs to update the location field whenever the server should be pulling more recent material. This is recommended.

We want to stop using option 1 above.

# Tasks
- [ ] Remove the maven plugin. This has been producing deprecation warnings since 0.33.0
- [ ] Remove the gradle plugin. This has been producing deprecation warnings since 0.33.0
- [ ] Remove the /testcatalog endpoint 
  - [ ] from the code
  - [ ] from the openapi.yaml doc
- [ ] Remove the PVC and mount from the helm chart
- [ ] Deploy to prod1 and ecosystem1
- [ ] Document in galasa.dev docs.
