### ISSUE TITLE
v0.33.0 : Pre-release, Release and Post-release

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1808]
## Story
As a galasa user I want to get the 0.33.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [ ] Run through the pre-release process
- [ ] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [ ] Identify problems/improvements and raise them for next time
- [ ] Add more detail for asking for release approval
- [ ] Make sure scan results are clean
