### ISSUE TITLE
Local test run to be able to use remote CPS

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1813]
# Story
As a tester, I want to run a test locally which uses the CPS properties which are stored on a remote galasa ecosystem.

# Background
In normal local runs of a test, we have this configuration of CPS properties, using a local properties file:
![Image](https://github.com/galasa-dev/projectmanagement/assets/77053/fbc0a47a-dd2f-4a25-95ce-e5c4a6e84d9a)

In v0.32.0 or below of Galasa, we can also support this configuration:
![Image](https://github.com/galasa-dev/projectmanagement/assets/77053/717703ca-87f2-410a-905e-a9fdd5976a6b)

To achieve this, you need to add these properties into your bootstrap.properties file locally.
```
framework.config.store=etcd\:http\://main-ecosystem-etcd\:1234
framework.extra.bundles=dev.galasa.cps.etcd,dev.galasa.ras.couchdb
```

What we want, is to support this configuration:
![Image](https://github.com/galasa-dev/projectmanagement/assets/77053/acc9a2ef-ab50-4273-a190-7b2a541f042f)

ie: A new implementation of CPS which talks rest over an authenticated HTTPS connection  talks to the existing CPS rest API.

The file-based implementation is here, in the framework project`galasa-parent/dev.galasa.framework/src/main/java/dev/galasa/framework/internal/cps/FpfConfigurationPropertyStore.java`

We need this code to be added to the extensions repository.

The /bootstrap endpoint needs to return this to external callers:
```
#Galasa Bootstrap Properties
#Fri Apr 05 09:13:36 UTC 2024
framework.config.store=galasacps://my.ecosystem.url/api
framework.extra.bundles=dev.galasa.cps.rest
```

The `galasacps://my.ecosystem.url/api` above indicates that the ecosystem REST API can be found at `https://my.ecosystem.url/api`

The `framework.extra.bundles` above indicates that the Galasa framework should load the `dev.galasa.cps.rest` extension, which itself informs the Galasa framework how to handle URLs which start with `galasacps` as the 'scheme' part of the URL.

## Q: How does the extension get the JWT ?
- The extension is only used locally.
- The `galasactl` program looks into the `$GALASA_HOME/bearer-token.json` file, fishes out the JWT information, and passes it on the command-line when the `jar -jar` gets invoked as a child process.
- The extension then picks the value up from `System.properties`
- The system property is called `GALASA_JWT`.
- The `galasactl` only does this if the bootstrap property `framework.config.store` starts with `galasacps`

# Task
- [x] Write extension with unit tests.
  - See pull request https://github.com/galasa-dev/extensions/pull/220
- [x] Test on live ecosystem
- [x] Extension picks up the JWT from system properties
- [x] Fix the signatures on the CPS interface which can't return errors.
  - [x] Framework https://github.com/galasa-dev/framework/pull/533
  - [x] Extensions https://github.com/galasa-dev/extensions/pull/222
- [x] Change the CLI to supply a JWT to the JVM when required. 
  - See PR https://github.com/galasa-dev/cli/pull/233
- ~~Change the external bootstrap URL returned payload in the API server~~
  - Scope moved to this story: [/bootstrap URL to return configuration to support remote CPS access #1841](https://github.com/galasa-dev/projectmanagement/issues/1841)
- ~~Wrap apache http client libraries so couchdb and the cps extensions can both rely on them rather than embedding them~~ Turns out this isn't necessary as the apache jars are already bundles. Couchdb just imports the packages and they are already exported by something.
- [x] If there is no JWT available, command-line tool should go get one prior to launching.
- [x] Docs in galasa.dev
- ~~Redact the value of the JWT in framework trace statements.~~
  - This requires changes to the boot jar which does this logging. Suggest we delay this until after 0.33.0 when we can fix it up. Don't want to get into chasing wiring problems due to the boot jar not being at the correct level, or delay the 0.33.0 release.
  - scope moved to [Boot jar should not log GALASA_JWT in the trace. This JWT should not be exposed. #1838](https://github.com/galasa-dev/projectmanagement/issues/1838)
