### ISSUE TITLE
Wrong JWT claim is being used to set requestor

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1816]
## Describe the bug
When doing a `galasactl runs get` on the prod1 ecosystem, the following requestor is shown in the results:
```
submitted-time(UTC) name requestor                                                          status   result  test-name
2024-04-08 08:36:55 C307 cil1awq9mti2nzqxody2lgm9z...mnvbriebgrhca finished Passed  dev.galasa.inttests.zos.local.isolated.ZosLocalJava11UbuntuIsolated
```

This is the value in the issued JWT's "sub" claim (see [getUserName()](https://github.com/galasa-dev/framework/blob/ecc2ace67720d71e0ba1eb79e45ba7088000ed7e/galasa-parent/dev.galasa.framework.api.authentication/src/main/java/dev/galasa/framework/api/authentication/JwtWrapper.java#L50)), which represents a user ID. We should grab a more human-readable claim, like the "preferred_username" or "name" claim instead.

A decoded JWT from the LDAP connector using our internal auth contains the following claims:
```json
{
  "iss": "https://my-dex-issuer/dex",
  "sub": "<user-id>",
  "aud": "<client-id>",
  "exp": 1234567,
  "iat": 1234567,
  "at_hash": "<access-token-hash>",
  "name": "eamonns@email.com"
}
```

A decoded JWT using the GitHub connector contains the following claims:
```json
{
  "iss": "https://my-dex-issuer/dex",
  "sub": "<user-id>",
  "aud": "<client-id>",
  "exp": 1234567,
  "iat": 1234567,
  "at_hash": "<access-token-hash>",
  "c_hash": "<auth-code-hash>",
  "name": "Eamonn Mansour",
  "preferred_username": "eamansour"
}

```

## Steps to reproduce
1. Run `galasactl runs get --age 1d` against prod1
2. See the requestor value

## Expected behavior
A human-readable value for the requestor should be displayed, like the user's username or email. For example:
```
submitted-time(UTC) name requestor status   result  test-name
2024-04-08 08:36:55 C307 eamansour finished Passed  dev.galasa.inttests.zos.local.isolated.ZosLocalJava11UbuntuIsolated
```

## Tasks
- [x] Look into passing a value in the helm chart containing the preferred JWT claim(s) to use when setting requestors
- [x] Update the [getUserName()](https://github.com/galasa-dev/framework/blob/ecc2ace67720d71e0ba1eb79e45ba7088000ed7e/galasa-parent/dev.galasa.framework.api.authentication/src/main/java/dev/galasa/framework/api/authentication/JwtWrapper.java#L46-L51) method to use the preferred claim, falling back to other preferred claims if the initial claim does not exist in the JWT
- [x] Check that running `galasactl runs get` now displays the correct username
