### ISSUE TITLE
pom xml developer tags should just refer to contributors

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1817]
# Story
As a galasa developer I don't want the hassle of keeping the list of contributors up to date in all the pom.xml files we ship, because if people want to see attribution they can look at the contributors in the galasa project on github. We don't need this duplication, and keeping it up to date is a pain.

# Background
- You can't publish a pom.xml to maven central without developer attribution.

- Currently we have things like this: 
```
<developers>
         <developer>
		<name>Michael Baylis</name>
		<email>Michael.Baylis@uk.ibm.com</email>
		<organization>IBM</organization>
		<organizationUrl>https://www.ibm.com</organizationUrl>
	</developer>
	<developer>
		<name>William Yates</name>
		<email>wyates@uk.ibm.com</email>
		<organization>IBM</organization>
		<organizationUrl>https://www.ibm.com</organizationUrl>
	</developer>
	<developer>
		<name>David Roberts</name>
		<email>david.roberts@uk.ibm.com</email>
		<organization>IBM</organization>
		<organizationUrl>https://www.ibm.com</organizationUrl>
	</developer>
	<developer>
		<name>James Davies</name>
		<email>james.davies@ibm.com</email>
		<organization>IBM</organization>
		<organizationUrl>https://www.ibm.com</organizationUrl>
	</developer>
</developers>
```

- We want them to all read like this:
```
<developers>
	<developer>
		<name>Galasa Contributors</name>
		<email>galasadelivery@ibm.com</email>
		<organization>Linux Foundation</organization>
		<organizationUrl>https://github.com/galasa-dev</organizationUrl>
	</developer>
</developers>
```

# Tasks
- [x] Do a build of all repositories
- [x] Look in the maven repo for all the folders in dev.galasa to all the pom.xml files.
- [x] Check you can find all the developers references.
- [x] Fix the references as above for the following repositories:
  - ~buildutils~ - none present
  - [x] framework
  - [x] gradle
  - ~isolated~ - none present
  - ~webui~ - none present
  - ~cli~ - none present
  - ~helm~ - none present
  - [x] managers
  - [x] obr
  - [x] simplatform
  - [x] wrapping
  - ~automation~ - none present
  - [x] extensions
  - ~githubapp-copyright~ - none present
  - ~integratedtests~ - none present
  - [x] maven
