### ISSUE TITLE
UI image is not pushed in the release process

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1826]
# Bug
The image registry doesn't contain the web UI image, so nobody can install an ecosystem without this.
The bug is in the publishing script. It gets images from harbor, and pushes them one-by-one to ICR.
The script needs to change to also move the UI image.

# Tasks
- [x] Create 'release' branch of webui repo from 'main'
- [x] Trigger branch-webui pipeline to build 'release' branch to build galasa-ui release docker image
- [x] Push galasa-ui image from harbor to ICR
