### ISSUE TITLE
Release v0.34.0 and v0.34.1

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1827]
## Story
As a galasa user I want to get the 0.34.0 release so that I can use the new functionality it offers.

## Background
We want to release more frequently (monthly), so that releasing becomes easier to do.

## Tasks
- [x] Run through the pre-release process
- [x] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [x] Identify problems/improvements and raise them for next time
- [x] Add more detail for asking for release approval
- [x] Make sure scan results are clean

**Comment by techcobweb** [comment]
Jade tells me all the tests are passing, so we have reached our criteria for releasing the 0.34.0 release to the open-source world on maven central & icr
