### ISSUE TITLE
Simplify the Galasa contribution + build process : 17-> 10 code repositories

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1828]
# Story
As a Galasa code developer I want a simpler build process, so it's easier to contribute changes.

# Background
Currently we have many repositories which have separate build processes. These 
1. cli  
1. githubapp-copyright 
1. isolated                
1. obr                     
1. extensions
1. gradle
1. managers
1. webui
1. automation
1. framework
1. helm
1. maven
1. wrapping
1. buildutils
1. galasa.dev
1. simplatform
1. homebrew-tap

Lets change things to have fewer, like this:

1. githubapp-copyright 
1. automation
1. buildutils, wrapping, gradle, maven, framework, extensions, managers, obr
1. cli
1. webui
1. simplatform
1. isolated
1. helm
1. galasa.dev
1. homebrew-tap

+ves: Easier to commit atomic changes across framework/extensions/managers/obr 
-ves: Slightly longer build time, as there is more code. We could speed things up with a build cache.

Question: Can VScode cope with this ? You can always open vscode one folder down in the source tree.

# Tasks
- [x] Analyse the existing github workflows to see how they can be combined into one, or called from one, with information flowing between them which does not need docker images to be stood-up on infrastructure.
- [x] Create a top-level prototype of a github workflow which builds the gradle and maven modules. Demonstrating how information is shared between them.

- [x] Create a PR to the mono-repo-creator containing this top-level gh actions wizardry.
  - [x] Master repo calls the sub-flows

- [x] When a PR build occurs it shouldn't have to build everything if it didn't touch it.
- [x] Test with different changes in different modules, to check that the logic builds the correct things
- [x] Release processed needs changing + release documentation.

**Comment by jlolivos** [comment]
test

**Comment by jlolivos** [comment]
**Tutorial to build Galasa on local:**

**1.- Disable GPG:**
pass flag: -Dgpg.skip=true  

galasa/modules/wrapping/.github/workflows/pr-build.yaml:78:          -Dgpg.skip=true \
galasa/modules/wrapping/build-locally.sh:182:#cmd="mvn clean install -Dgpg.passphrase=${gpg_passphrase} -Dgpg.skip=true"
galasa/modules/wrapping/build-locally.sh:183:cmd="mvn clean install -Dgpg.skip=true"
galasa/modules/maven/.github/workflows/pr-build.yaml:72:          mvn -f galasa-maven-plugin/pom.xml -X deploy -Dgpg.skip=true \
galasa/modules/obr/.github/workflows/pr-build.yaml:101:          -Dgpg.skip=true \
galasa/modules/obr/.github/workflows/pr-build.yaml:128:          -Dgpg.skip=true \
galasa/modules/obr/.github/workflows/pr-build.yaml:236:          -Dgpg.skip=true \
galasa/modules/obr/.github/workflows/pr-build.yaml:319:         -Dgpg.skip=true \
galasa/modules/obr/build-locally.sh:396:    -Dgpg.skip=true \


**2.- Disable check_secrets in build-locally.sh scripts**
Example_:
       sed -zi 's/check_secrets/#check_secrets/2' ./galasa/modules/wrapping/build-locally.sh

**3.- Create a GPG key on your local**
https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

Export the GPG key to: /home/jenkins/.gnupg/secring.gpg

**4.- Add next values to your gradle.properties file:**
Ensure this variable is false when it is not a release.
isMainOrRelease=false

signingPassword=galuser
signingKeyId=2306770CC30AB01D
signingKey=/home/jenkins/.gnupg/secring.gpg

**5.- Update script: galasa/modules/obr/build-locally.sh**
    In my case was trying to run galasabld-darwin, instead of linux version.
    Update accordingly to your architecture.

175     #export GALASA_BUILD_TOOL_NAME=galasabld-darwin-${ARCHITECTURE}
176     export GALASA_BUILD_TOOL_NAME=galasabld-linux-${ARCHITECTURE}

**6.- Run script: ./galasa/tools/build-locally.sh**


[INFO] Installing /home/jenkins/repo/galasa/galasa/modules/cli/temp/dev.galasa.example.banking/dev.galasa.example.banking.obr/target/testcatalog.json to /home/jenkins/.m2/repository/dev/galasa/example/banking/dev.galasa.example.banking.obr/0.0.1-SNAPSHOT/dev.galasa.example.banking.obr-0.0.1-SNAPSHOT-testcatalog.json
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dev.galasa.example.banking 0.0.1-SNAPSHOT:
[INFO]
[INFO] dev.galasa.example.banking ......................... SUCCESS [  0.364 s]
[INFO] dev.galasa.example.banking.account ................. SUCCESS [  3.327 s]
[INFO] dev.galasa.example.banking.payee ................... SUCCESS [  0.817 s]
[INFO] dev.galasa.example.banking.obr ..................... SUCCESS [  0.350 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.450 s
[INFO] Finished at: 2024-09-03T09:11:02-07:00
[INFO] ------------------------------------------------------------------------
✔ OK

**Comment by jlolivos** [comment]
Working on this task:
[  ]  Analyse the existing github workflows to see how they can be combined into one, or called from one, with information flowing between them which does not need docker images to be stood-up on infrastructure.

**Comment by jadecarino** [comment]
Release process/automation updates in this PR: https://github.com/galasa-dev/automation/pull/625

**Comment by jadecarino** [comment]
Updates to the Isolated/MVP build workflows to support the new mono repo structure in this PR: https://github.com/galasa-dev/isolated/pull/73

**Comment by jadecarino** [comment]
Updates to the CLI build workflows to support the new mono repo changes in this PR: https://github.com/galasa-dev/cli/pull/299

**Comment by techcobweb** [comment]
This works. Marking as done.
