### ISSUE TITLE
Test the released artifacts in post-release steps

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1829]
# Story
As a galasa ecosystem admin, I want to have confidence that I can install and use the ecosystem which has just been released.

# Background
- When trying to install an ecosystem, as a customer would, we found that the UI docker image was not present.
- We should add steps in the post-release process to upgrade a running ecosystem using the newly published helm chart and images to be sure it will work for customers.
- We need another ecosystem which draws from the released version on ICR.
- Our post-release tests need to test that this deploys Ok, that you can get a token from the UI
- And then use that token to run a simple test.

# Tasks
- [ ] Prepare a namespace on kubernetes ready to accept the new 'released' ecosystem
- [ ] Write a script which will take a values file and use helm to install the latest chart. Do we need a pipeline to do this? or is it simpler not doing that?
- [ ] Add instructions into the release docs
- [ ] Set up a stream on the ecosystem
- [ ] Allocate a fresh token on the ecosystem web ui
- [ ] Run a test on the ecosystem (doesn't have to do much)

That would have found the problems we encountered for sure.
