### ISSUE TITLE
Boot jar should not log GALASA_JWT in the trace. This JWT should not be exposed.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1838]
# Story
As a galasa tester, when I send a run log to someone for problem diagnostis, I don't want it to contain my jwt spelt-out for all to see, so I can feel more secure I can share logs without compromising the security of my galasa ecosystem.

# Background
- This is a follow-on story from this story: Local test run to be able to use remote CPS
[#1813](https://github.com/galasa-dev/projectmanagement/issues/1813)
  - We delayed implementing it originally so v0.33.0 release wasn't held up.
- The problem itself only occurs when a galasa tester is using hybrid mode: the CPS is remote on the ecosystem, but the test is running locally. A minority sport at best, and very new functionality introduced/re-introduced in v0.33.0
- The Log contains a trace of all the parameters passed on the command-line.
- The boot jar does this
- We need to stop any argument -DGALASA_JWT from actually being logged properly.
- Perhaps replace the value with "*********" instead of the real value.

# Tasks
- [x] Code the fix
- [x] Test that such parameters are hidden now.
- [x] Bump the version of the boot jar
- [x] Correct all the wiring which depends upon the boot jar
- [x] Update the version of the boot jar which ships inside the galasactl too.
