### ISSUE TITLE
Use Github actions to build all the galasa code

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1845]
# Story
As a galasa developer, I want to build all the code using github actions.

# Background
- A spike story is needed to try it out and assess whether this is a good move and how tricky it is.
  - see [Spike: Build 'buildutils' with GitHub Actions pipeline. #1719](https://github.com/galasa-dev/projectmanagement/issues/1719)

Follow-on stories have been raised here:
- [x] [Build 'wrapping' with GitHub Actions pipeline #1875](https://github.com/galasa-dev/projectmanagement/issues/1875)
- [x] [Build 'gradle' with GitHub Actions pipeline #1876](https://github.com/galasa-dev/projectmanagement/issues/1876)
- [x] [Build 'maven' with GitHub Actions pipeline #1877](https://github.com/galasa-dev/projectmanagement/issues/1877)
- [x] [Build 'framework' with GitHub Actions pipeline #1878](https://github.com/galasa-dev/projectmanagement/issues/1878)
- [x] [Build 'extensions' with GitHub Actions pipeline #1879](https://github.com/galasa-dev/projectmanagement/issues/1879)
- [x] [Build 'managers' with GitHub Actions pipeline #1880](https://github.com/galasa-dev/projectmanagement/issues/1880)
- [x] [Build 'obr' with GitHub Actions pipeline #1881](https://github.com/galasa-dev/projectmanagement/issues/1881)
- [x] [Build OBR Generic artefacts in GH Actions](https://github.com/galasa-dev/projectmanagement/issues/1942)
- [x] [Build 'cli' with GitHub Actions pipeline #1882](https://github.com/galasa-dev/projectmanagement/issues/1882)
- [x] [Build 'isolated' with GitHub Actions pipeline #1883](https://github.com/galasa-dev/projectmanagement/issues/1883)
- [x] [Build 'helm' with GitHub Actions pipeline](https://github.com/galasa-dev/projectmanagement/issues/1935)
- [x] [Build 'webui' with GH Actions](https://github.com/galasa-dev/projectmanagement/issues/1940)
- [x] [Build 'integratedtests' repo with GH Actions](https://github.com/galasa-dev/projectmanagement/issues/1941)
- [x] [Build 'simplatform' with GH Actions](https://github.com/galasa-dev/projectmanagement/issues/1943)

**Comment by osamamagdy** [comment]
Hello @techcobweb, I want to start contributing on this if accepted as a mentee for the LFX mentorship https://mentorship.lfx.linuxfoundation.org/project/2e784e4e-5569-45b8-98b8-4881f4b0e6e2
May I suggest a proposal to a complete CI/CD pipeline if needed?

**Comment by jaydee029** [comment]
@techcobweb Hi, I would like to apply for this as a part of Open Mainframe Mentorship. I would be submitting a proposal soon. Thanks.

**Comment by jaydee029** [comment]
@techcobweb does this involve building continuous deployment pipeline as well, or just CI and build pipelines ?

**Comment by techcobweb** [comment]
From memory, we currently deploy an Apache server application in a docker image to allow downloads of the tool, using ArgoCD.

**Comment by jaydee029** [comment]
@techcobweb  So I guess we'll stick to CI and build for now which also includes pushing artifacts to the maven repository using github actions, and CD can be an extended goal, can I ask what is the application deadline ?

**Comment by jaydee029** [comment]
Hey @techcobweb , I've formally submitted my application along with the proposal for this task(through mail as well), since the applications aren't closed yet can I get a proposal review ?
