### ISSUE TITLE
Vulnerabilities found in icr images

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1848]
Whilst looking at the galasa images in ICR a number of vulnerabilities have been identified in the images. 
These vulnerabilities appear across many of the galasa images.

1. CVE-2024-26883
2. CVE-2024-28085
3. CVE-2022-48303
4. CVE-2024-2961

This is caused by vulnerabilities in the base image used by the httpd:2.4 image

##Tasks

- [x] Bump the image from version of httpd to httpd:2.4.59
- [ ] Build the latest images again
- [ ] ensure that the vulnerability warning are no longer there
