### ISSUE TITLE
Deploy download site for DfG release candidate

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1860]
## Story
As an internal IBM team drawing Dfg into my product, I want to be able to download it, so that I don't have to wait for the Galasa team to upload it to where I want it.

## Background
The DfG end product should be built into a Docker image that contains a zip file of DfG. The image will then be hosted and deployed to a web server where the DfG releaser can go to on a browser and simply click to download the zip file containing DfG, to then upload it to the DfG release site.

The site is IBM internal. 
The build process for it must be IBM internal.
Anything to do with Dfg must be IBM internal.

## Tasks
- [ ] Create a new directory in cicsk8s/... that will manage the DfG download site in an ArgoCD app called 'distribution-for-galasa'
- [ ] Create /templates directory containing a Deployment, Service and Ingress in a non-open-source repository
- [ ] Create values.yaml file pointing at the docker image containing DfG and other values

**Comment by techcobweb** [comment]
@jadecarino Dfg is not open source so we shouldn't allow anyone outside of IBM to download it.
This story should probably be on our internal KanBan board ?

**Comment by jadecarino** [comment]
@techcobweb Okay it was my intention for the download site URL to be behind the IBM firewall similar to how all of our maven repos were ~2 years ago, before they moved to development.galasa.dev. I can move the story but then we should probably also move Holly's that has been on the board a while.

**Comment by techcobweb** [comment]
This is not something for the open source project. CLosing.
