### ISSUE TITLE
More space for etcd

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1861]
# Story
As a galasa ecosystem administrator, I want to make sure that the dss doesn't run out of space, so that I avoid a lock-out situation which is hard to recover from.

# Background
The ecosystem needs a bigger default amount of space to hold the creds/cps/dss in etcd, especially now that dex stores information there also.

Previously, prod had 10GB for each, but the helm chart only allocates 1GB for all of them.

Etcd also supports auto-compaction/de-fragmentation, which needs to be turned on by default to make the system less likely to blow.

# Tasks
- [x] The space allocated to the PVC should be 30GB or more. Change in the helm chart for the PVC.
- [x] Turn on etcd auto-compaction. Change to the etcd stateful set.
- [x] Check that the prod1 has a bigger PVC.
