### ISSUE TITLE
openapi2beans generator to use a @SerializedName("<snake_cased_name>") annotation

### ISSUE THREAD

**Issue by Wyvinar** [galasa-dev/projectmanagement#1868]
# Story
As a galasa developer, I want to specify snake_case variable names in fields within the openapi.yaml document, and when I do I want java code generated from those labels to be camelCase variable names in java code, with annotations such that Gson will render them as the original snake_case in any generated json documents, so the generated java code is more likely to conform to Java code naming standards.

# Background

- If the field name in openapi looks like a snake_case label, generate the annotation and the camelCase label for the java field.

## Examples

```
schemaType:
  type: object
  properties:
    snake_case:
      type: string
```
should become
```
class SchemaType {
...
    @SerializedName("snake_case")
    private String snakeCase;
...
```

The template would likely look like (at least for the single variable):
```
{{#SerializedOverrideName}}
@SerializedName("{{&.}}")
{{/SerializedOverrideName}}
[variable stuff continued]
```

# Tasks
- [x] edit the moustache template to have the @SerializedName annotation
- [x] add SerializedOverrideName as a variable to DataMembers (leave empty if not wanting to render)
- [x] ~add a convert to camelCase function~ found a library that does this
- [x] change schema2package to save the snake_case name to the new variable
