### ISSUE TITLE
Managers: managers to Have better logging for missing properties

### ISSUE THREAD

**Issue by KirbyKatcher** [galasa-dev/projectmanagement#1872]
## Story
As a Galasa user when I use a manager without specifying all the properties it needs, I want to receive an error message describing the name of the property it expected to find, so that I can add the property to my cps.properties or the ecosystem cps, in order to use the manager in my test.

## Background
Example: #1850
When you try to use the Db2 manager without any cps properties, you get the following exception:

```shell
dev.galasa.framework.spi.FrameworkException: Bundle failed to install and activate
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:57) ~[-1714452933856:?]
	at dev.galasa.framework.TestRunner.runTest(TestRunner.java:232) [-1714452933856:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at dev.galasa.boot.felix.FelixFramework.runTest(FelixFramework.java:233) [galasa-boot-0.31.0.jar:?]
	at dev.galasa.boot.Launcher.launch(Launcher.java:176) [galasa-boot-0.31.0.jar:?]
	at dev.galasa.boot.Launcher.main(Launcher.java:126) [galasa-boot-0.31.0.jar:?]
Caused by: dev.galasa.framework.spi.FrameworkException: Bundle failed to install and activate
	at dev.galasa.framework.BundleManagement.addResource(BundleManagement.java:168) ~[-1714452933856:?]
	at dev.galasa.framework.BundleManagement.loadBundle(BundleManagement.java:55) ~[-1714452933856:?]
	... 8 more
```
It would be easier to understand the message if the exception contained a message such as ` unable to provision "<Manager Name>"as the property "db2.dse.instance.<TestTagName>.name" is not set`

### properties needed for DB2 setup:
cps.properties:
```properties
db2.dse.instance.PRIMARY.name=DB2INST1
db2.dse.schema.PRIMARY.name=testdb
db2.instance.DB2INST1.url=jdbc:db2://127.0.0.1:50000/TESTDB
db2.instance.DB2INST1.credentials=TESTDB
```
credentials.properties
```properties
secure.credentials.TESTDB.username=<USERNAME>
secure.credentials.TESTDB.password=<PASSWORD>
```

## Tasks
- [ ]  Set up a local DB2 instance to use with testing.
- [ ] Add additional Logging to DB2 manager errors
- [ ] Add additional logging to zos manager
- [ ] Evaluate whether we should put a log in the exception raised by getCpsProperty(with no default)
- [ ] Look to see why exceptions from the above are ignored/lost/swallowed
- [ ] Unit test
- [ ] Update Documentation for managers

**Comment by eamansour** [comment]
Docs on running the Db2 manager IVT locally (includes setting up a local Db2 instance using Docker) - https://github.com/galasa-dev/managers/blob/main/galasa-managers-parent/galasa-managers-database-parent/dev.galasa.db2.manager.ivt/README.md
