### ISSUE TITLE
Build 'wrapping' with GitHub Actions pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1875]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for wrapping](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/wrapping) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

**Update:** The workflows are for the time being going to build docker images and supply the current development Maven registries until we have snapshotting set up in the source code. After this, we'll switch the workflows to use GH Packages.

# Tasks
Use GitHub actions to build the 'wrapping' repository similar to the existing Tekton pipelines but adapt where necessary:
- [x] Create any necessary Secrets in your personal GitHub to be pulled into the workflow such as the Maven GPG key etc using `secrets.GPG_KEY`
- [x] Set up Maven GPG signing (see Task `maven-gpg`) - this might require a custom GH action or there may be one available
- [x] Sign the artefacts if a main workflow, do not for PRs (see flag `-Dgpg.skip`)
- ~Build the source with Maven and deploy the artefacts to the GitHub Maven repository for this repository (https://maven.pkg.github.com/galasa-dev/wrapping) (see Task `branch-maven-build-wrapping`)~
- [x] Build the source with Maven
- [x] Build a Docker image containing these artefacts
- ~Ignore tasks `branch-docker-build-wrapping`, `recycle-deployment` and `wait-deployment` which are no longer required as these were for the download sites~
- [x] The GitHub actions workflow should be integrated with PRs as well as merges into the main branch, so we see the tekton and github actions build processes side by side
- [x] We gather metrics where we can, so we can discuss it further to see what we need to do next
