### ISSUE TITLE
Build 'managers' with GitHub Actions pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1880]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for managers](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/managers) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks

Dhruv:
- [x] Use GitHub actions to build the 'managers' repository 
- [x] The source should be built with Gradle and the artefacts deployed to the GitHub Maven repository
- [x] Create any necessary Secrets to be pulled into the workflow
- [x] The GitHub actions workflow should be integrated with PRs as well as merges into the main branch, so we see the tekton and github actions build processes side by side

Jade:
- [x] Recreate workflows and run as galasa-dev org so the Galasa secrets are used

Outstanding actions:
- ~Figure out how to avoid 409 conflicts when pushing the same artefact/version to the maven registry~
- ~Figure out why the `managers/codecoverage/manager-unit-tests/0.36.0` artefact is built/published twice in the managers build, as that causes a 409 conflict error in itself~ Moving to new issue
