### ISSUE TITLE
Build 'obr' with GitHub Actions pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1881]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for OBR](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/obr) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Use GitHub actions to build the 'obr' repository for Pull Requests
- [x] Reference any necessary Secrets to be pulled into the workflow (Maven GPG signing)
- [x] The Galasa BOM, OBR and Javadoc should be built with Maven
- [x] Build Docker images containing the Galasa OBR maven repo, then the Javadoc maven repo and site but do not publish
- [x] Use GitHub actions to build the 'obr' repository for merges to Main
- [x] Reference any necessary Secrets to be pulled into the workflow (Maven GPG signing)
- [x] The Galasa BOM, OBR and Javadoc should be built with Maven
- [x] Build Docker images containing the Galasa OBR maven repo, then the Javadoc maven repo and site and publish to GHCR
- [x] Recycle the ArgoCD apps for OBR, Javadoc maven repo and Javadoc site
- [x] Ignore tasks that reference the "release" branch for now

Jade:
- [x] Change obr, javadoc and javadocsite images in the argocd app to point at new GHCR images
