### ISSUE TITLE
Build 'isolated' with GitHub Actions pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1883]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for isolated](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/isolated) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Use GitHub actions to build the 'isolated' repository for Pull Requests and Main builds
- [x] Generate the Isolated pom.xml
- [x] Build the Isolated pom.xml
- [x] Build poms 2-6
- [x] Build pomJavadoc.xml
- [x] Build pomDocs.xml
- [x] Download the CLI binaries
- [x] Build pomGalasactl.xml
- [x] Copy text resources over
- [x] Docker build with Isolated Maven repo
- [x] Docker build Isolated Tar file
- [x] Build pomZip.xml
- [x] Docker build the Isolated zip
- [x] Repeat the same tasks for the MVP
- [x] For PR build do not publish the images
- [x] For Main build publish the images to GHCR
- [x] For Main build recycle the ArgoCD apps for Isolated and MVP
