### ISSUE TITLE
Set up and use Docker proxy cache for GitHub Container Registry

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1888]
## Story
As a Galasa developer, I want to use GHCR as a Docker cache, so that we don't encounter the Dockerhub pull limit during our build pipelines.

## Background
We currently have a Docker proxy cache set up in [Harbor](harbor.galasa.dev) and many of our custom images pull `FROM` a Docker official image like alpine. The proxy cache allows us not to hit the Dockerhub pull limit (100 pulls every 6 hours).

We need to set up the same thing for the GHCR so that when we eventually get rid of Harbor, our Docker builds don't start failing, and instead pull from the GHCR proxy cache.

So all `FROM` statements in our Dockerfiles that are like: `FROM harbor.galasa.dev/docker_proxy_cache/library/alpine:3.18.4` would become `FROM ghcr.io/library/alpine:3.18.4`.
 
## Tasks
- [x] Set up the Docker proxy cache for GHCR
- [x] Update all `FROM` statements in Dockerfiles to use this new proxy cache
   - [x] harbor.galasa.dev/docker_proxy_cache/library/httpd:alpine
   - [x] harbor.galasa.dev/docker_proxy_cache/library/alpine:3.18.4
   - [x] harbor.galasa.dev/docker_proxy_cache/library/alpine:3.18.6
   - [x] harbor.galasa.dev/docker_proxy_cache/library/ubuntu:20.04
   - [x] harbor.galasa.dev/docker_proxy_cache/library/openjdk:11
   - [x] harbor.galasa.dev/docker_proxy_cache/library/gradle:8.9-jdk17
   - [x] harbor.galasa.dev/docker_proxy_cache/library/maven:3.8.5-openjdk-17
   - [x] harbor.galasa.dev/docker_proxy_cache/library/openjdk:11
   - [x] harbor.galasa.dev/docker_proxy_cache/library/busybox:1.36.1
   - [x] harbor.galasa.dev/docker_proxy_cache/library/busybox:1.32.0
   - [x] harbor.galasa.dev/docker_proxy_cache/library/bash:3.2.57
   - [x] harbor.galasa.dev/docker_proxy_cache/library/golang:1.20.1
   - [x] harbor.galasa.dev/common/*
- [x] Delete cached images from Harbor

**Comment by jadecarino** [comment]
@techcobweb FYI - something I've just thought about while making the 'automation' GH Actions workflow.
