### ISSUE TITLE
opeanpi2beans enum values in capitals

### ISSUE THREAD

**Issue by Wyvinar** [galasa-dev/projectmanagement#1890]
# Story
As a Galasa developer, I want the enums produced by openapi2beans to conform to standard coding practice.
# Background
Currently the enums that the generator produces have lower case values when they should be in a constant name format with their output value beside them.
What we have currently:
```
public enum MyEnum {
    enumValue1,
    enumValue2;
}
```
What we should have:
```
public enum MyEnum {
    ENUM_VALUE_1 ("enumValue1"),
    ENUM_VALUE_2 ("enumValue2");
}
```
# Tasks
- [ ] create an enum value structure with 2 fields
- [ ] when converting from schematypes to java enums fill in the 2 fields
- [ ] change the enum moustache template to reflect  the new structure
