### ISSUE TITLE
Create Framework implementation of an Events Service

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1892]
## Story
As a Galasa user, I want to have a framework implementation of the Events Service, so that service is registered by the OSGi whiteboard pattern and other events services (like Kafka) can be plugged in optionally.

## Background
We have confirmed that we can publish test lifecycle events to a Kafka topic directly from the Framework. This story encompasses creating a Framework implementation for an Events Service that handles the service registration through the OSGi whiteboard pattern. This framework Events Service will run if the Galasa test is local, and essentially does nothing. 

## Tasks
- [x] Ensure feature flag only runs these pieces of code when set to true
- [x] Remove Event POJO and EventProducer code from the Framework 
- [x] Create Service and Registration classes in Framework that are registered with the OSGi whiteboard pattern but do nothing
- [x] Update unit tests that test FrameworkInitialisation
