### ISSUE TITLE
Add Event Streams token as an environment variable into the Helm chart

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1893]
## Story
As a Galasa user who uses the Kafka event reporting plugin, I want my event streams token to be consumed through the ecosystem as an environment variable, so that I do not need to expose/check in my token and I can authenticate to event streams.

## Background
The Kafka plugin requires a token to authenticate to whichever Kafka service the user chooses, such as Event Streams. This token is consumed by the plugin through the System environment, and so needs to be provided to the API and Engine Controller pods through the ecosystem Helm chart.

## Tasks
- [x] Provide token from secret into the API and Engine Controller deployments in the Helm chart
- [x] Search for the existence of a secret containing the token
- [x] If an existing Secret is not found, create one as part of the Chart (this will need improving, TBD with the team)
