### ISSUE TITLE
openapi2beans to support AnyOf

### ISSUE THREAD

**Issue by Wyvinar** [galasa-dev/projectmanagement#1901]
# Story
As a Galasa developer, I want to be able to use the AnyOf section to create and interface within java that my any of objects can inherit off
# Background
We have a schema within the openapi yaml that has the any of tag:
```
    Resources:
      type: object
      properties:
        action:
          type: string
          enum: ["apply","create","update","delete"]
        data:
          type: array
          description: An array of Galasa Resources that should contain one or more entrys matching any of the schemas outlined
          items:
            anyOf:
              - $ref: '#/components/schemas/GalasaProperty'
```
and it currently isn't being generated as a jave bean using openapi2beans.
so the basic structure of an any of:
```
AnyOfArray:
  type: array
  items:
    anyOf:
      [list of properties/schemas or references]
```
# Tasks
- [ ] yaml2schema types
  - [ ] store the information for an any of array
- [ ] schema2package
  - [ ] add a structure to JavaStructures that reflects an interface
  - [ ] add a transform from the schema type to this new structure
- [ ] package2java
  - [ ] add a new moustache file within embedded that takes the variables from the new javastructures struct and places them in a java interface format
  - [ ] use the new template
