### ISSUE TITLE
Improvements to the 0.34.0 release process

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1902]
# Story
As a galasa developer trying to deliver a release of galasa, I want the process to be improved to help me avoid mistakes, and to make the process run better

# Background
Listing things which should be improved to help speed up the release process, or make it more reliable.

# Tasks
- [x] Framework set-version script needs to update the version of dev.galasa.framework.api.openapi in the release.yaml, it currently only bumps it in the build.gradle for the bundle
- [x] Extensions set version script needs to bump the version of each Extension's build.gradle, it currently only bumps just the dev.galasa.ras.couchdb one
- [x] Extensions set version script should not insert a space between the colon and version in the galasa-extensions-parent/buildSrc/src/main/groovy/galasa.extensions.gradle, it currently does this: `dev.galasa.framework: 0.35.0`
- [x] Isolated set version script should be updating the version in the `/mvp/pomGalasactl.xml` and `/full/pomGalasactl.xml`, it currently does not
- [x] build-locally.sh script should copy the generated release.yaml (in the manifest project) file into the manually-maintained release.yaml after the gradle build step is performed. That will keep it up to date also. 
- [x] The zip artifacts created by the builds need to be uploaded into the 'releases' area in github so we keep an archive of them over time. Several customers ask for them, and we don't have copies archived anywhere for previous releases.
