### ISSUE TITLE
0.35.0 release

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1905]
## Tasks
- [x] Manually check all expected components to be released are at correct version
- [x] Test out the MVP zip for the DB2 fix
- [x] Build all code
- [x] Check all artefacts signed
- [x] Regression test
- [x] Complete MEND scan on the internal zip
- [x] Obtain release approval
- [x] Internal zip build
- [x] Code signing (Drew Hughes)
- [x] Deploy artefacts to Maven central (**ensure new wrappers are released by repeating step 30-deploy-maven-galasa.sh with manual input of 2.0.1 for jta, and 3.7.0 for kafka.clients**)
- [x] Build resources image
- [x] Deploy docker images to ICR
- [x] Tag GitHub repositories with the v0.35.0 tag
- [x] Upload CLI Release to GH
- [x] Upload Isolated/MVP Release to GH
- [x] Bump development to 0.36.0
