### ISSUE TITLE
Expose the server API version to a client

### ISSUE THREAD

**Issue by adamcoulthard** [galasa-dev/projectmanagement#1912]
# Story
As an developer of a client application, I want to be able to know what version the galasa server is running, so I can modify my client program's behaviour accordingly.

# Background
It should be possible to obtain the version level of the ecosystem to allow for a client to negotiate correctly with the system.  At the moment I've not found a way for the client to know what version of the ecosystem its talking too.  If this was done it would allow clients to be version sensitive and switch between API's to allow clients to work with many ecosystems or error nicely saying they are unable to communicate with the server due to incompatible versions.

We should add a new entry point which allows the servlet layer to serve-up the openapi.yaml file as a payload.

This endpoint should not be authenticated, you don't need a JWT bearer token to get to it.

The endpoint would look like this:

```
https://myhost/api/openapi
```

The Mime type would be "application/yaml" or "application/json" depending on what the requestor asks for.

# Tasks
- [x] Create the new endpoint with unit tests
- [x] Add the ecosystem host to the openapi `servers` field by templating it and injecting the appropriate host value
- [x] Support yaml or json to be returned, depending on what the client wants.
- [x] Gradle build process to pull the openapi.yaml from the maven artifact into a resources file held locally, from where it can be served up.
- [x] Build locally script calls the gradle which does the same as above.

**Comment by techcobweb** [comment]
@adamcoulthard How urgent is this please ? What does it stop you doing ? How should the priority of this issue compare with others you are aware of against the galasa team ?
