### ISSUE TITLE
Check for `framework.produce.events` CPS prop should be in the Framework so accessible from all classes with access to a Framework

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1917]
## Background
The Framework currently can produce one type of event from the TestRunner which is a TestRunLifecycleStatusChangedEvent. The TestRunner class has a method that checks for the CPS prop `framework.produce.events` and then skips or calls any event production methods depending on if its true or false.

The method to check for this flag should be in the Framework object itself as then all classes with access to a Framework, which is many of them, can simply do a get() for the property value.

Idea: This could also mean that for the user they can have more control over what type of events they want to produce if they are using the Kafka extension. The Framework class could contain checks for `framework.produce.events`, `managers.produce.events`, or `extensions.produce.events`, and as they all have access to a Framework, can check accordingly.

## Tasks
- [ ] Refactor the code so the method isProduceEventsFeatureFlagTrue() is called in the Framework
- [ ] Update the current event production method in the TestRunner to call the Framework to get the value instead
- [ ] Unit test as required and ensure no regressions
