### ISSUE TITLE
Design UI for access token list/revoke

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1918]
# Story 
As a galasa developer I want a deisgn agreed for the UI changes which I can create to list and revoke access tokens with.

# Background
This is a spike story, which is part of the wider epic here: https://github.com/galasa-dev/projectmanagement/issues/1513

Users need an access token to use Galasa. The access token is already allocated, so the user has a list of access tokens they need to maintain. 

We have command-line methods of doing this already (create/list/delete). So want to add the same to the web UI to bring it up to parity.

Questions:
- What if this user is an admin user, and can see everyone's tokens ? 
  - Currently everyone is an admin user.
- Do we support a filter on the user id ?
  - A simple text search should be fine. 
- Sort order based on user id and oldest first ?
  - Provide sort toggles on each column. Default is by user id.
- When a new one is created, making sure the new one is visible on the screen ?
  - Yes. Always. And when deleting, leave focus on nearest item 

## Version 4 (figma)

![Image](https://github.com/user-attachments/assets/df205c08-f7b5-4206-a0b5-368851f66d57)

![Image](https://github.com/user-attachments/assets/86988e26-ef90-41b7-92c0-72d6dce76496)

![Image](https://github.com/user-attachments/assets/97b85311-6aac-4579-a4fe-0255aa29ede4)

![Image](https://github.com/user-attachments/assets/0d3657e3-7e85-4db0-866a-03194dff6c88)

![Image](https://github.com/user-attachments/assets/7a1b9c7c-260b-41c6-abe7-4ae1aab659da)

![Image](https://github.com/user-attachments/assets/8a88a04c-3fbe-4268-b44a-b91de9f77923)

![Image](https://github.com/user-attachments/assets/bcb4ffd8-af69-4f38-a6ed-b0774bfb376d)

![Image](https://github.com/user-attachments/assets/74ff5343-9c7c-4a21-82a1-cb704d5a8eb6)

![Image](https://github.com/user-attachments/assets/1abcadf9-483c-46b9-a456-edd3a6b18c21)

## Version 3 (best so far)

[GalasaAccessTokenUIDesign-v3.pdf](https://github.com/user-attachments/files/16285710/GalasaAccessTokenUIDesign-v3.pdf)

[GalasaAccessTokenUIDesign-v3.docx](https://github.com/user-attachments/files/16285694/GalasaAccessTokenUIDesign-v3.docx)

## Version 2

[GalasaAccessTokenUIDesign-v2.pdf](https://github.com/user-attachments/files/16263221/GalasaAccessTokenUIDesign-v2.pdf)

[GalasaAccessTokenUIDesign-v2.docx](https://github.com/user-attachments/files/16263211/GalasaAccessTokenUIDesign-v2.docx)

## Version 1 (defunct)

[GalasaAccessTokenUIDesign.pdf](https://github.com/user-attachments/files/16190731/GalasaAccessTokenUIDesign.pdf)

[GalasaAccessTokenUIDesign.docx](https://github.com/user-attachments/files/16190726/GalasaAccessTokenUIDesign.docx)

# Tasks
- [ ] Create a design for how the listing of tokens in a table will be
- [ ] And how to revoke a token
- [ ] And an 'are you sure' dialog or similar

**Comment by techcobweb** [comment]
@lubelg I had a run-through with @jt-nti and we came to the conclusion that, given there are only 2-5 tokens at most, that they could be a list of tiles rather than a table.

That will also give us more room to do things like "Is this token stale?"

We also discussed that fact that IBM guidelines need an expiry date for tokens to be set, so it's likely we'll have more details on tokens in the future. That makes 4-5 attributes so far:
- Creation date
- Last used date
- Expiry date
- Name of the token
- Warning space that the token may be stale/not used, and could do with being deleted.

I will do another update to the mockups to save any confusion, and create a V3 shortly.

**Comment by techcobweb** [comment]
Updated the slides so it shows tiles now.

The only thing which came up since is being able to collect/edit the email address of the user, so we can email them when a token expires, or is about to expire.

**Comment by techcobweb** [comment]
Images of the figma flows added. Greg L has the originals.
