### ISSUE TITLE
Performance bug: galasactl runs get --age 2w takes a long time

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1921]
`galasactl runs get --age 2w` takes a huge amount of time, even though there are not loads of test records in the database.

Why is it taking so long ?

# Tasks
- [x] Couchdb extension always gets all the artifacts for all of the runs, rather than only doing that when we want a single run. 
- [x] Pagination and sort order fixes so the client doesn't ask for it all many times.
- [x] CLI changes to use new cursor-based pagination

**Comment by adamcoulthard** [comment]
From the rest I requested 500 test results on my page for a 2 week result and it seems to take a good 20 / 30 seconds to get the information back.  We only have about 600 tests over that period.

**Comment by techcobweb** [comment]
Seems that the query is passed to couchdb, but the date isn't indexed, so couchdb has a lot of work to do.

Answer: Add the date field as an index into the documents. That should speed it up.

eg: 
```
> galasactl runs get --age 120d:90d
...
Total:12013 Passed:1138 Failed:133 EnvFail:133 Active:10609   
0.10s user 0.05s system 0% cpu 1:21.26 total
```

**Comment by adamcoulthard** [comment]
@techcobweb is this something that we can do locally or do we need to wait for a fix from the galasa team?

**Comment by eamansour** [comment]
Fix released in 0.37.0
