### ISSUE TITLE
Onboard Ash

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1924]
# Story
As a Galasa developer I want Ash to be brought up to speed as fast as possible so he can contribute to the project.

# Tasks
- [x] System setup
- [x] Education
  - [x] Open source education
  - [x] Business conduct guidelines
  - [x] Internal team docs
