### ISSUE TITLE
Accept/ContentType header processing

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1925]
# Story
As an application developer coding an application which talks to the Galasa REST api I want to see in the documentation which ContentType mime types Galasa REST APIs accept, so that I can code my application accordingly.

As an application developer coding an application which talks to the Galasa REST api where I pass a payload to Galasa, I want Galasa to verify that it can process content of that mime type, in case I code something badly.

As an application developer reading the openapi documentation, I want to have listed the mime types that the server will accept, and the mime types that the server can return for each API call.

As an application developer coding an application which talks to the Galasa REST api, when I pass an Accept header which is not one of the supported types of responses Galasa can generate, then I want to see some failure rather than just get back a Json payload.

# Tasks
- [x] Make sure that every REST endpoint checks the Accept header for formats it can process.
- [x] Make sure that every REST endpoint returning a payload also sets the ContentType of that payload, and that content type is suitable for that request.
- [x] Make sure that distinct REST error codes are returned if this content type request negotiation fails.
- [x] Make sure the openapi.yaml documents each restriction/payload for each REST call.
