### ISSUE TITLE
Archive/remove the old 'buildutils' build and resources

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1928]
## Story
As a Galasa developer, I want to remove the old buildutils pipeline and resources, so that I can rely on the new ones and keep the codebase tidy.

## Background
The GH Actions workflow for the buildutils repo is ready and runs for PRs and Main builds. I want to remove the old buildutils build and any resources to rely on the workflow only. I also want to switch the downloadable URL to use the docker image from GHCR instead of Harbor.

## Tasks
- [x] Move the buildutils PR and Main build pipelines to a new directory `_archived` so it is not kept in sync by the ArgoCD app
- [x] Delete the dockerfiles in the automation repo
- [x] Switch the https://development.galasa.dev/main/binary/bld to pull from the image ghcr.io/galasa-dev/buildutils-executables:main image
- [x] Switch the current Tekton builds to use the buildutils GHCR images
