### ISSUE TITLE
Web UI shows the Galasa service name in the title bar

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1931]
# Story
As a galasa user, using several Galasa services, I want the UI to display the name of the service on the title bar, so my UIs don't all look the same.

# Background

We need to get the Helm user to put in a value into their helm chart values file.

The variable is called `galasa.service.name`
In the values file we provide, set it to `Galasa Service`

This value needs to be made available to the UI pod code as an environment variable.
Need to update the pod definition for the UI to include this new property, similar to the existing property `GALASA_API_SERVER_URL`. The environment variable should be called `GALASA_SERVICE_NAME`.

The UI can pick up the value to display from the environment variable.

Unit tests in the UI code are necessary.

If the helm user does not set it explicitly, it defaults to `Galasa Service`

The text should be centre-justified within the title bad, so the CSS needs changing to do that.

The service name should also be reflected on the tab when you look at it through chrome. This causes bookmarks of the URL to be recorded with the service name also.

# Tasks
- [ ] Helm chart values.yaml updates with docs inside there. Default to `Galasa Service`
- [ ] UI pod gets the extra environment variable.
- [ ] UI code displays the service name on the title bar. Defaulting it if the env var is not set.
- [ ] Chrome tab contains this service name also.
