### ISSUE TITLE
Trigger CLI (GH) from end of run-tests (Tekton)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1934]
## Story
As a Galasa developer, I want the CLI GH Actions workflow to be triggered after the prod1 ecosystem has been recycled and the run-tests pipeline has done an initial run of a test, so that the CLI code is tested against the newest API code now in the ecosystem.

## Background
In the current Tekton builds, after the recycle of the prod1 ecosystem, the CLI pipeline is triggered. This is done using the Tekton CLI. We now need to find a way to trigger the new CLI GH Actions workflow from the end of the recycle-prod1 pipeline, which will remain in Tekton.

## Tasks
- [x] Create task that triggers the CLI workflow using the GitHub CLI
- [x] Provide the necessary GitHub personal access token for this
- [x] The CLI Main build workflow will need a `workflow_dispatch` event to be able to be triggered with the GH CLI
- [x] Add task to the end of run-tests pipeline that triggers the CLI workflow using the GitHub CLI (merge in [this PR](https://github.com/galasa-dev/automation/pull/599/files) and sync up the Tasks and Pipelines in argocd)

**Comment by techcobweb** [comment]
@jadecarino Seems that we want to build the CLI before the Prod1 is deployed, so we have it there are ready to use to verify the installation went ok.
And we want to trigger a CLI test against the ecosystem after the Prod1 is deployed ?
ie: Two workflows for the CLI code: One to build the thing, and do local tests, and a second one to run tests against the ecosystem.
Thoughts on this ?

**Comment by techcobweb** [comment]
OR, we move the execution of the ecosystem tests into the same workflow that the Prod1 uses in tekton, and run them there, rather than in GH actions ?

Ideally we'd split the ecosystem tests into two
1. Those which don't need 3270
2. Those which do need 3270 (ie: The gherkin tests)

Then we can run the 3270 tests inside the IBM firewall (for now) as part of the tekton build, 
and run the (1) tests against the ecosystem1 system.

I think all we are missing for the ecosystem1 stuff is a set of property resources which get deployed, like the prod1 stuff. These can contain definitions of a stream, and of course the logic to deploy that.

Having the CLI tool available after helm install/upgrade would make it easy to deploy those properties.

Happy to discuss ...

**Comment by techcobweb** [comment]
Had a chat with @jadecarino just now.

Ignore my comments above for now pls. We'll do those later.

**Comment by jadecarino** [comment]
PR for this item [here](https://github.com/galasa-dev/automation/pull/599) - it has been approved and the build was successful, but waiting to merge it in when we switch over to GH Actions.
