### ISSUE TITLE
Build 'helm' with GitHub Actions pipeline

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1935]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for helm](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/helm) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Use GitHub actions to build the 'helm' repository for merges to Main only - create trigger from Helm to build-helm.yaml in automation
- [x] In build-helm.yaml - Use the Helm CLI to uninstall the ecosystem (task uninstall-ecosystem)
- [x] In build-helm.yaml - Use the Helm CLI to reinstall the ecosystem (task install-ecosystem)
- [x] In build-helm.yaml - Use the Helm CLI to test the ecosystem (task test-ecosystem)
- [x] (Jade) set up Kubeconfig secret in GitHub
- [x] (Jade) reactivate trigger when we fully move to GH Actions - disabled for now to avoid duplicate helm installs causing problems (see commented line [here](https://github.com/galasa-dev/helm/blob/main/.github/workflows/build.yaml#L10))

**Comment by jadecarino** [comment]
Waiting for 0.36.0 release to merge in PR: https://github.com/galasa-dev/helm/pull/41

**Comment by jadecarino** [comment]
The workflow is successful but I have got rid of the trigger so the GH and Tekton workflows don't run at the same time and cause issues with ecosystem1. I will reactivate the trigger (and close this item off) when we fully move to GH actions.
