### ISSUE TITLE
Ability to add properties into a CICSRegion during provisioning

### ISSUE THREAD

**Issue by adamcoulthard** [galasa-dev/projectmanagement#1937]
## Story
As a CICS Provisioning Manager, I want to be able to set properties on the CICSRegion that has been provisioned, so that other Managers / Tests can access information about the CICS region..

## Background
Our tests and potentially other managers we are creating will need to be able to access information about the CICSRegion.  At the moment there is no way to set properties onto the CICSRegion that another user (Manager / Test) could get access too.  For example a test wants to know what the HLQ of the CICS region datasets are for CICS / CPSM.

We would like to see the following method added to the ICicsRegion
```
/**
 * Allows a testcase to get a specific property about the region.
 * 
 * The list of properties supported will depend upon how the region was 
 * deployed/provisioned.
 * 
 * By default, no properties are supported, but each implementation of this
 * interface is free to provide tests with whatever values they wish to 
 * reflect this particular CICS region.
 * 
 * @param propertyName The name of the property for which the caller wishes to 
 * get a value.
 * 
 * @return A string value for the requested property, or null if that property
 * value is not available.
 * 
 * @throws CicstsManagerException
 */
public String getRegionProperty( String propertyName ) throws CicstsManagerException;
```

This would allow our implementation of the ICicsRegion which extends BaseCicsImpl to be able to hold a Map of properties to values that Tests / Managers could access.

## Tasks
- [x] Add the new method to the interface
- [x] Update all the managers which implement that interface
- [x] Make sure all the versions are uplifted

**Comment by techcobweb** [comment]
@adamcoulthard I've added a draft of what the UI would look like and how it would be documented.
I assume that's Ok to go ahead with ?

**Comment by adamcoulthard** [comment]
Looks great is the galasa team happy to implement?

**Comment by techcobweb** [comment]
I added the interface change to the 0.36.0 build code.

> Looks great is the galasa team happy to implement?
You want us to look at the sem manager and return some properties ? I think that's a non-open-source concern right ? We can discuss perhaps.
