### ISSUE TITLE
Build 'webui' with GH Actions

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1940]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for webui](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/galasa-ui) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Use GitHub actions to build the 'webui' repository for Pull Requests and Main builds
- [x] Pull down required dependencies with Gradle (task generate-api)
- [x] Manually fix the openapi client code (task fix-openapi-client)
- [x] Install the webui's dependencies (task npm-install-webui)
- [x] Run the webui's unit tests (task npm-test-webui)
- [x] Build the webui (task npm-build-webui)
- [x] Build a Docker image containing the webui (task docker-build-webui)
- [x] For PR build do not publish the Docker image
- [x] For Main build publish the image to GHCR

**Comment by jadecarino** [comment]
Waiting for 0.36.0 release to merge in PR: https://github.com/galasa-dev/webui/pull/47
