### ISSUE TITLE
Build 'integratedtests' repo with GH Actions

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1941]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for integratedtests](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/inttests) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Use GitHub actions to build the 'integratedtests' repository for Pull Requests and Main builds
- [x] Set up the JDK with Maven as the build cache
- [x] Set up Gradle
- [x] Reference the necessary secrets required for gradle and maven builds
- [x] Build the source code with Gradle (task branch-gradle-build-inttests)
- [x] Build the OBR with Maven (task branch-maven-build-inttests)
- [x] Build a Docker image with the artefacts inside (task branch-docker-build-inttests)
- [x] For the PR build do not publish the image
- [x] For the Main build publish the image to GHCR
- [x] For the Main build recycle the ArgoCD application (task recycle-deployment)
- [x] Then wait for the ArgoCD application to show as healthy (task wait-deployment)

**Comment by jadecarino** [comment]
Waiting for 0.36.0 release to merge in PR: https://github.com/galasa-dev/integratedtests/pull/199
