### ISSUE TITLE
Build OBR Generic artefacts in GH Actions

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1942]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for the "OBR Generic images"](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/obr-generic) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

The files required for these builds are contained in the OBR repository, so now that we are moving to GH Actions, the "OBR Generic" build will need to be a part of the OBR workflows. It can however be a separate job that should run after the main OBR job.

# Tasks
- [x] Use GitHub actions to build the obr generic artefacts (docker images) for Pull Requests and Main builds
- [x] Reference any necessary Secrets to be pulled into the workflow (Maven GPG signing)
- [x] Generate the OBR Generic pom.xml with galasabld (task generate-embedded)
- [x] Build the pom.xml with Maven (task maven-build-obr-generic)
- [x] Build the OBR Generic image (task docker-build-obr-generic)
- [x] Use the kubectl image (ghcr.io/galasa-dev/kubectl:main) to copy files from the kubectl directory into the obr-generic directory (task copy-files)
- [x] Build the boot-embedded Docker image (task docker-build-amd64-embedded)
- [x] Build the ibm-boot-embedded Docker image (task docker-build-ibm-embedded)
- [x] Only publish the images to GHCR for the Main builds
