### ISSUE TITLE
Build 'simplatform' with GH Actions

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1943]
# Story
As a contributor to the galasa open source project, I want builds to be in the open, and use github actions, so that I can see build logs, see built artifacts, benefit from integration with github actions, and all without using any resources within the secretive IBM firewall.

# Background
There are many benefits of moving our infrastructure to use github actions.
- Builds will be immediately kicked off, no 2-minute delay for them to start.
- build logs are available for ages
- built artifacts can be made available within the build results

Objectives:
- Now that we have learned more about GH Actions with the spike story #1719 , we can move on to recreating GH Actions builds for other components that are in the main build chain
- Side by side comparison with Tekton pipeline
- Try out the Docker registry

For reference, look at the [existing Tekton pipelines for simplatform](https://github.com/galasa-dev/automation/tree/main/pipelines/pipelines/simplatform) and the associated Tasks that it utilises, but remove/adapt Tasks as appropriate for GitHub actions.

# Tasks
- [x] Use GitHub actions to build the 'simplatform' repository for Pull Requests and merges to Main
- [x] Build the simplatform application code with Maven (task maven-build-simplatform-application)
- [x] Build the simbank tests with Maven (task maven-build-simbank-tests)
- [x] Build the simplatform maven repo Docker image (task docker-build-simplatform-repo)
- [x] Build the simplatform jar Docker image (task docker-build-simplatform-jar)
- [x] For PR builds do not publish the images
- [x] For Main builds publish the images to GHCR
- [x] For Main builds recycle the ArgoCD app

**Comment by jadecarino** [comment]
Waiting for 0.36.0 release to merge in PR: https://github.com/galasa-dev/simplatform/pull/160

**Comment by jadecarino** [comment]
Not closed this off yet as the builds (both GH and Tekton) are failing for Simplatform which I'll investigate tomorrow.

**Comment by jadecarino** [comment]
The Simplatform Tekton and GH builds are failing since upgrading the builds to use Java 17, but without upgrading the Maven versions to 3.9.+. The Tekton build uses Maven 3.8.7 and the GH build uses 3.8.8. Tekton can be updated, but I've been searching but cannot find a way to set the Maven version you want in a GH Actions build. Since it's using less than Maven 3.9, it's using the maven-war-plugin at 2.2, which is incompatible with Java 17.

To get the GH build working, I'll have to update the galasa-simplatform-application pom.xml to state which maven-war-plugin to use as 3.3.2. I'll then also need to update the galasa-simplatform-application version to 0.37.0 (currently 0.24.0) as there's just a change to the pom.
