### ISSUE TITLE
Web UI: Welcome panel shows customizable text from the Galasa system admin.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1947]
# Story
As a galasa web ui user I want to see some welcome text on the central panel when I first log on.

As a galasa sys admin, I want to be able to set my own welcome text which users will be able to read. eg: instructions, web locations of docs...etc.

# Background
Default text is found in the wireframes. See https://github.com/galasa-dev/projectmanagement/issues/1918

For example:
![Image](https://github.com/user-attachments/assets/818e66c7-3744-4efe-af18-13af752aa259)

How to set this text ? We will use a CPS property `service.welcome.markdown`

The value will be a block of markdown, which the client will process client-side.

Use the url /cps/service/properties/welcome.markdown

To set the value, use a file like this:
```
apiVersion: galasa-dev/v1alpha1
kind: GalasaProperty
metadata:
    namespace: service
    name: welcome.markdown
data:
    value: |-
      # Welcome !
      This is a long message
      spread over several lines
```

Then apply that using `galasactl resources apply -f <filename>`

Check that the `galasactl` tool should crop output on the summary view beyond 64 characters using "..."

Check that the `galasactl` tool should display the text (unformatted markdown) in the details view.

The `galasactl resources apply -f xxx` command should be able to take a multi-line piece of markdown text.

## Secondary story, which can be handled later... lets separate this out.
The galasactl tool needs adjustment to be able to set a value from a file:
```
galasactl properties set --name xxx --file <filename.md>
```

# Tasks
- [ ] Servlet returns the markdown out of the CPS
- [ ] `galasactl` summary format crops long values.
- [ ] `galasactl` details format shows long values.
- [ ] `galasactl set --file` is supported
- [ ] `galasactl resources apply -f` works with long input
- [ ] Web UI calls the servlet 
- [ ] Client can process markdown in the main panel
- [ ] Document this in the 'administering your Galasa service` section (which may not exist yet) in the galasa dev site docs.
