### ISSUE TITLE
Web UI: User can log out

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1948]
# Story
As a galasa web ui user, I want to be able to log out of the UI so nobody else can use my terminal while I go and have coffee.

# Background

Use needs to be able to log out

# Tasks
- [x] UI to have a 'profile' silhouette on the right of the title bar.
- [x] clicking the 'profile' silhouette shows a menu with 'logout' on.
- [x] Use clicking 'logout' will destroy the bearer token held in a cookie. So they have to log in again to get a new one.
- [x] Unit tests for all the above.
- [x] No external docs required.
