### ISSUE TITLE
Web UI : profile icon top-right launches a menu to a pretty blank "My Settings" page.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1949]
# Story
As a Galasa user I want to be able to navigate to a "My Settings" page which shows me some detail about myself, so I know which user ID I am logged in with.

# Background

This is a small part of an overall epic, detailed here: 
https://github.com/galasa-dev/projectmanagement/issues/1513

Just creating the page and showing a very small amount of information on it is good enough to provide some small value.

This will not require a new service endpoint holding the user information.
```
/api/users?name=me

```
Payload coming back should be:
```
[
  {
    "login_id" : "mikec@mydomain"
  }
]
```

A call to `/api/users` with no filter will get all the users on the system

The server should be able to interpret "me" into the current user (the owner of the JWT token).

This endpoint will be expanded later to include several things, like role, operations allowed...etc.

galasactl needs to be improved to show this information too. The galasactl tool needs to be maintained so that it can do everything any UI can.

```
$galasactl users get --id me
id: mikec@mydomain
```

"me" above is a special name, reserved to mean the owner of the token that the tool is configured with.

# Tasks
- [x] Servlet layer needs to return this information for the UI to display
- [x] openapi.yaml needs to reflect+document the new endpoint
-
- [x] The web UI needs a 'my profile' page attached to the top-right 'profile silhouette'.
- [x] The page should Show a "My Profile" header
- [x] The page should show a "login id" label and text field
- [x] The user can navigate from the "my settings" page to the "home" page and back at will
- [x] The title bar should have a Galasa symbol which gets you back to the home page

- [x] CLI supports `galasactl get user --name me`
