### ISSUE TITLE
Chain together GitHub Actions workflows

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1950]
## Story
As a Galasa build process, I want to call the next Galasa repo in the build chain after my workflow has finished, so that code changes make it all the way down the chain.

## Background
This is recreating the current build chain we have in Tekton that uses the tkn CLI, in our new GitHub Actions workflows.

## Tasks
- [x] wrapping > gradle
- [x] gradle > maven
- [x] maven > framework
- [x] framework > extensions
- [x] extensions > managers
- [x] managers > obr
- [x] obr > helm (main) - needs #1963
- [x] obr > recycle ecosystem (main) - needs #1933 
- [x] recycle ecosystem > run tests (main) 
- [x] run tests > cli (main) - needs #1934 
- [x] obr > cli (release) - needs #1964 
- [x] cli > isolated - needs #1966
