### ISSUE TITLE
Release notes for 0.36.0

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1953]
# Story
As a Galasa user I want to refer to the release notes to see if I want to upgrade to use the latest version.

# Background

# Tasks
- [ ] update the docs in the release notes
  - [ ] Mention Galasa CPS over rest from local to remote systems and that it can create a local cache of values to speed up local test runs.
  - [ ] Mention that Galasa now supports Gradle v8.x. Testcases can now use more recent versions of Gradle to align with build of other software.
  - [ ] Gherkin improvements in terms of scenario outlines being supported and sizes of 3270 terminals are configurable with CPS properties or from within the scenario itself.

**Comment by techcobweb** [comment]
@jt-nti I think this story can be closed now ?
