### ISSUE TITLE
Trigger Helm from end of OBR build (if main)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1963]
## Story
As a Galasa ecosystem(1), I want to be uninstalled and reinstalled after code changes have been rebuilt into the OBR runtime images, so that I can have access to the latest Galasa code.

## Tasks
- [x] Create a new job at the end of the OBR Main build workflow that only runs if the `github.ref` is `main`
- [x] Use the GitHub CLI to trigger the build-helm.yaml workflow that sits in the automation repo
- [x] The Helm Main build workflow will need a `workflow_dispatch` event to be able to be triggered with the GH CLI
- [x] (Jade) Uncomment out this trigger when we fully move to GitHub Actions (see commented line [here](https://github.com/galasa-dev/obr/blob/main/.github/workflows/build.yaml#L530))
