### ISSUE TITLE
Trigger CLI from end of OBR build (if not main)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1964]
## Story
As a Galasa release process, I want the CLI build (and subsequently the Isolated build) to be triggered after the OBR build to link together the main build chain to build all Galasa components for the release.

## Tasks
- [x] Add a new job to the end of the OBR workflow to run only if the `github.ref` is **not** `main`
- [x] Use the GitHub CLI to trigger the CLI main build (`cli/.github/workflows/build.yml`) ensuring to pass through the `github.ref` with  the`--ref` flag
- [x] The CLI Main build workflow will need a `workflow_dispatch` event to be able to be triggered with the GH CLI
