### ISSUE TITLE
Enhance Gradle build GitHub workflows

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1965]
## Story
As a Galasa contributor, I want to see as much output from the Gradle builds and be able to access the log and JUnit HTML report, so that I can diagnose and debug any build issues that might occur.

## Background
We have just completed the Gradle uplift for Galasa meaning Galasa source can be built with Gradle 8+ as well as 6. Whilst making the requested enhancements from Mike, we should upgrade the version of Gradle we are building with to 8.9 in the same PR.

Workflows with Gradle steps:
- [x] gradle
- [x] framework
- [x] extensions
- [x] managers
- [x] cli
- [x] webui
- [x] integratedtests

## Tasks (complete for all Gradle-based workflows)
- [x] Add the `--info` flag to the Gradle commands to see the exact cause of any failures
- [x] Export the Gradle text log and use the upload-artefact action to upload it to the workflow so the actions user can see if anything went wrong
- [x] Upgrade the version of Gradle used to 8.9 from 6.9.2 in the setup-gradle step
- [x] Upgrade the version of Java used to 17 from 11 in the setup-java step
