### ISSUE TITLE
Enhance Maven build GitHub workflows

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1967]
## Story
As a Galasa contributor, I want to see as much output from the Maven builds and be able to access the log and JUnit HTML report, so that I can diagnose and debug any build issues that might occur.

Workflows with Maven steps: 
- [x] wrapping
- [x] maven
- [x] obr
- [x] isolated
- [x] integratedtests
- [x] simplatform

## Tasks (complete for all Gradle-based workflows)
- [x]  Add the `-X` flag to the Maven commands to enable debug level logging so users can see the exact cause of any failures
- [x] Export the Maven text log and use the upload-artefact action to upload it to the workflow so the actions user can see if anything went wrong
- [x] (If available as unsure how many of the Maven-based repos have unit tests) Export the HTML report produced for any JUnit tests and use the upload-artefact action to upload to the workflow also
- [x] Upgrade the version of Java used to 17 from 11 in the setup-java step
