### ISSUE TITLE
Wrapped jars should all be versioned in same way as regular galasa jars.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1968]
# Story
As a galasa developer I want the same versioning rules to apply to all bundles, including the wrapping bundles.
Whenever something changes the bundle version should be bumped up to the latest version that is not yet released, so 
that the rules are more consistent, and it's easy to tell which bundles should be delivered to maven central.

# Background
The wrapping bundles are at a version which is representative of the things which are wrapped inside them.

This is OK to a point, but actually the rest of Galasa has a versioning scheme we use which could be consistently adopted in this
area also.

The suggestion is to change the names of the currently-wrapped bundles, in order that we can re-set the version of them.
All things which depend on them will need to be changed.

We can flow this through the various wrapping bundles individually.

- com.auth0.jwt 4.4.1 --> renamed to wrapped.jwt v0.37.0
- com.google.gson 2.10.1 --> renamed to wrapped.gson v0.37.0
- com.jcraft.jsch 0.1.55 --> renamed to wrapped.jsch v0.37.0
- io.gprc.java 1.60.0 --> renamed to wrapped.grpc v0.37.0
- jakarta.transaction 2.0.1 --> renamed to wrapped.transaction v0.37.0
- kafka.clients 3.7.0 --> renamed to wrapped.kafka.clients v0.37.0

# Tasks
- [x] com.auth0.jwt
- [x] com.google.gson
- [x] com.jcraft.jsch
- [x] io.gprc.java
- [x] jakarta.transaction
- [x] kafka.clients
