### ISSUE TITLE
Add kubeconfig as a Secret in the galasa-dev org on GitHub

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1970]
## Story
As a Helm install process, I want to get the kubeconfig as a Secret from GitHub, so that I can authenticate and connect to the Kubernetes cluster hosting the Galasa ecosystem1.

## Background
The [Helm install workflow](https://github.com/galasa-dev/automation/blob/main/.github/workflows/build-helm.yaml) has been created and placed in the automation repo to keep it in the same repo with the other resources needed for ecosystem1. It is missing the kubeconfig file as a Secret that can be pulled in and used in the workflow. Without, the current output is this: https://github.com/galasa-dev/automation/actions/runs/10386334945/job/28757397808 as it doesn't know what K8s cluster its meant to connect to, and needs this also for authentication.

## Tasks
- [x] Get the kubeconfig as a whole from the kubeconfig externalsecret and insert the confidential certificate information
- [x] Store the whole file in the galasa-dev Secrets in GitHub
- [x] Run the build-helm.yaml workflow to test the config is pulled into the workflow
