### ISSUE TITLE
Implement a "lock" system to avoid multiple workflows from redeploying dev ecosystems at once

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1971]
## Story
As a Galasa developer, I want the build process to have at most one workflow redeploying our development ecosystems (prod1 and ecosystem1) at once, so that running workflows don't clash and cause build failures.

As a Galasa developer, I want the development ecosystems to remain active during CLI builds, so that the CLI builds can run tests against an ecosystem and do not attempt to contact an ecosystem while its down.

## Background
When multiple main builds are running at the same time, they end up triggering multiple pipelines to redeploy prod1 and ecosystem1, as well as CLI builds.

The helm pipeline starts failing because some runs are installing ecosystem1, while others are uninstalling it. CLI builds also start failing because prod1 gets redeployed when the CLI builds are trying to run commands against prod1.

It would be good to implement a "lock" system that makes sure that only one pipeline that redeploys ecosystem1 and prod1 is running at once. This system should also prevent prod1 from being redeployed during a CLI build. Same goes for the inverse: CLI builds shouldn't be triggered during prod1 redeployment.

## Tasks
- [ ] Look into how we can lock GH Actions workflows from triggering CLI builds during prod1/ecosystem1 redeployments and vice versa
- [ ] Make the necessary changes to the GH Actions workflows based on the findings above
- [ ] Implement a lock mechanism in Tekton so that at most one recycle-prod1 pipeline is running at once
