### ISSUE TITLE
Add test tags to the JSON test report produced by Galasactl

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#1974]
## Story
As an infrastructure admin I want to be able to create a dashboard showing the number of tests passing and failing per "test area". This needs to be able to recieve the JSON test reports produced by Galasactl and sort them into separate graphs per test tag. 

## Background
Tests can be selected by tag using the "--tags" flag in Galasactl

eg: 
```
galasactl runs submit ... --tags tag1,tag2,tag3
```

or another way of doing the same thing.
```
galasactl runs submit ... --tags tag1 --tags tag2,tag3
```

The test runs get reported as having tag1, tag2 and tag3 associated with

## Tasks
- [x] CLI to be able to supply the runs submit with a set of test tags. Duplicates are ignored. Order is not important.
- [x] The runs submit rest call accepts the tags
- [x] The list of tags is maintained in the dss
- [x] The list of tags gets dumped into the teststructure in the RAS
- [x] galasactl runs get --age 1d will return the tag information and display it.
- [x] The REST call which gets active runs by group will return the tags also
- [x] The test runner will harvest tags embedded within the java code also, and add them to the list of tags associated with this test run.
- ~~`galasactl runs get --age 1d --tags tag1,tag2,tag3` will return the test runs only with any of the tag1, tag2, tag3 specified.~~ scope moved to separate story so we can close this one off.

This function was delivered in release 0.41.0

**Comment by Mark-J-Lawrence** [comment]
@mike-cobbett throwing this into the mix, a bit late I know. But there is also a `@Summary` annotation which also might be as helpful as passing `@Tags` around.
It contains a brief description of the test, but I think it would be a good addition. if devs populated this, it could easily end up in the test case descriptions in Test Rail....which can be done if the summary is in the test report/test run rest requests etc

**Comment by techcobweb** [comment]
See https://github.com/galasa-dev/galasa/pull/275

**Comment by techcobweb** [comment]
Tags are now working on Prod1 for test queries:
```
>galasactl runs get --age 1d
submitted-time(UTC) name   requestor               status   result    test-name                                                                                           group                                tags
2025-05-01 09:41:41 C22852 Galasadelivery@ibm.com  finished Passed    dev.galasa.inttests.core.local.mvp.CoreLocalJava11UbuntuMvp                                         7e3eafb1-e52b-4f72-a2b1-5d42586e2ea2 
2025-05-01 09:41:41 C22850 Galasadelivery@ibm.com  finished Passed    dev.galasa.inttests.simbank.local.SimBankLocalJava11Ubuntu                                          7e3eafb1-e52b-4f72-a2b1-5d42586e2ea2 codecoverage
2025-05-01 09:41:41 C22849 Galasadelivery@ibm.com  finished Passed    dev.galasa.inttests.simbank.local.isolated.SimBankLocalJava11UbuntuIsolated                         7e3eafb1-e52b-4f72-a2b1-5d42586e2ea2 
2025-05-01 09:41:41 C22848 Galasadelivery@ibm.com  finished Passed    dev.galasa.inttests.compilation.offline.mvp.CompilationLocalOfflineJava11UbuntuMVP                  7e3eafb1-e52b-4f72-a2b1-5d42586e2ea2 
2025-05-01 09:41:41 C22847 Galasadelivery@ibm.com  finished Passed    dev.galasa.inttests.core.local.isolated.CoreLocalJava11UbuntuIsolated                               7e3eafb1-e52b-4f72-a2b1-5d42586e2ea2 
2025-05-01 09:41:41 C22846 Galasadelivery@ibm.com  finished Passed    dev.galasa.inttests.artifact.local.mvp.ArtifactLocalJava11UbuntuMvp                                 7e3eafb1-e52b-4f72-a2b1-5d42586e2ea2 
2025-05-01 09:34:25 C22844 mike_cobbett@uk.ibm.com finished Passed    dev.galasa.ivts.core.CoreManagerIVT                                                                 mcobbett-1                           core,ivt,singletest
2025-05-01 08:38:49 C22843 mike_cobbett@uk.ibm.com finished Passed    dev.galasa.ivts.core.CoreManagerIVT                                                                 mcobbett-1                           core,ivt
2025-05-01 08:37:13 C22842 mike_cobbett@uk.ibm.com finished Passed    dev.galasa.ivts.core.CoreManagerIVT                                                                 mcobbett-1                           core,ivt
2025-05-01 08:35:32 C22841 mike_cobbett@uk.ibm.com finished Passed    dev.galasa.ivts.core.CoreManagerIVT                                                                 mcobbett-1                           core,ivt
2025-05-01 06:00:28 C22840 Galasadelivery@ibm.com  finished Passed    dev.galasa.zos.ivts.zos.ZosManagerFileVSAMIVT                                                       8c56348c-579f-415b-90eb-bd3146ea7e69 
2025-05-01 06:00:28 C22838 Galasadelivery@ibm.com  finished Passed    dev.galasa.zos.ivts.zos.ZosManagerFileIVT                                                           8c56348c-579f-415b-90eb-bd3146ea7e69 
2025-05-01 06:00:28 C22837 Galasadelivery@ibm.com  finished Passed    dev.galasa.zos.ivts.zos.ZosManagerBatchIVT                                                          8c56348c-579f-415b-90eb-bd3146ea7e69 
2025-05-01 06:00:22 C22836 Galasadelivery@ibm.com  finished Passed    dev.galasa.zos.ivts.zos.ZosManagerTSOCommandIVT                                                     830ffeb5-055b-4087-8c05-8e4fbaf7e425 
```
