### ISSUE TITLE
Web UI: Show table view of access tokens in a my settings page

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1976]
# Story
As a Galasa web UI user I want to see a list of access tokens I own, adding and removing items from the list, so I can control who has my user access.

# Background
The UI has a 'person' icon top-right. I can select this and see the 'my settings' option.

On the 'my settings' page I can see a list of tiles where each tile represents a personal access token.

I can use the '+' button to add a token, which causes the token to appear in the list.

I can see a disabled '-' button. When I select a token, this button is now active.

Clicking an active '-' button brings up a warning "are you sure" dialog.

Hitting OK on the dialog causes the token to be removed.

The web UI already provides a way of querying the tokens owned by this user.

Servlet layer which supports getting all tokens is changed to add a filter such that only tokens from a specific `login_id` are returned.

# Tasks
## Servlet tasks
- [x] User can supply a filter to the querying of access tokens, so the UI can request only tokens from a specific `login_id`.

## CLI tasks
- [x] User can supply a filter to limit which access tokens are displayed, using the `--login_id xxx` options on the `galasactl tokens get --login_id xxx`

## Web UI tasks
- [x] `My Settings` option appears on the personal menu and launches the `My Settings` page.
- [x] User can read some text about what a token is.
- [x] User can see existing tokens
- [x] User can use the '+' button to create a new token, which appears on the list.
- [x] User can select a tile and the '-' button un-greys
- [x] User can use the '-' button to remove a token, which disappears from the list.
- [x] User can select multiple tokens at once and delete them all in one go.
- [x] Each token shows the description for that token
- [x] Each token shows the date the token was created

**Comment by techcobweb** [comment]
We have a review with a UI designer on Friday. Lets leave this story open to mop-up any small tweaks he suggests.

**Comment by techcobweb** [comment]
Does the external documentation need an update ? as the button to create the new token moved to the settings page.

**Comment by techcobweb** [comment]
External docs updates ready when we next ship a release. See https://vnext.galasa.dev/docs/ecosystem/ecosystem-authentication
