### ISSUE TITLE
Galasa runs clean on various scan technologies

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1987]
# Story
As a Galasa user I want to be assured that Galasa has no security issues, based on reports which I can read about the codebase.

# Background
Various scan technologies exist, some of which Galasa should adopt into it's build processes.

The scans against Galasa code should be clean, or fairly clean with explainable exceptions.

Technologies include:
- Dependabot (enabled and clean on all repositories).
- Snyk
- IBM-internal tools as required
- Linux foundation scans
- Detect secrets tooling

# Tasks
- [ ] Dependabot should run cleanly with no suggested upgrades/fixes
- [ ] Snyk should run cleanly with no suggested fixes/upgrades
- [ ] IBM-internal tools should report cleanly for Galasa code
- [ ] Linux foundation scans should report cleanly for Galasa code
- [ ] Detect secrets tool should run before code is checked-in on every developers machine, during PR builds, during main builds.
