### ISSUE TITLE
Create an installer for Galasactl for Windows

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1989]
# Story
As a windows user I want a simple way to install Galasactl onto my machine, having an installer which can install (and update) the galasactl binary, so I don't have to worry about setting my Path, downloading, or checksum-checking the binary before I can use it.

# Background
Installing the `galasactl` tool onto a Windows machine could be easier. Lets try to make it easier.

# Tasks 
- [ ] Download an installer program rather than the binary tool itself.
- [ ] Create a readme to signpost users to information on how to use it further.
- [ ] Add the tool to the path, so the user doesn't have to.
- [ ] Enable updates to the tool if possible
- [ ] Tool checks the checksums of the binaries installed
- [ ] Build process (github actions) creates the program (extending an existing GH actions flow)
- [ ] User has fewer clicks to install the code on Windows
- [ ] Record a demonstration, and download/install instructions for the installer.

**Comment by eamansour** [comment]
[Chocolatey](https://chocolatey.org/) or [Scoop](https://scoop.sh/) could be worth investigating over a custom installer

Alternatively, [Inno Setup](https://jrsoftware.org/isinfo.php) is popular for building installers.
