### ISSUE TITLE
Create an installer for Galasactl for Linux

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#1990]
# Story
As a linux user I want a simple way to install Galasactl onto my machine, having an installer which can install (and update) the galasactl binary, so I don't have to worry about setting my Path, downloading, or checksum-checking the binary before I can use it.

# Background
Installing the `galasactl` tool onto a Windows machine could be easier. Lets try to make it easier.

# Tasks 
- [ ] Use the command-line tooling to download and install the tools (eg: yarn or other packageing managers)
- [ ] Create a readme to signpost users to information on how to use it further.
- [ ] Add the tool to the path, so the user doesn't have to.
- [ ] Enable updates to the tool if possible
- [ ] Tool checks the checksums of the binaries installed
- [ ] Build process (github actions) creates the program (extending an existing GH actions flow)
- [ ] User has fewer clicks/keystrokes to install the code on linux
- [ ] Record a demonstration, and download/install instructions for the installer.
- [ ] Update/suggest updates to the galasa documentation.
