### ISSUE TITLE
Release 0.37.0

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#1991]
## Story

As a galasa user I want to get the 0.37.0 release so that I can use the new functionality it offers, including Java 17 support.

## Tasks
- [x] Run through the pre-release process
- [x] Run through the release process documented here: https://github.com/galasa-dev/automation/tree/main/releasePipeline.
- [x] Identify problems/improvements and raise them for next time

**Comment by jt-nti** [comment]
Is this release process documentation still relevant? If not, I can create a PR to remove it.
https://github.com/galasa-dev/projectmanagement/tree/main/releasePipeline

**Comment by eamansour** [comment]
It definitely looks like those docs are out of date.

@jadecarino just to confirm, can you think of a reason not to remove the release docs from the projectmanagement repository?

**Comment by jadecarino** [comment]
@eamansour @jt-nti Hi both, no I see no reason why we can't delete those as they are very out of date. Thanks James for spotting that.
