### ISSUE TITLE
Remediate security advisories on Linux VMs (by 18th October)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1995]
## Background
The Linux VMs we use for our integration tests have security advisories and will be locked on **Friday 18th October** if not remediated.

## Tasks
- [x] Run the patch security scan on the Linux VMs in Openstack
- [x] Attempt auto patching
- [x] Create key pair on Openstack and upload to gain access to VMs
- [x] Fix out of date packages on gallnx01, gallnx02, gallnxi1, galasa-test and dkrengine01
- [x] Fix password policy on gallnx01, gallnx02, gallnxi1, galasa-test and dkrengine01

**Comment by SneakPeak2003** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler
