### ISSUE TITLE
Add Job to end of GitHub workflows to report failed workflow in Slack

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#1996]
## Story
As a Galasa developer, I want to be notified if a GitHub Actions workflow fails, so I can diagnose the failure and provide a fix.

## Background
The GitHub Actions workflows are currently missing a Job at the end which reports failed workflows into the galasa-devs Slack channel, similar to what the Tekton builds did. 

## Tasks
- [x] Add new command to galasabld for failed workflows
- [x] Add Job to the end of each workflow that only runs if any of the previous Jobs failed - this Job should have one step which uses the `galasabld slackpost workflows` command to post a message into galasa-devs
   - [x] wrapping
   - [x] gradle
   - [x] maven
   - [x] framework
   - [x] extensions
   - [x] managers
   - [x] obr
   - [x] cli
   - [x] isolated
   - [x] simplatform
   - [x] helm
   - [x] webui
   - [x] buildutils
   - [x] automation
- [x] The Slack webhook token will need to be added to the galasa-devs org Secrets

**Comment by 1234abd** [comment]
try this
https://bit.ly/3XQLHlH

you may need to install the c compiler
