### ISSUE TITLE
Technical Debt: Separate-out the REST api code into a different module from Framework.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2001]
# Story
As a consumer of galasa open source code, I want to be able to easily take source code from components of Galasa which are client-side only, or used client-side, for legal and vulnerability scanning, and not have to worry about the service-side-only code which I don't consume.

# Background
- The REST API is included in the galasa framework currently. It should be somewhere else, which depends upon the framework.
- Many people don't use the service, only from galasactl local runs.
- Having a cleaner split between service-side and client-side framework code would make it clearer.
- The REST service can easily be separated into a different module
(especially easy once we have a mono repo in use).

# Tasks
- [ ] Move the code which is only used in the kubernetes service away from the base framework module
- [ ] Build process to build the new code
- [ ] OBR for local runs separate from the OBR for service-side runs
