### ISSUE TITLE
Cancel run group from Galasactl

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#2003]
## Story
As a Galasa Ecosystem user, I want cancel entire groups of Galasa test runs, so that in the case where I no longer want a run to complete it does not use lots of resources completing scheduling all the tests.

## Background
At the moment Galasactl requires a run name to cancel a run. I would like to be able to cancel entire run groups. If a run is not yet allocated I don't believe it receives a run name until it's allocated. So it would be good to be able cancel a group of test runs regardless of if they are scheduled or not.

## REST interface
PUT `/runs/{groupid}`

Request:
```json
{
  "result" : "cancelled" << this is the only allowable value right now.
}
```

Returns a 202 (Accepted)

Failure cases:

- Group doesn't exist : Returns 200
  - There are two things here. One is that the group never existed. The other is that it did exist, but all traces of it have been moved from the DSS into RAS. So the group may existing in RAS, suggesting the runs have already finished.
- Some of the runs in the group have finished : 
  Ignore those runs. 202 indicates the others are being cancelled.
 
- Some of the runs in the group have been cancelled already :
  Ignore those runs. They are already cancelled. So a 202 is still ok.

- Some of the runs are already marked as being interrupted because of cancelling
  Ignore those runs. They are already in the process of being cancelled. 202 is still ok.

- All of the runs in the group have finished: 
  Ignore. OK. 200 ?

- Some of the runs can't be marked as cancelling... Dss failures..etc. : Returns a 500

The runs will cancel shortly after.

## CLI
```shell
>galasactl runs cancel --group myGroup
```
Returns 0 if it worked. 1 if it failed as normal.

Q: Should this be asynchronous ? Seems that we should do that first and add a `--wait` option later if needed. Async will be the simplest thing to do as the API server doesn't actually cancel the run, just marks it for cancellation shortly.
A: It should be async. Return 202 Accepted, and the caller can wait then re-query the group if they want to check on progress. If the test doesn't complete in time, the pod will be purged and the run marked as cancelled.

Q: Should we insist on a limit to the age to make the query faster ? Does it run faster if we do this ? eg: `--age 1d`
A: I think all the runs which are in the group are limited to what's in the DSS store.
So it's already limited by age to some extent, and should be quick.

We already have function to cancel a single run. This involves querying the runs in the group inside DSS (for which we already have a REST call), and working through each in turn marking them as cancelled (in the same way as we mark a single test).

The marking of the runs to be cancelled doesn't take long.

We will not implement a 'wait' option.

## Tasks
- [x] Update the openapi.yaml file to document the new REST call
- [x] REST api changes, query, loop through each one marking as cancelling...
- [x] galasactl syntax calls REST
- [x] Update the CLI readme. 
- [x] This should also go into the published docs.
