### ISSUE TITLE
Recycle prod1 and ecosystem1 after updates to the Web UI

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2007]
## Story
As a Galasa ecosystem, I want to be redeployed when there are updates to the Galasa Web UI so the latest authentication flows can be used.

## Tasks
- [x] Trigger the [Helm build](https://github.com/galasa-dev/automation/blob/main/.github/workflows/build-helm.yaml) workflow at the end of the [webui build.yaml](https://github.com/galasa-dev/webui/blob/main/.github/workflows/build.yaml) using the GitHub CLI
- [x] Conditionally do this based on the github org. So forking users will still have a viable build process.
- [x] Add trigger to [recycle-prod1 Tekton pipeline](https://github.com/galasa-dev/automation/blob/main/pipelines/pipelines/recycle-ecosystem/recycle-prod1.yaml) following successful completion of the [webui build.yaml](https://github.com/galasa-dev/webui/blob/main/.github/workflows/build.yaml) using the GitHub CLI
   - [x] As this is going from GitHub to Tekton, this will either need a new EventListener the same as "github-obr-workflow-completed-listener" but for the webui, or that EventListener will need to be updated to also trigger if the repo is "webui"
