### ISSUE TITLE
Update Token revoke UI based on comments from UX review

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2008]
# Story
As a user trying to manager my Galasa access tokens, I want the UI to be clearer, so it's easier to follow what I'm doing.

# Background
We had a review of the Galasa web UI with Greg L. Here are the notes I took of the changes he is suggesting:

# Tasks
- When you create the personal access token, a dialog appears:
  - [x] Change the title to "Create Galasa Person Access Token"
  - [x] Change the button "submit request" to "Create"
  - [x] Add text "You are about to allocate a new token, please give the token a name" above the text box in the text above
 - When you create a token, you get the info to copy-paste dialog...
   - [x] Add text like "If the file does not exist... run the following command in a terminal to create one" ie: in a terminal.
   - [x] Copy-button for the `galasactl local init` command should be the same as the copy button above. And the pop-up text to copy it should be removed. We only want one copy-button way of doing things, and the explicit button to hit is better.
   - [x] "Remember to copy the details above before closing this dialog" or similar needs adding.
 - When deleting a token... in the warning dialog
   - [x] "and whatever used the token will need to be re-configured to use a replacement" or similar.
 - When selecting tokens to delete... 
   - [ ] Only one token should be selectable (radio button instead of checkbox).
   - [ ] Only one token should be deleted at once
   - [ ] Button to delete should be a (red) '-' only active if a token has been selected.
   - Q: If you first select a token to delete, but chicken-out, how to you un-select a radio button ? Are we going to have to stay with check-boxes but only allow one to be selected ?
 - Once these changes are complete, we should give Greg the URL of our ecosystem1 and let him have a play to tell us which wording for the text he prefers/wants changed.

**Comment by aashir21** [comment]
The user of radio buttons instead of check boxes could potentially ruin UX, as a mentioned by Mike above, if the user changes their mind after selecting a token, how would they uncheck it? They will have to refresh the screen which would ruin the user experience.

**Comment by techcobweb** [comment]
I think we will have to go for another round of review with Greg, and raise a new story on the back of that
Lets close this one and move on.
