### ISSUE TITLE
PSIRT: protobuf-javalite (due 31/12/24)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2015]
## Background
There is a PSIRT advisory for the com.google.protobuf:protobuf-javalite:3.24.0 which is a dependency of the dev.galasa:io.grpc.java wrapper artefact. 

## Tasks
- [x] Remove dependency if it is not needed
- [x] If it is needed, upgrade to a version without the CVE
- [x] Run Dex locally to verify nothing is broken
- [x] Deliver fix
- [ ] Complete a release (DfG)

**Comment by techcobweb** [comment]
The fix is in the codebase now I believe.

**Comment by jadecarino** [comment]
PSIRT has been marked as "will not fix" by legal.
