### ISSUE TITLE
Prepare for GSE UK 2024 presentation

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2016]
## Tasks
- [x] Update presentation title
- [x] Update presentation abstract
- [ ] Create Powerpoint slides (download new slide template)
- [x] Prepare demos and practice
   - [x] brew install of galasactl
   - [x] creating a test project
   - [x] writing a test
   - [x] running locally
   - [x] delivering to GitHub and running locally in a CI/CD pipeline
