### ISSUE TITLE
Remediate network vulnerability of dkrengine01 (by 19th October)

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2017]
## Background
The Linux VM we use for the DockerLocalJava11Ubuntu integration test has a network vulnerability on it and will be locked on **Sunday 19th October** if not remediated. The vulnerability needs to be fixed on the machine but this might require updates to the Docker Manager as the way it makes calls to the Docker API might need to be more secure than they are currently.

## Tasks
- [x] Look at the Docker Manager to understand how it uses the Docker API to do things on the VM
- [ ] Update Manager code if required to work with fix to the VM
- [x] Fix Remote Docker API issue on dkrengine01
- [x] Run new network scan to see if issue fixed
- [ ] Repeat as required
- [ ] Run test and confirm everything works

**Comment by jadecarino** [comment]
Looking into the run.log and artifacts for the DockerLocalJava11Ubuntu test, it didn't look like it was actually using the DKRENGINE01 VM so I paused it on Openstack and reran the test, and again it was successful. This must mean the VM is not actually being used as we thought. I have gone ahead with fixing the vulnerability anyway but have not changed any Docker Manager or test code as it appears to work as is, using whichever VM it uses. I have reran the network scan to see if the issue is fixed which should come back in a few hours.
