### ISSUE TITLE
Query runs based on the run group used to launch them

### ISSUE THREAD

**Issue by adamcoulthard** [galasa-dev/projectmanagement#2027]
## Story
As a Tester, I want my tests to be grouped by the runs, so that its easier to display in a front end.

## Background
At the moment when we run a test we use the run group to queue it up. Once all the tests have finished it's not possible to see how the tests were grouped.  It would be really helpful to be able to group these still.  I could image the following queries would help in the long term but just having the run group in the ras would help.

GetRunsByGroupId - Passing in a group Id and returning a list of test runs in that group
CLI:
```shell
> galasactl runs get --group myGroup --age 1d
```
If you specify the group flag, we don't need any age flag or name

REST API:
This would be an extra parameter on the runs get call.

~~SearchGroupId - Passing in a userid and optionally start date / end date and returns all group ids for that user.~~
> This is a separate requirement, so will not be tackled here, but will be described in this issue: https://github.com/galasa-dev/projectmanagement/issues/2032

## Tasks
- [x] make sure the groupid is stored in the run record
- [x] new view to allow quick searching for records with that groupid
- [x] Define the rest interface and get that reviewed for the extra query parameter
- [x] Implement the rest logic for the query with the extra parameter
- [x] CLI changes
  - [x] new parameter to runs get 
  - [x] new field in the output formats - runs get should show the group of each run
- [x] test script added to the test-ecosystem tests
- [x] try with the older client to see if there are problems we need to warn people about.
- [x] External documentation for the new parameter.
- [ ] Mark getRunsByGroupId method as deprecated and tell its replacement.
  - Eamonn: Where is this method? Can't see it in the framework or in the CLI, so has this already been done?
