### ISSUE TITLE
Bundles need to be upgraded

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2028]
# Story
As a user of Galasa I want to know that the latest vulnerability-free versions of the code it depends upon are being used, so I can be more confident in the safety of using the galasa tools and systems.

# Background
Some of our dependencies are out of date, and need updating.

# Tasks
- [x] Javadoc vulnerabilities, upgrade jszip.js and jszip.min.js to 3.8.0
  - [x] galasa-simplatform-javadoc - Eamonn: this was found within the MVP in `maven/dev/galasa/galasa-simplatform/0.24.0/galasa-simplatform-0.24.0-javadoc/jquery/jszip/dist/` - the 0.38.0 javadoc jar no longer contains this.
  - [x] gson-javadoc - Eamonn: latest version is still vulnerable, the Galasa team can't do anything here
  - [x] jakarta.activation-javadoc - Eamonn: jakarta.activation is no longer used now that jakarta.xml.bind-api has been uplifted, removed in https://github.com/galasa-dev/galasa/pull/62

- [x] guava-jre 30.1.1-jre - upgrade to 32.0.1-jre or later
- [x] jakarta.xml.bind-api 3.0.0 - upgrade to 4.0.2
- [x] commons-logging 1.2 - upgrade to 1.3.4
- [x] velocity-engine-core 2.3 - upgrade to 2.4.1
- [x] jose4j-0.9.2.jar - dependency of [io-kubernetes:client-java:17.0.0](https://mvnrepository.com/artifact/io.kubernetes/client-java/17.0.0), upgrade to [22.0.0](https://mvnrepository.com/artifact/io.kubernetes/client-java/22.0.0)
- [x] protobuf-java-3.21.10.jar - dependency of [io-kubernetes:client-java:17.0.0](https://mvnrepository.com/artifact/io.kubernetes/client-java/17.0.0), upgrade to [22.0.0](https://mvnrepository.com/artifact/io.kubernetes/client-java/22.0.0)

- [x] slf4j-ext-1.7.25.jar : upgrade to org.slf4j:slf4j-ext:1.7.26,1.8.0-beta2 - Eamonn: Upgraded log4j-slf4j-impl to 2.24.1 alongside the log4j-core as suggested

- [x] bcprov-jdk18on-1.75.jar - Eamonn: Upgraded to 1.79

- [x] logging-log4j2-log4j-2.17.1 - Eamonn: Upgraded to [2.24.1](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.24.1)
  - [x] framework < It's the boot jar !
  - [x] managers
  - [x] extensions
  - [x] obr

- [x] kafka-clients-1.1.1.jar : upgrade to org.apache.kafka:kafka-clients:2.1.1 - Eamonn: this is an optional dependency of log4j-core-2.17.1 (I don't think galasa uses this), log4j-core has been bumped to 2.24.1
  - [x] Also, explain why the framework directly depends upon Kafka, when it should only be extensions which do. Remove that dependency if possible - Eamonn: it doesn't, this is an optional dependency that we don't use

- [x] snakeyaml-1.27.jar : upgrade to org.yaml:snakeyaml:2.0 - Eamonn: 1.27 is a dependency of jackson-dataformat-yaml, which is an optional dependency of log4j-core-2.17.1 (I don't think galasa uses this), log4j-core has been bumped to [2.24.1](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.24.1)

- [x] commons-compress-1.21.jar : upgrade to org.apache.commons:commons-compress:1.26.0 - Eamonn: this is an optional dependency of log4-core-2.17.1 (I don't think galasa uses this), log4j-core has been bumped to [2.24.1](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.24.1)

- [x] jackson-databind-2.12.4.jar : upgrade to com.fasterxml.jackson.core:jackson-databind:2.13.4 - Eamonn: this is an optional dependency of log4j-core-2.17.1 (I don't think galasa uses this), log4j-core has been bumped to [2.24.1](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.24.1)

- [x] Snappy java needs upgrading to 1.1.10.4 - this is a dependency of kafka-clients-1.1.1, which is an optional dependency of log4j-core-2.17.1 (I don't think galasa uses this), log4j-core has been bumped to [2.24.1](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core/2.24.1)

Separate story:

- (Later) investigate using a red hat base image instead of the dockerhub image, and put it back. Probably using the Red hat image : https://catalog.redhat.com/software/containers/rhel8/httpd-24/5ba0addbbed8bd6ee819856a
  - The above task will remove the following vulnerability: gary-os-httpd-2.4.54 : upgrade to v 2.4.60
  - Moved to https://github.com/galasa-dev/projectmanagement/issues/2057

**Comment by jlolivos** [comment]
Please find below dependecies High and Medium.

High:

log4j-1.2.17.jar:
	log4j-manua-1.2.17-16
	log4j-javadoc - 1.2.17-16
	log4j-1.2.17-16,1.2.17-16
	uom-parent -1.0.3-3.module,1.0.3-3.module;
	uom-se-javadoc - 1.0.4-3.module;
	parfait-examples - 0.5.4-4.module;
	log4j-manual - 1.2.17-16;
	si-units-javadoc - 0.6.5-2.module;
	unit-api - 1.0-5.module,1.0-5.module;
	unit-apijavadoc - 1.0-5.module;
	parfait - 0.5.4-4.module,0.5.4-4.module;
	log4j-javadoc - 1.2.17-16;
	uom-systems-javadoc - 0.7-1.module;
	uom-lib-javadoc - 1.0.1-6.module;
	uom-systems - 0.7-1.module,0.7-1.module;
	log4j - 1.2.17-16,1.2.17-16;
	uom-se - 1.0.4-3.module,1.0.4-3.module;uom-lib - 1.0.1-6.module,1.0.1-6.module;
	parfaitjavadoc - 0.5.4-4.module;
	pcpparfait-agent - 0.5.4-4.module;
	siunits - 0.6.5-2.module,0.6.5-2.module
	org.apache.logging.log4j:log4jcore:2.0
	ch.qos.reload4j:reload4j:1.2.18.3

kafka-clients-1.1.1.jar:
	org.apache.servicemi
	x.bundles:org.apache.servicemix.
	bundles.kafka-clients:2.1.1_1

protobuf-java-3.21.10.jar:
	com.google.protobuf:protobufjavalite - 3.25.5,4.28.2,4.27.5;com.google.protobuf:protobuf-java - 4.27.5,3.25.5,4.28.2

jose4j-0.9.2.jar:
	org.bitbucket.b_c:jose4j:0.9.3
	org.bitbucket.b_c:jose4j:0.9.4

protobuf-java-3.24.0.jar:
	com.google.protobuf:protobufjavalite - 3.25.5,4.28.2,4.27.5;com.google.protobuf:protobuf-java - 4.27.5,3.25.5,4.28.2

protobuf-javalite-3.24.0.jar:
	com.google.protobuf:protobufjavalite - 3.25.5,4.28.2,4.27.5;com.google.protobuf:protobuf-java - 4.27.5,3.25.5,4.28.2

httpd-2.4.59-rc1-candidate: (pag 8)
  httpd-2.4.60
  
bcprov-jdk18on-1.75.jar:
	org.bouncycastle:bcprovjdk15to18:1.78,
	org.bouncycastle:bcprovjdk18on:1.78,
	BouncyCastle.Cryptography - 2.3.1
	
commons-io-2.8.0.jar:
	commonsio:commons-io:2.14.0
	
snakeyaml-1.27.jar:
	org.yaml:snakeyaml:1.31
	org.yaml:snakeyaml:1.32
	
snappy-java-1.1.7.1.jar:
	org.xerial.snappy:snappyjava:1.1.10.1
    org.xerial.snappy:snappyjava:1.1.10.4

jszip-3.7.1.js:
	 jszip - 3.8.0

Medium:

jquery-3.3.1.js:
	jquery - 3.5.0;jquery-rails - 4.4.0
	
commons-codec-1.11.jar:
	commonscodec:commons-codec:1.13

woodstox-core-6.2.6.jar:
	com.fasterxml.woodstox:woodstox-core:5.4.0,6.4.0

bcprov-jdk18on-1.75.jar:
	org.bouncycastle:bcprovjdk18on:1.78,org.bouncycastle:bcprov-jdk15to18:1.78
	org.bouncycastle:bcprovjdk14:1.78
	BouncyCastle.Cryptography - 2.3.1

jackson-databind-2.12.4.jar:
	com.fasterxml.jackson.core:jackson-databind:2.12.6, 2.13.1;
	com.fasterxml.jackson.core:jackson-core:2.12.6, 2.13.1

okio-jvm-3.0.0.jar:
	com.squareup.okio:okio-jvm:3.4.0

commons-compress-1.21.jar:
	org.apache.commons:commonscompress:1.26.0

guava-30.1.1-jre.jar:
	com.google.guava:guava:32.0.1-android,32.0.1-jre

**Comment by jlolivos** [comment]
Below are:
+ mvn dependencies tree
+ gradle dependencies tree

[mvn_dependencies.txt](https://github.com/user-attachments/files/17575617/mvn_dependencies.txt)
[gradle_dependencies.txt](https://github.com/user-attachments/files/17575618/gradle_dependencies.txt)

**Comment by jlolivos** [comment]
Please find here:
+ maven dependencies tree.
+ gradle dependencies tree.

[gradle_dependencies.txt](https://github.com/user-attachments/files/17575663/gradle_dependencies.txt)
[mvn_dependencies.txt](https://github.com/user-attachments/files/17575664/mvn_dependencies.txt)

**Comment by techcobweb** [comment]
@jlolivos I've no idea what that gradle_dependencies.txt file means. Doesn't look like dependencies as I know them.

I actually was asking if we upgraded everything in the description, do you think the scans would pass ?

**Comment by jlolivos** [comment]
Regarding gradle file is the output for all Galasa repositories for this command:
$ find . -name 'build.gradle' -exec grep -H ""bundleDependency"" {} \;  > gradle_dependencies.txt

Regarding updates, to have scan pass please include the ones I added, those are also in the report.

**Comment by techcobweb** [comment]
This is complete.
