### ISSUE TITLE
Access tokens have an expiry time, and expire

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2029]
# Story
As a Galasa service user, using a galasa access token to enable my CLI tool, I want the token to be able to expire at which point it becomes useless and I have to get another one, so that I can conform to security requirements for my organisation.

# Background
Some organisations require that access tokens expire, and need to be re-allocated and re-configured.

Dex doesn't seem to allow refresh token expiry times to be dynamically set, so instead, we can:

1. Store the expiry time of an access token when the token is created
2. When a request comes in to the REST API to get a new JWT, the REST API checks if the user's personal access token has expired, and if so, deletes the token from the auth store and does not return a new JWT

### CLI
The `galasactl auth tokens get` command shows the expiry time, like:

```
tokenid                          created(YYYY-MM-DD) expiry(YYYY-MM-DD) user         description
a47968535ec38b9a7f2b050c98000338 2025-11-27          2026-02-14         jadecarino   galasaservice1 galasactl access for macbook
e47968535ec38b9a7f2b050c9800074b 2025-11-27          2026-03-14         galasa-team  galasa-team galasactl access for automation
4255bcea4287f5bc41c97da8db016329 2025-11-28          2026-04-14         James-Cocker Token 1
6cf7eb29dc42aa2ca3a2122f77014771 2025-12-03          2026-05-14         eamansour    my token
a368f6329424edf515ee684daf00e6d4 2025-12-18          2026-06-14         galasa-team  galasactl jade testing 2
```

## Tasks

- [ ] When you allocate an access token it asks for a number of days/months/years, or a certain date when it will expire. That expiry time is associated with the user.
- [ ] When the current time is beyond the token expiry time, the token fails to be exchanged for a JWT, and is no longer useable.
- [ ] The Systems administrator can set the max time the token is valid for in a CPS property `service.tokens.lifespan.max.days` to reflect the policy of the test organisation using the Galasa service. Max value: 10 years * 365. Min value: 1. Defaults to 2 years.
- [ ] Getting the details of a token shows it's expiry time in the CLI
- [ ] Showing the token in the web UI also shows it's expiry time.

- [ ] Any expiry time which is "getting close" will be marked on the UI with a warning.
- [ ] The definition of "getting close" is defined by a CPS property `service.tokens.lifespan.nearly.expired.warning.days` Min 1 day. Max 30 days.
- [ ] If the token is used to login on the CLI, and the token used is "getting close" then the CLI issues a warning:
```
GALxxxxW:
