### ISSUE TITLE
Pass multiple overrides files into galasactl runs submit overridesfile 

### ISSUE THREAD

**Issue by Tom-Slattery** [galasa-dev/projectmanagement#2048]
## Story
As a Galasa user, I want to separate my CPS properties into multiple CPS files, so that I get better separation and isolation of properties relating to certain namespaces / managers. 

We can easily achieve this by separating the properties into multiple files and applying them individually to the ecosystem, but we also want to test our properties using a PR run before allowing them into the repo. We currently run the tests in the PR run and pass the PR CPS properties file using --overridesfile. To test multiple properties files, we would need --overridesfile to take a comma separated list of files. 

## Background
Currently the CLI only accepts one overrides file.

Allow the CLI to specify multiple overrides files, and combine them all before using them.

Create a temporary file in which the override values can be stored (if there isn't one already being used, can't remember).

Support syntax like this:
```
--overridefile x,y,z
--overridefile x --overridefile y --overridefile z
```

## Tasks
- [x] If there are multiple overrides files specified....
  - [x] Can we validate each override file before we combine them ? That would make errors easier to fix for users
  - [x] CLI creates a temporary file to put the overrides into. This should be using the createTempFile APIs provided by go. Filename should be different for each run.
  - [x] files get combined into a single file, which is used as the file is today
  - [x] File should be cleaned-up if the command passes. Error messages will refer to that file so if there are failures, then it's best to leave it there.
- [x] Documentation in the command-line syntax, which will get published.
