### ISSUE TITLE
Enhance mono repo's build process

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2050]
## Background
A new build process was created to support the mono repo and there are some enhancements to be made which will make the process more efficient and reliable, and improve the quality of the scripts.

To dynamically get and use the list of modules, we could do this:
```bash
for module_name in $(ls $REPO_ROOT_DIR/modules); do
        info "Looking at module $module_name"
        ...
    done
```

## Tasks
- [x] Dynamically calculate the array of module names in both `get-changed-modules-pull-request.sh` and `get-changed-modules-push.sh` by listing directories inside the `modules` directory
- [x] Move all scripts in the `tools` directory that are only used for the build process to the `.github` directory 
- [x] Main Build Orchestrator should build all modules including and after the first module changed, instead of all modules that have changed. For example, if Framework and Managers have changed, don't just rebuild Framework and Managers - rebuild Framework, Managers and Extensions to reveal if the Framework changes affected the Extensions 
- [x] Add sparse-checkout so each module only checks out its own source code
