### ISSUE TITLE
Increase test coverage of existing Managers in MVP/Isolated disributions

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2051]
## Story
As a user of the Galasa Isolated/MVP configurations, I want to see that managers included in these distributions are integration tested appropriately, so that I have confidence they work not only when using Galasa online, but offline too.

## Background
There are several managers that are included in the Isolated/MVP distributions of Galasa but do not have an integration test in our suite that tests them as part of that distribution, only as part of the online. We should add these missing tests to ensure full coverage of our Managers testing. If there is any reason these Managers would not work as part of the offline configuration, then they should be removed from those zips.

## Tasks
- [x] CICS TS Manager needs MVP test
- [x] CEMT Manager needs MVP test
- [x] CECI Manager needs MVP test
- [x] CEDA Manager needs MVP test
- [x] SDV Manager needs MVP test
- [ ] Docker Manager needs MVP and Isolated tests
- [ ] HTTP Manager needs MVP and Isolated tests
