### ISSUE TITLE
Implement Gradle's Java Platform to manage dependency versions

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2052]
## Story
As a Galasa developer/maintainer, I want to use Gradle's Java Platform plugin to manage versions of the project's dependencies, so that they are easier to maintain and update, we can create a Bill of Materials for Galasa, and that can help us with vulnerability scanning.

## Background
This [story](https://github.com/galasa-dev/projectmanagement/issues/2028) to do with upgrading bundles for vulnerability scans was originally opened, and the idea of using Gradle's Java Platform plugin to control dependencies' versions across all projects was initially to help with that. This separate story has been created to track the work as it's scope is larger than just helping to upgrade bundles, but to help maintain the project with a single location for versions going forward, to help us generate a BOM, and more.

## Tasks
(In Framework module first)
- [x] Experiment with Gradle's Java Platform plugin to see if suitable for Galasa's structure
- [x] Remove hard coded versions in dependencies and draw version from the Platform 
- [x] Include Platform module in the GitHub build process so it can be built and used remotely
- [x] Replace hard coded versions in bnd.bnd files to also be drawn from the Platform
- [x] Inspect jar META-INF files to ensure wildcards in bnd.bnd files are drawing correct version from class path
- [x] Test API server locally
- [x] Deliver into Framework

Roll out across other modules:
- [x] dev.galasa.wrapping.com.jcraft.jsch
- [x] dev.galasa.wrapping.gson
- [x] dev.galasa.wrapping.io.grpc.java
- [x] dev.galasa.wrapping.io.kubernetes.client-java
- [x] dev.galasa.wrapping.jta
- [x] dev.galasa.wrapping.protobuf-java
- [x] Implement in Gradle
- [x] Implement in Maven
- [x] Implement in Extensions
- [x] Implement in Managers
- [x] Implement in OBR
- [x] Capture all other dependencies mentioned in bnd.bnd files in the platform and substitute their version with a wildcard - PR here https://github.com/galasa-dev/galasa/pull/98

(Changes/enhancements to make across all modules using the platform)
- [x] Add Signing to the Platform project's build.gradle so it can be released to Maven Central
- [x] Uplift io.prometheus to work with 0.15.0 across all bundles instead of 0.6.0. **Update**: io.prometheus uplifted to 0.16.0
