### ISSUE TITLE
Infrastructure: Tool to update the release version dynamically wherever it is referenced.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2053]
# Story
As a galasa user, I want to see everything associated with release 0.38.0 to have a version number of 0.38.0 if possible, so that things are not confusing.

As a Galasa developer, or automated release process, I want the ability to update all of the galasa deliverables with a few single commands, rather than have to edit tons of files with an editor bumping versions of things, which takes ages.

# Background
We are moving Galasa to version everything with a single release number. The release it was released with.
So we need a tool (or tools) which can help us do this easily and simply.

We want to be able to run the tool as part of the build proces also, so that we can set the version on the fly, and it will work for any release branch.

A script in the tooling folder will do it.

`./tools/set-version.sh --version "0.38.0"`

This can call all the smaller set-version.sh scripts in the modules.

# Tasks
- [x] Upate the gradle files so that only the top level project has a version inside, and passes it to the sub-projects. Prove this works in the framework module.
  - [x] Do this for all other modules.
-  ~~Plug this into the build script for the galasa repo~~ Not necessary. Currently, the build.properties dictates which version is set

- [x] Write a new set-version.sh script for the simplatform code.
- ~~Write a new set-version.sh script for the Isolated code~~
- [x] Write a set-version for the dev.galasa.platform
- [x] Write a set-version that finds the dev.galasa.platform throughout all Galasa modules (mono repo and others) to upgrade its version
