### ISSUE TITLE
Uplift org.assertj:assertj-core dependency to 3.25.3 in Platform and fix unit test failures.

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2054]
**Note**: This story was originally to uplift to version 3.23.1 but usages of 3.25.3 have been found so uplifting to that so there is only one version used.

## Story
As a Galasa developer, I want there to be only one version of our dependencies used everywhere and stored in the Platform, so that it's easier to maintain the project and I know my projects are using the most up to date versions.

## Background
We recently started using the Gradle Java Platform plugin to manage the versions of our dependencies. I initially put the version 3.23.1 for `org.assertj:assertj-core` in the Platform but then this caused unit test failures (only one consuming project was already using 3.23.1 and the rest were using 3.16.1). I have changed the Platform to contain 3.16.1 and the project that was using 3.23.1 overrides the suggested version.

I have since found usages of 3.25.3 in the gradle plugins and buildutils project.

We need to uplift the Platform's version to 3.25.3 and make the necessary changes to the unit tests that now fail as a result of the upgrade.

## Tasks
- [x] Uplift the `org.assertj:assertj-core` version to 3.25.3 in the Platform
- [x] Remove explicit versions throughout the Galasa repo
- [x] Make sure the Galasa repo builds
- [x] Make sure the all Galasa modules unit tests pass
- [x] Make sure the Managers IVTs pass
- [x] Make sure the CLI repo builds and the generated tests pass
- [x] Make sure the Simplatform repo builds
- [x] Make sure the Simplatform tests pass
- [x] Make sure the Isolated repo builds
- [x] Make sure the tests run as part of the Isolated repo
- [x] Make sure the Integratedtests repo builds
- [x] Ensure API Server starts locally
- [x] Make sure the integration tests run in prod1
