### ISSUE TITLE
Docker image used for httpd serving and isolated need to be a scanned-clean image

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2057]
# Story
As a galasa user of the mvp zip I want to know that the docker image contained in isolated.tar uses a clean and secure docker image with the httpd server inside, so I have fewer concerns over security vulnerabilities.

# Background

# Tasks
- [x] investigate using a red hat base image instead of the dockerhub image, and put it back. 
httpd:alpine could be a good option for base, it is an "MIT-like" license
  - The above task will remove the following vulnerability: gary-os-httpd-2.4.54 : upgrade to v 2.4.60
- [x] Add new base image usage to the code
- [x] Test that it builds and is usable
- [x] Test that it appears in mvp.zip
- [x] Make sure the existing httpd.cnf files work with this newer version of httpd.
- [x] Change to use this in:
   - [x] mvp packaging
   - [x] build process infrastructures:
     - [x] base image
     - [x] integration tests
     - [x] simplatform

**Comment by techcobweb** [comment]
On the basis that the scan didn't find any further issues, I am closing this one.
