### ISSUE TITLE
CPS properties should allow @ characters in the property name.

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2059]
# Story
As a Galasa user I want to add a user-id which contains a '@' character into a CPS property name as an infix, so that I can use an email address as part of a CPS property name.

# Background
Currently the character restrictions don't allow a '@' character. ETCD does allow it.

# Tasks
- Remove restriction and test:
  - [x] CLI properties set, update, delete
  - [x] REST interface properties set, update, delete
  - [x] REST resources apply create update delete
