### ISSUE TITLE
Uplift dependencies initially left out of the Platform

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2061]
## Story
As a Galasa developer, I want there to be one version used for our dependencies, so that the project is easier to maintain and it is clearer to know which of our dependencies are vulnerable.

## Background
As part of issue #2052 we implemented Gradle's Java Platform plugin to have a central location to control dependencies' versions throughout the codebase. Most dependencies were easy substitutes as there was only one version used throughout the codebase. But some dependencies had a few conflicting versions throughout so have been left out of the platform. When we tried to enforce a single version on them with the platform, there were errors as code changes are required for the components where their versions were changed. These need to be looked at in closer detail so that eventually only one version is used for the dependency then this can be enforced by the platform.

## Tasks
- [ ] mockito-core 3.1.0 in the Platform - but 4.6.1 and 5.3.1 found in Managers
- [ ] okhttp 4.9.2 in the Platform - but 4.10.1 found in Managers and 4.12.0 found in Wrapping
- [ ] kotlin-osgi-bundle 1.4.0 in the Platform - but 1.7.22 found in Managers and 2.0.21 found in Wrapping
