### ISSUE TITLE
Resource Management to support managers created externally  - Phase 1

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [galasa-dev/projectmanagement#2067]
## Story
As an end-user, I want the ecosystem resource management service to run RM implemented by my internally written Galasa managers, so that I can have a maintained DSS without requiring to deliver my internal managers to the OS galasa repo.

## Background
Users are encouraged to develop their own managers, and many of these will be bespoke and specific and will never be contributed back to OS Galasa.
These managers may create resources, which may need to be tracked via the DSS. To handle when there are problems with test runs, resulting in resources being left behind and orphaned from a test run, Resource Management should resolve the orphaned records and free/release the resource allocations.

Resource Management is a long running service in an ecosystem, usually started when the ecosystem installs. It is started from the Galasa boot image. This boot image contains all compiled jars of OS Galasa managers, resource management appears to simply use these locally available jars to find resource management providers.
From the logs, it does not appear to look anywhere else.

Therefore:

1. It is only currently possible to run resource management providers that exist within the Galasa OS repo. It is not possible to have the ecosystem run resource management provided by customer managers.
2. It is a long running service that isn't intended to be interrupted. So if it did support external managers, and someone made a change to one of their resource management providers. How do they indicate to resource management that it needs to restart itself to pick up the new version? (always pull image policy & delete pod maybe?)

@techcobweb has had a first idea of it cycling through a list of specific test streams loading a list of managers and using those. 

I'm thinking the test stream might only have a few managers in there, so they would have to be combined with the managers in the boot image. Customers might also keep their managers & test seperate? In CICS, we also have the scenario of copying Galasa OS managers internally (keeping the same name), and we've modified their resource management, so would want to use those versions.
I don't know if being able to optionally point it to an OBR and a custom maven repo works?

# Monitors

A Galasa monitor is a part of the Galasa Service which monitors something, and optionally periodically does something as a result of what it sees.

There are different types of resource monitor, depending on the task you wish the resource monitor to perform.

## Monitor Types currently planned:
- Resource Cleanup Monitor - A monitor which periodically looks at the list of running tests which have failed, or stopped part way through, for which some remote resource may still be allocated which needs cleaning up. Such monitors can read the DSS to get information on what resources need cleaning up.

## Monitor Types planned for the future:
- Secrets monitor - Monitors a source of secrets and synchronizes the secrets down to the Galasa service
- Test Stream monitor - An active component which collects metadata about the available tests on a stream, used for providing lists of tests which can be launched.
- ...etc.
##

# Resource Cleanup Monitor
A monitor which periodically looks at the list of running tests which have failed, or stopped part way through, for which some remote resource may still be allocated which needs cleaning up. Such monitors can read the DSS to get information on what resources need cleaning up.

yaml definition for a Resource Cleanup Monitor
```yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaResourceCleanupMonitor
metadata:
    name: myCustomResourceCleanupMonitor
    description: A monitor which looks at DSS to find resources which need cleaning up for the system resources allocated by Galasa Managers

    audit-history:
        - started:
          comment: upped the interval time.
          requestor: mike
          date-time: T2025-02-25 09:33:59Z << an instant in time.
        - stopped:
          comment: changed the obr loaded
          requestor: jade
          date-time: T2025-02-25 07:20:59Z << an instant in time.
        - created:
          comment: initial setup of the monitor
          requestor: mike
          date-time: T2025-02-25 02:33:59Z << an instant in time.

    run-history:
        - ran:
          date-time: T2025-02-25 09:33:59Z << an instant in time.
          status: OK
        - ran:
          date-time: T2025-02-25 09:33:59Z << an instant in time.
          status: OK

data:
    monitor-data:
        is-deletable: false << Indicates whether an admin can delete this resource. eg; The _system-cleanup-monitor resource cleanup monitor cannot be deleted. Custom resource cleanup monitors must use true
    
    is-enabled: true << Set this to true/false to stop/start the active behaviour of the monitor.

    resource-cleanup-data:
        stream: myStream << refers to a Galasa Stream resource by name. This is how Galasa knows where to get a list of OBRs from in order to run the monitor.
        filters:
            includes:
                - '*' << include all resource management providers we can find
                - '*myResourceManagementProvider*' << include the resource management providers with that in their fully-qualified class name.
                - 'mycompany.com.*' << include all the resource management providers which have this prefix in their fully qualified class name.
        excludes: 
                - 'dev.galasa.*' << don't run any built-in resource management providers
```

yaml definition of a Galasa Stream:
```yaml
apiVersion: galasa-dev/v1alpha1
kind: GalasaStream
metadata: 
    name: myStream
    description: Tells Galasa about a set of trusted data that it can load on demand. The stream can refer to Galasa tests, or Galasa managers, and/or Galasa resource cleanup implementations.

    audit-history:
        - updated:
          comment: renamed OBR we use
          requestor: mike
          date-time: T2025-02-25 09:33:59Z << an instant in time.
        - updated:
          comment: moved repo location
          requestor: jade
          date-time: T2025-02-25 07:20:59Z << an instant in time.
        - created:
          comment: initial setup of the stream
          requestor: mike
          date-time: T2025-02-25 02:33:59Z << an instant in time.
data:
    repository:
        location: https://internal-build-process-artifacts.my.company
        certificates:  << optional. This may not be needed. eg; If the location is an http location.
            - my.company.certificate << The name of the public certificate used to contact the remote location. Galasa loads this certificate for your JVM prior to starting it.
        login-credentials: my.artifact.repo.login.userid.and.password.secret << The name of a Galasa Secret resource used to log into this repository. Could be a token-secret or a userid+password secret.
    obrs: << says which OBRs to load from within that location
        - maven:
            groupId: mycompany.com
            artifactId: mycompany.my.resource.cleanup.monitors
            version: 2.10.1
            classifier: obr
        - maven:
            groupId: mycompany.com
            artifactId: mycompany.my.other.resource.cleanup.monitors
            version: 4.6.2
            classifier: obr

    is-enabled: true << If false, Galasa will not reach out to this stream at all.
```
## CLI for the monitors

To list the monitors available:
```bash
> galasactl monitors get 
name                             kind                         is-enabled last-run-status last-run-time
_system-certificate-monitor      GalasaCertificateMonitor     true       OK              2023-12-24:8:34:22
_system-resource-cleanup-monitor GalasaResourceCleanupMonitor true       OK              2023-12-24:8:34:22
myCustomResourceMonitor          GalasaResourceCleanupMonitor true       OK              2023-12-24:8:34:22
Total: 3
```

Or get the yaml definition of the monitor:
```bash
> galasactl monitors get --name GalasaCertificateMonitor --format yaml
... yaml format of the monitor ...
```

To enable/disable:
```bash
> galasactl monitors set --name myCustomResourceCleanupMonitor --is-enabled true

> galasactl monitors set --name myCustomResourceCleanupMonitor --is-enabled false
```

### Phase 1 : Kube administrator sets it up
- [x] boot jar is told from the environment which cleanup monitor it is
- [x] start by defining 1 extra custom monitor using the helm chart which is defined by helm
- [x] helm chart defines 2 deployments, one for the systems monitor, one for the customs monitor.
- [x] The scale of the system monitor defaults to 1, the scale of the custom monitor defaults to 0.

loading:
- [x] includes/excludes are passed in as env vars from both deployment definitions.
- [x] for custom cleanup monitors, use a stream to get the obr/location...etc
- [x] for system one, load managers from the image
- [x] all bundle loads are filtered using the includes/excludes regexes for both

- [x] galasactl get - gets the information about monitor using the deployment definitions in kube

- [x] /enable/disable - controls the deployment scaling definition dynamically from 0..1
- [x] docs updates: include that the galasa api server can manipulate scaling definitions

### Phase 2 : Galasa admin sets it up using REST
- allows REST (and galasactl) to set definitions, and sync between the definitions and the kube definitions
- new action so only admins can enable/disable the monitors

### How do we see logs from the resource monitor ?
TBD

### How does a resource manager know that it should be cleaning up resources within this resource cleanup monitor, or a different resource cleanup monitor ?

We use `includes` and `excludes` regexes against the java package name of the resource management provider classes ? or against the bundles they are part of ?
I've updated the above example with an example to give the overall idea... thoughts ?

**Comment by Mark-J-Lawrence** [comment]
I've just had a realisation about our resource management.....this is the command I use to run resource management locally to debug my own resource management:

```
java -agentlib:jdwp=transport=dt_socket,server=y,address=2970 -jar ~/.galasa/lib/0.37.0/galasa-boot-0.37.0.jar --resourcemanagement --obr mvn:com.ibm.cics.galasa.tests/com.ibm.cics.galasa.tests.obr/0.0.1/obr --obr mvn:dev.galasa/dev.galasa.uber.obr/0.37.0/obr
```

We're going to see if we can hack the resource management deployment to give it these extra options, and possibly setting remoteMaven......if this works, we'll likely change the deployment temporarily to deploy the COTS resource management and have another POD pointing to our own OBR with our own managers.

Perhaps an easy way to fix this in Galasa, is it uses all the managers in jar available in the boot jar to source resource management providers, and a user can optionally provide an OBR via values.yaml, and the resource manager will load those. If any from the custom OBR are named the same as the ones in the boot jar, the one from the boot jar is ignored and the custom OBR takes precedence?

**Comment by techcobweb** [comment]
I'm thinking that we need custom managers to do cleanup in their own pod, separate to the existing resource manager.

So we define a resource, called a ResourceMonitor, which you can start and stop, and get the state of via the REST API. That relates directly to a pod which gets started/stopped as a result.

The definition of the ResourceMonitor indicates the stream the custom manager is taken from, and hence the list of custom managers which would be grouped together to do resource management cleanup together.

This would mean we can use something like the existing resource manager demon code doing the looping forever...etc, but it would only enable the custom managers for cleanup, and we could load them remotely rather than insisting them being available on the boot image.

Users get to decide what mix of managers get cleaned up together, and have *n* ResourceMonitor resources to play with

Or we make this ResourceMonitor a type of stream resource. Streams can already be enabled/disabled and have a state I believe, so we could extend that idea.

I think streams should be more pro-active anyway, in that they should monitor the underlying maven location to keep a notional combined test catalog up to date on the server side.
So this idea may help move that on, in that we would need a streams monitor for that.

We also know we need to create a SecretsSyncMonitor which regularly synchronizes IBM secrets manager secrets into Galasa. So there is another case for a type of 'monitor' in the system with a starting/running/stopped/disabled state.

I'm thinking that a separate resource monitor would give Galasa users control without interfering with the 'standard' managers cleanup resource monitor which only loads from the boot image.

We could re-cast the existing resource monitor into a resource also, but a special type of one which only loads managers from the boot image. '_system' resource monitor perhaps.

What do you think of that ?

**Comment by Mark-J-Lawrence** [comment]
Hi Mike, this sounds great.

1. If we had one hundred custom managers, does this mean we would have to individually list each one in whatever definition is introduced.
2. Then, if someone introduced a new one, would that list need to be updated?
3. If we had a resource manager from a custom manager, however the naming of it exactly matched one of the pre-existing Galasa OS managers, would it take precedence over the Galasa version?

If it were a stream, would the resource management service just suck in all the resource management providers it can find on that stream?

**Comment by techcobweb** [comment]
> If it were a stream, would the resource management service just suck in all the resource management providers it can find on that stream?

I was hoping we could get that to work yes.

**Comment by techcobweb** [comment]
@Mark-J-Lawrence @adamcoulthard See above for a more detailed outline of what I was thinking... comments ?

**Comment by techcobweb** [comment]
Implementation is done. Closing. If there are problems we can raise further issues.
