### ISSUE TITLE
Publish new mkdocs based Galasa website(s)

### ISSUE THREAD

**Issue by jt-nti** [galasa-dev/projectmanagement#2068]
## Story

As a Galasa developer, I want to have my documentation updates published to GitHub pages automatically, so that Galasa users have up-to-date information to help them use the project.

## Background

The existing Gatsby based galasa.dev documentation and custom hosting solution is being migrated to mkdocs and GitHub pages hosting.

## Tasks

During doc migration:

- [ ] automatically publish docs to GitHub pages on push to the `mkdocs` branch on `galasa.dev`

After migration (tbc):

- [ ] automatically publish docs to GitHub pages on push to a new "release" branch on `galasa.dev`
- [ ] automatically publish docs to GitHub pages on push to the `main` branch on `galasa.dev`
    Will a "next/" directory on the same GitHub pages site work with the vnext.galasa.dev domain?
    Alternatively, publish the `main` branch to a "publish only" vnext docs repo?
- [ ] remove the `mkdocs` and `next` branches on `galasa.dev`
- [ ] DNS magic to switch the current https://galasa.dev/ and https://vnext.galasa.dev/ sites to the new GitHub pages deploys

Other tasks:

- [ ] include broken link checks in the new builds
- [ ] anything else?

**Comment by techcobweb** [comment]
I thought github pages were all published to a special url called https://{userid}.github.io/{reponame} which re-directs to contents on a single branch.

You nominate a single branch as the 'stuff to serve up' (you want to call this 'release' ?)

So the publishing process for main, next, v1...etc branches will all have to publish to that same branch, but in different folders ?

**Comment by jt-nti** [comment]
GitHub pages can publish from a branch and, optionally, a folder, however the mkdocs site requires a build step so it probably makes sense to use a [custom GitHub Actions workflow](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) instead.

The "release" branch I was suggesting was for the stable/released documentation _source_ (not the published site), with the `main` branch being for the unstable "vnext" documentation. That's slightly different to the current setup where `main` is the stable branch, which seems unusual, and `next` is the unstable branch.

Galasa doesn't seem to have release branches so I'm not sure exactly what you'd want to call it. Maybe "release-0.x", or "v0.x", or just "stable" since there is only one version? Or something completely different!

For simplicity, including for DNS setup if we want to keep `vnext.galasa.dev` instead of `galasa.dev/vnext`, it might be worth avoiding publishing to subdirectories on the same GitHub pages site, i.e. use a separate repository without the documentation source, specifically for publishing to and nothing else.

**Comment by jt-nti** [comment]
Documentation for deploying mkdocs sites is here...
https://www.mkdocs.org/user-guide/deploying-your-docs/

So far I've just been manually running `mkdocs gh-deploy` to update the https://jt-nti.github.io/galasa.dev/ GitHub pages prototype.

**Comment by jt-nti** [comment]
Just keeping track of progress updating the old Gatsby markdown files for mkdocs:

- [x] Getting started using the Galasa CLI
- [x] Exploring Galasa SimBank
- [ ] Writing your own independent Galasa tests
- [x] The Galasa Ecosystem
- [x] Managing tests in a Galasa Ecosystem
- [ ] Upgrading
- [ ] Managers
- [x] FAQs
- [ ] ...and anything else I've missed!
