### ISSUE TITLE
Minimal Admin/Non-admin RBAC

### ISSUE THREAD

**Issue by techcobweb** [galasa-dev/projectmanagement#2071]
# Story
As a galasa admin, I want to be able to set other users as non-admins, so that they can't get or set secrets into the ecosystem.

# Scope 0 (minimum)
- A user record has a new field "role" which can be set to a value. It's a string.

It can have one of three values:
|id|name       |description                          |
|--|-----------|-------------------------------------|
|0 |deactivated| user is inactive, unable to perform any tasks|
|1 |tester     | a normal user able to launch tests remotely and get run information|
|2 |admin      | A privileged user, able to do anything on the service|

|id| name                         | description |
|--|------------------------------|-------------|
|0| USER_ROLE_UPDATE_ANY | Able to update the role of any user|
|1| SECRETS_GET_VALUES | Able to get secret values, rather than redacted values|
|2| GENERAL_API_ACCESS | Able to access the REST API|
|2| CPS_PROPERTIES_SET | Able to set a CPS property|

- When `GET a specific user` REST call is issued, the user's Role field will be resolved into a list of actions that role is allowed to perform. 

eg: `GET http://myservice/api/users?loginid=mike_cobbett@my.domain`
```json
[
  {
    "id" : "456789787646"
    "login-id" : "mike_cobbett@my.domain",
    ...etc...
    "role" : "1"
    "synthetic": {  << This section is all derived from the value in the 'role' field.
      "permitted-actions" : [
        USER_ROLE_UPDATE_ANY, GENERAL_API_ACCESS
      ]
      "role": {
        "apiVersion": "galasa-dev/v1alpha1"
        "kind": "GalasaRole"
        "metadata": {
          "id" : "1"
          "name" : "default" << This is the role name a UI/CLI would show
          "description": "a normal user able to launch tests remotely and get run information"
          "url" : "https://myhost/api/auth/roles/1"
        }
        "data": {
          "actions" : [ 
            "USER_ROLE_UPDATE_ANY", << Allows a UI to check whether this user has permission to do things before they get displayed.
            "GENERAL_API_ACCESS"
          ]
        }
      }
    }
  }
]
```
The `permitted-actions` field is synthetic. Just an expansion from the user role.
The `role` field is also synthetic, just an expansion of the role mentioned in the user record above.

- The REST interface call which updates a user record now allows the update of a a new value for the role field
For example: Setting the role of user 56799875767 to be a default user would be:

`PUT http://myservice/api/users/56799875767`:
```json
{
  "role" : "1" 
}
```

- Currently ANYONE can update the user record of anyone else (it's not secure in this story), as the default user role has the USER_ROLE_UPDATE_ANY action. This means we can avoid having to worry about lock-out or initial admin users.
- Currently we don't care about setting/updating/deleting roles or actions. They are immutable so far. That will change later...
- [ ] @aashir21 The role is visible in the CLI
```
>galasactl users get  
login-id                  web-last-login(UTC) rest-api-last-login(UTC) role
Galasadelivery@my.domain                      2024-12-03 13:09         admin
Jade.Carino@ibm.com                           2024-12-03 10:22         tester
mike_cobbett@my.domain    2024-12-02 14:55    2024-12-03 14:09         admin
Eamonn.Mansour@my.domain  2024-11-19 11:24    2024-12-03 12:05         admin
Aashir.Siddiqui@my.domain 2024-11-27 15:44    2024-11-28 16:11         tester

Total:5
```
- [x] @aashir21 The role can be set in the CLI
```
>galasactl users set --login-id mike_cobbett@my.domain --role admin
```
(silent return if it worked, 0 return code)

### Within the framework
- [x] @techcobweb  A new interface will be created which can support this:
```java

public interface Action {
    String getName();
    String getId();
    String getDescription();
}

public interface Role {    
    String getName();
    String getId();
    List<String> getActionIds();
    String getDescription();
}

// An exception type we can use when the user is not permitted to perform an operation.
class UserActionNotAuthorised extends AuthException {
...etc...
}

interface RoleBasedAccessControllerService {
  RoleBasedAccessController getRoleBasedAccessController();
}

public interface RBACService {
    /**
     * Gets all the roles available.
     * @return A map. The index is the role ID. The value is the role object.
     */
    Map<String,Role> getRolesMapById() throws RBACException;

    List<Role> getRolesSortedByName() throws RBACException;

    /**
     * Gets all the actions available.
     * @return A map. The index is the action id. The value is the action object.
     */
    Map<String,Action> getActionsMapById() throws RBACException;

    List<Action> getActionsSortedByName() throws RBACException;
    Role getRoleById( String id ) throws RBACException;
    Action getActionById( String id ) throws RBACException;
}
```

This should allow us to create actions and roles in-memory statically, and serve them up as if they are hosted on couchdb and etcd.

Ultimately we will need an OSGi service which supplies the implementation

Do we need a null/blank service implementation which works on local runs?

## Rest call to get the list of roles
- A REST call exists which returns the list of allowable roles. Each role has a list of actions which it enables. These are hard-coded for now.
  - Each role has an ID, and the ID is used to refer to the role. This means a role can be re-named and everything referring to it will still be linked to it.
  - A special role ID of 2 means you are an admin
  - A special role ID of 1 means you are a default user
  - A special role ID of 0 means you are deactivated
  - Later, other role-IDs will be user-definable, and we can use a document-ID from a couch database or similar to be the role-id.

`URL: GET /api/auth/roles`
```json
[
  {
        "id" : "0"
        "name" : "deactivated"
        "description": "user is inactive, unable to perform any tasks"
        "url" : "https://myhost/api/auth/roles/0"
  },
  {
        "id" : "1"
        "name" : "default"
        "description": "a normal user able to launch tests remotely and get run information"
        "url" : "https://myhost/api/auth/roles/1"
    }
    ...etc
]
```
Note: We need a `deactivated` role so we can set a user to that and it stops them doing anything.

- Smaller rest calls exist to get a single role at once.
eg: `GET /api/auth/roles/2`
```json
{
  "apiVersion": "galasa-dev/v1alpha1"
  "kind": "GalasaRole"
  "metadata": {
      "id" : "2"
      "name" : "admin"
      "description": "A privileged user, able to do anything on the service"
      "url" : "https://myhost/api/auth/roles/1"
  }
  "data" : {
    "actions" : [
      {
        ...
      }
    ]
  }
}
```

- [x] A REST call exists to get the available actions known to the system. These can be hard-coded responses right now.

`GET /api/auth/actions`
```json
[
  {
    "apiVersion": "galasa-dev/v1alpha1"
    "kind": "GalasaAction"
    "metadata": {
        "id" : "0"
        "name": "USER_ROLE_UPDATE_ANY"
        "description": "Able to update the role of any user."
        "url": "http://myservice/api/auth/actions/0"
    }
  },
  {
    "apiVersion": "galasa-dev/v1alpha1"
    "kind": "GalasaAction"
    "metadata": {
        "id" : "1"
        "name": "SECRETS_GET"
        "description": "Able to get secret values"
        "url": "http://myservice/api/auth/actions/1"
    }
  },
  {
    "apiVersion": "galasa-dev/v1alpha1"
    "kind": "GalasaAction"
    "metadata": {
        "id" : "2"
        "name": "GENERAL_API_ACCESS"
        "description": "Able to access the REST API"
        "url": "http://myservice/api/auth/actions/2"
    }
  }
```

- [x] Individual REST calls exist to get each action separately
For example: `GET http://myservice/api/auth/actions/0`
```json
{
  "apiVersion": "galasa-dev/v1alpha1"
  "kind": "GalasaAction"
  "metadata": {
    "id" : "0"
    "name": "USER_ROLE_UPDATE_ANY"
    "description": "Able to update the role of any user."
    "url": "http://myservice/api/auth/actions/0"
  }
}
```

### Protected Actions
- [x] USER_ROLE_UPDATE_ANY - able to update the user role of any user.

- The REST interface rejects attempts for which the user is not authorised. They need GENERAL_API_ACCESS

- User with admin rights has SECRETS_GET auth. User with default role does not.

### Demo

- The user tries to get a secret. Can't do it.
- An admin user logs in, and sets the original user to an admin using the CLI
- The original user tries to get a secret. He can now get it.

### Default user role
A user with no role, or one you has just logged-in will have a `default` role.

# Tasks
- Foundation: Roles and Actions foundation:
  - [x] Framework has an RBAC interface which details available Roles and Actions
  - [x] REST calls to get list of available roles
  - [x] CLI can query list of available roles, rendering into summary and yaml formats.
  - [x] Resolve the comments from the review on PR: https://github.com/galasa-dev/galasa/pull/158
- Enablement: A user has a role:
  - [x] User record can contain a role field
  - [x] User record role displayed on CLI
  - [x] User record role displayed on Web UI
  - ~~CLI can set user record role~~ scope moved to separate story.
  - ~~Web UI can see user record role, and the role description.~~ scope moved to separate story
- Enforcement: A users' role enables/disables some functions  
  - [x] user-to-actions list/cache maintained in framework RBAC service cache (roles don't change so only user-role-set causes eviction. State held in etcd. 
  - [x] user-to-actions list/cache enforces general API access
    - [x] Visible with errors on CLI
    - [x] Visible with errors on WebUI
  - [x] user-to-actions list/cache enforces who can get secret values
    - [x] visible with errors on CLI
  - [x] user-to-actions list/cache enforces who can set a role for a user
    - [x] visible with errors on the CLI when the user tries to do it
- Documentation
  - [x] Concept of User, Role, Action in the docs
  - [x] CLI user listing user detail, listing available roles and updating user role in docs
  - [x] Detailed list of which user roles can do what out of the box, and which actions exist (and are enforced) based on the role.

# Scope 1 **(to be moved to another story)**
  
- [ ] An admin using the web UI can change the role of any other user

- [ ] The role can be set in the web UI, only if the user has the USER_ROLE_UPDATE_ANY action.

- [ ] CLI `galasactl users get --format yaml` supported

## CLI to get available roles
- [x] CLI can get the roles
```
>galasactl auth roles get 
id name        description                                                         
0  deactivated user is inactive, unable to perform any tasks
1  default     a normal user able to launch tests remotely and get run information 
2  admin       A privileged user, able to do anything on the service

Total: 3
```

- [x] CLI can get a role by id
- ~~CLI `--format details` view also lists actions~~

- [ ] A CLI call exists to list the available actions:
```
>galasactl auth actions get
id                   description
USER_ROLE_UPDATE_ANY Able to update the role of any user
SECRETS_GET          Able to get secret values
GENERAL_API_ACCESS   Able to access the REST API

Total: 3
```

- [ ] A CLI call exists to list an available action individually by name
```
>galasactl auth actions get --id SECRETS_GET
id          description
SECRETS_GET Able to get secret values

Total: 1
```
