### ISSUE TITLE
API server should be able to handle a large number of requests in a short amount of time

### ISSUE THREAD

**Issue by eamansour** [galasa-dev/projectmanagement#2072]
## Describe the bug
This is a defect spawned from https://github.com/galasa-dev/projectmanagement/issues/2020.

Running a lot of galasactl commands in a short amount of time (e.g. by running commands and sending them to the background) seems to eventually crash the API server. This isn't specific to `runs delete`, but also seems to happen with `runs get`, `auth tokens get`, and potentially other commands, which means the API server is susceptible to denial of service attacks.

We should look into rate limiting requests to help prevent this from happening.

## Steps to reproduce
Run the following bash snippet, substituting the `runs get` command with any galasactl command you would like to run:
```bash
for i in {1..100000}; do
  galasactl runs get --age 1w &
done
```

## Expected behavior
The API server should be able to handle a lot of requests without ever crashing.

## Tasks
- [x] Find out why the API server crashes
  - When the API server receives a lot of requests (which temporarily overload it) and the Kubernetes liveness probe attempts to send a HTTP request to the `/health` endpoint, the probe continuously receives a 503 Service Unavailable response, causing it to restart the API server pod.

Scaling up to handle more requests:
- [x] Make the API server replicas configurable in the Helm chart
- [x] Add autoscaling to the API server 

Preventing denial-of-service:
- [x] Add default rate limiting settings to the API server as nginx Ingress annotations in the helm chart values - see https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rate-limiting
- [x] Add `--rate-limit-retries` flag (defaults to 3 retries) to the CLI so that the CLI can retry when it receives rate-limit-related errors
- [x] Add `--rate-limit-retry-backoff` flag to the CLI to configure the time between retries when being rate-limited
