### ISSUE TITLE
Make store locations configurable via helm values

### ISSUE THREAD

**Issue by Mark-J-Lawrence** [galasa-dev/projectmanagement#2074]
## Story
As an ecosystem owner, I want to use stores different than the Galasa provided ones, so that I have the option to share the DSS and/or RAS with external processes.

## Background
In CICS, our ecosystem test runs and our local developer test runs, all run on the same zOS machine, which we have particular resource pools set up for. These pools are for ports, and APPLIDs.

A new complication we have, is we have a Galasa zosSecurityManager, which is responsible for issuing test users for test runs, wherever those tests run (ecosystem, or developer machine). The zosSecurityManager uses the CPS to provide the pool setup for test users, amongst other options, and it uses the DSS to keep track of the users it creates.
The zosSecurityManager, after generating a user ID, then makes a call to a 'security server' service running on the zos machine, which then runs TSO commands on the PLEX to create that user with the given ID, which then commits it to RACF. It then may be later given further instructions from the zosSecurityManager on how to provision that user further. From this point, the 'Security server' is done, and it is not aware of what has been historically created. This is all meant to be managed by the zosSecurityManager and its DSS store.
Should a test abort for whatever reason, test users will be orphaned, and will continue to live on the zOS machine RACF.  zosSecurityManager has resource management to check the DSS for stale runs, and will removed test users on RACF for these runs, releasing them back to the pool.

The snag we have in all this is, developers run tests locally, and have their own local DSS. The tests are going to provision test users on the zOS machine RACF. Firstly, we'd have to make sure there are a pool of ecosystem user names & a pool of user names unique for every developer to use so they don't clash with each other, and the ecosystem. Secondly, local tests abort and abruptly end all the time. This will result in test users being orphaned in RACF, with nothing aware of their existence other than some scattered DSS files on developer machines.

The simplest solution for us is to have a shared pool of resources for everything/everyone running tests on that zOS machine, and everything/everyone running tests must share the same DSS, so they don't clash with resources, and we can 100% rely on resource management to keep RACF tidy. This also releases the huge burden of having to micro-manage resources on a per developer basis doing it any other way.

We have already implemented this by creating our own etcd cluster, and we've edited all Galasa deployments so:

```
- name: GALASA_DYNAMICSTATUS_STORE
          value: etcd:http://<our own etcd service>
``` 

CPS property `framework dynamicstatus.store` has also been updated to point to our cluster. (NOTE: GALASA_CONFIG_STORE &  GALASA_CREDENTIALS_STORE are not changed, and still point to the Galasa provided stores. We are only sharing manager state)

We've also a nodePort on a separate service for the store so developers can point to it.  This is now working.

This should really be configurable, so customers can store anything in any location they want at install time. Therefore, it would make sense that the following environment variables were changable for all deployments via Helm values.yaml: 

https://github.com/galasa-dev/helm/blob/9ae859cebb813950a1c532fc3d0160f17304bd44/charts/ecosystem/templates/engine-controller.yaml#L63-L66

~In addition to this, we would like to put authentication on any external store, which could be input as a k8 secret, as a username and password. Currently, it doesn't appear Galasa supports an authenticated etcd cluster?~

# See also
- [ ] Galasa to use a more recent/up-to-date version of etcd. One which does support TLS certificates. See story https://github.com/galasa-dev/projectmanagement/issues/1508
- [ ] Galasa needs to use TLS to talk to etcd. See story https://github.com/galasa-dev/projectmanagement/issues/2076

# Tasks
- [x] Helm parameters to allow the etcd configuration to be set for:
  - dss url, over-ridden by framework.dynamicstatus.store CPS property, so that local users can set it when not running inside kubernetes.
  - ~dss user id (used by Galasa to log into etcd from every pod~
  - ~dss password (a secret in kube, set up by the helm chart if it's not present)~
- [x] Similar mechanism for creds store (even if mark won't use it)
- [x] Similar mechanism for CPS store (even if mark won't use it)
- [ ] ~Figure out how to enable auth on the Galasa etcd server~
- [ ] ~Figure out how to minimize the number of times a pod authenticates, or passes a token around to itself.~
- [ ] ~When does API server need to refresh it's login to etcd ?~
- [ ] ~The above things need to be shared with every pod on the system (including dynamically allocated pods for running tests)~

**Comment by techcobweb** [comment]
Wondering how this differs from just using different settings inside the bootstrap.properties file ?

We have an 'internal' bootstrap.properties file which is shared by all the pods (as they all ask for it) when they start up. Locally this happens too, but defaults to the file implementation if no GALASA_BOOTSTRAP url is set.

So is this really a request to change the content of the internal bootstrap ?

I know etcd supports authentication. Galasa 0.40.0 is running on an older version right now, or auth hasn't been enabled, so we currently don't worry about re-authenticating.
We have another story to turn that on, but we'll probably have to add the name of the credential into the url used by the bootstrap property, then de-reference that within the etcd cps/dss extension.

**Comment by techcobweb** [comment]
I think parameters for the etcd should be passed on the environment, and controlled from the Helm chart, as it's an installation parameter really, not a run-time thing.

**Comment by jadecarino** [comment]
@techcobweb @Mark-J-Lawrence FYI I've moved some scope of this story into a new story: #2163
