### ISSUE TITLE
Implement Gradle Java Platform in the Galasa CLI

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2084]
## Story
As a Galasa developer/maintainer, I want to use Gradle's Java Platform plugin to manage versions of the project's dependencies, so that they are easier to maintain and update, we can create a Bill of Materials for Galasa, and that can help us with vulnerability scanning.

## Tasks
- [x] Remove hard coded versions from the Galasa CLI repo
- [x] Build it locally to test it worked
- [x] Adjust the set-versions.sh script to keep it up to date in future
- [x] ~Adapt GH Actions workflow to download the platform before building~ Not needed - the CLI looks at development.galasa.dev/main/maven-repo/obr for artifacts and the platform is in there.
