### ISSUE TITLE
Update GitHub Actions workflows to work for forks

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2085]
## Story
As a Galasa contributor, I want the GitHub Actions workflows to run successfully for my forks of the repositories, so that I can build my own versions of the components if I want to for testing or general use.

## Background
The GitHub Actions workflows created for the Galasa repos do not necessarily support forks, as they use secrets that are only accessible from the galasa-dev organisation, attempt to do things that are specific to the internal galasa-dev team, etc. The workflows need to be adapted slightly to either skip certain jobs if they are not being run by the galasa-dev organisation (i.e., a fork), or to check for the presence of secrets before attempting to run.

## Tasks
- [x] Remove hard coded `galasa-dev`s and replace with the repository owner
- [x] Skip any job to trigger the next workflow in chain etc if it reaches out to Galasa specific build chain
- [x] Skip job that reports failure in workflow to Slack if a fork
- [x] Skip argocd recycle steps if a fork
- [x] Check for the presence of any secret used before proceeding, if not configured, stop workflow - jade: in progress on my fork
- [x] Roll out changes to other repos outside of 'galasa'
   - [x] cli
   - [x] webui
   - [x] simplatform
   - [x] isolated
   - [x] integratedtests
   - [x] automation
   - [x] helm
