### ISSUE TITLE
Create GitHub replacements for Tekton pipelines used in the OS release

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2087]
## Story
As a Galasa releaser, I want all pipelines used to be in GitHub Actions not Tekton, so that we aren't relying on the cicsk8s system when we come to do a release and the release process is completely external.

## Background
A few pipelines for the open source release process for Galasa remain in Tekton as its not been high priority to convert them to GH Actions - but most will be very simple to convert to a GH Actions pipeline so should be done when we have capacity. 

These Tekton pipelines can be found [here](https://github.com/galasa-dev/automation/tree/main/releasePipeline/argocd-synced/pipelines).
The release process documentation [here](https://github.com/galasa-dev/automation/blob/main/releasePipeline/prerelease.md) and [here](https://github.com/galasa-dev/automation/blob/main/releasePipeline/release.md) tells the person doing the release to run a bash script > which creates a Tekton PipelineRun > which calls the Pipeline.

We want to convert this to having the bash script > call a GitHub Actions workflow instead. The new GitHub Actions workflows to replace the Tekton pipelines should should live in the [automation](https://github.com/galasa-dev/automation) repo in the `.github/workflows` directory.

## Tasks
- [x] Replace branch-create-galasa Tekton with GH Actions
- [x] Replace branch-delete-all Tekton with GH Actions
- [x] Replace branch-tag-galasa Tekton with GH Actions
- [x] Replace resources-build Tekton with GH Actions
- [x] Replace deploy-maven-galasa Tekton with GH Actions
- [x] Update release instructions to kick off gh actions flows instead of tekton flows.
- [x] Add to setup section of release instructions to say to authenticate to the github CLI.

**Comment by jaydee029** [comment]
Hello @jadecarino , I'm back after a long time i can help with some ci/cd issues , I see a few of them listed.
