### ISSUE TITLE
Move Java archive used by integration tests off Artifactory

### ISSUE THREAD

**Issue by jadecarino** [galasa-dev/projectmanagement#2089]
## Story
As a Galasa tester, I want the integration tests to be able to download the Java archives from a repo we maintain, so that we don't rely on the cicsk8s Artifactory instance anymore.

## Background
We have been asked to move the Java archives to somewhere else as we are the only users of the cicsk8s Artifactory instance which they would like to take down, given that it is often unstable and has to be manually rebooted regularly.

We need a maven repo, which lives internally in the IBM firewall as the Java archive has IBM certs embedded, that we can point the Java Manager to through CPS properties so it can download Java from there.

## Tasks
- [x] Create Dockerfile which serves up the OpenJDK archives to be downloaded
- [x] Create Deployment, Service and Ingress to deploy download site 
- [x] Create build pipeline to build the Docker image initially (not likely this will need to be rerun as the archives we use are from 2022 and don't change)
- [x] Update Java Manager's CPS props to download Java 11 from the new download site and run a test
- [x] Notify when cicsk8s artifactory can be taken down
