### ISSUE TITLE
Generate api pojos from openapi.yaml

### ISSUE THREAD

**Issue by Michael-Baylis** [galasa-dev/projectmanagement#529]
# Story
As a galasa developer I want to have the pojos for the REST api generated, so I can be 100% sure that the openapi.yaml document describes the structures that the code uses, and the two are consistent, and I can trust that the openapi.yaml fully describes the REST api.

# Background
Currently all the pojos are hand-crafted. They need to be generated instead during every build.

The generation should happen as part of the gradle build, not a separate step in the tekton pipeline process.
This will help local builds and the pipeline build use the same build process, and see the same failures.
The api generator jar can be downloaded as part of the build if necessary.

I suggest we generate a java client, as that will contain the pojos in anyway, and will be useful in it's own right for Java code to contact the API server.

Update: I tried generating them using the available generators, and got a client, but it was dependent on jackson. See https://github.com/galasa-dev/framework/pull/484

We could adopt that, but so far we've used the gson library instead.

# Tasks
- [x] ~gradle process to generate the POJOs in a java client package, as a separate bundle.~ build locally generates, as it is a better reflection of the tekton build process
  - [x] Try generating beans using standard generators. Generation works. Not run anything using it yet. See https://github.com/galasa-dev/framework/pull/484
    - Abandoning this, as it forces us to use Jackson. We want to stick with gson so need to write our own generator.
- [x] Write our own generator
  - [x] Read yaml file into map
  - [x] generate files from map
    - [x] Empty class
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test (don't think it's needed)
    - [x] class with single primitive property
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test
    - [x] class with multiple primitive properties
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test
    - [x] class with array property
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test
    - [x] class with multidimensional array
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
    - [x] class with mix of array and primitive properties
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test
    - [x] class with references to another class
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test
    - [x] class with array property with type as reference to object
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
    - [x] class with reference to array of another class type
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
    - [x] OneOf + AllOf swagger yaml handling (errors)
    - [ ] AnyOf swagger yaml handling - java interface + classes implementing them
    - [x] class with required property
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
    - [x] class with reference to property in wider schema map
      - [x] yaml -> schema structs
    - [x] property with enum
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
      - [x] java test
    - [x] property with constant (represented as enum[value] in yaml)
      - [x] yaml -> schema structs
      - [x] schema structs -> java structs
      - [x] java structs -> file
  - [x] use package name to generate sub folders
  - [x] add readable fatal errors
  - [x] add readable errors that don't immediately cause a panic, but should cause the program to fail
  - [x] add commands
- [x] Plug generator into buildutils
- [x] Build code generator into the build utils docker images. So we can use it in a build process.
- [x] have automation generate POJOs on each framework build
- [ ] ~POJOs are all adopted and used by the servlet code.~ see below
- [ ] ~Old pojos removed~ transfered to new issue: https://github.com/orgs/galasa-dev/projects/3?pane=issue&itemId=64133839

**Comment by techcobweb** [comment]
Decide whether we are going to use the PR or not.

**Comment by techcobweb** [comment]
I think we are going to have to write our own generator. So we have exactly what we want generated.
